### ISSUE TITLE
Start recording in android null point expection occcurs

### ISSUE THREAD

**Issue by jagadish906** [flutter-webrtc/flutter-webrtc#100]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Platform information**

* **Flutter version**: 
* **Plugin version**:
* **OS**: 
* **OS version**:

**Comment by rostopira** [comment]
LogCat please

**Comment by hiteshjoshi** [comment]
E/MethodChannel#FlutterWebRTC.Method(25723): Failed to handle method call
E/MethodChannel#FlutterWebRTC.Method(25723): java.lang.IllegalArgumentException: Unsupported value: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
E/MethodChannel#FlutterWebRTC.Method(25723): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:294)
E/MethodChannel#FlutterWebRTC.Method(25723): 	at io.flutter.plugin.common.StandardMethodCodec.encodeErrorEnvelope(StandardMethodCodec.java:70)
E/MethodChannel#FlutterWebRTC.Method(25723): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:230)
E/MethodChannel#FlutterWebRTC.Method(25723): 	at com.cloudwebrtc.webrtc.utils.AnyThreadResult.lambda$error$1(AnyThreadResult.java:23)
E/MethodChannel#FlutterWebRTC.Method(25723): 	at com.cloudwebrtc.webrtc.utils.-$$Lambda$AnyThreadResult$ccKxFpM2amkNZNKH8YO8t8OktKE.run(Unknown Source:8)
E/MethodChannel#FlutterWebRTC.Method(25723): 	at com.cloudwebrtc.webrtc.utils.AnyThreadResult.post(AnyThreadResult.java:33)
E/MethodChannel#FlutterWebRTC.Method(25723): 	at com.cloudwebrtc.webrtc.utils.AnyThreadResult.error(AnyThreadResult.java:23)
E/MethodChannel#FlutterWebRTC.Method(25723): 	at com.cloudwebrtc.webrtc.FlutterWebRTCPlugin.onMethodCall(FlutterWebRTCPlugin.java:344)
E/MethodChannel#FlutterWebRTC.Method(25723): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#FlutterWebRTC.Method(25723): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:90)
E/MethodChannel#FlutterWebRTC.Method(25723): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:234)
E/MethodChannel#FlutterWebRTC.Method(25723): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#FlutterWebRTC.Method(25723): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#FlutterWebRTC.Method(25723): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#FlutterWebRTC.Method(25723): 	at android.app.ActivityThread.main(ActivityThread.java:6762)
E/MethodChannel#FlutterWebRTC.Method(25723): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#FlutterWebRTC.Method(25723): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#FlutterWebRTC.Method(25723): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (25723): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Unsupported value: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null)
E/flutter (25723): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (25723): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (25723): <asynchronous suspension>
E/flutter (25723): #2      MediaRecorder.start (package:flutter_webrtc/media_recorder.dart:24:34)
E/flutter (25723): <asynchronous suspension>

**Comment by hiteshjoshi** [comment]
same here. Using this as example https://github.com/cloudwebrtc/flutter-webrtc/blob/4cbd9128d8280cb0744e0ab33f9bb9c1af560f49/example/lib/src/get_user_media_sample.dart

**Comment by projectpitchfork** [comment]
same here. Using the same example https://github.com/cloudwebrtc/flutter-webrtc/tree/master/example, getting the same results -- `Unhandled Exception: PlatformException(error, Unsupported value: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null)`
