### ISSUE TITLE
Since version 0.8.11 - macOS cameraLED stays active after stopping a video track

### ISSUE THREAD

**Issue by jdde** [flutter-webrtc/flutter-webrtc#1000]
**Describe the bug**
Since version 0.8.11 the physical camera LED from my macbook stays active, when I terminate a track. (Even when I terminate the full webrtc connection, it stays active)

**To Reproduce**
To reproduce it very easily, just take the example project from https://github.com/livekit/client-sdk-flutter, take the current main branch (which points to 0.8.11 as a dependency) and start it natively with macos.
Join a room, then leave a room, camera LED is still active.

Hint: when you start the same project for chrome - the bug does not exists

**Expected behavior**
LED should be turned off.

**Platform information**
tested on macOS 12.0.1

* **Flutter version**: 
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.0.1 21A559
    darwin-arm (Rosetta), locale en-DE)
    • Flutter version 3.0.0 at /Users/unping/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (9 weeks ago), 2022-05-09
      16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

* **Plugin version**: 0.8.11
* **OS**:  macOS
* **OS version**: macOS 12.0.1

**Comment by Jaehyeon0415** [comment]
iOS 15.5 same issue

**Comment by jdde** [comment]
Awesome! thank you very much guys for this fast fix!!!
