### ISSUE TITLE
Does flutter webrtcwebrtc support mdns?

### ISSUE THREAD

**Issue by 0Franky** [flutter-webrtc/flutter-webrtc#1009]
Hi, 
first of all congratulations for your work and this great plugin. 

I'm writing because reading some papers, I find out that a client using webrtc API, can discover the IP of the other users by reading the offer/response messages. 

To avoid this issue, is possible to use mdns, that expose to users a random mDNS that it registers on the local network.

I want ask you if this solution is possible with this plugin and how to configure this.

Thank you!

**Comment by ycherniavskyi** [comment]
`flutter_webrtc` is based on the GooleWebRTC library (currently on m97 version), so if it is possible with it, then it is possible with `flutter_webrtc`.

If you do not receive a direct answer from someone from the community, I could recommend you to find the solution for your task with the GooleWebRTC library directly and then translate it to `flutter_webrtc`. If some interfaces/methods are unavailable, then feel free to point them here.

**Comment by 0Franky** [comment]
Hi @ycherniavskyi,
Thank you for your reply!

About what I've seen on the web, this feature is only accessible by changing a flag on the browser. 
So I'm asking if there are any method or API to allow the same behaviour on other devices like desktop and mobile. 

Anyway I think the version is compatible. 

Thank you again!

**Comment by ycherniavskyi** [comment]
Hm, from fast grasp on [`webrtc`](https://github.com/webrtc-sdk/webrtc) and [`webrtc-build`](https://github.com/webrtc-sdk/webrtc-build) I couldn't see any mDNS disabling. So I suggest you to try to implement/check the required functionality, for example, within [`flutter-webrtc-demo`](https://github.com/flutter-webrtc/flutter-webrtc-demo) and then create a more specific issue or even PR 😉.
