### ISSUE TITLE
Typo in peerConnectionEvent channel name

### ISSUE THREAD

**Issue by doesnotexist** [flutter-webrtc/flutter-webrtc#1017]
https://github.com/flutter-webrtc/flutter-webrtc/blob/98d08c75ce4de0a994cfd771f560a89f716ae700/lib/src/native/rtc_peerconnection_impl.dart#L225

the substring peerConnectoinEvent should be changed to peerConnectionEvent

**Comment by cloudwebrtc** [comment]
Oops, the branch doesn't seem to be merged into the main, @doesnotexist would you mind creating a new one?
