### ISSUE TITLE
MediaStreamTrack enableSpeakerphone not working on Android 12 device

### ISSUE THREAD

**Issue by jianchon** [flutter-webrtc/flutter-webrtc#1031]
loudspeaker working on Android 11 and below, but not working on Android 12 code as below

MediaStream.getAudioTracks().forEach((track) {
      track.enabled = true;
      track.enableSpeakerphone(true);
    });

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.4 21F79 darwin-x64, locale en-MY)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.69.2)
[!] Connected device
    ! No devices available
[✓] HTTP Host Availability

OS version: Android 12

**Comment by smaznet** [comment]
```xml
 <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
 ```
 
 add this permission to your AndroidManifest.xml

**Comment by jianchon** [comment]
working after add

<uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30" />
<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />

> ```
>  <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
> ```
> 
> add this permission to your AndroidManifest.xml

Yes, working after added 
 <uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
 <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30" />
 <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />

from document Bluetooth device
