### ISSUE TITLE
Sound is playing through earspeaker even if `enableSpeakerphone(true)` set on Samsungs

### ISSUE THREAD

**Issue by PawelBijok** [flutter-webrtc/flutter-webrtc#1032]
**Bug description**
On 2 samsung devices (described bellow) that I have tested: sound is always played through ear speaker and it is very silent. 
Setting `enableSpeakerphone(true)` on track does not change anything. 
This issue does not appear on iPhone Xr (iOS 15.5) and OnePlus 6 (Android 11). Main speaker is used by default. Furthermore setting `enableSpeakerphone(false)` on them works and they start to use earspeaker.

**Expected behavior**
App should use main speaker when `enableSpeakerphone(true)` is set on desired track.

**Platform information**

* **Flutter version**: 3.0.4
* **Plugin version**: 0.8.10
* **OS**: Android: Samsung Galaxy S10+ / Samsung Galaxy A52s
* **OS version**: Android 12

**More info**
Those Samsung models use ear speaker as secondary main  speaker for stereo audio. Maybe this is what causing this issue...

**Comment by itsarjunsinh** [comment]
This is a blocking issue - not limited to any specific manufacturer. Along with complaints from Galaxy devices, my Poco F1 with similar stereo speaker setup are unusable for calls. Are there any workarounds? @PawelBijok did you make any progress?

**Comment by PawelBijok** [comment]
@itsarjunsinh unfortunately no 😞  I've stoped looking for one after posting this issue hoping that someone will respond.

**Comment by Perondas** [comment]
I have the same problem with a Google Pixel 6 pro, #1039.

**Comment by Perondas** [comment]
I have found the problem in the code. 
For some reason, and I cannot tell why, in the file 'FlutterWebRTCPlugin.java' the rtcAudioManager is null, when it should not be.
Even by changing: `
```java
public void onAudioManagerRequested(boolean requested) {
                        if (requested) {
                            if (rtcAudioManager == null) {
                                rtcAudioManager = RTCAudioManager.create(context);
                            }
```
to:
```java
public void onAudioManagerRequested(boolean requested) {
                        if (true) {
                            if (true) {
                                rtcAudioManager = RTCAudioManager.create(context);
                            }
```

the rtcAudioManager will still be null when calling 'setSpeakerphoneOn'

**Comment by Perondas** [comment]
A solution could be changing:
```java
@Override
                    public void setSpeakerphoneOn(boolean on) {
                        if (rtcAudioManager != null) {
                            rtcAudioManager.setSpeakerphoneOn(on);
                        }
                    }
```
to:
```java
@Override
                    public void setSpeakerphoneOn(boolean on) {
                        if (rtcAudioManager != null) {
                            rtcAudioManager.setSpeakerphoneOn(on);
                        } else {
                            rtcAudioManager = RTCAudioManager.create(context);
                            rtcAudioManager.setSpeakerphoneOn(on);
                        }
                    }
```

But I feel as tough that is not the proper way to solve this. From what I can tell, the only way for the rtcAudioManager to become null is by calling:
```java
private void stopListening()
```
This is only called from 
```java
public void onDetachedFromEngine()
```
and in the view destroy callback:
```java
registrar.addViewDestroyListener(view -> {
            plugin.stopListening();
            return false;
        });
```
But neither of these should be called. At least the way that I understand it.
I will probably use my bad fix in my own project for now, but someone who better understands how this code works, should really look into this.

**Comment by Perondas** [comment]
Here is my fix implemented:
https://github.com/Perondas/flutter-webrtc/tree/speakerphoneTempFix
This is more than likely going to break something, so use at your own risk.

**Comment by Perondas** [comment]
It seems that I have found a good solution to this. 
The reason why 'enableSpeakerphone(true)' does not work is because 'onAudioManagerRequested' is never called.
This happens due to these lines in 'MethodCallHandlerImpl.java'
```java
ArrayList<String> permissions = new ArrayList<>();
        permissions.add(Manifest.permission.BLUETOOTH_CONNECT);
        requestPermissions(
                permissions,
                (args) -> {
                  audioManager.onAudioManagerRequested(true);
                },
                (args) -> {
                });
```
As you can see, we request the BLUETOOTH_CONNECT permission. Should that fail, we simply do nothing, thereby never creating a AudioManager.

So, to fix this issue, we simply need to add the BLUETOOTH_CONNECT permission to the manifest. 
```xml
<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
```
Just add this line to the manifest and it should work.

**Comment by Perondas** [comment]
The README should be updated to reflect this.

**Comment by maulikchak** [comment]
the issue is not coming in android 11 or and when i tested in android 12 the issue is coming volume came from ear speaker same things happen for iOS 15 or higher so we just wait for next update

**Comment by Perondas** [comment]
> the issue is not coming in android 11 or and when i tested in android 12 the issue is coming volume came from ear speaker
This seems to be intended behavior, as you can see with Android 12 and up the BLUETOOTH_CONNECT permission becomes a requirement. See this issue and its PR #846

Dont know about iOS 15, as I don't have any device to test it.

**Comment by PawelBijok** [comment]
@Perondas your fix with 
`<uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />`
worked for me.

Thank you very much, great analyze 👍

**Comment by maulikchak** [comment]
still same problem exits in iOS 15+ device on android Samsung and Pixel side its fixed

**Comment by tigrenok00** [comment]
Same here - the problem exists on iOS 15+ with version 0.9.18 of the plugin, please help as it is a blocking issue for us!

**Comment by fullflash** [comment]
still no fixes ? 😱
