### ISSUE TITLE
Unable to RTCPeerConnection::setRemoteDescription: Failed to set remote offer sdp: Failed to set remote video description send parameters.

### ISSUE THREAD

**Issue by pkwom** [flutter-webrtc/flutter-webrtc#104]
I keep getting this error on my android webrtc app when I take the sdp from janus-gateway and try to set it as remote description. My sdp offer from janus-gateway is :
v=0
o=- 1560396930181938 1 IN IP4 "ip"
s=Mountpoint 99
t=0 0
a=group:BUNDLE video
a=msid-semantic: WMS janus
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 "ip"
*a=sendonly
a=mid:video
a=rtcp-mux
a=ice-ufrag:fg6W
a=ice-pwd:wyQGuelBzLh8ToRawNUf9p
a=ice-options:trickle
a=fingerprint:sha-256
a=setup:actpass
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=4d002a;sprop-parameter-sets=Z00AKpY1QPAET8s3AQEBQAAAAwBAAAAKIQ==,aO48gA==
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 goog-remb
a=ssrc:3959652904 cname:janus
a=ssrc:3959652904 msid:janus janusv0
a=ssrc:3959652904 mslabel:janus
a=ssrc:3959652904 label:janusv0
a=candidate:1 1 udp 2013266431 "ip" 50391 typ host
a=end-of-candidates

**Comment by cloudwebrtc** [comment]
@pkwom 
I found multiple errors in this SDP.
`o=- 1560396930181938 1 IN IP4 "ip"` <-- ip address is wrong
`*a=sendonly` <-- a letter should not have * before
`a=fingerprint:sha-256 `<--The fingerprint information is missing.

If this information is intentionally hidden, you can try to replace the framework inside the flutter-webrtc plugin by compiling the debug version of the WebRTC framework. You can quickly find the problem based on the log information in the webrtc native.

**Comment by Tonigt** [comment]
when set remote description the plugin occur error: 
Unhandled Exception: Unable to RTCPeerConnection::setRemoteDescription: Failed to set remote answer sdp: Failed to apply the description for audio: Answerer must use either active or passive value for setup attribute.
E/flutter ( 8042): #0      RTCPeerConnection.setRemoteDescription (package:flutter_webrtc/rtc_peerconnection.dart:275:7)

v=0
o=- 493305778556546059 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS 08915356-9BAE-40D3-B290-923D3C3CB285
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:kZMJ
a=ice-pwd:KG8UYyXbMVOsIujV9ISwSfXX
a=ice-options:trickle renomination
a=fingerprint:sha-256 10:B4:F1:18:D9:4D:52:0D:A2:53:6B:41:42:3B:46:78:85:61:AB:1B:C7:5A:15:F1:0C:BC:7A:69:4F:6F:02:61
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=sendonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:102 ILBC/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:850542037 cname:zhiJQ3qRym8QkUi9
a=ssrc:850542037 msid:08915356-9BAE-40D3-B290-923D3C3CB285 CDCC89A3-DC04-40D4-B3C7-9310692C21E2
a=ssrc:850542037 mslabel:08915356-9BAE-40D3-B290-923D3C3CB285
a=ssrc:850542037 label:CDCC89A3-DC04-40D4-B3C7-9310692C21E2
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 124 125
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:kZMJ
a=ice-pwd:KG8UYyXbMVOsIujV9ISwSfXX
a=ice-options:trickle renomination
a=fingerprint:sha-256 10:B4:F1:18:D9:4D:52:0D:A2:53:6B:41:42:3B:46:78:85:61:AB:1B:C7:5A:15:F1:0C:BC:7A:69:4F:6F:02:61
a=setup:actpass
a=mid:video
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
a=extmap:9 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=sendrecv
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 H264/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640c33
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 H264/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e033
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:127 red/90000
a=rtpmap:124 rtx/90000
a=fmtp:124 apt=127
a=rtpmap:125 ulpfec/90000
a=ssrc-group:FID 1457659246 153433241
a=ssrc:1457659246 cname:zhiJQ3qRym8QkUi9
a=ssrc:1457659246 msid:08915356-9BAE-40D3-B290-923D3C3CB285 28D040BB-DF40-4BE4-8B6D-CCDB882169D6
a=ssrc:1457659246 mslabel:08915356-9BAE-40D3-B290-923D3C3CB285
a=ssrc:1457659246 label:28D040BB-DF40-4BE4-8B6D-CCDB882169D6
a=ssrc:153433241 cname:zhiJQ3qRym8QkUi9
a=ssrc:153433241 msid:08915356-9BAE-40D3-B290-923D3C3CB285 28D040BB-DF40-4BE4-8B6D-CCDB882169D6
a=ssrc:153433241 mslabel:08915356-9BAE-40D3-B290-923D3C3CB285
a=ssrc:153433241 label:28D040BB-DF40-4BE4-8B6D-CCDB882169D6
