### ISSUE TITLE
Critical bug: No way to select iOS external audio input

### ISSUE THREAD

**Issue by ollydixon** [flutter-webrtc/flutter-webrtc#1041]
On iOS there's no external microphone to select, only the internal one. Makes the whole library useless since a lot of people use Airpods for video calls etc. (phone in the pocket, meeting booths, on-the-go, etc)

Permissions for microphone are enabled.
Info.plist has the entry for microphone access for iOS.

Tested on Mac/Web and it works just fine, on iPad and iPhone it breaks.

Calling

`List<MediaDeviceInfo> devices = await navigator.mediaDevices.enumerateDevices();`

We can see below that the Airpods are missing, they are on the device. Even after restarting the app/device. They don't show.
![devices missing](https://user-images.githubusercontent.com/6940726/183089033-a36478e3-82b5-4e49-815b-a38c6a36a4c5.jpg)

Only the built-in microphone is returned in the "audioinput"

![2022-08-05 14 58 47](https://user-images.githubusercontent.com/6940726/183088597-bd242ac8-a6ff-4b5c-a77f-50db8f948305.jpeg)
![2022-08-05 14 58 37](https://user-images.githubusercontent.com/6940726/183088601-3b51eed6-6326-45a8-a290-2cc1677dc0da.jpeg)

**Comment by cloudwebrtc** [comment]
@ollydixon Should be fixed in this commit https://github.com/flutter-webrtc/flutter-webrtc/pull/1030/commits/c6ba3242e347037fe6d03d8551d942f89021185d, can you help me test it and give feedback?

**Comment by ollydixon** [comment]
@cloudwebrtc sure, give me a few days though :-)

**Comment by ollydixon** [comment]
@cloudwebrtc is this one the main branch, or should I checkout locally? 😎

**Comment by ollydixon** [comment]
@cloudwebrtc how should I test this?

**Comment by ollydixon** [comment]
@cloudwebrtc I switched to flutter_webrtc: 0.9.3 and it won't compile. Everytime we update this library we got a ton of issues with compiling on iOS.

<img width="819" alt="Screenshot 2022-08-17 at 13 26 22" src="https://user-images.githubusercontent.com/6940726/185107347-898a0a21-9fd3-4ff3-844f-1f039f55a31d.png">

**Comment by ollydixon** [comment]
@cloudwebrtc I can confirm that 0.9.3 doesn't fix the audio selection issue.

**Comment by cloudwebrtc** [comment]
Ah sorry, I haven't merged `feat/select-audio-output` into `main`, so you can try this
```yaml
flutter_webrtc:
   git:
     url: https://github.com/flutter-webrtc/flutter-webrtc.git
     ref: feat/select-audio-output
```

**Comment by ollydixon** [comment]
@cloudwebrtc can confirm that it works!

**Comment by ollydixon** [comment]
![IMG_0095](https://user-images.githubusercontent.com/6940726/185400461-be1197db-0d34-49c9-b8ef-2c0ecbea3cc3.PNG)

I tested across devices and with switching audio. Worked perfectly.

**Comment by ollydixon** [comment]
@cloudwebrtc there is an issue with Chrome though

<img width="1555" alt="Screenshot 2022-08-18 at 16 52 38" src="https://user-images.githubusercontent.com/6940726/185426396-339c352a-8d29-4dec-8b97-5d683c1f8b10.png">
<img width="524" alt="Screenshot 2022-08-18 at 16 53 43" src="https://user-images.githubusercontent.com/6940726/185426494-cb8e3bcd-d5a5-405c-9230-76fa026b0683.png">

**Comment by ycherniavskyi** [comment]
@ollydixon I propose to create a new issue related to Chrome, but I am closing this one related to iOS because of its resolution.
