### ISSUE TITLE
Switch mobile speakers not working

### ISSUE THREAD

**Issue by ehsan097** [flutter-webrtc/flutter-webrtc#1051]
I want to switch mobile speakers from earpiece to loudspeaker and vice versa.

I tried the provided solution but its not working on Android 12.
https://github.com/flutter-webrtc/flutter-webrtc-demo/issues/73#issuecomment-616553610

**Platform information**

Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2

[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-x64, locale en-US)
[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

**Comment by cloudwebrtc** [comment]
Please try to update flutter-webrtc to 0.9.4, this branch has fixed the setSpeakerphoneOn method.
