### ISSUE TITLE
Is suport windows 7 ? it's not work on windows 7 .

### ISSUE THREAD

**Issue by yangjiejie12308** [flutter-webrtc/flutter-webrtc#1065]
Is suport windows 7 ? it's not work on windows 7 ,

**Comment by cloudwebrtc** [comment]
I think this depends on the minimum windows version supported by flutter and google webrtc.

**Comment by ycherniavskyi** [comment]
As for [Flutter 3.3 and Windows](https://docs.flutter.dev/get-started/install/windows):
- System requirements:
  - Operating Systems: Windows 10 or later (64-bit), x86-64 based.

As for [WebRTC and Windows](https://docs.microsoft.com/en-us/winrtc/getting-started):
- Machine requirements
  - Windows 10 (build 19041) or later.

🤷🏻‍♂️ it seems that Windows 7 time is gone, at last, if you want to use the last versions of the mentioned projects.

**Comment by yangjiejie12308** [comment]
thanks
