### ISSUE TITLE
Mandatory Audio Constraints

### ISSUE THREAD

**Issue by clg236** [flutter-webrtc/flutter-webrtc#107]
Hi,

I've been trying to force audio constraints in my SDP, but am not sure if I'm formatting the contraints argument to `navigator.getUserMedia` correctly. 

Currently I tried the following, but it doesn't seem to be working in the SDP:

```
"video: false,
"audio": {
          "exact": {
            "channelCount": 2,
            "echoCancellation": false,
            "autoGainControl": false,
            "noiseSuppression": false,
            "latency": 50,
            "sampleRate": 48,
            "sampleSize": 16,
          }
      }
```

**Comment by cloudwebrtc** [comment]
These parameters belong to the WebRTC private constraint parameter and need to be available at Android: 
https://github.com/cloudwebrtc/flutter-webrtc/blob/master/android/src/main/java/com/cloudwebrtc/webrtc/FlutterWebRTCPlugin.java#L547
And 
iOS: 
https://github.com/cloudwebrtc/flutter-webrtc/blob/master/ios/Classes/FlutterWebRTCPlugin.m#L647 additional parameter conversion

**Comment by cloudwebrtc** [comment]
These parameters seem to be less common, and if you are interested in adding, we would be happy to accept a PR.

**Comment by clg236** [comment]
Cool. I’d love to work on a PR. Any advice on where to start? (I am am amateur)

**Comment by cloudwebrtc** [comment]
@clg236 
The set of constraints that can be used in the webrtc native library is in this file. [media_constraints.h](https://chromium.googlesource.com/external/webrtc/+/a4d873786f10eedd72de25ad0d94ad7c53c1f68a/sdk/media_constraints.h).
You can try to test these parameters and apply them to the flutter-webrtc plugin via the objc/java interface.

**Comment by clg236** [comment]
Awesome! Let me try this out and get back to you.

On Mon, Jul 8, 2019 at 07:44 CloudWebRTC <notifications@github.com> wrote:

> @clg236
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_clg236&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=cFA0fE-wF7Pd4u5URHmIEHar5XGb_L0apgzztbrDjv8&m=PXjNh81nHq7r8JlnDL8VkUZ49phbtlfMpglTcjQ7fOA&s=ble8HpWNSgw11BqFgyBt3rpUUxAT365tTCkjg7l1tJc&e=>
> The set of constraints that can be used in the webrtc native library is in
> this file. media_constraints.h
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__chromium.googlesource.com_external_webrtc_-2B_a4d873786f10eedd72de25ad0d94ad7c53c1f68a_sdk_media-5Fconstraints.h&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=cFA0fE-wF7Pd4u5URHmIEHar5XGb_L0apgzztbrDjv8&m=PXjNh81nHq7r8JlnDL8VkUZ49phbtlfMpglTcjQ7fOA&s=wqEXVk5YI34xQw4pbRTpA3IVm122yXMX9qhKDKidq9g&e=>
> .
> You can try to test these parameters and apply them to the flutter-webrtc
> plugin via the objc/java interface.
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cloudwebrtc_flutter-2Dwebrtc_issues_107-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAAN2QP24YVXNLTHYUYVHUKDP6NHETA5CNFSM4H2XKRE2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZNJ4HI-23issuecomment-2D509255197&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=cFA0fE-wF7Pd4u5URHmIEHar5XGb_L0apgzztbrDjv8&m=PXjNh81nHq7r8JlnDL8VkUZ49phbtlfMpglTcjQ7fOA&s=BIyT4E0-l0ay5ajTxDY1mdNhh3p4pVNPKNFzwhu5rzQ&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AAN2QP4IUMHDFL3KJVA4ETLP6NHETANCNFSM4H2XKREQ&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=cFA0fE-wF7Pd4u5URHmIEHar5XGb_L0apgzztbrDjv8&m=PXjNh81nHq7r8JlnDL8VkUZ49phbtlfMpglTcjQ7fOA&s=kIN2-K3oPZdn2DvyTxDIElBhWBfzUqSKG7Vb6o1oAYo&e=>
> .
>
-- 


Christian Grewell | 葛瑞田

Assistant Arts Professor, Interactive Media + Business

Associate Director, Program on Creativity + Innovation

Associate Director, Interactive Media Arts

http://creativityandinnovation.shanghai.nyu.edu/


Room 950 / 1025
1555 Century Ave., Pudong
Shanghai, China 200122
Phone: +86 021 2059 5890
Cell: +86 186 1656 8844
shanghai.nyu.edu

**Comment by rostopira** [comment]
@clg236 On android you can set this parameters on `JavaAudioDeviceModule` directly
https://github.com/cloudwebrtc/flutter-webrtc/blob/master/android/src/main/java/com/cloudwebrtc/webrtc/FlutterWebRTCPlugin.java#L113
Modify source and forget about it, I have high doubts that anyone else would ever need this

**Comment by carloselborges** [comment]
@clg236 Is this already implemented?
Is there a place to set latency, or disable other audio settings, like noiseSupression?

**Comment by wer-mathurin** [comment]
If you were using the web implementation, any constraints where not taken into account before this [PR](https://github.com/flutter-webrtc/flutter-webrtc/pull/372).

@carloselborges :  Let us know if you were using the native or web implementation.  So we can track it properly.

**Comment by carloselborges** [comment]
Hello @wer-mathurin, I'm working **native**.
I just want to know if thats is available on native **iOS** and **Android**.
On web, I've noticed that it's supported by some browsers...
