### ISSUE TITLE
Playing music or tone on the call

### ISSUE THREAD

**Issue by nikohpng** [flutter-webrtc/flutter-webrtc#1074]
**Is your feature request related to a problem? Please describe.**

I want to make music during the call so that the callee can hear it. 

**Describe the solution you'd like**

I want to mix the audio before sending it out.

At present, I don't have a good solution. I want to discuss it 

Of course, if you have a better solution, it will be good

**Comment by alexzh16** [comment]
you can implement/use the MediaPlayer for play music or tone on the status Ringing. webrtc cannot make fake ringtone and its not for webrtc project necessary features, only sip server can do.

**Comment by nikohpng** [comment]
I need to play pcm by rtp, because I will detect tone in **inband dtmf**. 
So I can't play it by sip.
Thank you reply.

**Comment by alexzh16** [comment]
> 

i can explain you, that stream technology cannot make tone from nothing. tone must generate the server. the server work as signalling server and the serve know if client a or b is online after that send tone to channel. on webrtc all another technology. its p2p. and client don't know of another side its online or not. after exchange handshake build the tunnel, and on this tunnel you can send to the stream your tone, or music from caller or from callee. but, if you send music to stream - on this moment all subscriber can lessen the music or tone. its not good idea. on this way you can only caller side client play the music or tone with your player. its not another way.

**Comment by nikohpng** [comment]
You mean the effect of playing music or tone is not good ？

I need it in **inband dtmf** ,like this [FreeSWTICH DTMF](https://freeswitch.org/confluence/display/FREESWITCH/DTMF#DTMF-2.2DTMFpassthroughinbandw/DTMFdetection). I don't care about sound effects. **FreeSWITCH will detect tone by pcm in rtp**
```
If you are receiving the DTMF inband and FreeSWITCH hasn't automatically started inband detection, use [mod_dptools: start_dtmf](https://freeswitch.org/confluence/display/FREESWITCH/mod_dptools%3A+start_dtmf)
```

I must make freeswitch to detect tone in rtp, such as 1, 2...... eg.

**Comment by nikohpng** [comment]
Hello everyone, I have solve it. I can't open source because of the company.

In this google group, I find solution.  If anyone is interested, you can do it.
[https://groups.google.com/g/discuss-webrtc/c/f3lIyA3Otyo/m/mWsQfaYVCAAJ](https://groups.google.com/g/discuss-webrtc/c/f3lIyA3Otyo/m/mWsQfaYVCAAJ)

The main idea is to inherit audioSource，then, you can get a AudioTrackSinkInterface.
AudioTrackSinkInterface can push pcm data to rtp (**Note that the audio will not have echo cancellation**)

**Comment by ycherniavskyi** [comment]
If the author said that the issue was solved then I think we could close it.

**Comment by mohamedxblac** [comment]
Hi,

I had the exact same requirement — playing music during a call so other participants can hear it, mixed with microphone audio.

After extensive research (no working solutions on StackOverflow, and 100ms built something similar but requires their full platform), I ended up modifying the WebRTC source directly.

Modified three core classes:
- AudioDeviceModule
- JavaAudioDeviceModule
- AudioRecord

Uses Android's AudioPlaybackCapture API (Android 10+) to capture system audio and mix it with microphone input into a single WebRTC stream.

Been running in production for months. Clean audio quality.

Fork is here:
 https://github.com/mohamedxblac/webrtc_mediaprojection

Works as a drop-in replacement — no breaking changes to the existing flutter-webrtc API.

Hope this helps.
