### ISSUE TITLE
Error: The non-abstract class 'RTCVideoRenderer' is missing implementations for these members:

### ISSUE THREAD

**Issue by chitraarasu** [flutter-webrtc/flutter-webrtc#1079]
/C:/src/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.12/lib/src/native/rtc_video_renderer_impl.dart:11:7: Error: The non-abstract class 'RTCVideoRenderer' is missing implementations for these members:
 - VideoRenderer.onFirstFrameRendered
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class RTCVideoRenderer extends ValueNotifier<RTCVideoValue>
      ^^^^^^^^^^^^^^^^
/C:/src/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/webrtc_interface-1.0.8/lib/src/rtc_video_renderer.dart:51:13: Context: 'VideoRenderer.onFirstFrameRendered' is defined here.
  Function? onFirstFrameRendered;
            ^^^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by MCYBA** [comment]
I am exactly encountering the same issue.

**Comment by jakobleck** [comment]
Maybe check compatibility between the versions of webrtc-interface and flutter_webrtc that you are using? Cf. https://github.com/flutter-webrtc/flutter-webrtc/issues/899

**Comment by MCYBA** [comment]
I solved with overriding `onFirstFrameRendered` and created a PR #1081

**Comment by ayushsahu7447** [comment]
> I solved with overriding `onFirstFrameRendered` and created a PR #1081

how can u pls provide code sir
i am not able to solve 
from last 3 month and it is very neccesory me

**Comment by MCYBA** [comment]
@ayushsahu7447 please look at [this](https://github.com/flutter-webrtc/flutter-webrtc/pull/1081/commits/052ed45db56205bfe14c1da51106a83a1f7863f6) commit. Or you can simply add my fork to your `pubspec.yaml` like:
```
dependencies:
  flutter:
    sdk: flutter
    # ... Rest of the dependencies 
    flutter_webrtc:
    git:
      url: https://github.com/MCYBA/flutter-webrtc
      ref: 0.8.12_fixed
```

**Comment by ChiragLiveu** [comment]
I have to same issue once i update the flutter and xcode I get below error  Error (Xcode): ../../../../.pub-cache/hosted/pub.dev/flutter_webrtc-0.10.8/lib/src/native/rtc_video_renderer_impl.dart:11:7: Error: The
non-abstract class 'RTCVideoRenderer' is missing implementations for these members: any one can help me?????
