### ISSUE TITLE
[Bug] Uknown native RtpTransceiverDirection type4

### ISSUE THREAD

**Issue by duyjack** [flutter-webrtc/flutter-webrtc#1084]
I have this problem, i don't know how to happening. I use lib [mediasoup-client-flutter](https://github.com/Blancduman/mediasoup-client-flutter).
When close and create multi consumer, app often crash.

<img width="1156" alt="Screen Shot 2022-09-19 at 14 39 42" src="https://user-images.githubusercontent.com/46467707/190971723-6b26f312-d594-4a2a-a80c-9a2d74540486.png">

I found issue have problem in this function in lib webrtc:android ( native lib), but i cannot debug in function because RtpTransceiver.class just read-only.
<img width="831" alt="Screen Shot 2022-09-19 at 14 58 58" src="https://user-images.githubusercontent.com/46467707/190973797-3dc24ae0-a972-4093-afa7-d2c0129e01e6.png">

Why nativeIndex = 4 ? Maybe constant wrong in flutter layer or C++ layer 

Hope you fix it soon.

**Comment by duyjack** [comment]
I pulled commit #1067 
I have test with it on branch dev, I don't have this problem anymore. 
Maybe I will test somecase.

Info to everyone which have problem like me

**Comment by duyjack** [comment]
Hi everyone,

Android maybe fine but audio on IOS not works anymore.

**Comment by dragontran** [comment]
Hello! I'm having iOS audio issues too but it seems to kinda start working whenever you enable speaker on the iOS device. Even with this "fix" seems like the audio on IOS seems to be affected and it pretty poor compared to Android.

**Comment by cloudwebrtc** [comment]
fixed https://github.com/flutter-webrtc/flutter-webrtc/pull/1114
