### ISSUE TITLE
createPeerConnection unnecesary Bluetooth permission requested for Android

### ISSUE THREAD

**Issue by fcancela** [flutter-webrtc/flutter-webrtc#1089]
I find it unnecessary to request BLUETOOTH_CONNECT permissions during [createPeerConnection](https://github.com/flutter-webrtc/flutter-webrtc/blob/main/android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java#L169-L178) method for Android SDK versions > 31.

[This code](https://github.com/flutter-webrtc/flutter-webrtc/blob/main/android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java#L993-L1003) does nothing with this permission, why is it needed?

This permissions request during createPeerConnection method generating a bad UX at the moment I want to stream. The easiest solution I found was to request the permission during the app startup so it's not requested afterwards by that method. But I'd rather not request Bluetooth permission if my app does not need it.

**Comment by cloudwebrtc** [comment]
Yes, I'm considering removing this code snippet in a recent update.

**Comment by cloudwebrtc** [comment]
Here is the code left over from the old audio manager to try to confirm access to the audio device after the real peerconnection is created.

**Comment by fcancela** [comment]
Thanks for the quick answer! Good to hear that.
