### ISSUE TITLE
ATAudioSesisonPropertyManager.mm Invalid input size for property 

### ISSUE THREAD

**Issue by UserSense** [flutter-webrtc/flutter-webrtc#1094]
**Describe the bug**
Problems with audio streams on iOS 16+. 
`ATAudioSessionPropertyManager.mm:71 Invalid input size for property 1684431725`
`ATAudioSessionPropertyManager.mm:255 Invalid input size for property 1684431725`

**To Reproduce**

Webrtc with microphone feed

**Expected behavior**

Correct input size for both properties

**Platform information**

iOS 16.0.2

* **Flutter version**: 
Flutter version 3.3.2
Dart version 2.18.1
* **Plugin version**:
0.9.7
* **OS**: 
iOS
* **OS version**:
16.0.2

Possible related solution: https://developer.apple.com/forums/thread/715177

My guess is that we need a different mode.

**Comment by gwumkt** [comment]
Hi, we have the same issue. did you solve it?

**Comment by Antonito** [comment]
I have the same issue with a custom libwebrtc build. It occurs on every kind of device, on iOS 16. It causes latency issues with bluetooth devices (I have only tried with AirPods so far)
It seems to be related to `kAudioUnitSubType_VoiceProcessingIO` but I haven't found a solution yet.

**Comment by riffsliu** [comment]
iOS 16.1 is OK
