### ISSUE TITLE
update to 0.9.8 ..crash app 

### ISSUE THREAD

**Issue by rezadevelopers2** [flutter-webrtc/flutter-webrtc#1105]
E/rtc     ( 4406): #
E/rtc     ( 4406): # Fatal error in: ../../pc/peer_connection.cc, line 823
E/rtc     ( 4406): # last system error: 0
E/rtc     ( 4406): # Check failed: !IsUnifiedPlan()
E/rtc     ( 4406): # AddStream is not available with Unified Plan SdpSemantics. Please use AddTrack instead.
F/libc    ( 4406): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 4696 (signaling_threa), pid 4406 (orena.messenger)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86_arm:11/RSR1.201013.001/6903271:user/release-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2022-10-04 10:11:09+0330

**Comment by dragontran** [comment]
Update your peer connection configuration to include or maybe consider [migrating from addStream to addTrack](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addStream#migrating_to_addtrack)
```swift
  Map<String, dynamic> configuration = {
    "sdpSemantics": "plan-b", // Add this line
    'iceServers': [
      {
        'urls': [
          'stun:stun1.l.google.com:19302',
          'stun:stun2.l.google.com:19302'
        ]
      }
    ]
  };
```

**Comment by DilipKumar64** [comment]
this issue is still not resolved and I am facing this issue.

**Comment by USAMAWIZARD** [comment]
# Fatal error in: ../../pc/peer_connection.cc, line 823
# last system error: 0
# Check failed.
 Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 27111 (signaling_threa), pid 26959 (flutter_example)

**Comment by DilipKumar64** [comment]
which  version are you using @USAMAWIZARD
