### ISSUE TITLE
Ice Connection State remains In Checking In IOS

### ISSUE THREAD

**Issue by hasssanshah7864** [flutter-webrtc/flutter-webrtc#112]
In android this plugins working fine. But in IOS it's not working. IceCandidate Connection State remains in Checking while i have send candidates to server and also adding received candidates from server to peer connection

**Fluter Version**: Flutter 1.7.8 
**Plugin Version**: Latest

**Comment by cloudwebrtc** [comment]
I think it is related to the LAN environment, can you provide more console logs of iOS?

**Comment by hasssanshah7864** [comment]
**Log For Android**

I/org.webrtc.Logging( 6390): WebRtcAudioTrackExternal: startPlayout
D/android.media.AudioTrack( 6390): [HSM] AudioTrace play() uid: 10403, pid: 6390
I/org.webrtc.Logging( 6390): WebRtcAudioTrackExternal: AudioTrackThread@[name=AudioTrackJavaThread, id=81076]
D/FlutterWebRTCPlugin( 6390): onAddTrack
D/FlutterWebRTCPlugin( 6390): peerConnectionSetRemoteDescription() end
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() start
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() end
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() start
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() end
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() start
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() end
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() start
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() end
I/flutter ( 6390): --------ICE CONNECTION STATE: RTCIceConnectionState.RTCIceConnectionStateChecking-------------
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() start
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() end
I/flutter ( 6390): ----------ON ADD STREAM-----------: 
I/flutter ( 6390): EMITTING CANDIDATE FROM LOOP
I/chatty  ( 6390): uid=10403(u0_a403) Thread-9 identical 4 lines
I/flutter ( 6390): EMITTING CANDIDATE FROM LOOP
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() start
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() end
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() start
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() end
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() start
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() end
I/AudioTrack( 6390): audioTrack continuously zero data counter >= 20, send pause/stop state to pg, counter: 20
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() start
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() end
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() start
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() end
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() start
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() end
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() start
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() end
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() start
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() end
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() start
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() end
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() start
D/FlutterWebRTCPlugin( 6390): peerConnectionAddICECandidate() end
D/FlutterWebRTCPlugin( 6390): onIceCandidate
I/flutter ( 6390): {success: true, message: {ar: لا يوجد سجلات, en: No record found}, data: {comments: [], pagination: {total: 0, pages: 0, per_page: 60, page: 1}}, errors: {}}
D/FlutterWebRTCPlugin( 6390): onIceGatheringChangeCOMPLETE
I/flutter ( 6390): --------ICE GATHERING STATE: RTCIceGatheringState.RTCIceGatheringStateComplete-------------
I/org.webrtc.Logging( 6390): EglRenderer: Duration: 4008 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/flutter ( 6390): --------ICE CONNECTION STATE: RTCIceConnectionState.RTCIceConnectionStateConnected-------------
I/AudioTrack( 6390): audioTrack send start state to pg

***************************************************************************************************

**Log For IOS**

flutter: ----------Sending SDP To Server-----------
flutter: SDP TYPE: offer
flutter: --------ICE GATHERING STATE: RTCIceGatheringState.RTCIceGatheringStateGathering-------------
flutter: ----------------IN WATCH BROADCAST-----------------
flutter: ----------------IN WATCH BROADCAST SETTING REMOTE DESCRIPTION-----------------
output client:  1 ch,  48000 Hz, Int16, output HW:  1 ch,  48000 Hz, Float32
input client:   1 ch,  48000 Hz, Int16, input HW:   1 ch,  48000 Hz, Float32
flutter: --------ICE CONNECTION STATE: RTCIceConnectionState.RTCIceConnectionStateChecking-------------
flutter: ----------ON ADD STREAM-----------:
No video track for RTCMediaStream: default
flutter: EMITTING CANDIDATE FROM LOOP
flutter: EMITTING CANDIDATE FROM LOOP
flutter: EMITTING CANDIDATE FROM LOOP
flutter: --------ICE GATHERING STATE: RTCIceGatheringState.RTCIceGatheringStateComplete-------------

**Comment by hasssanshah7864** [comment]
New version of this plugin(0.1.7) has issues in IOS. Ice connection state remains in checking but previous versions are working well in IOS & Android. But there is no enableSpeakerphone method in previous versions :(

**Comment by RodrigoBertotti** [comment]
_(Helping others who will find this page searching on Google)_

I was having the same problem,  I fixed it by using **[TURN](https://stackoverflow.com/a/35862243/4508758)** servers (instead of STUN), you can host your own TURN server or sign up for one like [metered.ca](https://www.metered.ca/pricing), which starts for free

Also, keep in mind to use **real devices**, avoid iOS Simulator and Android Simulator when testing WebRTC

    createPeerConnection({
      'iceServers': [
        {
          "urls": "turn:a.relay.metered.ca:80",
          "username": "...",
          "credential": "...",
        },
        {
          "urls": "turn:a.relay.metered.ca:80?transport=tcp",
          "username": "...",
          "credential": "...",
        },
        {
          "urls": "turn:a.relay.metered.ca:443",
          "username": "...",
          "credential": "...",
        },
        {
          "urls": "turn:a.relay.metered.ca:443?transport=tcp",
          "username": "...",
          "credential": "...",
        },
      ]
    })
