### ISSUE TITLE
Implementation of insertable streams.

### ISSUE THREAD

**Issue by Yogesh-Dubey-Ayesavi** [flutter-webrtc/flutter-webrtc#1124]
First of all a great library thanks for that, now coming to the main point I want to implement some video filters in frames of the user insertable stream is something that I think can work for me. So when i can expect it to arrive 

regards !

**Comment by cloudwebrtc** [comment]
insertable streams is a useful feature, but it's also a hard job, and I may have to wait until I have some free time to do it,

**Comment by HoangTrongKhanh** [comment]
Any update?

**Comment by tangenttechno** [comment]
any update? it's a very useful USP.

**Comment by Yogesh-Dubey-Ayesavi** [comment]
> any update? it's a very useful USP.

No update yet

**Comment by cloudwebrtc** [comment]
duplicate https://github.com/flutter-webrtc/flutter-webrtc/issues/959
