### ISSUE TITLE
When testing with flutter-webrtc-demo, I found that I couldn't see myself and each other on Windows 7.

### ISSUE THREAD

**Issue by 9yen** [flutter-webrtc/flutter-webrtc#1127]
**Describe the bug**
When testing with flutter-webrtc-demo, I found that I couldn't see myself and each other on Windows 7.

**To Reproduce**

**Expected behavior**
I have run this demo in win10, audio and video calls are normal. I thought Windows 7 would be the same.
**Platform information**
Windows 7 Professional, Version 6.1, internal version 7601: Service Pack 1
* **Flutter version**: 
$ flutter doctor -v
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 2.10.5 at C:\Users\Administrator\Downloads\flutter_windows_2.10.5-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (6 months ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[√] Chrome - develop for the web
    • Chrome at C:\Users\Administrator\AppData\Local\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Professional 2019 16.11.19)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional
    • Visual Studio Professional 2019 version 16.11.32901.82
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.70.3)
    • VS Code at C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.50.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 6.1.7601]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 49.0.2623.112

[☠] HTTP Host Availability (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    X HandshakeException: Connection terminated during handshake
    •

! Doctor found issues in 3 categories.
* **Plugin version**:
* **OS**: 
windows
* **OS version**:
Windows 7 Professional, Version 6.1, internal version 7601: Service Pack 1

**Comment by JiaoLiu** [comment]
> Can you see any logs in the flutter console when running on windows 7?

我也测试发现在旗舰版win7 有问题，显示不了对端视频。 专业版、家庭版可以显示。
日志显示信令、打洞都正常，onaddtrack也回来了，就是渲染不了界面。

**Comment by cloudwebrtc** [comment]
我认为和flutter 支持windows 7 有关, 你可以试试flutter video player 是否可以正常工作在windows 7
