### ISSUE TITLE
When using screen sharing, the frame rate of the video is very low, especially on the ipad of ios, the frame rate is only about 2 frames per second.

### ISSUE THREAD

**Issue by 1056824847** [flutter-webrtc/flutter-webrtc#1143]
**Describe the bug**
When using screen sharing, the frame rate of the video is very low, especially on the ipad of ios, the frame rate is only about 2 frames per second.So the video looks very slow.
```
     static Future<LocalStream> getDisplayMedia({Constraints? constraints,DesktopCapturerSource? desktopCapturerSource}) async {
    var stream = await navigator.mediaDevices.getDisplayMedia(<String, dynamic>{
      'audio': true,
      'video': desktopCapturerSource == null && WebRTC.platformIsAndroid
          ? true
          : {
        'frameRate': 17,
        'deviceId': WebRTC.platformIsIOS ? 'broadcast' : {'exact': desktopCapturerSource!.id},
        'mandatory': {
          'minWidth': 1280,
          'minHeight': 720,
          'minFrameRate': 10
        }
      }
    });
    print(stream.getVideoTracks().toString());
    return LocalStream(stream, Constraints.defaults);
  }
```
But it seems useless for me to set the frame rate. How should I change the minimum frame rate?

**Platform information**

* **Flutter version**: 
```
-> % flutter doctor  
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.0, on macOS 12.6 21G115 darwin-arm, locale zh-Hans-CN)                                     Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
[✓] VS Code (version 1.72.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```
* **Plugin version**:  0.9.11
* **OS**: Android (11) / iOS (15.6)/  macos (12.6)

**Comment by jonghanL** [comment]
Same with me. did you solve it? T.T

**Comment by mohd-afid** [comment]
@1056824847 how you got stream from broadcast extension in screen sharing
  Map<String, dynamic> mediaConstraints = <String, dynamic>{
      'audio': false,
      'video': {
        'mandatory': {
          'minWidth':
          '320', // Provide your own width, height and frame rate here
          'minHeight': '240',
          'minFrameRate': '30',
        },
        'displaySurface': 'application'
      },
      'deviceId': 'broadcast',
    };
when i calling getdisplaymedia the stream of  contents of your app  only getting . how to get full entire screen ?

**Comment by FlawLessx** [comment]
@mohd-afid Put your devideId inside video
