### ISSUE TITLE
'WebRTC/RTCCVPixelBuffer.h' file not found

### ISSUE THREAD

**Issue by lyricdon** [flutter-webrtc/flutter-webrtc#1156]
**Describe the bug**
Lexical or Preprocessor Issue (Xcode): 'WebRTC/RTCCVPixelBuffer.h' file not found
/Users/lyric/.pub-cache/hosted/pub.flutter-io.cn/flutter_webrtc-0.9.11/ios/Classes/Broadcast/FlutterSocketConnectionFrameReader.m:9:8

I can build apk, but I can not archive ipa!

* **Flutter version**: 
* [✓] Flutter (Channel stable, 3.3.2, on macOS 12.3 21E230 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.3.2 on channel stable at /Users/lyric/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (8 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/lyric/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13F100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.3 21E230 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by lyricdon** [comment]
CompileC /Users/lyric/Library/Developer/Xcode/DerivedData/Runner-fvkustipvhqgatdbczioufhwzuef/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/flutter_webrtc.build/Objects-normal/arm64/FlutterSocketConnectionFrameReader.o /Users/lyric/.pub-cache/hosted/pub.flutter-io.cn/flutter_webrtc-0.9.11/ios/Classes/Broadcast/FlutterSocketConnectionFrameReader.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'flutter_webrtc' from project 'Pods')
    cd /Users/lyric/Desktop/ganlin-app/ios/Pods
    export LANG\=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target arm64-apple-ios13.0 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu11 -fobjc-arc -fmodules -gmodules -fmodules-cache-path\=/Users/lyric/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/lyric/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -fmodule-name\=flutter_webrtc -Wno-trigraphs -fpascal-strings -Os -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DPOD_CONFIGURATION_RELEASE\=1 -DCOCOAPODS\=1 -DNS_BLOCK_ASSERTIONS\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.5.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fembed-bitcode -iquote /Users/lyric/Library/Developer/Xcode/DerivedData/Runner-fvkustipvhqgatdbczioufhwzuef/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/flutter_webrtc.build/flutter_webrtc-generated-files.hmap -I/Users/lyric/Library/Developer/Xcode/DerivedData/Runner-fvkustipvhqgatdbczioufhwzuef/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/flutter_webrtc.build/flutter_webrtc-own-target-headers.hmap -I/Users/lyric/Library/Developer/Xcode/DerivedData/Runner-fvkustipvhqgatdbczioufhwzuef/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/flutter_webrtc.build/flutter_webrtc-all-non-framework-target-headers.hmap -ivfsoverlay /Users/lyric/Library/Developer/Xcode/DerivedData/Runner-fvkustipvhqgatdbczioufhwzuef/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/flutter_webrtc.build/all-product-headers.yaml -iquote /Users/lyric/Library/Developer/Xcode/DerivedData/Runner-fvkustipvhqgatdbczioufhwzuef/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/flutter_webrtc.build/flutter_webrtc-project-headers.hmap -I/Users/lyric/Library/Developer/Xcode/DerivedData/Runner-fvkustipvhqgatdbczioufhwzuef/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/flutter_webrtc/include -I/Users/lyric/Library/Developer/Xcode/DerivedData/Runner-fvkustipvhqgatdbczioufhwzuef/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/flutter_webrtc.build/DerivedSources-normal/arm64 -I/Users/lyric/Library/Developer/Xcode/DerivedData/Runner-fvkustipvhqgatdbczioufhwzuef/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/flutter_webrtc.build/DerivedSources/arm64 -I/Users/lyric/Library/Developer/Xcode/DerivedData/Runner-fvkustipvhqgatdbczioufhwzuef/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/flutter_webrtc.build/DerivedSources -F/Users/lyric/Library/Developer/Xcode/DerivedData/Runner-fvkustipvhqgatdbczioufhwzuef/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/flutter_webrtc -F/Users/lyric/Desktop/flutter/bin/cache/artifacts/engine/ios-release/Flutter.xcframework/ios-arm64 -F/Users/lyric/Desktop/ganlin-app/ios/Pods/WebRTC-SDK -F/Users/lyric/Library/Developer/Xcode/DerivedData/Runner-fvkustipvhqgatdbczioufhwzuef/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/XCFrameworkIntermediates/WebRTC-SDK -include /Users/lyric/Desktop/ganlin-app/ios/Pods/Target\ Support\ Files/flutter_webrtc/flutter_webrtc-prefix.pch -MMD -MT dependencies -MF /Users/lyric/Library/Developer/Xcode/DerivedData/Runner-fvkustipvhqgatdbczioufhwzuef/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/flutter_webrtc.build/Objects-normal/arm64/FlutterSocketConnectionFrameReader.d --serialize-diagnostics /Users/lyric/Library/Developer/Xcode/DerivedData/Runner-fvkustipvhqgatdbczioufhwzuef/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/flutter_webrtc.build/Objects-normal/arm64/FlutterSocketConnectionFrameReader.dia -c /Users/lyric/.pub-cache/hosted/pub.flutter-io.cn/flutter_webrtc-0.9.11/ios/Classes/Broadcast/FlutterSocketConnectionFrameReader.m -o /Users/lyric/Library/Developer/Xcode/DerivedData/Runner-fvkustipvhqgatdbczioufhwzuef/Build/Intermediates.noindex/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/flutter_webrtc.build/Objects-normal/arm64/FlutterSocketConnectionFrameReader.o

/Users/lyric/.pub-cache/hosted/pub.flutter-io.cn/flutter_webrtc-0.9.11/ios/Classes/Broadcast/FlutterSocketConnectionFrameReader.m:10:9: fatal error: 'WebRTC/RTCCVPixelBuffer.h' file not found
#import <WebRTC/RTCCVPixelBuffer.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by lyricdon** [comment]
啥情况啊, 兄弟? 支援一波, 脑瓜子疼

**Comment by minhdangoz** [comment]
Could you pls change architecture to arm64 and try to build release ipa again

<img width="544" alt="image" src="https://user-images.githubusercontent.com/3844258/201577908-c58804a4-d5e2-40eb-a510-13d1d37c883d.png">

**Comment by lyricdon** [comment]
thanks, It works ! 
only change architecture to arm64 is not enough, 
also need to change Build Active Architecture Only to Yes
