### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by wangzewa** [flutter-webrtc/flutter-webrtc#1169]
webrtc version:0.9.14
error:[!] CocoaPods could not find compatible versions for pod "WebRTC-SDK":
  In snapshot (Podfile.lock):
    WebRTC-SDK (= 104.5112.02)

  In Podfile:
    flutter_webrtc (from `.symlinks/plugins/flutter_webrtc/ios`) was resolved to 0.9.13, which depends on
      WebRTC-SDK (= 104.5112.06)

Specs satisfying the `WebRTC-SDK (= 104.5112.02), WebRTC-SDK (= 104.5112.06)` dependency were found, but they required a higher minimum deployment target.

current target: platform :ios, '12.1'
what is the minimum deployment target of 0.9.14 version.

**Comment by tigrenok00** [comment]
@wangzewa  I have the same error, what was your solution?

**Comment by wangzewa** [comment]
> @wangzewa I have the same error, what was your solution?

In your project, "cd ios" and then try "pod update WebRTC-SDK --verbose "
