### ISSUE TITLE
Issue with dual sim on iPhone

### ISSUE THREAD

**Issue by magdabudzinskagoodsoft** [flutter-webrtc/flutter-webrtc#1171]
There is problem with establish connection when on iPhone both a physical SIM and the eSIM are in use and device works over the mobile network. 
RTCIceGatheringState goes from gathering to complete in about 20 seconds. In case of connection via wifi or with only one sim card, this time is 2s. During this time the websocket operation is disturbed. This websocket is used to send connection information (for example ice candidates, offer, answer). It takes long time to establish connection (~40s) because websocket messages take a very long time. 

There is no problem when connect via wifi or with only one sim enabled. 

[✓] Flutter (Channel stable, 3.3.8, on macOS 12.6 21G115 darwin-arm, locale en-PL)
    • Flutter version 3.3.8 on channel stable at /Users/magdabudzinska/Library/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (5 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/magdabudzinska/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • iPhone 11 pro (mobile) • 00008030-001669D4028A802E • ios            • iOS 16.1 20B82
    • macOS (desktop)        • macos                     • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

**Comment by cloudwebrtc** [comment]
you should use `Trickle ICE`, so you don't have to wait for `RTCIceGatheringStateComplete`.
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

**Comment by magdabudzinskagoodsoft** [comment]
I don't wait for RTCIceGatheringStateComplete. I send single ICE candidate when it become available, but each message with ice candidate takes a long time to send. It looks like there was a problem with the internet while collecting candidates. After change status to RTCIceGatheringStateComplete, internet is back to normal.

**Comment by cloudwebrtc** [comment]
Do you mean it took a long time to send the candidate via websocket signaling?

**Comment by magdabudzinskagoodsoft** [comment]
Yes exactly

**Comment by magdabudzinskagoodsoft** [comment]
This code solved my problem 
`let fieldtrials = [kRTCFieldTrialUseNWPathMonitor: kRTCFieldTrialEnabledValue]
      RTCInitFieldTrialDictionary(fieldtrials)`

**Comment by JiaoLiu** [comment]
> This code solved my problem `let fieldtrials = [kRTCFieldTrialUseNWPathMonitor: kRTCFieldTrialEnabledValue] RTCInitFieldTrialDictionary(fieldtrials)`

same problem, where did you add those code?
