### ISSUE TITLE
Linux appears to be broken after installing flutter_webrtc

### ISSUE THREAD

**Issue by Joe-Blow** [flutter-webrtc/flutter-webrtc#1174]
**Describe the bug**
flutter run -d linux fails after installing flutter_webrtc

/snap/flutter/current/usr/lib/x86_64-linux-gnu/libglib-2.0.so && :
[   +1 ms] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libwayland-server.so.0: undefined reference to `pthread_setspecific@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libgbm.so.1: undefined reference to `dlopen@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libgbm.so.1: undefined reference to `fstat64@GLIBC_2.33'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libgbm.so.1: undefined reference to `dlerror@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libgbm.so.1: undefined reference to `stat64@GLIBC_2.33'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libwayland-server.so.0: undefined reference to `pthread_getspecific@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libgbm.so.1: undefined reference to `dlclose@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libwayland-server.so.0: undefined reference to `pthread_once@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libwayland-server.so.0: undefined reference to `pthread_key_create@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libgbm.so.1: undefined reference to `dlsym@GLIBC_2.34'
[        ] /snap/flutter/current/usr/bin/ld: /lib/x86_64-linux-gnu/libwayland-server.so.0: undefined reference to `lstat64@GLIBC_2.33'
[        ] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[   +1 ms] ninja: build stopped: subcommand failed.
[   +7 ms] Building Linux application... (completed in 4.3s)
[        ] Exception: Build process failed
[   +2 ms] "flutter run" took 4,812ms.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:713:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1209:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
           
[  +36 ms] ensureAnalyticsSent: 35ms
[        ] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 1

**To Reproduce**

**Expected behavior**

**Platform information**

* **Flutter version**: 
* [✓] Flutter (Channel stable, 3.3.8, on Ubuntu 22.04.1 LTS 5.15.0-52-generic, locale
    en_US.UTF-8)
    • Flutter version 3.3.8 on channel stable at /home/joe/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 52b3dc25f6 (8 days ago), 2022-11-09 12:09:26 +0800
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0
* [✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

* **Plugin version**:
* any version after  v0.8.12
* 
* **OS**: 
* Linux Desktop 
* 
* **OS version**:
* Ubuntu 22.04.1 LTS

**Comment by cloudwebrtc** [comment]
okay, I also encountered the same problem, the flutter sdk installed with snap will not be able to link libwebrtc.so correctly, you only need to download the stable sdk from flutter.dev and install it according to the official instructions to compile and run correctly.

**Comment by cloudwebrtc** [comment]
Actually the first version of flutter-webrtc to support linux is 0.9.16, this problem seems to be related to wayland, not flutter-webrtc

**Comment by Joe-Blow** [comment]
I got this resolved. The problem was using the snap package. Thank you for your help!

These are the steps I took:

snap remove flutter
Download flutter as a tar file [here](https://docs.flutter.dev/get-started/install/linux).
cd ~/development
tar xf ~/Downloads/flutter_linux_3.3.8-stable.tar.xz
export PATH="$PATH:`pwd`/flutter/bin"
sudo apt-get update
sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
flutter doctor

**Comment by PeterNjeim** [comment]
I don't use the snap version and it's still linking libwebrtc.so incorrectly. I tried using WSL, tried using a clean Ubuntu 22.04 VM, nothing's working for me. I followed Joe-Blow's instructions. Version 0.9.17. Flutter 3.3.9. It keeps linking to the `linux/flutter/ephemeral/.plugin_symlinks` location. Any help is appreciated

**Comment by cloudwebrtc** [comment]
Can you use `flutter run -v` to print out error messages?

**Comment by cloudwebrtc** [comment]
You can `rm -rf linux/flutter/ephemeral && flutter pub get`, and call `flutter run` again.

**Comment by PeterNjeim** [comment]
I'm using `flutter build --linux`, and the app works fine, no errors, just that it's not portable. If I move the `bundle` folder to another computer, it won't use the `libwebrtc.so` file that is in the `lib` folder, and instead say that it doesn't find it. The `ldd` command shows it linked to the `ephemeral` folder, instead of the local `lib` like the other `.so` files, despite the fact that the `libwebrtc.so` file is present in the `lib` folder along with the other `.so` files.

I tried using the `run` command instead, producing a debug build. No errors in the verbose build output, and I can't see anything that would make `libwebrtc.so` act any differently than the other `.so` files in the `lib` folder. Tried deleting the `ephemeral` folder, same result.

**Comment by PeterNjeim** [comment]
Fixed it by running `patchelf --add-needed libwebrtc.so build/linux/x64/release/bundle/<name>`. After running this command, `libwebrtc.so` is added to the `Dynamic Section` as `NEEDED` from `objdump -p build/linux/x64/release/bundle/<name>`. This works because the `RUNPATH` is set to `$ORIGIN/lib` in the `Dynamic Section`, meaning it'll look in the local `lib` folder when trying to find the `libwebrtc.so` file. Maybe this is enough information to help you track down the problem

**Comment by henri2h** [comment]
The issue is that `libflutter_webrtc_plugin.so` has the wrong RUNPATH.

```
objdump -p  build/linux/x64/release/bundle/lib/libflutter_webrtc_plugin.so
```

Adding `set(CMAKE_INSTALL_RPATH "$ORIGIN/lib")` into this library CMakeList (`linux/CMakeLists.txt`) doesn't resolve the issue. https://github.com/flutter/flutter/issues/65400 might be why.

A temporal workaround is to run

```
patchelf  build/linux/x64/release/bundle/lib/libflutter_webrtc_plugin.so  --set-rpath "\$ORIGIN"
```

Which correct the library RUNPATH and thus making the app properly portable.

**Comment by PeterNjeim** [comment]
Temporary*, not "temporal". Temporal means related to time, temporary means for a short period of time.
