### ISSUE TITLE
captureFrame and MediaRecorder produce desaturated images/videos with artefacts

### ISSUE THREAD

**Issue by Parfyonator** [flutter-webrtc/flutter-webrtc#1176]
**Describe the bug**
Captured frames and recorded videos appear to be desaturated with some artefacts such as oblique stripes of blue and red and a green horizontal line at the bottom.

**To Reproduce**
In my case this plugin is used as dependency in `livekit_client` (version: 1.1.6).
*Frame capture*
After the `room` (instance of class `Room`) is 
```
final videoTrack = room.localParticipant.videoTracks?.firstOrNull;
final frameBuffer = await videoTrack?.track?.mediaStreamTrack?.captureFrame();
final img = frameBuffer.asUint8List();
```
In order to display the image `img` one can use the following widget `Image.memory(img)`.
*Video recording*
Create an instance of MediaRecorder: `MediaRecorder mediaRecorder = MediaRecorder();`. Then assuming the `Room` instance is created, in order to get a 5 seconds sample video recording the following code may be used
```
Future.delayed(
  Duration(seconds: 5),
  () => mediaRecorder.start(
    '/storage/emulated/0/Download/sample_recording.mp4',
    videoTrack: room.localParticipant.videoTracks.firstOrNull.track.mediaStreamTrack,
  ).then(
    (value) => Future.delayed(Duration(seconds: 5), mediaRecorder.stop)
  )
);
```

**Expected behavior**
Get the same image/video quality of captured frame or recorded video as a render of the video track in a widget. 

**Platform information**

* **Flutter version**: 
```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.5.1 21G83 darwin-arm, locale en-UA)
    • Flutter version 3.3.4 on channel stable at /Users/parf/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (6 weeks ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/parf/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.73.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.5.1 21G83 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
* **Plugin version**: 0.9.9+hotfix.1
* **OS**: Android
* **OS version**: 12

**Comment by Perondas** [comment]
Can reproduce on plenty of android devices. 
Does not happen on iOS

**Comment by Perondas** [comment]
![image](https://user-images.githubusercontent.com/47948606/216595232-c753d917-8659-44e6-b414-9cd452880d6e.png)
![image](https://user-images.githubusercontent.com/47948606/216595259-4e24a5a0-d7a3-4714-906f-a8ccf775043e.png)

Here are 2 example images. The square is supposed to be green in the first, and red in the second image. 

I am trying to look into what is causing this issue. 
I have 2 working theories: 
1. [This](https://github.com/flutter-webrtc/flutter-webrtc/blob/main/android/src/main/java/com/cloudwebrtc/webrtc/record/FrameCapturer.java#:~:text=YuvHelper.I420ToNV12(y%2C%20strides%5B0%5D%2C%20v%2C%20strides%5B2%5D%2C%20u%2C%20strides%5B1%5D%2C%20yuvBuffer%2C%20width%2C%20height)%3B) conversion is not working correctly.
2. [Or this] (https://github.com/flutter-webrtc/flutter-webrtc/blob/main/android/src/main/java/com/cloudwebrtc/webrtc/record/FrameCapturer.java#:~:text=yuvImage.compressToJpeg,)%3B) compression is misinterpreting the YUV byte array.

Things I have tried:
* Manually convert the i420 buffer to an NV21 array
* Manually convert the i420 buffer to an NV12 array 
* See if the strides buffer does anything much (not that I can tell)

**Comment by Perondas** [comment]
@cloudwebrtc Could this get the bug tag?

**Comment by Parfyonator** [comment]
Hi. I found this [library](https://github.com/crow-misia/libyuv-android). It seems to have the required function [`I420ToNV12`](https://github.com/crow-misia/libyuv-android/blob/ffaea9bc63f8db0d7bc9e77a1ea0fca7a1d70b55/core/src/main/java/io/github/crow_misia/libyuv/Yuv.kt#L938). I didn't have the opportunity to test it but according to @ChihayaK in [this](https://github.com/flutter-webrtc/flutter-webrtc/issues/496) the implementation in this library (`libyuv`) works fine for android.
@cloudwebrtc can you use this library for android?

**Comment by Perondas** [comment]
@Parfyonator from what I can tell, that library is already used for the i420 to NV12 step. That exact function is called natively. 
I may try and hand implement i420 to RGB just to see if that is the issue. 

On that note, in the code the i420 frame is converted to a NV12 array. The YUVFrame is however constructed with the NV21 parameter, and [does not support NV12](https://developer.android.com/reference/android/graphics/YuvImage#compressToJpeg(android.graphics.Rect,%20int,%20java.io.OutputStream):~:text=to%20a%20jpeg.-,Only%20ImageFormat.NV21%20and%20ImageFormat.YUY2,-are%20supported%20for). That doesn't seem to be the issue however, as I tried converting to NV21 and it still had the same color issue. 
It would also result in a different defect, as NV12 and NV21 only differ in that the U and V channels are switched.

**Comment by Perondas** [comment]
@Parfyonator fixed the captureFrame part of the issue. I would appreciate if you could test it.

**Comment by Parfyonator** [comment]
Hi @Perondas. Sorry that didn't respond when you've just made a fix. Yes, looks like the problem is solved. Thank you.
