### ISSUE TITLE
Asks for microphone permission, even when audio isn't used

### ISSUE THREAD

**Issue by rostopira** [flutter-webrtc/flutter-webrtc#118]
Request for microphone permission is showing, even if it's not used on iOS
It's bug in WebRTC framework: https://bugs.chromium.org/p/webrtc/issues/detail?id=10396

Be aware, that if you app doesn't use microphone it might be rejected by Apple
Looks like WebRTC team don't care about it

**Comment by cloudwebrtc** [comment]
It seems that the AudioUnit of iOS audio device defaults to full-duplex startup, regardless of whether or not recording is required.

**Comment by kurtiev** [comment]
Hello.
@rostopira Do you know how to manage this?
