### ISSUE TITLE
Execution failed for task ':flutter_webrtc:compileDebugKotlin'

### ISSUE THREAD

**Issue by Tim-byte-afk** [flutter-webrtc/flutter-webrtc#1182]
Hello!

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_webrtc:compileDebugKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':flutter_webrtc:compileDebugKotlin'
   > Could not resolve all files for configuration ':flutter_webrtc:debugCompileClasspath'.
      > Failed to transform android-104.5112.03.jar (com.github.webrtc-sdk:android:104.5112.03) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
         > Could not find android-104.5112.03.jar (com.github.webrtc-sdk:android:104.5112.03).
           Searched in the following locations:
               https://jitpack.io/com/github/webrtc-sdk/android/104.5112.03/android-104.5112.03.jar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
Exception: Gradle task assembleDebug failed with exit code 1

doctor --verbose

[✓] Flutter (Channel unknown, 3.0.0, on macOS 13.0.1 22A400 darwin-arm, locale en-GE)
    • Flutter version 3.0.0 at /development/flutter
    • Upstream repository unknown
    • Framework revision ee4e09cce0 (7 months ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • sdk gphone arm64 (mobile) • emulator-5556 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

can you help me to fix problem?

**Comment by Tim-byte-afk** [comment]
The problem appears from version 0.9.9+hotfix.1 and higher.

**Comment by Clement-Marchais-Wiztivi** [comment]
Same issues with Flutter 3.3.8. Any ideas ?

**Comment by Clement-Marchais-Wiztivi** [comment]
@Tim-byte-afk  use git url instead of version, the [fix](https://github.com/webrtc-sdk/android/commit/28e5d742115bc6f0499e9e0ef288a18921b358c9) is not available on pub dev for now

**Comment by Tim-byte-afk** [comment]
@Clement-Marchais-Wiztivi Thanks for the quick fix!

**Comment by Taym95** [comment]
You mean use `flutter-webrtc` from git?
