### ISSUE TITLE
android error could not find android-104.5112.03.jar (com.github.webrtc-sdk:android:104.5112.03).

### ISSUE THREAD

**Issue by bilalgodesto** [flutter-webrtc/flutter-webrtc#1184]
When creating apk file when i run ``` flutter build apk ``` i am getting

```
Execution failed for task ':flutter_webrtc:compileReleaseKotlin'.
> Could not resolve all files for configuration ':flutter_webrtc:releaseCompileClasspath'.
   > Failed to transform android-104.5112.03.jar (com.github.webrtc-sdk:android:104.5112.03) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find android-104.5112.03.jar (com.github.webrtc-sdk:android:104.5112.03).
        Searched in the following locations:
            https://jitpack.io/com/github/webrtc-sdk/android/104.5112.03/android-104.5112.03.jar
```

**To Reproduce**
With the latest version of flutter add latest flutter_webrtc and create apk.
<details>
<summary>
flutter doctor -v
</summary>
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.1 21C52 darwin-arm, locale en-GB)
    • Flutter version 3.3.9 on channel stable at /Users/bilalrabbi/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (3 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/bilalrabbi/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • ANDROID_HOME = /Users/bilalrabbi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (3 available)
    • iPhone 12 (mobile) • 7C6BAF92-BF07-42B2-A865-516A805D5F50 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.1 21C52 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 107.0.5304.121

[✓] HTTP Host Availability
    • All required HTTP hosts are available
</details>

**Platform information**

* **Flutter version**:  3.3.9
* **Plugin version**:   flutter_webrtc: ^0.9.16
* **OS**: Android
* **OS version**: Mac OS monterey

**Comment by thejufo** [comment]
Facing the same issue here, any solution yet?

**Comment by codesalatdev** [comment]
@thejufo you can use the git repo as a source for the dependency. There is a commit on master that's not included in the 0.9.16 release.

In your pubspec:
```
flutter_webrtc:
  git: https://github.com/flutter-webrtc/flutter-webrtc
```
This resulted in a successful build for me.

**Comment by quangkhaidam93** [comment]
I have the same problem

**Platform information**

- Flutter version: 3.3.7
- Package version: flutter_webrtc:0.9.14
- OS: Android
- OS Version: macOS Ventura 13.0.1

**Comment by quangkhaidam93** [comment]
> @thejufo you can use the git repo as a source for the dependency. There is a commit on master that's not included in the 0.9.16 release.
> 
> In your pubspec:
> 
> ```
> flutter_webrtc:
>   git: https://github.com/flutter-webrtc/flutter-webrtc
> ```
> 
> This resulted in a successful build for me.

Is there any other workaround? Because **livekit_client** conflicts with git version of **flutter_webrtc**. Thank you in advance.

**Comment by quangkhaidam93** [comment]
I have solved it by go to downloaded package and change 1 line in **android/build.gradle**

`
implementation 'com.github.webrtc-sdk:android:104.5112.03' // -> change to
implementation 'com.github.webrtc-sdk:android:104.5112.05'
`

You can find downloaded package either in **$HOME/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-{version}** or **$HOME/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-{version}** (flutter location dir)

**Comment by Silfalion** [comment]
Hello! Thank you for the fix, though I'm experiencing the same issue in Github actions with the follow error:

```
 What went wrong:
Execution failed for task ':flutter_webrtc:generateReleaseRFile'.
> Could not resolve all files for configuration ':flutter_webrtc:releaseCompileClasspath'.
   > Could not resolve com.github.webrtc-sdk:android:104.5112.05.
     Required by:
         project :flutter_webrtc
      > Skipped due to earlier error
```

**Comment by wtus** [comment]
> Hello! Thank you for the fix, though I'm experiencing the same issue in Github actions with the follow error:
> 
> ```
>  What went wrong:
> Execution failed for task ':flutter_webrtc:generateReleaseRFile'.
> > Could not resolve all files for configuration ':flutter_webrtc:releaseCompileClasspath'.
>    > Could not resolve com.github.webrtc-sdk:android:104.5112.05.
>      Required by:
>          project :flutter_webrtc
>       > Skipped due to earlier error
> ```
> 
> * Flutter version: 3.3.10
> * Plugin version: flutter_webrtc: ^0.9.18
> * OS: Android
> * OS version: Ubuntu

same issue

**Comment by Ansh-Rathod** [comment]
> Hello! Thank you for the fix, though I'm experiencing the same issue in Github actions with the follow error:
> 
> ```
>  What went wrong:
> Execution failed for task ':flutter_webrtc:generateReleaseRFile'.
> > Could not resolve all files for configuration ':flutter_webrtc:releaseCompileClasspath'.
>    > Could not resolve com.github.webrtc-sdk:android:104.5112.05.
>      Required by:
>          project :flutter_webrtc
>       > Skipped due to earlier error
> ```
> 
> * Flutter version: 3.3.10
> * Plugin version: flutter_webrtc: ^0.9.18
> * OS: Android
> * OS version: Ubuntu

I'm having same issue on mac.

**Comment by cloudwebrtc** [comment]
This is an [issue ](https://github.com/jitpack/jitpack.io/issues/5289) in the jitpack repository, and there is nothing we can do about it,
You can download the corresponding libwebrtc.aar from here
https://github.com/webrtc-sdk/android/releases/tag/104.5112.03
