### ISSUE TITLE
App force close after dispose local stream on windows

### ISSUE THREAD

**Issue by MohsenHaydari** [flutter-webrtc/flutter-webrtc#1185]
* **Flutter version**: 
* Flutter version 3.3.9 on channel stable at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (5 days ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0
* **Plugin version**: 0.9.16
* **OS**: Windows
* **OS version**: windows 11

***
I tracked the issue and I find when I use dispose method of local media stream, the camera is still alive and don't close, but after 10-20 seconds  camera will deactivate and the app will be force closed

```

for (var i in localStream!.getTracks()) {
        i.stop();
      }
 localStream?.dispose();


```
10-20 seconds after dispose local stream, camera will be shutdown and app will be forced closed

**Comment by MohsenHaydari** [comment]
Problem found I should have closed the RTCPeerConnection before disposing it

**Comment by Nightwelf** [comment]
> Problem found I should have closed the RTCPeerConnection before disposing it

hi!
can you explain how you do it? please, show some more code
