### ISSUE TITLE
[iOS] Adopting Picture in Picture for video calls & Accessing the camera while multitasking

### ISSUE THREAD

**Issue by Iambiengcode** [flutter-webrtc/flutter-webrtc#1193]
Since iOS 16.0, capture session support multitasking, I want to enable captureSession.isMultitaskingCameraAccessEnabled = true and show Picture in Picture (PiP) when go to background in iOS.

I was able to start the picture-in-picture when join the video call, but it doesn't show camera in my PiP view, I try start PiP when app started and its can be show up user camera.

I think can show user's camera when join WebRTC video call if I can get correct capture session.

This is my swift code configuration Picture in Picture controller:

```swift
func configurationPiPViewController() {
        if #available(iOS 16.0, *) {
            // --> I want try to get [self.videoCapturer.captureSession] like in file [common/darwin/Classes/FlutterRTCMediaStream.m], I think it will work
            let captureSession = AVCaptureSession()
            // Configure the capture session.
            captureSession.beginConfiguration()
            if captureSession.isMultitaskingCameraAccessSupported {
                // Enable using the camera in multitasking modes.
                captureSession.isMultitaskingCameraAccessEnabled = true
            } else {
                print("NOT SUPPORT")
            }
            captureSession.commitConfiguration()
            let captureDevice = self.getFrontCamera(captureSession: captureSession)
            
            if (captureDevice != nil) {
                do {
                    let input = try AVCaptureDeviceInput(device: captureDevice!)
                    if (captureSession.canAddInput(input)) {
                        captureSession.addInput(input)
                        print("Add device input successfully")
                    }
                }catch let error {
                    print("Error Unable to initialize front camera:  \(error.localizedDescription)")
                }
            }
            
            if (PictureInPictureViewController.pipContentSource != nil && PictureInPictureViewController.pipVideoCallViewController != nil) {
                let videoPreviewLayer = AVCaptureVideoPreviewLayer(session: captureSession)
                    
                videoPreviewLayer.videoGravity = .resizeAspect
                videoPreviewLayer.connection?.videoOrientation = .portrait
                
                DispatchQueue.main.async {
                    videoPreviewLayer.frame = self.previewView.bounds
                }
                
                previewView.session = captureSession
                previewView.layer.addSublayer(videoPreviewLayer)
                
                DispatchQueue.global(qos: .userInitiated).async { [weak self] in
                    captureSession.startRunning()
                    print("captureSession isRunning:", captureSession.isRunning)
                    print("camera is multitask enabled:", captureSession.isMultitaskingCameraAccessEnabled)
                    print("camera is multitask supported:", captureSession.isMultitaskingCameraAccessSupported)
                }
                
                PictureInPictureViewController.pipController = AVPictureInPictureController(contentSource: PictureInPictureViewController.pipContentSource as! AVPictureInPictureController.ContentSource)
                PictureInPictureViewController.pipController?.canStartPictureInPictureAutomaticallyFromInline = false
                PictureInPictureViewController.pipController?.delegate = self
            }
        }
    }
```

- [Adopting Picture in Picture for video calls - Apple Docs](https://developer.apple.com/documentation/avkit/adopting_picture_in_picture_for_video_calls)
- [Accessing the camera while multitasking - Apple Docs](https://developer.apple.com/documentation/avfoundation/capture_setup/accessing_the_camera_while_multitasking)

**Comment by Iambiengcode** [comment]
I'm completed this feature! I edited repo webrtc-interface for public peer connection id, and in flutter-webrtc I create singleton instance, when join video call and receive remote stream, I will invoke method channel sent peer connection id and stream id for get RTCMediaStream in native iOS. See demo below:

https://user-images.githubusercontent.com/60530946/207387472-d92d5c65-05bb-44fe-bd83-d4d704428acc.MP4

**Comment by trungdang29122000** [comment]
Super cool!

**Comment by MCLeehuan** [comment]
-isMultitaskingCameraAccessSupported returns true for iPad Pro (4th generation), iPad Pro (5th generation) and iPad Air (5th generation).
Why did -isMultitaskingCameraAccessSupported return true for your iPhone？

**Comment by mohd-afid** [comment]
@Iambiengcode how you implemented pip mode in flutter. which package you used ?
is there any package support both ios and android ?

**Comment by fukemy** [comment]
to be honest I am sure that isMultitaskingCameraAccessSupported always return false on all iPhone devices, It's really hard to do it, @Iambiengcode can u share your ios native solution?

**Comment by Iambiengcode** [comment]
@MCLeehuan @fukemy read this [Apple Document](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_avfoundation_multitasking-camera-access) and fill [this form](https://developer.apple.com/contact/request/multitasking-camera-access/) for request camera multitasking, after your request approved, let define in Runner.entitlements file like below:

```entitlements
<key>com.apple.developer.avfoundation.multitasking-camera-access</key>
<true/>
```

**Comment by Iambiengcode** [comment]
@mohd-afid you can implement pip mode in Android with this package [simple_pip_mode](https://pub.dev/packages/simple_pip_mode), for iOS I implemented with native code following by this [Document](https://developer.apple.com/documentation/avkit/adopting_picture_in_picture_for_video_calls)

**Comment by Iambiengcode** [comment]
I can share my way for implement on iOS in [flutter-webrtc-demo](https://github.com/flutter-webrtc/flutter-webrtc-demo), it's maybe spent about 2 weeks for coding and document step by step. If @cloudwebrtc agree then I can start next week.

**Comment by mohd-afid** [comment]
@Iambiengcode is there any other documentation or sample project for IOS PIP mode implementation  ?

**Comment by itsthetaste** [comment]
@lambiengcode this looks awesome.

did your changes to webrtc_interface and flutter_webrtc make it into the repo?

**Comment by thammaknot** [comment]
@lambiengcode Did you get a chance to share your iOS implementation somewhere?
It sounds awesome and useful.

Thank you.

**Comment by lambiengcode** [comment]
@thammaknot  yesterday I were contributed to [this project](https://github.com/shohel01716/flutter-whip-pip) for implement PiP on iOS (currently it's not look like with video demo above but you can see my idea in there).

Here is video demo for this project:

https://user-images.githubusercontent.com/60530946/236081192-3f43f122-e398-4d39-a078-d56a4b06d2dc.MP4

**Comment by lambiengcode** [comment]
@itsthetaste yes, I need to changes them for get peer connection id

**Comment by thammaknot** [comment]
> @thammaknot yesterday I were contributed to [this project](https://github.com/shohel01716/flutter-whip-pip) for implement PiP on iOS (currently it's not look like with video demo above but you can see my idea in there).
> 
> Here is video demo for this project:
> 
>  pip_ios_demo_whip.MP4

Thank you so much! I'll check it out :)

**Comment by mihir-concetto** [comment]
@lambiengcode Is this IOS PIP demo working well?.

If yes then I will refer to this code

**Comment by lambiengcode** [comment]
@mihir-concetto  Definitely, it's working well and I'm using it in production [Askany](https://apps.apple.com/vn/app/askany-tư-vấn-hỏi-đáp/id1589217505) or reference my side project [Waterbus](https://github.com/lambiengcode/waterbus)
