### ISSUE TITLE
how to make  the audio/video sounds from speaker, it likes only through headphone

### ISSUE THREAD

**Issue by cuijinfeng68** [flutter-webrtc/flutter-webrtc#121]
how to make  the audio/video sounds from speaker, it likes only through headphone

**Comment by Condelab** [comment]
Make use of this plugin [https://github.com/kangshaojun/flutter-incall-manager](https://github.com/kangshaojun/flutter-incall-manager). Then to know how to apply it with your signalling file check out this [https://github.com/GioviQ/video-chat-experiment](https://github.com/GioviQ/video-chat-experiment). The guy sure did justice to it (answering and rejecting call inclusive) and the plugin also provides you with callback and busy tone. enjoy.

**Comment by cuijinfeng68** [comment]
> Make use of this plugin https://github.com/kangshaojun/flutter-incall-manager. Then to know how to apply it with your signalling file check out this https://github.com/GioviQ/video-chat-experiment. The guy sure did justice to it (answering and rejecting call inclusive) and the plugin also provides you with callback and busy tone. enjoy.

Thank you !

**Comment by CoreyCole** [comment]
@cuijinfeng68 did you figure it out? I don't think anywhere in https://github.com/GioviQ/video-chat-experiment does the developer call `incall.setForceSpeakerphoneOn(flag: ForceSpeakerType.FORCE_ON);`.

Using this force speakerphone function is working on android, but not iOS.

**Comment by animeshjain** [comment]
Have you tried using the `enableSpeakerphone` method on `MediaStreamTrack`. For instance, something like..

```
if (stream.getAudioTracks() != null) {
  stream.getAudioTracks().forEach((track) {
    track.enableSpeakerphone(true);
  });
}
```

This works for me on iOS.

**Comment by wer-mathurin** [comment]
@cuijinfeng68 : feel free to reopen the bug if @animeshjain response is not working for you.
