### ISSUE TITLE
Custom encryption (change data for encryption)

### ISSUE THREAD

**Issue by wilmakelcey** [flutter-webrtc/flutter-webrtc#1244]
Hello friends
This is a very important issue and it is a pity that this package does not have it

I want inside the package
https://pub.dev/packages/flutter_webrtc
In the audio and video mode, put the desired encryption

Any platform, especially the web version, is very important to me

I want to know where the data is sent to the server and exactly where it is received and displayed on the receiver side so that I can encrypt the data as I want.

Please answer, this is the problem of many people

Even WhatsApp and Telegram have their own encryption in WebRtc
I want to set up a custom encryption

thank you very much

**Comment by cloudwebrtc** [comment]
duplicated https://github.com/flutter-webrtc/flutter-webrtc/issues/1249
