### ISSUE TITLE
Infinite Buffering Of none-WebRTC Livestreams

### ISSUE THREAD

**Issue by MrTeeXD** [flutter-webrtc/flutter-webrtc#1252]
**Describe the bug**
Hey Flutter WebRTC Devs, I have a problem with the Flutter WebRTC version which is, I stream on a Platform called GlimeshTV. Glimesh is a next-generation streaming platform that eliminates stream delay and has a blazing fast chat. Glimesh has flagged some accounts to test streaming over WHIP (WebRTC HTTPS Ingest Protocol) and their Mobile App that uses this Library has that implementation to watch WebRTC Livestreams. However, Glimesh has ran into a problem where for some reason, your Library stopped playing back Glimesh's WebRTC Streams and therefor yields a infinite loading circle.

**To Reproduce**
You guys may have to join the Glimesh Discord and help Clone1018 to eliminate this issue.

**Expected behavior**
I expect that this Library would playback WebRTC Streams with no issues.

**Platform information**
Again, you may have to join the GlimeshTV Discord and ask Clone1018 for the required info.

**Comment by clone1018** [comment]
Hi folks, the issue actually exists in our usage of the library. We're testing out a very early version of WHEP negotiated streams, and the problem absolutely exists in our setup of the peer connection. We're in the process debugging it on our end but of course life gets in the way! At this time we do not need any specific assistance from flutter-webrtc -- however I want to take the time to thank you all for the great library!
