### ISSUE TITLE
dead loop?

### ISSUE THREAD

**Issue by cuijinfeng68** [flutter-webrtc/flutter-webrtc#126]
I/org.webrtc.Logging(28548): EglRenderer: Duration: 4006 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(28548): EglRenderer: Duration: 4005 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(28548): EglRenderer: Duration: 4004 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(28548): EglRenderer: Duration: 4005 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(28548): EglRenderer: Duration: 4006 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(28548): EglRenderer: Duration: 4006 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(28548): EglRenderer: Duration: 4004 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(28548): EglRenderer: Duration: 4006 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(28548): EglRenderer: Duration: 4006 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(28548): EglRenderer: Duration: 4004 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(28548): EglRenderer: Duration: 4003 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(28548): EglRenderer: Duration: 4005 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(28548): EglRenderer: Duration: 4004 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(28548): EglRenderer: Duration: 4005 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(28548): EglRenderer: Duration: 4006 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(28548): EglRenderer: Duration: 4005 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(28548): EglRenderer: Duration: 4004 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(28548): EglRenderer: Duration: 4006 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(28548): EglRenderer: Duration: 4004 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(28548): EglRenderer: Duration: 4004 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(28548): EglRenderer: Duration: 4006 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.

**Comment by cloudwebrtc** [comment]
Maybe you forgot to call RTCVideoRenderer.dispose?

**Comment by ChauNTM** [comment]
I call RTCVideoRenderer.dispose() already, even I init new RTCVideoRender but I still haven't receive any frame, do anyone help me?

**Comment by raimsargado** [comment]
Any updates on this? I am also getting this problem.

**Comment by ycherniavskyi** [comment]
Sorry, but to get any help with such a question/issue you need to be more specific. At last, you need to point the Flutter version, OS version, and maybe even device name. But to get precise help - a tiny demo project where this issue is reproduced could be provided.

**Comment by raimsargado** [comment]
Yea thanks. I always experience the  "EglRenderer: Duration: ... " as a continuous log when initiating a connection running the p2p call sample from the flutter webrtc demo. 
While replicating the issue for more than once , I found out that the signaling stream listeners are the  ones who were causing it.  So I had to put a filter like from the code below: 

FILE: signaling.dart

    _signaling.onLocalStream = ((stream) async {
      if (_isCallAnswered) {
        localRenderer.srcObject = stream;
      }
    });

    _signaling.onAddRemoteStream = ((stream) async {
      if (_isCallAnswered){
        remoteRenderer.srcObject = stream;
      }
    });

I guess I did it right .. And seems like Im getting the right log after the dispose as below: 

I/org.webrtc.Logging( 7773): EglRenderer: Releasing.
I/org.webrtc.Logging( 7773): GlShader: Deleting shader.
I/org.webrtc.Logging( 7773): EglRenderer: eglBase detach and release.
I/org.webrtc.Logging( 7773): EglRenderer: Releasing done.
I/org.webrtc.Logging( 7773): EglRenderer: Quitting render thread.

**Comment by PedroRTomas** [comment]
Hi there,
Have been any advances in this topic? @cloudwebrtc 
Configuring and running according to the example available at https://uiflutter.com/tutorial/flutter-webrtc-plugin-for-ios-android.html
I'm still experiencing this issue.

flutter version:
Channel beta, v1.17.0-3.2.pre, on Microsoft Windows [Version 10.0.18362.1016], locale pt-PT

Note: flutter doctor doesn't present any issues. Detected when running with Android device.

**Comment by MurtuzaSrashtaSoft** [comment]
same issue facing.

**Comment by MurtuzaSrashtaSoft** [comment]
I/org.webrtc.Logging(25267): EglRenderer: Duration: 4005 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.

**Comment by ghenry** [comment]
I'm seeing this using the on my own app which uses https://github.com/cloudwebrtc/dart-sip-ua :

```
I/org.webrtc.Logging(11666): EglRenderer: Duration: 4006 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging(11666): EglRenderer: Duration: 4005 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.
```

then I tested with the the example app from `dart-sip-ua` and see a successful call ends like so:

```
E/BufferQueueProducer(29961): [SurfaceTexture-0-29961-0] disconnect: not connected (req=1)
W/libEGL  (29961): EGLNativeWindowType 0x724cdad010 disconnect failed
I/org.webrtc.Logging(29961): EglRenderer: Releasing done.
I/org.webrtc.Logging(29961): EglRenderer: Quitting render thread.
I/org.webrtc.Logging(29961): EglRenderer: Releasing.
I/org.webrtc.Logging(29961): EglRenderer: eglBase detach and release.
I/mali_egl(29961): eglDestroySurface() in
I/mali_winsys(29961): delete_surface() [1x1] return
I/mali_egl(29961): eglDestroySurface() out
E/BufferQueueProducer(29961): [SurfaceTexture-0-29961-1] disconnect: not connected (req=1)
W/libEGL  (29961): EGLNativeWindowType 0x71d0700010 disconnect failed
I/org.webrtc.Logging(29961): EglRenderer: Quitting render thread.
I/org.webrtc.Logging(29961): EglRenderer: Releasing done.
```
and I don't see anymore `EglRenderer` logs, so it must be my app :-)

https://github.com/flutter-webrtc/dart-sip-ua/blob/b68eb7a66dcee9e3404343695e1eac167f03e6d8/example/lib/src/callscreen.dart#L59

This may help others.

**Comment by Ayman-Kortobaa** [comment]
> and I don't see anymore `EglRenderer` logs, so it must be my app :-)
> 
> [flutter-webrtc/dart-sip-ua@`b68eb7a`/example/lib/src/callscreen.dart#L59](https://github.com/flutter-webrtc/dart-sip-ua/blob/b68eb7a66dcee9e3404343695e1eac167f03e6d8/example/lib/src/callscreen.dart#L59)
> 
> This may help others.

Thank you so much for opening my eyes, I was having a similar issue and apparently, I wasn't disposing of all renderers which caused memory leaking and sometimes app crashes.

I am gonna share the issue I had for anyone else who has it:
I had a `Map<String, RTCVideoRenderer>` where I added to it the renderers for each participant in the session, and I was disposing of them correctly by using: 
```dart
    for (RTCVideoRenderer renderer in _remoteRenderers.values) {
		await renderer.dispose();
    }
    _remoteRenderers.clear();
```
when the session terminates.
But the issue is not only disposing, but creating unnecessary renderers and initializing them, this will keep them in the background causing memory leakage even if the variable is garbage collected on the Flutter side.
Don't create renderers unnecessarily, I used to create renderers and add them in both `onAddStream` and `onAddTrack` callbacks, which caused creating double renderers and only having one in memory to dispose of later.
So yeah, this is not an issue with the package but with how we use it and I suggest that it would be closed.

**Comment by ghenry** [comment]
Thanks for the follow up and knowledge share @Ayman-Kortobaa

**Comment by telinx** [comment]
you may Initialized RTCVideoRenderer twice or more, but dispose one time, check you code, I faced the same problem, it is my solution.

**Comment by Bharavi26** [comment]
i am getting white screen when opponent screen is not rendering ... anyone have idea about this ?
thank you.


when opponent screen is not rendering receiving this log..

`I/org.webrtc.Logging(28658): EglRenderer: Releasing.
I/org.webrtc.Logging(28658): GlShader: Deleting shader.
I/org.webrtc.Logging(28658): EglRenderer: eglBase detach and release.
D/Surface (28658): Surface::disconnect(this=0x7f5fb5c000,api=1)
I/BufferQueueProducer(28658): [SurfaceTexture-0-28658-19](this:0x7f4c5fa400,id:19,api:1,p:-1,c:28658) disconnect(P): api 1
I/BufferQueueConsumer(28658): [SurfaceTexture-0-28658-19](this:0x7f4c5fa400,id:19,api:1,p:-1,c:28658) getReleasedBuffers: returning mask 0xffffffffffffffff
D/GraphicBuffer(28658): unregister, handle(0x7f491693c0) (w:540 h:960 s:544 f:0x2 u:0x000300)
I/[MALI][Gralloc](28658): [-]r_hnd(0x7f491693c0), client(109), share_fd(261)
D/GraphicBuffer(28658): unregister, handle(0x7f49169320) (w:540 h:960 s:544 f:0x2 u:0x000300)
I/[MALI][Gralloc](28658): [-]r_hnd(0x7f49169320), client(109), share_fd(239)
D/GraphicBuffer(28658): unregister, handle(0x7f461907c0) (w:360 h:640 s:368 f:0x2 u:0x000300)
I/[MALI][Gralloc](28658): [-]r_hnd(0x7f461907c0), client(109), share_fd(259)
D/GraphicBuffer(28658): unregister, handle(0x7f49169500) (w:360 h:640 s:368 f:0x2 u:0x000300)
I/[MALI][Gralloc](28658): [-]r_hnd(0x7f49169500), client(109), share_fd(241)
D/Surface (28658): Surface::disconnect(this=0x7f5fb5c000,api=1)
I/BufferQueueProducer(28658): [SurfaceTexture-0-28658-19](this:0x7f4c5fa400,id:19,api:1,p:-1,c:28658) disconnect(P): api 1
I/org.webrtc.Logging(28658): EglRenderer: Quitting render thread.
I/org.webrtc.Logging(28658): EglRenderer: Releasing done.
I/BufferQueueConsumer(28658): [SurfaceTexture-0-28658-19](this:0x7f4c5fa400,id:19,api:1,p:-1,c:-1) disconnect(C)
D/GraphicBuffer(28658): unregister, handle(0x7f49169460) (w:360 h:640 s:368 f:0x2 u:0x000300)
I/[MALI][Gralloc](28658): [-]r_hnd(0x7f49169460), client(109), share_fd(264)
I/org.webrtc.Logging(28658): EglRenderer: Releasing.
I/org.webrtc.Logging(28658): EglRenderer: eglBase detach and release.
D/Surface (28658): Surface::disconnect(this=0x7f5fb5ea00,api=1)
I/BufferQueueProducer(28658): [SurfaceTexture-0-28658-20](this:0x7f4d569400,id:20,api:1,p:-1,c:28658) disconnect(P): api 1
I/BufferQueueConsumer(28658): [SurfaceTexture-0-28658-20](this:0x7f4d569400,id:20,api:1,p:-1,c:28658) getReleasedBuffers: returning mask 0xffffffffffffffff
D/Surface (28658): Surface::disconnect(this=0x7f5fb5ea00,api=1)
I/BufferQueueProducer(28658): [SurfaceTexture-0-28658-20](this:0x7f4d569400,id:20,api:1,p:-1,c:28658) disconnect(P): api 1
I/org.webrtc.Logging(28658): EglRenderer: Quitting render thread.
I/org.webrtc.Logging(28658): EglRenderer: Releasing done.
I/BufferQueueConsumer(28658): [SurfaceTexture-0-28658-20](this:0x7f4d569400,id:20,api:1,p:-1,c:-1) disconnect(C)`

**Comment by Bharavi26** [comment]
this thing is happening in demo also, i checked,
**steps for this issue in demo**
1. login in one device. (like witho user1) 
2. call to user2
3. open app in other device and login with user2
4. after login as soon as incoming screen apper because we are already calling from user1 from another device
5. after accepting call from user2

    getting blank screen of opponent user in both device (call screen)

**Comment by benyamin218118** [comment]
check your  ice servers list @cuijinfeng68 
make sure you are using a valid and ok turn server if you are running on global internet.

**Comment by elizaan** [comment]
> Maybe you forgot to call RTCVideoRenderer.dispose?

Where to call this?
