### ISSUE TITLE
DRAM usage jump after navigator.mediaDevices.getDisplayMedia, Mac Pro

### ISSUE THREAD

**Issue by sportmachine** [flutter-webrtc/flutter-webrtc#1272]
**Describe the bug**
MACOS: DRAM usage increase several GB per 20 sec, once 
navigator.mediaDevices.getDisplayMedia is called. more specifically after await WebRTC.invokeMethod is called.

I decrease resolution and frame rate =2, problem still there. within minutes, the memory go to dozens of GB for flutter app. likely due to captured and transferred frames are continuously stored in memory and not released. sent frame buffers need to be recycled (need buffer pooling, not allocating new memory, buffers that surpass max size should overwrite old of rounded buffers, so that the fix size buffer always contain the most recent frames)

**To Reproduce**
var stream = await navigator.mediaDevices.getDisplayMedia(<String, dynamic>{
        'video': mc.selected_source_ == null
            ? true
            : {
          'deviceId': {'exact': mc.selected_source_!.id},
          'mandatory': {'frameRate': 15.0}
        }
**Expected behavior**
slightly increase memory, not continue increase to dozen of GB

**Platform information**
MACOS, Mac Pro M1, 

* **Flutter version**: 
flutter_webrtc: ^0.9.23
* 
* **Plugin version**:
* **OS**: 
Desktop
* **OS version**:
MACOS ventural 13.2.1

**Comment by cloudwebrtc** [comment]
okay, This may be a bug at the native level

**Comment by cloudwebrtc** [comment]
Probably this line  https://github.com/webrtc-sdk/webrtc/blob/m104_release/sdk/objc/native/src/objc_desktop_capture.mm#L175 is missing a reference release
`
CVPixelBufferRelease(pixelBuffer);
`

**Comment by sportmachine** [comment]
yes, possibly there or somewhere later, after the imagebuffer finished passing to the network. Due to Huge image data, my guess is that we need to use buffer pooling to fix the number of buffers.

**Comment by cloudwebrtc** [comment]
https://github.com/webrtc-sdk/webrtc/pull/64

**Comment by sportmachine** [comment]
Excellent, so fast. how to generate configure file: "dotfile_settings.gni"

I find the compile command, but not the configure file before that: https://github.com/webrtc-sdk/webrtc-build/blob/main/docs/build.md

**Comment by cloudwebrtc** [comment]
you can try to delete `Podfile.lock`, and recompile.

**Comment by sportmachine** [comment]
I was able to get 0.9.24 working with new change. great. thanks a lot 👍  @cloudwebrtc
