### ISSUE TITLE
[iOS] Audio Output device switches to earpiece when mic is turner On and switch to speaker when mic turned off

### ISSUE THREAD

**Issue by rajansurani** [flutter-webrtc/flutter-webrtc#1284]
**Describe the bug**
When the user trie to turn ON the mic on **iOS devices**, the audio output switches from speaker to earpiece. And once the mic is turned OFF, audio output switches back to speaker.

Here is the similar issue reported on the live-kits flutter SDK.
https://github.com/livekit/client-sdk-flutter/issues/245

**To Reproduce**
Here is a test app, one can join from two iOS device and when the mic is turned on, the output device will be switched. 

https://testflight.apple.com/join/C1UOYbxh

**Expected behavior**
Audio output device should not switch when audio is toggled.

**Platform information**

* **Flutter version**:
 Flutter (Channel stable, 3.7.3, on macOS 13.1 22C65 darwin-arm64, locale
    en-IN)
    • Flutter version 3.7.3 on channel stable at
      /Users/dhiwise/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9944297138 (4 weeks ago), 2023-02-08 15:46:04 -0800
    • Engine revision 248290d6d5
    • Dart version 2.19.2
    • DevTools version 2.20.1
* **Plugin version**:
* **OS**:  iOS
* **OS version**: 16.1.1

**Comment by rajansurani** [comment]
Fixed in the version `0.0.24`

**Comment by rajansurani** [comment]
@fullflash as per docs of AVAudioSession, when using video chat, it allows to use the output device suitable for video calls, and since earpiece is not one of that, it seems to resolve the issue.

**Comment by shivanshtalwar0** [comment]
@rajansurani any update on #1285 ?
