### ISSUE TITLE
Linux build: libwebrtc.so: error adding symbols: file in wrong format

### ISSUE THREAD

**Issue by MosheYamini** [flutter-webrtc/flutter-webrtc#1331]
Hi

I am making a linux desktop build with sip_ua. And getting this error in the build:
```
../third_party/libwebrtc/lib/linux-x64/libwebrtc.so: error adding symbols: file in wrong format
[        ] clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Ubuntu: 20.04
Flutter: 3.7.1
Using docker

Any help will be appreciate...

**Comment by sbistram** [comment]
Hi Moshe, 
I have the same problem and actually it was the wrong file format - 32 instead 64 bit for an x86-64 architecture. You can check it by ``$ objdump -f <file>``. Now the library file for linux-x64 is completely missing, so I get a different error:
```
linux/flutter/ephemeral/.plugin_symlinks/flutter_webrtc/third_party/libwebrtc/lib/linux-x64/libwebrtc.so', needed by 'plugins/flutter_webrtc/libflutter_webrtc_plugin.so', missing and no known rule to make it
```
I hope someone is working on it ;-)

**Comment by cloudwebrtc** [comment]
hey @MosheYamini @sbistram, please try this branch https://github.com/flutter-webrtc/flutter-webrtc/pull/1335

**Comment by MosheYamini** [comment]
@cloudwebrtc Thank you very much! I am using the sip_ua package. I did a build now and its still failing with same error. Do I need to wait to version to come out for sip_ua? How can I use this fix?

**Comment by cloudwebrtc** [comment]
I will release a new version soon and bump flutter-webrtc version for dart-sip-ua

**Comment by MosheYamini** [comment]
Thank you! This is the fastest open source contibution team ever!

**Comment by sbistram** [comment]
I've just tested the new version 0.9.28 - works fine! 
Great support - Thanks!

**Comment by MosheYamini** [comment]
Works like a charm! Thamk you very much!
