### ISSUE TITLE
Screen Sharing - Using Broadcast Extension to share any app doesn't work

### ISSUE THREAD

**Issue by ipainchaud** [flutter-webrtc/flutter-webrtc#1345]
There are two different ways to share the screen on iOS described [here](https://github.com/flutter-webrtc/flutter-webrtc/wiki/iOS-Screen-Sharing): 

1. In-App
2. Broadcast Extension

I followed all the instructions described [here](https://github.com/flutter-webrtc/flutter-webrtc/wiki/iOS-Screen-Sharing) without success. It doesn't crash, doesn't give any error message, just doesn't seem to return the MediaStream containing the video track to transmit.

When I use the In-App screen sharing, no issue.

**To Reproduce**
Follow steps described [here](https://github.com/flutter-webrtc/flutter-webrtc/wiki/iOS-Screen-Sharing).

**Expected behavior**
The Screen should be shared.

* **Flutter version**: 
$ flutter doctor -v
[✓] Flutter (Channel stable, 3.7.12, on macOS 13.3.1 22E772610a darwin-x64, locale en-US)
    • Flutter version 3.7.12 on channel stable at /usr/local/Caskroom/flutter/3.0.2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (3 weeks ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/israelpainchaud/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] IntelliJ IDEA Community Edition (version 2022.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 222.4560

[✓] Connected device (3 available)
    • iPhone 14 (mobile) • FEFDB00B-9DAA-4FA0-87FA-5BAFBB333441 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-x64     • macOS 13.3.1 22E772610a darwin-x64
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 113.0.5672.92

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

* **Plugin version**: 0.9.26
* **OS**: iOS
* **OS version**: 16.4.1

**Comment by cloudwebrtc** [comment]
merged https://github.com/flutter-webrtc/flutter-webrtc/pull/1347
