### ISSUE TITLE
unable to run flutter app to open usb camera on ubuntu 22.04

### ISSUE THREAD

**Issue by learncodingforweb** [flutter-webrtc/flutter-webrtc#1352]
**Describe the bug**
clang: error: linker command failed with exit code 1 (use -v to see invocation)
**To Reproduce**
flutter create myapp
flutter pub add flutter_webrtc

added following code in main.dart

```
import 'package:flutter/material.dart';
import 'package:flutter_webrtc/flutter_webrtc.dart';

void main() {
  runApp(
    const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: HomeScreen(),
    ),
  );
}

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  final RTCVideoRenderer _localRenderer = RTCVideoRenderer();
  MediaStream? _localStream;

  @override
  void initState() {
    super.initState();
    openCamera();
  }

  @override
  void dispose() {
    try {
      _localStream?.dispose();
    } catch (e) {
      debugPrint(e.toString());
    }
    try {
      _localRenderer.dispose();
    } catch (e) {
      debugPrint(e.toString());
    }
    super.dispose();
  }

  Future<void> openCamera() async {
    await _localRenderer.initialize();
    try {
      _localStream = await navigator.mediaDevices.getUserMedia({'video': true});
      _localRenderer.srcObject = _localStream;
      setState(() {});
    } catch (e) {
      debugPrint(e.toString());
    }
  }

  Widget showCamera() {
    if (_localStream != null) {
      return RTCVideoView(_localRenderer);
    } else {
      return const CircularProgressIndicator();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Stack(
          children: [
            const Positioned(
              top: 0,
              left: 0,
              right: 0,
              child: Text("webrtc"),
            ),
            Positioned(
              bottom: 0,
              right: 0,
              child: SizedBox(
                width: 320,
                // height: 240,
                child: AspectRatio(
                  aspectRatio: 3 / 4,
                  child: showCamera(),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

**Expected behavior**
It should show usb camera attached with ubuntu 22.04
**Platform information**
uname -a
``  Linux notebook 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux  ``
* **Flutter version**: 
* Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on Ubuntu 22.04.2 LTS 5.19.0-41-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] VS Code (version 1.78.2)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

* **Plugin version**:
* flutter_webrtc: ^0.9.29+hotfix.1
* **OS**: 
*  ubuntu 22.04
* **OS version**:
* Linux notebook 5.19.0-41-generic 42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by learncodingforweb** [comment]
Hi,
    I am able to solve problem by following below steps
1) remove flutter installed by snap using ``sudo snap remove flutter``
2) deleted ``.dartServer`` inside home directoy
3) deleted ``.pub-cache`` inside home directoy
4) download flutter tar file and included its path in .bashrc
5) create new flutter and installed flutter_webrtc inside and included above code.

Then able to view camera in ubuntu.

conclusion, **flutter install from snap package is creating problem**.

**Comment by toantam1290** [comment]
clang: error: linker command failed with exit code 1 (use -v to see invocation)
i used newest version ([0.9.30+hotfix.2](https://github.com/flutter-webrtc/flutter-webrtc/releases/tag/0.9.30%2Bhotfix.2)) but still error

**Comment by learncodingforweb** [comment]
try to install flutter from tar file and include its path in .bashrc file. perform following. may be this will help
```
1) flutter clean
2) flutter pub get
```

**Comment by toantam1290** [comment]
i used ubuntu 20.04, and it encounter error . But with ubuntu 22.04, i can build lib flutter webrtc ok.
