### ISSUE TITLE
Linux build failing:  no member named 'max_ipv6_networks' in 'libwebrtc::RTCConfiguration'

### ISSUE THREAD

**Issue by MosheYamini** [flutter-webrtc/flutter-webrtc#1356]
flutter: 3.7.12
Linux
flutter_webrtc 0.9.30

/app/linux/flutter/ephemeral/.plugin_symlinks/flutter_webrtc/common/cpp/src/flutter_webrtc_base.cc:306:10: error: no member named 'max_ipv6_networks' in 'libwebrtc::RTCConfiguration'

**Comment by sbistram** [comment]
Hi Moshe,
jep, same for me using Flutter 3.10.0
Probably related to the changelog: [Darwin/Android/Windows/Linux] Added maxIPv6Networks configuration (#1350)

**Comment by cloudwebrtc** [comment]
I think you need to use
`flutter_webrtc: 0.9.29+hotfix.1`
replace
`flutter_webrtc: ^0.9.29+hotfix.1`

**Comment by cloudwebrtc** [comment]
It was my fault for not checking the PR for windows and Linux before merging, let me fix i

**Comment by cloudwebrtc** [comment]
fixed https://github.com/flutter-webrtc/flutter-webrtc/releases/tag/0.9.30%2Bhotfix.1

**Comment by sbistram** [comment]
Hi,
thanks for the support! 
I'm using **0.9.30+hotfix.1** now, but something has changed. Right now I don't know where it's coming from, but I get a simple **Lost connection to device** error when I run myh test app. With version **0.9.29+hotfix.1** that was not the case, but I cannot compare it because that tag is gone.

**Comment by Omar-Qalei** [comment]
I moved to the previous version and got the same issue on Windows.

**Comment by MosheYamini** [comment]
@cloudwebrtc I have successfully built Linux.
More info:
I am using the sip_ua plugin. Placed   flutter_webrtc: ^0.9.30+hotfix.1 in my pubspec.yaml to override the dependence. Because he didn't pick the HOTFIX version. Maybe you need to publish a new minor version so it will pick it.

**Comment by sbistram** [comment]
Hi,
I've just tested the main branch and it's working fine for me with Linux, Chrome and Android.
Thanks for your support - great job!

**Comment by cloudwebrtc** [comment]
> @cloudwebrtc I have successfully built Linux. More info: I am using the sip_ua plugin. Placed flutter_webrtc: ^0.9.30+hotfix.1 in my pubspec.yaml to override the dependence. Because he didn't pick the HOTFIX version. Maybe you need to publish a new minor version so it will pick it.

thanks for your testing, I will release a hotfix ASAP, which should be within tomorrow

**Comment by Omar-Qalei** [comment]
> @sbistram @Omar-Qalei @MosheYamini , I think this is a glitch caused by a recent PR, I should fix it, can you guys test the main branch? and let me know if the issue is fixed

Fixed thanks.
