### ISSUE TITLE
Multiple compiler warning on build macos

### ISSUE THREAD

**Issue by rshillington** [flutter-webrtc/flutter-webrtc#1362]
Several (more than is easily counted) compiler warnings on build.  Examples include:
warning: a block declaration without a prototype is deprecated
warning: 'NSOpenGLView' is deprecated: first deprecated in macOS 10.14 - Please use MTKView instead
warning: 'NSOpenGLPixelFormat' is deprecated: first deprecated in macOS 10.14 - Please use Metal or MetalKit.
(See attached output file)
[errors.txt](https://github.com/flutter-webrtc/flutter-webrtc/files/11529828/errors.txt)

**To Reproduce**
```
flutter create webrtc_bugreport -e --platforms macos
cd webrtc_bugreport
flutter pub add flutter_webrtc
flutter build macos
```

**Expected behavior**
compile without warnings

**Platform information**

* **Flutter version**: 
✓] Flutter (Channel stable, 3.10.1, on macOS 13.3.1 22E772610a darwin-arm64, locale en-CA)
    • Flutter version 3.10.1 on channel stable at /Users/ralphshillington/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d3d8effc68 (5 days ago), 2023-05-16 17:59:05 -0700
    • Engine revision b4fb11214d
    • Dart version 3.0.1
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/ralphshillington/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.78.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 113.0.5672.126

[✓] Network resources
    • All expected network resources are available.

* **Plugin version**:
flutter_webrtc: ^0.9.30+hotfix.2

* **OS**: 
Desktop (Apple M1 Pro)
* **OS version**:
macOS 13.3.1 (a)

**Comment by LiangHuangBC** [comment]
And after flutter clean, video is not showing on my mac app.

**Comment by cloudwebrtc** [comment]
ah, okay, Will try to create a PR to fix these warnings

**Comment by omofolarin** [comment]
Hello, please I'm having this issue also I can't build webrtc for macOS
