### ISSUE TITLE
Ios screenshare doesn't work when app is minimized in broadcast mode

### ISSUE THREAD

**Issue by shivanshtalwar** [flutter-webrtc/flutter-webrtc#1383]
**Describe the bug**
screen sharing in ios after setting up works fine for in app screenshare but as soon as app is minimized other user recieves no video i set it up using `deviceId:'broadcast'`

**To Reproduce**
try to see if you recieve screenshare video on other device from ios when app is minimized 

**Expected behavior**
video should be recieved in broadcast mode
**Platform information**

* **Flutter version**: 
`[✓] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64
    (Rosetta), locale en-CY)
    • Flutter version 3.10.5 on channel stable at
      /Users/utopia/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (10 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/utopia/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.79.2)
    • VS Code at /Users/utopia/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.66.0

[✓] Connected device (3 available)
    • Shivansh’s iPhone (mobile) • 00008101-001C1D5136F0001E • ios            •
      iOS 14.2.1 18B121
    • macOS (desktop)            • macos                     • darwin-arm64   •
      macOS 13.4.1 22F82 darwin-arm64 (Rosetta)
    • Chrome (web)               • chrome                    • web-javascript •
      Google Chrome 114.0.5735.133

[✓] Network resources
    • All expected network resources are available.

• No issues found!
`
* **Plugin version**:0.9.34
* **OS**: Ios
* **OS version**: 14.12.1

**Comment by shivanshtalwar** [comment]
@cloudwebrtc can you guide me after setting up broadcastExtension successfuly ios is recording the screen and saving it to storage instead of sending it to remote peer through webrtc stack

**Comment by JiaoLiu** [comment]
> @cloudwebrtc can you guide me after setting up broadcastExtension successfuly ios is recording the screen and saving it to storage instead of sending it to remote peer through webrtc stack

The simplest way is to modify 'FlutterSocketConnectionFrameReader.m' located at '../../../../../../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_webrtc-0.9.34/ios/Classes/Broadcast/FlutterSocketConnectionFrameReader.m'.

line 199 - 231

```
- (void)didCaptureVideoFrame:(CVPixelBufferRef)pixelBuffer
             withOrientation:(CGImagePropertyOrientation)orientation {
  int64_t currentTime = mach_absolute_time();
  int64_t currentTimeStampNs = currentTime * _timebaseInfo.numer / _timebaseInfo.denom;

  if (_startTimeStampNs < 0) {
    _startTimeStampNs = currentTimeStampNs;
  }

  RTCCVPixelBuffer* rtcPixelBuffer = [[RTCCVPixelBuffer alloc] initWithPixelBuffer:pixelBuffer];
  int64_t frameTimeStampNs = currentTimeStampNs - _startTimeStampNs;

  RTCVideoRotation rotation;
  switch (orientation) {
    case kCGImagePropertyOrientationLeft:
      rotation = RTCVideoRotation_90;
      break;
    case kCGImagePropertyOrientationDown:
      rotation = RTCVideoRotation_180;
      break;
    case kCGImagePropertyOrientationRight:
      rotation = RTCVideoRotation_270;
      break;
    default:
      rotation = RTCVideoRotation_0;
      break;
  }

  RTCVideoFrame* videoFrame = [[RTCVideoFrame alloc] initWithBuffer:rtcPixelBuffer
                                                           rotation:rotation
                                                        timeStampNs:frameTimeStampNs];

  [self.delegate capturer:self didCaptureVideoFrame:videoFrame];
}
```

The pixelBuffer is the video recording you want, and you can save it anywhere you want. If you don't want to send it through WebRTC, you can simply comment out `[self.delegate capturer:self didCaptureVideoFrame:videoFrame];`.

**Comment by shivanshtalwar0** [comment]
@JiaoLiu but i don't want to save it to storage and send it to webrtc but that's not what is happening i am not receiving any video on remote peer end just screen recording completes and is saved to storage when i press stop screen recording
The changes you suggest should implicitly work for webrtc but it isn't, i am not following how your suggested change solves the issue?

**Comment by JiaoLiu** [comment]
> @JiaoLiu but i don't want to save it to storage and send it to webrtc but that's not what is happening i am not receiving any video on remote peer end just screen recording completes and is saved to storage when i press stop screen recording The changes you suggest should implicitly work for webrtc but it isn't, i am not following how your suggested change solves the issue?

Do you want to screen share with another device? You should follow this [tutorial](https://github.com/flutter-webrtc/flutter-webrtc/wiki/iOS-Screen-Sharing).

some key points:
The info.plist of the main target must contain the `RTCAppGroupIdentifier` & `RTCScreenSharingExtension` item。

<img width="1003" alt="image" src="https://github.com/flutter-webrtc/flutter-webrtc/assets/4370982/715e2b37-fe42-41e0-9573-af7fb163f601">

The broadcast upload target also with the same bundle id.
<img width="787" alt="image" src="https://github.com/flutter-webrtc/flutter-webrtc/assets/4370982/0d82affd-20ee-49d9-942e-c3428ee49be7">


Before sharing your iPhone screen, the system alert view should only display your app but other apps(like photos etc.) if you have correctly set up the`RTCScreenSharingExtension`.

**Comment by shivanshtalwar0** [comment]
I have setup broadcast extension exactly like the tutorial that you shared but my problem is instead of sharing the screen with another device it starts recording screen of device to storage and i am not sure what is wrong why it is behaving that way

**Comment by JiaoLiu** [comment]
> I have setup broadcast extension exactly like the tutorial that you shared but my problem is instead of sharing the screen with another device it starts recording screen of device to storage and i am not sure what is wrong why it is behaving that way

Does 'it starts recording the screen of the device to storage' mean that it will be saved to the photo gallery? Before starting the screen recording, the system view will appear. Could you please provide screenshots?

**Comment by shivanshtalwar0** [comment]
Yes you are absolutely right video is being recorded and saved to photo gallery i will upload video of it in a bit

**Comment by JiaoLiu** [comment]
> Yes you are absolutely right video is being recorded and saved to photo gallery i will upload video of it in a bit

check this.

**Before sharing your iPhone screen, the system alert view should only display your app but other apps(like photos etc.) if you have correctly set up theRTCScreenSharingExtension.**

https://github.com/flutter-webrtc/flutter-webrtc/issues/1383#issuecomment-1606933426

**Comment by shivanshtalwar** [comment]
watch the screenrecording that was produced from `getDisplayMedia({'video':{'deviceId':'broadcast'}})`
https://drive.google.com/file/d/1IcXxny_q2o-piLYNvUeWwWFZSbO8qodQ/view?usp=sharing
i have tried everything still it shows broadcast recording instead of sharing broadcast to webrtc peer

**Comment by JiaoLiu** [comment]
> watch the screenrecording that was produced from `getDisplayMedia({'video':{'deviceId':'broadcast'}})` https://drive.google.com/file/d/1IcXxny_q2o-piLYNvUeWwWFZSbO8qodQ/view?usp=sharing i have tried everything still it shows broadcast recording instead of sharing broadcast to webrtc peer


The reason is that the RTCScreenSharingExtension and broadcast target bundle ID are not set correctly. The system couldn't find a workable target to start recording.

You had better carefully check the tutorial step by step again, or run the demo project.

Here is another tutorial that is more general
https://www.zegocloud.com/docs/video-call/screen-sharing?platform=ios&language=objective-c

**Comment by shivanshtalwar** [comment]
i tried again step by step the problem remains same :(

**Comment by shivanshtalwar0** [comment]
Is there any limitation on os version or any api difference of this approach?

**Comment by shivanshtalwar** [comment]
okay so after upgrading to ios16 it works
