### ISSUE TITLE
Does flutter_webrtc support AVD (Audio Voice Detection)?

### ISSUE THREAD

**Issue by maxmeng93** [flutter-webrtc/flutter-webrtc#1409]
Hello maintainers and contributors of `flutter_webrtc`,

I've been exploring the capabilities of the `flutter_webrtc` plugin and was curious to know if it supports Audio Voice Detection (AVD) functionality. I couldn't find any explicit mention of this feature in the documentation or the GitHub repository.

AVD is crucial for my project as it helps in optimizing bandwidth and provides a better user experience during voice calls by transmitting audio only when a user is speaking.

Could you please confirm if this feature is available or if there are any plans to implement it in the near future?

Thank you for your time and the great work on this plugin!

**Comment by cloudwebrtc** [comment]
hey  @maxmeng93,  libwebrtc does not expose the VAD interface, so flutter-webrtc cannot access the VAD status, but I think it is possible to obtain the stats information from the local track to obtain the audio level to judge the VAD status
https://developer.mozilla.org/en-US/docs/Web/API/RTCAudioSourceStats

**Comment by dunghacknicktao** [comment]
Currently I also really need the voice detection feature, could this be a feature in future updates? Or can you walk me through the integrations right now?
I tried getStats() every 500milisecount by peerConnection, then checked the stat type as 'inbound-rtp' along with the comparison condition audioLevel > 0.05 to say... however the return result is not there!

**Comment by btpf** [comment]
@dunghacknicktao 
I had success with using the type 'media-source'.
 ```dart
getAudioLevel() async{
        final sender = (await rtcPeerConnection!.getSenders())
        .firstWhere((s) => s.track?.kind == 'audio');

        Timer.periodic(Duration(milliseconds: 250), (timer) async {
          var stats = await sender.getStats();
          stats.forEach((report) {
          if (report.type == 'media-source') {
            var audioLevel = report.values['audioLevel'];
            print('Audio Level: $audioLevel');
          }
          });
        });
  }
```
