### ISSUE TITLE
Forgot to update podspec to 0.9.37

### ISSUE THREAD

**Issue by Taym95** [flutter-webrtc/flutter-webrtc#1414]
https://github.com/flutter-webrtc/flutter-webrtc/blob/5e6e3daa7cf44663dd9558342edbca9630726e7c/ios/flutter_webrtc.podspec#L6C24-L6C24

```
      In snapshot (Podfile.lock):
        WebRTC-SDK (= 104.5112.16)
      In Podfile:
        flutter_webrtc (from `.symlinks/plugins/flutter_webrtc/ios`) was resolved to 0.9.36, which depends on
          WebRTC-SDK (= 114.5735.02)

```

**Comment by pogenz45** [comment]
I have same error, I delete Podfile in IOS folder and run pod install again to fix this error
