### ISSUE TITLE
channel sent a message from native to Flutter on a non-platform thread

### ISSUE THREAD

**Issue by RazaGR** [flutter-webrtc/flutter-webrtc#1428]
when I try to do:
```
state.localStream?.getTracks().forEach((track) {
   state.peerConnection!.addTrack(track, state.localStream!); 
});
```
I get this message in console:

> [VERBOSE-2:shell.cc(1004)] The 'FlutterWebRTC/peerConnectionEventD6FF241F-5337-4DF1-A556-169EFAB99FF0' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
> See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.

flutter_webrtc: ^0.9.40

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.3.1 22E772610a
    darwin-arm64, locale en-SE)
[✓] Android toolchain - develop for Android devices (Android
    SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] Network resources
```

**Comment by shuax** [comment]
I think that 3.13 has stricter detection of multi-threaded calls, and I still don't know how to call them in the main thread.

**Comment by Allansekyewa** [comment]
can anyone help me this problem also

**Comment by Redab0** [comment]
any updates on the problem?

**Comment by Redab0** [comment]
I found a temporary solution. Open your iOS code and search for instances of using eventSink, search for "eventSink(" in FlutterWebRtc classes and then wrap it with 

dispatch_async(dispatch_get_main_queue(), ^{}); 

for now I wrapped every instance with the above code and the crash + error are gone. I'm still trying to find the exact cause of the issue I will update you once I find the exact event trigger that's causing it.

@RazaGR

**Comment by SooChang-Lee** [comment]
This issue is still occurring in Windows apps.

flutter_webrtc: ^0.9.45

I get this message in console:

> [ERROR:flutter/shell/common/shell.cc(1004)] The 'FlutterWebRTC/dataChannelEvent21D92203-600E-4D85-A228-AE8E51267D752CF7F183-BE3A-4086-9B0D-081FC380FC68' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
> See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.

flutter doctor

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 3.13.5, on macOS 14.0 23A344 darwin-arm64, locale ko-KR)
> [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 15.0)
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 2022.3)
> [✓] IntelliJ IDEA Ultimate Edition (version 2023.2.2)
> [✓] VS Code (version 1.83.0)
> [✓] Connected device (2 available)
>     ! Device 03206817094078c9 is not authorized.
>       You might need to check your device for an authorization dialog.
> [✓] Network resources
> 
> • No issues found!

**Comment by wjmetcalfiiii** [comment]
RedabO: You mention wrapping EventSink in dispatch_async(dispatch_get_main_queue(), ^{});

"....for now I wrapped every instance with the above code and the crash + error are gone. Can you please be more specific regarding the syntax? Right now I'm looking at event_sink.dart and it's not clear (at least to me) what you are saying. Here is event_sink.dart.

// Copyright (c) 2015, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

import 'dart:async';

/// Simple delegating wrapper around an [EventSink].
///
/// Subclasses can override individual methods, or use this to expose only the
/// [EventSink] methods of a subclass.
class DelegatingEventSink<T> implements EventSink<T> {
  final EventSink _sink;

  /// Create a delegating sink forwarding calls to [sink].
  DelegatingEventSink(EventSink<T> sink) : _sink = sink;

  DelegatingEventSink._(this._sink);

  /// Creates a wrapper that coerces the type of [sink].
  ///
  /// Unlike [DelegatingEventSink.new], this only requires its argument to be an
  /// instance of `EventSink`, not `EventSink<T>`. This means that calls to
  /// [add] may throw a [TypeError] if the argument type doesn't match the
  /// reified type of [sink].
  @Deprecated(
      'Use StreamController<T>(sync: true)..stream.cast<S>().pipe(sink)')
  static EventSink<T> typed<T>(EventSink sink) =>
      sink is EventSink<T> ? sink : DelegatingEventSink._(sink);

  @override
  void add(T data) {
    _sink.add(data);
  }

  @override
  void addError(Object error, [StackTrace? stackTrace]) {
    _sink.addError(error, stackTrace);
  }

  @override
  void close() {
    _sink.close();
  }
}

**Comment by blackshadowsoftwareltd** [comment]
I am getting the same issue in my Linux Machine(Fedora Linux 39). 

```
[ERROR:flutter/shell/common/shell.cc(1038)] The 'FlutterWebRTC/peerConnectionEventB583CF0F-659D-4AD6-B476-EC03617AF125' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
```

```
localStream?.getTracks().forEach((track) async {
        peerConnection?.addTrack(track, localStream!);
      });
```

**Comment by groupsell** [comment]
> I think that 3.13 has stricter detection of multi-threaded calls, and I still don't know how to call them in the main thread.
How to solve this problem

**Comment by Stofkat** [comment]
I see this issue was closed but looking at the MR the fix only targets iOS

Is there also a fix planned for Windows?

**Comment by fullflash** [comment]
it would be nice to add an explanation before closing the issue that was not resolved.

**Comment by dnintzeli** [comment]
I'm still seeing this issue with firebase_auth: ^5.7.0 on Windows 11.
