### ISSUE TITLE
Help! needed: How can I get local audio byte data in iOS?

### ISSUE THREAD

**Issue by Jaemin-VIRNECT** [flutter-webrtc/flutter-webrtc#1455]
I'm trying to get local audio byte data in Android and iOS.

To get the local audio byte data before sending the audio stream in Android, 

We can get the data with code like this:
JavaAudioDeviceModule.Builder.setSamplesReadyCallback(callback);

And I made it to work on flutter for Android, but I'm stuck in the iOS way.

Any hints or ways to achieve this on iOS? (If this is not possible or difficult to achieve, It is also okay after sending audio stream)

Thank you in advance.

**Comment by LeCua** [comment]
Hi! I found some code in iOS Broadcast Extension in the screen sharing example:
// File: ios\ScreenBroadcast\SampleHandler.swift
    override func processSampleBuffer(_ sampleBuffer: CMSampleBuffer, with sampleBufferType: RPSampleBufferType) {
        switch sampleBufferType {
        case RPSampleBufferType.video:
            uploader?.send(sample: sampleBuffer)
			break;
		case RPSampleBufferType.audioApp:
			// app audio here
			break;
        default:
            break
        }
    }
But I have no idea how to put that into practice.

**Comment by JiaoLiu** [comment]
On iOS, screen recording permission can only capture system sound and microphone sound, and cannot capture sound from other applications. Therefore, even if you have screen recording permission, you cannot directly capture the sound played by other applications. However, you can use other methods to capture sound from other applications, such as using audio line input or external microphone to record sound.

**Comment by Jaemin-VIRNECT** [comment]
Thank you for your feedback. While using the flutter webrtc plugin, I was able to access local audio bytes directly with other flutter plugin.

**Comment by Jaemin-VIRNECT** [comment]
@razasaddiqi
Here you go. [better_audio_capture ](https://pub.dev/packages/better_audio_capture)
