### ISSUE TITLE
[DESKTOP] App Crashes When Making a Call

### ISSUE THREAD

**Issue by Vinayak006** [flutter-webrtc/flutter-webrtc#1504]
We are engaged in implementing VoIP calling functionality using the [Marix] platform. To facilitate seamless communication, we are utilizing the WebRTCDelegate.

**Describe the bug**
When receiving an incoming call or making an outgoing call, the WebRTCDelegate's handleNewCall function is triggered as expected. However, immediately afterwards, the application unexpectedly crashes, leading to an abrupt closure. This issue disrupts the expected call-handling flow. But this works well in Android mobile.

**Platform information**
* **Flutter version**:
✓] Flutter (Channel stable, 3.16.3, on Ubuntu 23.10 6.5.0-14-generic, locale
    en_GB.UTF-8)
    • Flutter version 3.16.3 on channel stable at
      /home/kingkong/Documents/flutter_linux_3.3.9-stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (2 weeks ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/kingkong/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/kingkong/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 16.0.6 (15)
    • cmake version 3.27.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[!] Android Studio (version unknown)
    • Android Studio at /home/kingkong/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.78.0

[✓] Connected device (3 available)
    • RMX1851 (mobile) • 6164aa8e • android-arm64  • Android 11 (API 30)
    • Linux (desktop)  • linux    • linux-x64      • Ubuntu 23.10
      6.5.0-14-generic
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 120.0.6099.62

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

* **Plugin version**: flutter_webrtc 0.9.47
* **OS**: Linux Desktop
* **OS version**: Ubuntu 23.10

**Comment by AleksandrLapin** [comment]
I have a similar problem. iOS crashes when making a call but works fine on Android.

**Comment by Vinayak006** [comment]
Any Update on this?!

**Comment by Garciconx** [comment]
Any Update on this?
