### ISSUE TITLE
Flutter Desktop App Getting Crashed When Joining a Call

### ISSUE THREAD

**Issue by Vinayak0-0** [flutter-webrtc/flutter-webrtc#1525]
**Describe the bug**

We are building a application with matrix org and using flutter_webrtc for calls. When joining a call, flutter desktop application getting killed and crashed.

**To Reproduce**
- run a application in desktop and initiate a call.
- app will get killed without any warnings
log
[ERROR:flutter/shell/common/shell.cc(1015)] The 'FlutterWebRTC/peerConnectionEventD199868B-D1EE-4A0B-A66B-EF54CDEAB6FA' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.

**Expected behavior**

The call should be made without app getting crashed

**Platform information**

* **Flutter version**:
[✓] Flutter (Channel stable, 3.16.3, on Ubuntu 23.10 6.5.0-17-generic, locale
    en_GB.UTF-8)
    • Flutter version 3.16.3 on channel stable at
      /home/kingkong/Documents/flutter_linux_3.3.9-stable/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0366e0a3f (2 months ago), 2023-12-05 19:46:39 -0800
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/kingkong/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /home/kingkong/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • Ubuntu clang version 16.0.6 (15)
    • cmake version 3.27.4
    • ninja version 1.11.1
    • pkg-config version 1.8.1

[!] Android Studio (version unknown)
    • Android Studio at /home/kingkong/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to determine Android Studio version.
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b829.9-10027231)

[✓] VS Code (version 1.84.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.82.0

[✓] Connected device (4 available)
    • V2247 (mobile)   • 10BD6Y0PGH000A2 • android-arm64  • Android 13 (API 33)
    • RMX1851 (mobile) • 6164aa8e        • android-arm64  • Android 11 (API 30)
    • Linux (desktop)  • linux           • linux-x64      • Ubuntu 23.10
      6.5.0-17-generic
    • Chrome (web)     • chrome          • web-javascript • Google Chrome
      121.0.6167.139

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.

* **Plugin version**: 0.9.48+hotfix.1
* **OS**: Desktop linux
* **OS version**: Ubuntu 23.10

**Comment by blackshadowsoftwareltd** [comment]
Is there any solution?

**Comment by thanhle7** [comment]
Problem still but no solution yet.

**Comment by thanhle7** [comment]
> Is there any solution?

I am trying to update the pluggin according to newly updated security policies made by flutter.
