### ISSUE TITLE
Regarding how to compile the WebRTC library by myself and replace it / 关于如何自己编译webrtc库并替换

### ISSUE THREAD

**Issue by yuemenglong** [flutter-webrtc/flutter-webrtc#1572]
Hello, I noticed that the three libraries under third_party/libwebrtc/lib are all dynamic link libraries. I would like to ask how these libraries are compiled. I can compile using the official WebRTC source code, but the outputs are all static libraries. If I want to modify the WebRTC source code and apply it to flutter-webrtc, what should I do?

你好，我发现third_party/libwebrtc/lib下的三个库都是动态链接库，我想请问这些库是如何编译出来的，我能够用官方的webrtc源码编译，但是编译出来的都是静态库。如果我想修改webrtc的源码并应用到flutter-webrtc上，我该怎么做

**Comment by cloudwebrtc** [comment]
这里有dll对应的源码及编译步骤
https://github.com/webrtc-sdk/libwebrtc

**Comment by yuemenglong** [comment]
> 这里有dll对应的源码及编译步骤 https://github.com/webrtc-sdk/libwebrtc

请教一下，当时没有选择官方的版本的原因是什么。因为我看这个项目从114之后就没有更新了，如果一直不更新，会不会与官方版本差距越来越大，一些新的特性就无法及时用到。
后续有考虑迁移到官方版本上吗

**Comment by cloudwebrtc** [comment]
因为我们在m114 上做了大量优化补丁， 迁移不是很方便，但会考虑在今年升级到新m 版本。

**Comment by yuemenglong** [comment]
问题已解决
