### ISSUE TITLE
onRenegotiationNeeded callback no longer being called on Web

### ISSUE THREAD

**Issue by DaveBubenik** [flutter-webrtc/flutter-webrtc#1584]
**Describe the bug**
The onRenegotiationNeeded is never called. This is being caused by a bug introduced in version 0.10.0 of this library and version 1.3.0 of the dart-webrtc library. I've opened a bug in that library as well:
https://github.com/flutter-webrtc/dart-webrtc/issues/36

The onRenegotiationNeeded callback is never being triggered. 

The issue is occurring because the webrtc event listener is listening to the wrong event in rtc_peerconnection_impl.dart in the dart-webrtc library.

The following code is incorrect:
```
_jsPc.addEventListener( 'onnegotiationneeded', (_) { onRenegotiationNeeded?.call(); }.toJS);
```

It should be updated to:
```
_jsPc.addEventListener( 'negotiationneeded', (_) { onRenegotiationNeeded?.call(); }.toJS);
````

**To Reproduce**
Create a peer connection and add a stream, the onRenegotiationNeeded event is never triggered.

**Expected behavior**
onRenegotiationNeeded is called.

**Platform information**

* **Flutter version**: 3.19.6
* **Plugin version**:0.10.0
* **OS**: Web
* **OS version**: All

**Comment by cloudwebrtc** [comment]
fixed
https://github.com/flutter-webrtc/dart-webrtc/pull/38
https://github.com/flutter-webrtc/flutter-webrtc/releases/tag/0.10.6
