### ISSUE TITLE
The `onAddStream` callback is not fired on Web.

### ISSUE THREAD

**Issue by jpsantosbh** [flutter-webrtc/flutter-webrtc#1595]
**Describe the bug**

The `onAddStream` callback is not fired on Web.

I have this same code working on iOS devices, but when I run the app in Chrome the `onAddStream` is never fired.
```dart
rtcPeerConnection ??= await createPeerConnection(connectionOptions, {
      "mandatory": {
        "OfferToReceiveAudio": true,
        "OfferToReceiveVideo": true,
      },
      "optional": [],
    });

    logger.d(
        '### RTCPeerConnection Config ${rtcPeerConnection!.getConfiguration}');

    rtcPeerConnection!.onAddStream = (MediaStream stream) async {
      logger.d('onAddStream: ${stream.toString()}');

      _remoteStream ??= RTCVideoRenderer();
      await _remoteStream!.initialize();
      _remoteStream!.srcObject = stream;
    };
```

I'm getting the `onConnectionState` called with `RTCPeerConnectionState.RTCPeerConnectionStateConnected` so I belive it's not a remote connection issue.

**To Reproduce**

**Expected behavior**

The `onAddStream` callback should fired like in iOS

**Platform information**
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.4.1 23E224 darwin-arm64, locale en-BR)
    • Flutter version 3.22.1 on channel stable at /Users/jpsantos/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (9 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/jpsantos/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.7+0-17.0.7b1000.6-10550314)

[✓] VS Code (version 1.89.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (4 available)
    • iPhone X JP (mobile)            • 00008120-XXXXXXXXXX • ios            • iOS 17.4.1 21E236
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.4.1 23E224 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.4.1 23E224 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 125.0.6422.141

[✓] Network resources
    • All expected network resources are available.

• No issues found!
 **Plugin version**:  flutter_webrtc: 0.10.7
* **OS**: 
* **OS version**:

**Comment by cloudwebrtc** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addstream_event
`onAddStream` has been removed in the webrtc standard, please use `onTrack` instead

**Comment by jpsantosbh** [comment]
Thanks, that solved the problem

> https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addstream_event `onAddStream` has been removed in the webrtc standard, please use `onTrack` instead
> 
> ```
>     rtcPeerConnection!.onTrack = (event) {
>       if (event.track.kind == 'video') {
>         _remoteStream!.srcObject = event.streams[0];
>         setState(() {});
>       }
>     };
> ```
