### ISSUE TITLE
mediastreamtrack's enableSpeakerPhone method not working

### ISSUE THREAD

**Issue by ashimregme** [flutter-webrtc/flutter-webrtc#161]
Getting this exception when enableSpeakerPhone is called.

`Unhandled Exception: MissingPluginException(No implementation found for method enableSpeakerphone on channel FlutterWebRTC.Method)`
`#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>`
`#1      MediaStreamTrack.enableSpeakerphone`
`(package:flutter_webrtc/media_stream_track.dart:60:20)`

In Issue#45, we are suggested to use in-call-manager plugin. Is the method `enableSpeakerPhone`added in 0.2.0 is intended to work or is just a stub?

Using flutter 0.2.2

**Comment by cloudwebrtc** [comment]
On which platform？

**Comment by aregmee** [comment]
> On which platform？

on iOS

**Comment by aregmee** [comment]
Also, I am adding it to an existing app.
