### ISSUE TITLE
Support iOS 12

### ISSUE THREAD

**Issue by xalanq** [flutter-webrtc/flutter-webrtc#1646]
Why did you upgrade iOS deployment target to 13.0 from 12.1 in this commit #1591 ?

https://github.com/flutter-webrtc/flutter-webrtc/blob/5fe7976e1c50ac0f7a71b724e2c2c29f1ff44bcc/example/ios/Podfile#L2

**Comment by jakobleck** [comment]
https://en.wikipedia.org/wiki/IOS_version_history iOS 12 is quite old, not sure you can expect it still being supported...

**Comment by xalanq** [comment]
> https://en.wikipedia.org/wiki/IOS_version_history iOS 12 is quite old, not sure you can expect it still being supported...

I think the 3rd party library should use the minimum supported os version that it could, whatever the version is quite old or not.

**Comment by xalanq** [comment]
If the lib has not used any new feature of iOS 13.0, it should not declare the minimum iOS deployment target as 13.0.

**Comment by cloudwebrtc** [comment]
This is because the minimum deployment requirement for libwebrtc to compile the framework dependency on iOS is 13.0
