### ISSUE TITLE
Slow data channel bandwidth in local network 

### ISSUE THREAD

**Issue by TheSquad** [flutter-webrtc/flutter-webrtc#166]
**Describe the bug**
The bandwidth between 2 peers on the same network hardly goes more than 2MB/sec. While a raw socket connection goes to 50-70MB/s

**To Reproduce**
- connect peers on the same network
- send a file from on peer to the other
- measure bandwidth (Mb/sec) 

**Expected behavior**
- The bandwidth should be much higher

**Platform information**
- iOS -> Android
- Android -> iOS

Am I the only one having this low bandwidth using data channels ?

**Comment by jayaram9877** [comment]
Have you succeeded in sending binary data from one peer to another if yes can you please help?
