### ISSUE TITLE
Rendering H.264 video failed on Android

### ISSUE THREAD

**Issue by chanchalyadav272** [flutter-webrtc/flutter-webrtc#1664]
**Describe the bug**
I am using this library for live streaming my camera's feed which uses video-codec H.264 and audio-codec ALAW. I am able to create the RTC peer connection successfully and receive both audio and video streams but unable to render the video using RTCVideoView.

The SDP packet received:

v=0
o=- 1495799811084970 1495799811084970 IN IP4 0.0.0.0
s=-
t=0 0
a=msid-semantic: iot
a=group:BUNDLE video audio
m=video 9 UDP/TLS/RTP/SAVPF 96 102
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:96 profile-level-id=42e01f;level-asymmetry-allowed=1
a=fmtp:102 profile-level-id=42e01f;packetization-mode=1;level-asymmetry-allowed=1
a=rtpmap:96 H264/90000
a=rtpmap:102 H264/90000
a=ssrc:1 cname:webrtc-h264
a=sendrecv
a=mid:video
c=IN IP4 0.0.0.0
a=rtcp-mux
a=fingerprint:sha-256 1F:17:8B:92:C1:02:23:84:46:01:46:A5:0B:5C:AE:03:16:07:0A:8A:83:C6:C0:F7:A3:4B:A3:B5:F5:74:E5:69
a=setup:passive
a=ice-ufrag:ywiD
a=ice-pwd:ywiDaQPVV4S3Q7gT6iN94w29
a=candidate:1 1 UDP 1688444927 103.159.11.246 41887 typ srflx raddr 0.0.0.0 rport 0
a=candidate:2 1 UDP 2124652543 192.168.1.163 41887 typ host
m=audio 9 UDP/TLS/RTP/SAVP 8
a=rtpmap:8 PCMA/8000
a=ptime:20
a=ssrc:4 cname:webrtc-pcma
a=sendrecv
a=mid:audio
c=IN IP4 0.0.0.0
a=rtcp-mux
a=fingerprint:sha-256 1F:17:8B:92:C1:02:23:84:46:01:46:A5:0B:5C:A

It is giving this error:

```sh
IMGSRV                  com.example.webrtc_integration       E  :4879: IsTextureConsistent: IMGEGLImage is not consistent
```

**Platform information**

* **Flutter version**: 3.19.5
* **Plugin version**: 0.11.6+hotfix.1
* **OS**: Android
* **OS version**: 12

**Comment by lurongshuang** [comment]
请问，解决了吗

**Comment by chanchalyadav272** [comment]
Resolved it by adding missing parameter `packetization-mode=1` to `a=fmtp:96 profile-level-id=42e01f;level-asymmetry-allowed=1` in sdp

**Comment by JeetMatalia** [comment]
Hello,
I am facing an issue with playing my video avatar. I was able to successfully establish a peer-to-peer connection, and I can hear the audio, but the video is not working. I am using flutter_webrtc: 1.1.0.

Is there any solution for this? Kindly revert back.

**Comment by chanchalyadav272** [comment]
are you getting video candidates in your sdp?

**Comment by JeetPatel2862** [comment]
@chanchalyadav272 Yes, I am getting the SDP video candidate like this: m=video 0 UDP/TLS/RTP/SAVPF 0.
Why am I getting 0 in Flutter?

This is the method where I get answer.sdp:

final answer = await _peerConnection!.createAnswer();
await _peerConnection!.setLocalDescription(answer);


But when I use the D-ID method, I get the video candidate in SDP like this:
m=video 9 UDP/TLS/RTP/SAVPF 102 103\r\n
