### ISSUE TITLE
Unable to getUserMedia (Need check number of cameras)

### ISSUE THREAD

**Issue by gitanderson** [flutter-webrtc/flutter-webrtc#171]
**Describe the bug**

Unhandled Exception: Unable to getUserMedia: Failed to create new track

E/flutter ( 7394): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Unable to getUserMedia: Failed to create new track
E/flutter ( 7394): #0      navigator.getUserMedia (package:flutter_webrtc/get_user_media.dart:20:7)
E/flutter ( 7394): <asynchronous suspension>
E/flutter ( 7394): #1      Signaling.createStream (package:flutter_webrtc_demo/src/call_sample/signaling.dart:310:27)
E/flutter ( 7394): #2      Signaling._createPeerConnection (package:flutter_webrtc_demo/src/call_sample/signaling.dart:318:47)

**To Reproduce**
Press "P2P Call Sample" button
Connect to the server
Press Video icon to start video call

**Expected behavior**
Initiate video conference between emulator and web chrome 

**Platform information**

* **Flutter version**: 
Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [versÃ£o 6.3.9600], locale pt-BR)
    • Flutter version 1.12.13+hotfix.5 at C:\dev\sdk\flutter
    • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

* **Plugin version**: 
0.2.2

* **OS**: 
Windows 
Nexus 5X API 25 Android 7.1.1

* **OS version**:
Windows 8

**Comment by yonatann** [comment]
I'm seeing the same issue on an Android emulator. 
Are there any news on this?

**Comment by yonatann** [comment]
After digging around the java code, I found the problem on my side.
The demo project requests a front-facing camera and the emulator does not support that.

It would be helpful if the error message was more clear.

I hope this helps someone

**Comment by cloudwebrtc** [comment]
Looks like we need to check the number of cameras before setting whether to turn on the front camera by default. I'm sure this is a bug.

**Comment by DQvsRA** [comment]
This issue took me few hours to figure it out. Anyway thanks for the hint @yonatann.

**Comment by wer-mathurin** [comment]
@cloudwebrtc :
Basically, if we found only one camera use that cam?
