### ISSUE TITLE
End to end encryption

### ISSUE THREAD

**Issue by harsh-wesee** [flutter-webrtc/flutter-webrtc#1724]
I am using flutter-webrtc version 0.11.6+hotfix.1 for my use case. On the website it is written that this version supports end to end encryption. From Google I came to know that webrtc uses DTLS-SRTP protocol and exchange media in encrypted format, but the signalling server knows the key. But in this package I didn't find any function or anything that can modify the SRTP protocol and where the exactly the encryption of packets do happen. So, I want to know how it will make video and audio calls end to end encrypted. 
Thanks,

**Comment by cloudwebrtc** [comment]
Please refer to this document and leave a message if you have any questions
https://github.com/flutter-webrtc/flutter-webrtc/blob/duan/e2ee-docs/Documentation/E2EE.md

**Comment by harsh-wesee** [comment]
Thanks for the documentation!

**Comment by akvus** [comment]
How does a 3rd party that forwards the data get the AES key required to decrypt SRTP?
