### ISSUE TITLE
meta: GoogleWebRTC is Deprecating binary mobile libraries

### ISSUE THREAD

**Issue by CoreyCole** [flutter-webrtc/flutter-webrtc#175]
In the [WebRTC M80 Release Notes](https://groups.google.com/forum/#!topic/discuss-webrtc/Ozvbd0p7Q1Y) they state they are going to be deprecating the mobile libraries. It makes sense I guess the release cadence on cocoapods/jcenter was very slow and outdated.

To stay up to date it looks like we need to build binaries from source for iOS & Android.
  - https://webrtc.googlesource.com/src/+/refs/heads/master/docs/native-code/ios/index.md
  - https://webrtc.googlesource.com/src/+/refs/heads/master/docs/native-code/android/index.md

I'm also wondering how to manage updating the webrtc source in this repository. I guess a git submodule?

EDIT: it looks like we are not using a git submodule for the macos `WebRTC.framework` binary. I guess we would do the same for iOS and android where we just build the binary outside the repo and then commit the built binary to the repository?

**Comment by cloudwebrtc** [comment]
It looks like we need to maintain native SDK for mobile and desktop by ourselves.
This will bring more work, but also more flexibility.

**Comment by CoreyCole** [comment]
Here are some tips I found on the webrtc message board:
> - wait for a chrome release to happen, wait a couple of weeks and watch the bugtracker for issues
> - look at the git changelog between the versions, read *every* commit message at least so you know what has changed at a high level. This is enough effort to do it not on every new chrome version but you don't want the changes to get too big either.
> - make a build, QA it according to some checklist you have for it
> - distribute it to internal users via testflight or similar, ask people to test
> - submit new version to the store, then do a gradual rollout to 10%-ish
> - make sure performance metrics (bitrate, connectivity, ...) of the new version have not regressed. Make sure your support has the tools to correlate user reports with the new version.
> - increase rollout percentage, monitoring metrics
> - if things go bad, revert, file a bug and ideally a workaround
>  
> Not being forced to roll a new version including regressions is an advantage you have on mobile compared to web.
> On the other hand getting a new version published to the store is more difficult than rolling back a js file so...
>  
> And yes, this is extremely time-consuming.

https://groups.google.com/forum/#!msg/discuss-webrtc/yIZnblSeWNo/Ia6qYtxwCQAJ

@cloudwebrtc when you say

> It looks like we need to maintain native SDK for mobile and desktop by ourselves.

Do you mean we want to stop depending on Google's native WebRTC libraries all together and roll our own? Or you just mean we will need to build from source?

**Comment by cloudwebrtc** [comment]
I think that just using the official version of Google to compile SDK can't satisfy my function extension of the flutter-webrtc plugin.

For example:
* MediaRecorder cannot use the official WebRTC SDK to achieve arbitrary local/remote track recording.
* I have a case where the native interface is incomplete when I encapsulate the Unified Plan function.
* Insert images into VideoSourceTrack or connect Canvas to generate mixed video source
* Insert PCM in AudioSourceTrack, such as generating speech in TTS
* Get RAW data from VideoTrack/AudioTrack and connect to CV/ML/ASR

The official SDK does not expose enough APIs to complete the above functions.
Exporting APIs through patches is the fastest way.

**Comment by wer-mathurin** [comment]
@cloudwebrtc do we need to continue the discussion.  Or we can close the issue?

**Comment by cloudwebrtc** [comment]
@wer-mathurin Can be closed now, and then opened if necessary.
