### ISSUE TITLE
Is it possible to select the audio output channel?

### ISSUE THREAD

**Issue by DomingoMG** [flutter-webrtc/flutter-webrtc#176]
For example, here I attach an image where the camera is viewed and at the same time a drop-down menu is displayed to select the sound channel.

In this repository, could you choose the output audio channel?

I attached the demo through this link.
https://webrtc.github.io/samples/src/content/devices/multi/

![Captura de pantalla 2020-01-27 a las 23 36 24](https://user-images.githubusercontent.com/36201422/73223402-de908a80-415d-11ea-8e38-4a828c510f2a.png)

**Comment by cloudwebrtc** [comment]
Not supported yet.
I think we need to add a `VideoElement.setSinkId` method similar to the `video` in js to select the playback device.

**Comment by DomingoMG** [comment]
Currently it is still incompatible ?, I hope to receive a response, thanks
