### ISSUE TITLE
Low Frame Rate

### ISSUE THREAD

**Issue by CodeStrings** [flutter-webrtc/flutter-webrtc#186]
**Describe the bug**
Pretty low Framerate when using the Screen as the source to transmit trough webrtc.

**To Reproduce**
Just take the call example and then use the screen as the source.

**Expected behavior**
Framerate at around 21FPS
**Platform information**

* **Flutter version**: 
• Flutter version 1.12.13+hotfix.7 at C:\flutter
    • Framework revision 9f5ff2306b (11 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0
* **Plugin version**: ^0.2.6
* **OS**:  Android
* **OS version**:  7.0

Edit: So I just forced h264 through the SDP now my problem is that the Snapdragon 425 only supports 1080p but the resolution is 1280x800px so is there any possibility to set the video width and height?

**Comment by cloudwebrtc** [comment]
Screen capture uses low frame rate mode by default.

**Comment by CodeStrings** [comment]
Nice to know after forcing h264 it was running recently smooth but there are some artifcats. So how can I edit the resolution and framerate? And also is it possible to capture the System sound?

**Comment by d3fkon** [comment]
@CodeStrings can you explain how you forced h264 through the SDP?
Im having severe performance issues in a video call, as flutter-webrtc uses VP8 by default. I either need to lower the resolution (which isn't working through media_constraints) or use h264 instead of vp8.
