### ISSUE TITLE
Version and dependency update

### ISSUE THREAD

**Issue by kefayuan** [flutter-webrtc/flutter-webrtc#192]
can you please update the version in flutter_webrtc.podspec from '0.2.2' to latest version and also the dependency version of GoogleWebRTC', '1.1.29400' to GoogleWebRTC', '1.1.29400'?

**Comment by ycherniavskyi** [comment]
@kefayuan hmm from '1.1.29400' to '1.1.29400? In which version did you make a typo (as I understand in the last one)?
Also, could you please explain a bit the reason why you need each of the requested changes?

**Comment by wer-mathurin** [comment]
Library have been updated in the lastest version of the library
