### ISSUE TITLE
Unable to compile for iOS

### ISSUE THREAD

**Issue by cadaniel** [flutter-webrtc/flutter-webrtc#197]
**Describe the bug**

Unable to compile to iOS

`
Launching lib/main.dart on iPhone 11 in debug mode...
Running Xcode build...
Xcode build done.                                            7.1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    In file included from /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCPeerConnection.m:3:
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCPeerConnection.h:4:81: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    @property (nonatomic, strong) NSMutableDictionary<NSString *, RTCDataChannel *> *dataChannels;
                                                                                    ^
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCPeerConnection.h:4:81: note: insert '_Nullable' if the pointer may be null
    @property (nonatomic, strong) NSMutableDictionary<NSString *, RTCDataChannel *> *dataChannels;
                                                                                    ^
                                                                                      _Nullable 
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCPeerConnection.h:4:81: note: insert '_Nonnull' if the pointer should never be null
    @property (nonatomic, strong) NSMutableDictionary<NSString *, RTCDataChannel *> *dataChannels;
                                                                                    ^
                                                                                      _Nonnull 
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCPeerConnection.h:38:23: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    -(RTCMediaConstraints *) parseMediaConstraints:(nonnull NSDictionary *)constraints;
                          ^
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCPeerConnection.h:38:23: note: insert '_Nullable' if the pointer may be null
    -(RTCMediaConstraints *) parseMediaConstraints:(nonnull NSDictionary *)constraints;
                          ^
                           _Nullable
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCPeerConnection.h:38:23: note: insert '_Nonnull' if the pointer should never be null
    -(RTCMediaConstraints *) parseMediaConstraints:(nonnull NSDictionary *)constraints;
                          ^
                           _Nonnull
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCPeerConnection.h:40:57: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    -(void) peerConnectionSetConfiguration:(RTCConfiguration*)configuration
                                                            ^
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCPeerConnection.h:40:57: note: insert '_Nullable' if the pointer may be null
    -(void) peerConnectionSetConfiguration:(RTCConfiguration*)configuration
                                                            ^
                                                             _Nullable
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCPeerConnection.h:40:57: note: insert '_Nonnull' if the pointer should never be null
    -(void) peerConnectionSetConfiguration:(RTCConfiguration*)configuration
                                                            ^
                                                             _Nonnull
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCPeerConnection.h:41:58: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
                            peerConnection:(RTCPeerConnection*)peerConnection;
                                                             ^
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCPeerConnection.h:41:58: note: insert '_Nullable' if the pointer may be null
                            peerConnection:(RTCPeerConnection*)peerConnection;
                                                             ^
                                                              _Nullable
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCPeerConnection.h:41:58: note: insert '_Nonnull' if the pointer should never be null
                            peerConnection:(RTCPeerConnection*)peerConnection;
                                                             ^
                                                              _Nonnull
    In file included from /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCPeerConnection.m:4:
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCDataChannel.h:5:40: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
    @property (nonatomic, strong) NSString *peerConnectionId;
                                           ^
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCDataChannel.h:5:40: note: insert '_Nullable' if the pointer may be null
    @property (nonatomic, strong) NSString *peerConnectionId;
                                           ^
                                             _Nullable 
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCDataChannel.h:5:40: note: insert '_Nonnull' if the pointer should never be null
    @property (nonatomic, strong) NSString *peerConnectionId;
                                           ^
                                             _Nonnull 
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCDataChannel.h:17:59: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
                   messenger:(NSObject<FlutterBinaryMessenger>*)messenger;
                                                              ^
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCDataChannel.h:17:59: note: insert '_Nullable' if the pointer may be null
                   messenger:(NSObject<FlutterBinaryMessenger>*)messenger;
                                                              ^
                                                               _Nullable
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCDataChannel.h:17:59: note: insert '_Nonnull' if the pointer should never be null
                   messenger:(NSObject<FlutterBinaryMessenger>*)messenger;
                                                              ^
                                                               _Nonnull
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCPeerConnection.m:331:1: warning: category is implementing a method which will also be implemented by its primary class [-Wobjc-protocol-method-implementation]
    - (void)peerConnection:(RTCPeerConnection *)peerConnection didChangeSignalingState:(RTCSignalingState)newState {
    ^
    In module 'WebRTC' imported from /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterWebRTCPlugin.h:4:
    /Users/archer/Work/ldrc/ios/Pods/GoogleWebRTC/Frameworks/frameworks/WebRTC.framework/Headers/RTCPeerConnection.h:90:1: note: method 'peerConnection:didChangeSignalingState:' declared here
    - (void)peerConnection:(RTCPeerConnection *)peerConnection
    ^
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCPeerConnection.m:385:1: warning: category is implementing a method which will also be implemented by its primary class [-Wobjc-protocol-method-implementation]
    - (void)peerConnection:(RTCPeerConnection *)peerConnection didAddStream:(RTCMediaStream *)stream {
    ^
    In module 'WebRTC' imported from /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterWebRTCPlugin.h:4:
    /Users/archer/Work/ldrc/ios/Pods/GoogleWebRTC/Frameworks/frameworks/WebRTC.framework/Headers/RTCPeerConnection.h:94:1: note: method 'peerConnection:didAddStream:' declared here
    - (void)peerConnection:(RTCPeerConnection *)peerConnection didAddStream:(RTCMediaStream *)stream;
    ^
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCPeerConnection.m:413:1: warning: category is implementing a method which will also be implemented by its primary class [-Wobjc-protocol-method-implementation]
    - (void)peerConnection:(RTCPeerConnection *)peerConnection didRemoveStream:(RTCMediaStream *)stream {
    ^
    In module 'WebRTC' imported from /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterWebRTCPlugin.h:4:
    /Users/archer/Work/ldrc/ios/Pods/GoogleWebRTC/Frameworks/frameworks/WebRTC.framework/Headers/RTCPeerConnection.h:99:1: note: method 'peerConnection:didRemoveStream:' declared here
    - (void)peerConnection:(RTCPeerConnection *)peerConnection didRemoveStream:(RTCMediaStream *)stream;
    ^
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCPeerConnection.m:438:1: warning: category is implementing a method which will also be implemented by its primary class [-Wobjc-protocol-method-implementation]
    - (void)peerConnectionShouldNegotiate:(RTCPeerConnection *)peerConnection {
    ^
    In module 'WebRTC' imported from /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterWebRTCPlugin.h:4:
    /Users/archer/Work/ldrc/ios/Pods/GoogleWebRTC/Frameworks/frameworks/WebRTC.framework/Headers/RTCPeerConnection.h:102:1: note: method 'peerConnectionShouldNegotiate:' declared here
    - (void)peerConnectionShouldNegotiate:(RTCPeerConnection *)peerConnection;
    ^
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCPeerConnection.m:445:1: warning: category is implementing a method which will also be implemented by its primary class [-Wobjc-protocol-method-implementation]
    - (void)peerConnection:(RTCPeerConnection *)peerConnection didChangeIceConnectionState:(RTCIceConnectionState)newState {
    ^
    In module 'WebRTC' imported from /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterWebRTCPlugin.h:4:
    /Users/archer/Work/ldrc/ios/Pods/GoogleWebRTC/Frameworks/frameworks/WebRTC.framework/Headers/RTCPeerConnection.h:105:1: note: method 'peerConnection:didChangeIceConnectionState:' declared here
    - (void)peerConnection:(RTCPeerConnection *)peerConnection
    ^
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCPeerConnection.m:455:1: warning: category is implementing a method which will also be implemented by its primary class [-Wobjc-protocol-method-implementation]
    - (void)peerConnection:(RTCPeerConnection *)peerConnection didChangeIceGatheringState:(RTCIceGatheringState)newState {
    ^
    In module 'WebRTC' imported from /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterWebRTCPlugin.h:4:
    /Users/archer/Work/ldrc/ios/Pods/GoogleWebRTC/Frameworks/frameworks/WebRTC.framework/Headers/RTCPeerConnection.h:109:1: note: method 'peerConnection:didChangeIceGatheringState:' declared here
    - (void)peerConnection:(RTCPeerConnection *)peerConnection
    ^
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCPeerConnection.m:465:1: warning: category is implementing a method which will also be implemented by its primary class [-Wobjc-protocol-method-implementation]
    - (void)peerConnection:(RTCPeerConnection *)peerConnection didGenerateIceCandidate:(RTCIceCandidate *)candidate {
    ^
    In module 'WebRTC' imported from /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterWebRTCPlugin.h:4:
    /Users/archer/Work/ldrc/ios/Pods/GoogleWebRTC/Frameworks/frameworks/WebRTC.framework/Headers/RTCPeerConnection.h:113:1: note: method 'peerConnection:didGenerateIceCandidate:' declared here
    - (void)peerConnection:(RTCPeerConnection *)peerConnection
    ^
    /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCPeerConnection.m:475:1: warning: category is implementing a method which will also be implemented by its primary class [-Wobjc-protocol-method-implementation]
    - (void)peerConnection:(RTCPeerConnection*)peerConnection didOpenDataChannel:(RTCDataChannel*)dataChannel {
    ^
    In module 'WebRTC' imported from /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterWebRTCPlugin.h:4:
    /Users/archer/Work/ldrc/ios/Pods/GoogleWebRTC/Frameworks/frameworks/WebRTC.framework/Headers/RTCPeerConnection.h:121:1: note: method 'peerConnection:didOpenDataChannel:' declared here
    - (void)peerConnection:(RTCPeerConnection *)peerConnection
    ^
    14 warnings generated.
    In file included from /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCVideoRenderer.m:9:
    In file included from /Users/archer/Work/ldrc/ios/Pods/libyuv-iOS/headers/libyuv.h:15:
    /Users/archer/Work/ldrc/ios/Pods/abseil/absl/types/compare.h:33:10: fatal error: 'cstddef' file not found
    #include <cstddef>
             ^~~~~~~~~
    1 error generated.
    In file included from /Users/archer/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.2.6/ios/Classes/FlutterRTCFrameCapturer.m:5:
    In file included from /Users/archer/Work/ldrc/ios/Pods/libyuv-iOS/headers/libyuv.h:15:
    /Users/archer/Work/ldrc/ios/Pods/abseil/absl/types/compare.h:33:10: fatal error: 'cstddef' file not found
    #include <cstddef>
             ^~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11.
`

**To Reproduce**

Compile flutter on iOS 13

**Expected behavior**

Compiles and runs app

**Platform information**

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-CA)
    • Flutter version 1.12.13+hotfix.8 at /Users/archer/flutter/flutter
    • Framework revision 0b8abb4724 (12 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

**Comment by cadaniel** [comment]
It seems to be related to 
https://github.com/firebase/firebase-ios-sdk/issues/4537

There's a conflict between cloud_firestore and webRTC

**Comment by enex** [comment]
I am having the same issue, is there a workaround?
