### ISSUE TITLE
Bluetooth headset switching on iOS

### ISSUE THREAD

**Issue by arcticfox1919** [flutter-webrtc/flutter-webrtc#201]
I wonder if there are any plans to switch Bluetooth headsets on iOS? I read the source code and it's implemented in Android, but there is no such code on iOS.

**Comment by cloudwebrtc** [comment]
Welcome patches.

**Comment by romilmeghani** [comment]
+1 for this functionality. When can it be expected?

**Comment by Ayman-Kortobaa** [comment]
Is there any news about this issue?
