### ISSUE TITLE
Android bluetooth headset not working

### ISSUE THREAD

**Issue by mencnert** [flutter-webrtc/flutter-webrtc#211]
I had an issue with my bluetooth headsets on android.
After headset was connecting, the audio was still running from speaker. I tried to search but it looks nobody had that issue. 

The problem was with permissions on bluetooth in AndroidManifest.xml so I added this lines:

`<uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <permission android:name="android.permission.BLUETOOTH" android:label="BLUETOOTH" />
    <permission android:name="android.permission.BLUETOOTH_ADMIN" />`

This solved my problem, so please notice this requirement somewhere in readme if this is the root of problem.

version: flutter_webrtc: ^0.2.7
Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (7 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0

Thank you

**Comment by carloselborges** [comment]
Thank you @mencnert !
Our issue resolved my problem. I had the exact same problem.
Just for feedback, I put only the two following lines:
```xml
<uses-permission android:name="android.permission.BLUETOOTH" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
```

Thanks for helping others! I had no idea what to do...

**Comment by cloudwebrtc** [comment]
@carloselborges @mencnert Thanks for your feedback.
