### ISSUE TITLE
[web] navigator.getUserMedia() is Deprecated and not work on mobile browsers

### ISSUE THREAD

**Issue by viplifes** [flutter-webrtc/flutter-webrtc#219]
Deprecated API - https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia

New API - https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

**Comment by wer-mathurin** [comment]
Have been implemented in lastest build.
Feel free to reopen if not working.
