### ISSUE TITLE
iOS does not use the media speaker for the audio

### ISSUE THREAD

**Issue by ZatacaSystems** [flutter-webrtc/flutter-webrtc#222]
**Describe the bug**
iOS uses the ear speaker instead of the media speaker

**To Reproduce**
Do a call with an iphone

**Expected behavior**
The audio should use the media speaker

**Platform information**

* **Flutter version**: 

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57, locale es-ES)
    • Flutter version 1.12.13+hotfix.8 at /Users/jose/developement/flutter
    • Framework revision 0b8abb4724 (8 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jose/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • 5024D EEA • V7LB18BBMMC01BI • android-arm64 • Android 9 (API 28)

• No issues found!

* **Plugin version**:v 0.2.6 (0.2.7 does this with android so I downgraded)
* **OS**:  iOS
* **OS version**: 13.3

**Comment by ycherniavskyi** [comment]
@ZatacaSystems Have you seen #45?

But if do not want to use a separate plugin for this, currently you can use `enableSpeakerphone` method of `MediaStreamTrack` class (for example see cloudwebrtc/flutter-webrtc-demo#73).
