### ISSUE TITLE
getUserMedia fails on Safari

### ISSUE THREAD

**Issue by HiroshiHorie** [flutter-webrtc/flutter-webrtc#225]
Is it expected that this doesn't work on Safari ?
The demo also doesn't work on Safari https://demo.cloudwebrtc.com:8086/#/
but Chrome and Firefox is ok.

am I doing something wrong ?
I think it is related to  #219

**Comment by wer-mathurin** [comment]
Have been implemented in lastest build.
Feel free to reopen if not working.

**Comment by StefanoGR** [comment]
Hello the problem still happens on iOS safari. I've opened an issue with more details. #434

**Comment by wer-mathurin** [comment]
Hi,

I do not tested on my side, but maybe look at this thread.
https://stackoverflow.com/questions/53483975/navigator-mediadevices-getusermedia-not-working-on-ios-12-safari
