### ISSUE TITLE
RTCPeerConnection dispose vs close

### ISSUE THREAD

**Issue by tapkain** [flutter-webrtc/flutter-webrtc#227]
Hello, I am looking at the dispose and close methods, they do kinda the same, could it be possible to have more light on this? Specifically when my app will have a lot of calls during one session (like chatroulette) should I dispose peer connection or close it? Or even re-use it for the whole session? Is this possible?

**Comment by jakobleck** [comment]
Same here, some info on the difference of close() and dispose() would be appreciated.
Especially since I seem to be unable to find dispose() in the WebRTC specs: https://www.w3.org/TR/webrtc/#interface-definition
