### ISSUE TITLE
Screen sharing functionallity 

### ISSUE THREAD

**Issue by kashifzahid** [flutter-webrtc/flutter-webrtc#230]
How can i implement screen sharing during the video call in the flutter webrtc

**Comment by ycherniavskyi** [comment]
Hm, sorry @kashifzahid but you give to few details to get a valuable response.
What is your target platform?
What is your particular use case scenario?
What did you already try to do?

**Comment by kashifzahid** [comment]
hey, @ycherniavskyi I need to implement screen sharing(same as skype) during a video call on both ios and android in the flutter. I tried to use agora.io SDK for flutter for this but unfortunately, they don't have this functionality .

**Comment by RAJIABEFE1412** [comment]
I have the same blocker I need to implement screen sharing while still on video call with the same session.

**Comment by Dyadee** [comment]
Did someone already have some resources produced for screen sharing using flutter_webrtc?

**Comment by mohd-afid** [comment]
@Dyadee hi 
how to stop screen share in ios through mobile app
