### ISSUE TITLE
**Screen/Window Capture for Windows**

### ISSUE THREAD

**Issue by cloudwebrtc** [flutter-webrtc/flutter-webrtc#236]

**Comment by danilonogueirateixeira** [comment]
Waiting for this feature, is there any forecast to publish?

**Comment by cloudwebrtc** [comment]
I will discuss the desktop platform together, please move to
https://github.com/flutter-webrtc/flutter-webrtc/issues/799

**Comment by cloudwebrtc** [comment]
support now
