### ISSUE TITLE
Add meaning toString to main classes

### ISSUE THREAD

**Issue by ycherniavskyi** [flutter-webrtc/flutter-webrtc#237]
To get adequate login information with main classes, it must reimplement the basic toString method implementation.
So for example for `RTCPeerConnection` class instead of `Instance of 'RTCPeerConnection'` as it now, `toString` method may for example return `RTCPeerConnection-$_peerConnectionId`.

**Comment by cloudwebrtc** [comment]
Good idea, so that you can accurately locate the instance when debugging.

**Comment by ycherniavskyi** [comment]
@cloudwebrtc 👍, I am going to implement PR with this functionality this week.
