### ISSUE TITLE
Switch Camera

### ISSUE THREAD

**Issue by MSalaah96** [flutter-webrtc/flutter-webrtc#246]
**Describe the bug**
Switch Camera
**To Reproduce**
Honor 10 lite switching camera 
**Expected behavior**
it takes three clicks to switch from rear camera to the front camera 
and one click to switch from the front to back
**Platform information**

* **Flutter version**: Flutter 1.12.13+hotfix.8 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (3 months ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0
* **Plugin version**: ^0.2.6
* **OS**: Android
* **OS version**: EMUI 9.1.0 Android 9

**Comment by MSalaah96** [comment]
I've made work around to solve it 
switchCamera function return Future<Bool>
if switching to the front camera it return true 
and if switching to the rear camera it return false 

so this is the code for the work around it. 

```
 bool isFrontCamera = true;

  void switchCamera() async {
    if (_localStream != null) {
      bool value = await _localStream.getVideoTracks()[0].switchCamera();
      while (value == this.isFrontCamera)
        value = await _localStream.getVideoTracks()[0].switchCamera();
      this.isFrontCamera = value;
    }
  }
```
but it takes more than one second to switch

**Comment by ycherniavskyi** [comment]
As you can see from Android [`switchCamera` method implemntation](https://github.com/cloudwebrtc/flutter-webrtc/blob/2a6a6ec426284e5dc0d93bea3a6caff50fe98eae/android/src/main/java/com/cloudwebrtc/webrtc/GetUserMediaImpl.java#L763), it fully depends on WebRTC implementation. So with this issue, you need to Google WebRTC library community or [source code](https://chromium.googlesource.com/external/webrtc/+/refs/heads/master/sdk/android/src/java/org/webrtc/CameraCapturer.java#331).
