### ISSUE TITLE
Do you have any plan to add method addtransceiver to RtcPeerConnection?

### ISSUE THREAD

**Issue by kefayuan** [flutter-webrtc/flutter-webrtc#249]
I am trying to use it make broadcast function, but need addtransceiver to set send only and receive only, do you have any plan to add this api on RtcPeerConnection?

**Comment by cloudwebrtc** [comment]
The method API is included in the [unified-plan branch](https://github.com/cloudwebrtc/flutter-webrtc/tree/unified-plan), which is WIP
