### ISSUE TITLE
Construction of IOS demo encountered an error

### ISSUE THREAD

**Issue by yx-12138** [flutter-webrtc/flutter-webrtc#250]
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `flutter_webrtc` from `.symlinks/plugins/flutter_webrtc/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `path_provider_macos` from `.symlinks/plugins/path_provider_macos/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_7_7_8.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/7/7/8/Libyuv/1703/Libyuv.podspec.json to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/7/8/Libyuv/1703/Libyuv.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/7/7/8/Libyuv/1703.1/Libyuv.podspec.json to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/7/8/Libyuv/1703.1/Libyuv.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/7/7/8/Libyuv/1744/Libyuv.podspec.json to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/7/8/Libyuv/1744/Libyuv.podspec.json
      CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/7/8/Libyuv/1703/Libyuv.podspec.json Response: Couldn't connect to server, retries: 4
      CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/7/8/Libyuv/1703.1/Libyuv.podspec.json Response: Couldn't connect to server, retries: 4
      CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/7/8/Libyuv/1744/Libyuv.podspec.json Response: Couldn't connect to server, retries: 4
      CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/7/8/Libyuv/1703/Libyuv.podspec.json Response: Couldn't connect to server, retries: 3
      CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/7/8/Libyuv/1703.1/Libyuv.podspec.json Response: Couldn't connect to server, retries: 3
      CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/7/8/Libyuv/1744/Libyuv.podspec.json Response: Couldn't connect to server, retries: 3
      CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/7/8/Libyuv/1703/Libyuv.podspec.json Response: Couldn't connect to server, retries: 2
      CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/7/8/Libyuv/1703.1/Libyuv.podspec.json Response: Couldn't connect to server, retries: 2
      CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/7/8/Libyuv/1744/Libyuv.podspec.json Response: Couldn't connect to server, retries: 2
      CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/7/8/Libyuv/1703/Libyuv.podspec.json Response: Couldn't connect to server, retries: 1
      CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/7/8/Libyuv/1703.1/Libyuv.podspec.json Response: Couldn't connect to server, retries: 1
      CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/7/8/Libyuv/1744/Libyuv.podspec.json Response: Couldn't connect to server, retries: 1
    [!] CDN: trunk Repo update failed - 3 error(s):
    CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/7/8/Libyuv/1703/Libyuv.podspec.json Response: Couldn't connect to server
    CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/7/8/Libyuv/1703.1/Libyuv.podspec.json Response: Couldn't connect to server
    CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/7/8/Libyuv/1744/Libyuv.podspec.json Response: Couldn't connect to server

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/cdn_source.rb:475:in `rescue in concurrent_requests_catching_errors'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/cdn_source.rb:470:in `concurrent_requests_catching_errors'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/cdn_source.rb:121:in `versions'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/specification/set.rb:99:in `block in versions_by_source'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/specification/set.rb:98:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/specification/set.rb:98:in `each_with_object'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/specification/set.rb:98:in `versions_by_source'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/cdn_source.rb:216:in `search'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/source/aggregate.rb:83:in `select'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/source/aggregate.rb:83:in `search'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:385:in `find_cached_set'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:165:in `search_for'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:267:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:267:in `sort_by'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:410:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Finished with error: Error running pod install

**Comment by ycherniavskyi** [comment]
It seems you have a network issue `Couldn't connect to server`.
But in any case, you did not provide enough information to troubleshoot your issue.
* `flutter-webrtc` version?
* XCode version? 
* OS version?
* etc.

**Comment by yx-12138** [comment]
flutter-webrtc 0.2.8
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287,
    locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.43.2)

**Comment by yx-12138** [comment]
> 看来您遇到了网络问题`Couldn't connect to server`。
> 但是无论如何，您都没有提供足够的信息来解决问题。
> 
> * `flutter-webrtc` 版？
> * XCode版本？
> * 操作系统版本？
> * 等等

flutter-webrtc 0.2.8
[✓] Flutter（通道稳定，v1.12.13 + hotfix.9，在Mac OS X 10.15.4 19E287上，
语言环境zh-Hans-CN）

[✓] Android工具链-为Android设备开发（Android SDK版本29.0.2）
[✓] Xcode- 为iOS和macOS开发（Xcode 11.4.1）
[✓] Android Studio（版本3.6）
[✓] VS代码（版本1.43.2）

**Comment by yx-12138** [comment]
> It seems you have a network issue `Couldn't connect to server`.
> But in any case, you did not provide enough information to troubleshoot your issue.
> 
> * `flutter-webrtc` version?
> * XCode version?
> * OS version?
> * etc.

web-rtc0.2.8
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287,
    locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.43.2)

**Comment by cloudwebrtc** [comment]
@yx-12138  It looks like you are blocked by GFW from downloading libyuv related files, please make sure the network is smooth (科学上网).
```
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/7/8/Libyuv/1703/Libyuv.podspec.json Response: Couldn't connect to server, retries: 4
CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/7/8/Libyuv/1703.1/Libyuv.podspec.json Response: Couldn't connect to server, retries: 4
```

**Comment by yx-12138** [comment]
是的 我挂了VPN 能正常访问外网 但是还是这个结果

**Comment by yx-12138** [comment]
> @yx-12138 It looks like you are blocked by GFW from downloading libyuv related files, please make sure the network is smooth (科学上网).
> 
> ```
> CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/7/8/Libyuv/1703/Libyuv.podspec.json Response: Couldn't connect to server, retries: 4
> CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/7/7/8/Libyuv/1703.1/Libyuv.podspec.json Response: Couldn't connect to server, retries: 4
> ```

I did that, but it ’s still the same
