### ISSUE TITLE
Android device overheats while on video call

### ISSUE THREAD

**Issue by d3fkon** [flutter-webrtc/flutter-webrtc#252]
While on a video call, my android devices (OnePlus 6, One Plus 7, Redmi Note 5, Redmi Note 5  Plus) report a base temperature of 70 degrees Celsius and more. I observed that this persists for the first 5-7 mins of the video call. After that, the temperatures fall back to a normal. 
The phone almost becomes too hot to hold, and not to mention the battery drain this induces.

I ran the example app with my own server in Nodejs, hosted in the cloud. 
I haven't tested on iOS, so I cannot say what happens then.
I was pretty surprised that this wasn't already reported here, as it happens consistently, across all my devices
Thank you for this wonderful library. I just wish that this small thing gets some attention.

**Comment by cloudwebrtc** [comment]
By default, VP8 SW encoding will be used. You can try to modify it to H264 HW hardware acceleration encoding, which only requires extremely low CPU usage and energy consumption.

**Comment by d3fkon** [comment]
Great. Do I need to compile WebRTC and then import it into my project as mentioned [here](https://github.com/cloudwebrtc/flutter-webrtc/issues/53#issuecomment-521941144)? or is there a way of changing the Codec from the API's this library exposes

**Comment by maaarcus** [comment]
@cloudwebrtc 
Would you let us know more details about `modify it to H264 HW hardware acceleration encoding`? I am having the same problem that my phone's battery is drawing super fast. Thanks!

**Comment by patthipati** [comment]
@cloudwebrtc
I am also having the same problem that my phone's battery is drawing super fast. 
Any help would be great. This has become a huge issue right now.
Thanks!
