### ISSUE TITLE
Support creating empty MediaStream

### ISSUE THREAD

**Issue by leonidl** [flutter-webrtc/flutter-webrtc#253]
Sometimes it might be needed to create an empty local MediaStream object (e.g. when using SFU stuff).

Web based JS WebRTC API supports creating MediaStream object without any constructor parameters. Android and iOS WebRTC APIs have createLocalMediaStream() method in PeerConnectionFactory. It could be helpful to have this method wrapped in Dart.

I would suggest adding createLocalMediaStream() to web/mobile platforms, thus making the API universal across all platforms supported by flutter_webrtc.

I have coded the change in my flutter_webrtc fork and can submit a pull request.

**Comment by ycherniavskyi** [comment]
@leonidl PR is always welcome!

**Comment by leonidl** [comment]
Thanks, PR submitted (#254 )
