### ISSUE TITLE
Noise from Android devices

### ISSUE THREAD

**Issue by huulbaek** [flutter-webrtc/flutter-webrtc#255]
This may not be related to this repo and maybe it should be in GooglWebRTC but here goes:

When making media calls my test Android devices (two Pixel 3's) make a terrible noise to the other callers. So for example, if two iOS users talk everything is fine. If one iOS and one Android talk, the iOS user will hear loud noises and popping crackles.

The Android user will not hear anything strange.

If the Android user uses Bluetooth headset everything will sound ok on the iOS device – maybe this is related to echos?

**To Reproduce**
Make a call from any iOS device to a Pixel 3 device and set speakerphone like
```dart
_localStream.getAudioTracks().first.enableSpeakerphone(true);
```

**Expected behavior**
Crisp sound.

**Platform information**

* **Flutter version**: v1.17.0
* **Plugin version**: master

**Comment by ycherniavskyi** [comment]
From your description, it seems an echo-canceler issue.
Have you tried your experiment with a call from iOS to Pixel when devices in different rooms (or another world, has not to reach each other acoustically)?

**Comment by huulbaek** [comment]
Yes, I make all the calls in rooms a long way from each other in different rooms.

**Comment by huulbaek** [comment]
I'm thinking it may be related to [something like this](https://github.com/twilio/video-quickstart-android/issues/399) or [this](https://stackoverflow.com/questions/56429987/acoustic-echo-cancellation-on-android-not-working) or maybe it's choosing a wrong microphone by default.

I checked on another Android device, a Samsung tablet, and the problem did not occur so it seems device specific.

**Comment by ycherniavskyi** [comment]
@huulbaek hm, interesting, do you think we need to bring `WebRtcAudioManager.setBlacklistDeviceForOpenSLESUsage` method and/or `WebRtcAudioUtils.BLACKLISTED_OPEN_SL_ES_MODELS` variable to specific part of library API?

**Comment by huulbaek** [comment]
@ycherniavskyi Maybe. I will try to test the methods.

**Comment by ened** [comment]
@ycherniavskyi I've done similar tests as the problems appeared in the same way as @huulbaek explained. There are some particular Android devices that officially support AEC, but ship with a less than optimal implementation.

The following 3 lines helped:
```
WebRtcAudioManager.setBlacklistDeviceForOpenSLESUsage(true);
WebRtcAudioUtils.setWebRtcBasedAcousticEchoCanceler(true);
WebRtcAudioUtils.setWebRtcBasedNoiseSuppressor(true);
```

I've added them to the plugin itself, before the peers factory initialization, and now observe a improved call quality on Android.

Technically, those options are implementation details of flutter-webrtc; and I'm not sure where we'll end up if the plugin offers configuration of them. There simply a lot of options available in the WebRTC stack.

**Comment by MillerAdulu** [comment]
@ened In which particular file of the package did you add to these three lines of code?

**Comment by snowlyg** [comment]
> @ycherniavskyi I've done similar tests as the problems appeared in the same way as @huulbaek explained. There are some particular Android devices that officially support AEC, but ship with a less than optimal implementation.
> 
> The following 3 lines helped:
> 
> ```
> WebRtcAudioManager.setBlacklistDeviceForOpenSLESUsage(true);
> WebRtcAudioUtils.setWebRtcBasedAcousticEchoCanceler(true);
> WebRtcAudioUtils.setWebRtcBasedNoiseSuppressor(true);
> ```
> 
> I've added them to the plugin itself, before the peers factory initialization, and now observe a improved call quality on Android.
> 
> Technically, those options are implementation details of flutter-webrtc; and I'm not sure where we'll end up if the plugin offers configuration of them. There simply a lot of options available in the WebRTC stack.


> I added two lines below the methods of the JavaAudioDeviceModule.class to disable hardware echo cancellation, it works well.
  [webrtc-android-echo-cancellation](https://stackoverflow.com/questions/62479789/webrtc-android-echo-cancellation) :

```java
setUseHardwareAcousticEchoCanceler(false)       
setUseHardwareNoiseSuppressor(false)
```
