### ISSUE TITLE
Missing bufferedAmount property in RTCDataChannel 

### ISSUE THREAD

**Issue by achjqz** [flutter-webrtc/flutter-webrtc#257]
The data channel will be closed When sending large file since the buffer is full.

I found a solution that I should stop sending when bufferedAmount is over a threshold. 

But currently, the bufferedAmount property is missing. It would be better if there is a callback when the bufferedAmount  is below bufferedAmountLowThreshold.

**Comment by ycherniavskyi** [comment]
Are any examples of such API already exist in any library?

**Comment by achjqz** [comment]
> Are any examples of such API already exist in any library?

In android WebRTC library, there is a bufferedAmount function to get send buffer. It also has a callback named onBufferedAmountChange. [Ref](https://chromium.googlesource.com/external/webrtc/+/refs/heads/master/sdk/android/api/org/webrtc/DataChannel.java)

I also learned that aiortc, a WebRTC  library in python has such API. [Ref](https://github.com/aiortc/aiortc/blob/31abde4c7f142527a2a59c76333aafe627d4b2c6/src/aiortc/rtcdatachannel.py#L84)

**Comment by Codeusa** [comment]
We'll be opening a pull request to add this into flutter-webrtc. For reference however, here is how we do it in our other WebRTC library.


https://github.com/RainwayApp/spitfire/blob/master/Spitfire/DataChannelObserver.cpp

**Comment by jakobleck** [comment]
No resolution of this issue so far? This is still a relevant problem!

**Comment by ekwoue** [comment]
I need this for my application. Can this issue be reopened?
