### ISSUE TITLE
Recorder app does not work after video call on Android

### ISSUE THREAD

**Issue by neoend** [flutter-webrtc/flutter-webrtc#265]
Recorder app does not work after video call on Android with following message:
"Cannot record during a call"
The recorder app worked only after the app was completely removed in task with menu button.

It seems that the app is still using the microphone even after the app is finished.

**Comment by vibhoothiiaanand** [comment]
I can confirm that when I am trying to build an app with flutter ion sdk, I am facing similar/same issue.

**Comment by MrAlek** [comment]
Bumping this as we're also experiencing this issue.

The exact message in English is "Unable to record video during call". Googling this gives almost nothing.
