### ISSUE TITLE
Camera not disposing

### ISSUE THREAD

**Issue by rajababu3** [flutter-webrtc/flutter-webrtc#277]
I have disposed the local and remote stream but still, I get this 

`I/org.webrtc.Logging(21849): CameraStatistics: Camera fps: 30.`

What will be the possible fix for this solution?

I am disposing of everything. 

```
  var helper = widget._helper;
      var rid = helper.roomId;
      var client = helper.client;

      if (_localVideo != null) {
        // stop local video

        print("\n LOCAL STREAM");

        var stream = _localVideo.stream;
        await client.unpublish(_localVideo.mid);
        await stream.dispose();

        await _localVideo.dispose();
        _localVideo = null;
      }

      _remoteVideos.forEach((item) async {
        var stream = item.stream;
        print("\n\n\n\n $item \n\n\n REMOTE VIDEOS");
        try {
          await client.unsubscribe(rid, item.mid);
          await stream.dispose();
        } catch (error) {}
      });
      this.setState(() {});
      _remoteVideos.clear();
      await widget._helper.close();

      this.setState(() {
        userDevice = {};
      });

      Navigator.of(context).pop();
```

**Comment by HathTech** [comment]
Any update on this? 

I have developed the app with this and we are launching this app end of this month. 

Please help me :(

**Comment by pfaffenrodt** [comment]
@rajababu3 your Issue report is lacking in Information. In my usecase, it is disposing.

What Developers need to know, what an Issue report should contain is:

* Your version of the framework. 
* What Device did you have used? 
* What Os your device is Running? This is an multiplatform framework.
* Android has multiple camera implementations. What camera version do your device use? 
* never ask someone to fix your code. That sample code is not helpful. if it is not telling anything. provide maybe an sample app via fork of the demo app?
