### ISSUE TITLE
Passing calling signals between page

### ISSUE THREAD

**Issue by rhanifrizal** [flutter-webrtc/flutter-webrtc#279]
Currently i am using one page with all the signaling function. 
However, i am thinking on creating multiple page. Is there any way i can pass the signals between pages if the user went on another page?

**Comment by simon-twonary** [comment]
I recommend you use the Bloc Pattern, separating your signaling functions from the UI.

**Comment by rhanifrizal** [comment]
Thank you for answering. I am still new with flutter so I am still learning about it. Is there any documentation you would recommend for the bloc pattern or is there any flutter webrtc that used bloc pattern?

**Comment by wer-mathurin** [comment]
https://bloclibrary.dev/#/

I will close this ticket since is not related to this library.
