### ISSUE TITLE
If we first create a peer-to-peer connection and then create a local stream, "add stream" does not work.

### ISSUE THREAD

**Issue by tqfso** [flutter-webrtc/flutter-webrtc#282]
**Describe the bug**

I've successfully created peer to peer connection  without a local stream, and after a period of time, I want to add local stream to this connection, but it doesn't work. and the 'onAddStream' event  never occurred.

**Comment by pfaffenrodt** [comment]
It is not helpful, if you just delete the whole bug template.

I guess this is not a Bug. You just not know how to deal with it.
