### ISSUE TITLE
Using flutter-webrtc with Ant Media server

### ISSUE THREAD

**Issue by prashantspandey** [flutter-webrtc/flutter-webrtc#283]
HI I am new to webrtc tech. 
But we have bought aws ant media server (https://aws.amazon.com/marketplace/pp/Ant-Media-Ant-Media-Server-Enterprise-Low-Latency-/B07569Y9SJ).
How am trying to make a many to many web conferencing live video . Is it possible to connect flutter-webrtc and ant media server?
Is there any guide for this?

Thanks.

**Comment by cloudwebrtc** [comment]
@prashantspandey You need to analyze the Ant Media Server protocol and develop the flutter client sdk for the server.

**Comment by lumec** [comment]
> HI I am new to webrtc tech.
> But we have bought aws ant media server (https://aws.amazon.com/marketplace/pp/Ant-Media-Ant-Media-Server-Enterprise-Low-Latency-/B07569Y9SJ).
> How am trying to make a many to many web conferencing live video . Is it possible to connect flutter-webrtc and ant media server?
> Is there any guide for this?
> 
> Thanks.

Could you integrate your Ant Media Server with this plugin?

**Comment by cloudwebrtc** [comment]
@lumec 
Yes, if you need it, you can send an email to me, we can provide fee-based services.
