### ISSUE TITLE
ICE status Disconnected

### ISSUE THREAD

**Issue by Rajnish63** [flutter-webrtc/flutter-webrtc#284]
I have been trying the plugin to connect my android device with my website but I keep on getting ICE status disconnected. I have used Socket for signalling and I'am sure that candidates are being sent and received on both sides. But I am still not able to connect.

**Comment by Afael** [comment]
@Rajnish63 I have The same issue, did you find any solutions?

**Comment by Rajnish63** [comment]
No, I am still struggling hard for it.

**Comment by ycherniavskyi** [comment]
Only by providing a minimal test project with your issue could give someone the possibility to help you.

But in general, does [flutter-webrtc-demo](/flutter-webrtc/flutter-webrtc-demo) work for you? Do you have the same issue with it?

**Comment by Rajnish63** [comment]
Code for socket connection:
`
class Signaling {
  Signaling._();
  static final Signaling instance = Signaling._();

  IO.Socket _socket =
      IO.io(Constant.HOST, <String, dynamic>{
    'transports': ['websocket'],
    'autoConnect': false,
  });

  BuildContext _context;

  // for video call
  MediaStream _localStream;
  RTCPeerConnection _peerConnection;
  var _localRenderer;
  var _remoteRenderer;
  String socketID = '';
  var _remoteCandidates = [];

  String _username; // contact of self

  final Map<String, dynamic> mediaConstraints = {
    "audio": true,
    'video': {
      'mandatory': {
        "minWidth": '640',
        "minHeight": '480',
        "minFrameRate": '30',
      },
      'facingMode': 'environment',
      'optional': [],
    },
  };

  Map<String, dynamic> configuration = {
    "iceServers": [
      {"urls": "stun:stun.**********"},
      {
        'urls': 'turn:turn.********?transport=tcp',
        'username': '*******',
        'credential': '**********',
      },
    ]
  };

  final Map<String, dynamic> offer_sdp_constraints = {
    "optional": [],
    "mandatory": {
      "OfferToReceiveAudio": true,
      "OfferToReceiveVideo": true,
    },
  };

  final Map<String, dynamic> loopback_constraints = {
    'mandatory': {},
    'optional': [
      {'DtlsSrtpKeyAgreement': true},
    ],
  };

  String getUser() {
    return _username;
  }

  // connecting socket
  void connect() {
    _socket.connect();
    _registerEvents(); // register events once initiated
  }

  void close() {
    if (_socket != null) _socket.io.disconnect();
  }

  IO.Socket getSocketInstance() {
    return _socket;
  }

  // function to initalize params
  void setEssentials({ BuildContext context }) {
    _context = context; // some other stuuffs too...
  }

  // register events
  void _registerEvents() {
    // on connected
    _socket.on('connect', _joinRoom);

    // on disonnect
    _socket.on('disconnect', (_) => print('Disconnected'));

    // on call
    _socket.on('call', answerCall);

    _socket.on('pick', (data) async {
      print('socket event callback: pick');
      socketID = data['sid'];
      _createCall();
    });

    _socket.on('webrtc_offer', (data) async {
      print('Socket event callback: webrtc_offer');
      _answerCall(data);
    });

    _socket.on('webrtc_answer', (sid) {
      RTCSessionDescription _rempteDesc =
          new RTCSessionDescription(sid['sdp'], sid['type']);
      _peerConnection.setRemoteDescription(_rempteDesc); // remote
      print('Socket event callback: webrtc_answer');
    });

    _socket.on('cut_call', (data) {
      Navigator.pop(_context);
      hangUp();
    });

    _socket.on('webrtc_ice_candidate', (event) {
      print('Socket event callback: webrtc_ice_candidate');
      var a = event['candidate']['sdpMlineIndex'] ?? 0;
      // ICE candidate add
      RTCIceCandidate candidate = new RTCIceCandidate(
          event['candidate']['candidate'], event['candidate']['sdpMid'], a);
      if (_peerConnection != null) {
        _peerConnection.addCandidate(candidate);
      } else {
        _remoteCandidates.add(candidate);
      }
    });
  }

  void switchCamera() {
    if (_localStream != null) {
      _localStream.getVideoTracks()[0].switchCamera();
    }
  }

  Future<void> startCall(callTo) async {
    // init data
    _localRenderer = RTCVideoRenderer();
    _remoteRenderer = RTCVideoRenderer();

    await _localRenderer.initialize();
    await _remoteRenderer.initialize();

    _peerConnection = null;

    _socket.emit('call', {
      'from': _username,
      'to': callTo,
      'type': 'video',
    });
    Navigator.pushNamed(_context, '/video');
  }

  void answerCall(data) async {
    // init data
    socketID = data['sid']; // 'from' & 'to'
    _localRenderer = RTCVideoRenderer();
    _remoteRenderer = RTCVideoRenderer();

    await _localRenderer.initialize();
    await _remoteRenderer.initialize();

    _peerConnection = null;
    Navigator.pushNamed(_context, '/calling',
        arguments: {'name': data['from'], 'type': 'video'});
  }

  pickupCall() {
    _socket.emit('pick', {'sid': socketID});
    Navigator.pushReplacementNamed(_context, '/video-recieve');
  }

  cutCall() {
    _socket.emit('cut_call', {'sid': socketID});
  }

  _onSignalingState(RTCSignalingState state) {
    print('!!!!!!!!!!!!!');
    print(state);
  }

  _onIceGatheringState(RTCIceGatheringState state) {
    print('!!!!!!!!!!!!!');
    print(state);
  }

  _onIceConnectionState(RTCIceConnectionState state) async {
    print('!!!!!!!!!!!!!');
    if (state == RTCIceConnectionState.RTCIceConnectionStateDisconnected ||
        state == RTCIceConnectionState.RTCIceConnectionStateFailed) {
      await hangUp();
    }
    print(state);
  }

  _onAddStream(MediaStream stream) {
    print('addStream: ' + stream.id);
    _remoteRenderer.srcObject = stream;
  }

  _onRemoveStream(MediaStream stream) {
    _remoteRenderer.srcObject = null;
  }

  _onRenegotiationNeeded() {
    print('RenegotiationNeeded');
  }

  _sendIceCandidate(RTCIceCandidate candidate) {
    if (candidate != null) {
      _socket.emit('webrtc_ice_candidate', {
        'sid': socketID,
        'candidate': {
          'sdpMid': candidate.sdpMid,
          'sdpMlineIndex': candidate.sdpMlineIndex,
          'candidate': candidate.candidate,
        }
      });
    }
  }

  _createCall() async {
    if (_peerConnection != null) return;

    try {
      _localStream = await navigator.getUserMedia(mediaConstraints);
      _localRenderer.srcObject = _localStream;

      _peerConnection =
          await createPeerConnection(configuration, loopback_constraints);

      _peerConnection.onSignalingState = _onSignalingState;
      _peerConnection.onIceGatheringState = _onIceGatheringState;
      _peerConnection.onIceConnectionState = _onIceConnectionState;
      _peerConnection.onAddStream = _onAddStream;
      _peerConnection.onRenegotiationNeeded = _onRenegotiationNeeded;

      _peerConnection.onAddStream = _onAddStream;
      // _peerConnection.onRemoveStream = _onRemoveStream;
      _peerConnection.onIceCandidate = _sendIceCandidate;
      _peerConnection.addStream(_localStream);

      _peerConnection.createOffer(offer_sdp_constraints).then((description) {
        _peerConnection.setLocalDescription(description);
        _localStream.getAudioTracks()[0].setMicrophoneMute(false);
        _socket.emit('webrtc_offer', {
          'type': 'webrtc_offer',
          'sdp': description.toMap(),
          'sid': socketID,
        });
      });
    } catch (e) {
      print(e.toString());
    }
  }

  _answerCall(sid) async {
    if (_peerConnection != null) return;

    try {
      _localStream = await navigator.getUserMedia(mediaConstraints);
      _localRenderer.srcObject = _localStream;

      _peerConnection =
          await createPeerConnection(configuration, loopback_constraints);

      _peerConnection.onSignalingState = _onSignalingState;
      _peerConnection.onIceGatheringState = _onIceGatheringState;
      _peerConnection.onIceConnectionState = _onIceConnectionState;
      _peerConnection.onAddStream = _onAddStream;
      _peerConnection.onRenegotiationNeeded = _onRenegotiationNeeded;

      _peerConnection.onAddStream = _onAddStream;
      // _peerConnection.onRemoveStream = _onRemoveStream;
      _peerConnection.onIceCandidate = _sendIceCandidate;
      _peerConnection.addStream(_localStream);

      // adding left overs candidates
      if (_remoteCandidates.length > 0) {
        _remoteCandidates.forEach((candidate) async {
          await _peerConnection.addCandidate(candidate);
        });
        _remoteCandidates.clear();
      }

      RTCSessionDescription _rempteDesc =
          new RTCSessionDescription(sid['sdp'], sid['type']);
      _peerConnection.setRemoteDescription(_rempteDesc); // remote

      _peerConnection.createAnswer(offer_sdp_constraints).then((description) {
        _peerConnection.setLocalDescription(description);
        _localStream.getAudioTracks()[0].setMicrophoneMute(false);
        _socket.emit('webrtc_answer', {
          'type': 'webrtc_answer',
          'sdp': description.toMap(),
          'sid': socketID,
        });
      });
    } catch (e) {
      print(e.toString());
    }
  }

  getLocalRenderer() {
    return _localRenderer;
  }

  getRemoteRenderer() {
    return _remoteRenderer;
  }

  hangUp() async {
    try {
      if (_localStream != null) {
        await _localStream.dispose();
        _localRenderer.srcObject = null;
      }
      if (_peerConnection != null) await _peerConnection.close();
      _peerConnection = null;
      if (_remoteRenderer != null) {
        _remoteRenderer.srcObject = null;
      }
    } catch (e) {
      print(e.toString());
    } finally {
      Navigator.of(_context).popUntil((route) => route.isFirst);
    }
  }

  _joinRoom(data) async {
    var prefs = await SharedPreferences.getInstance();
    _username = prefs.getString(Constant.USER_CONTACT);
    Map<String, dynamic> userData = {'username': _username};
    _socket.emit('joinPrivateRoom', userData);
  }
}
`

Video recieve call
`import 'package:flutter/material.dart';
import 'package:flutter_webrtc/rtc_video_view.dart';
import 'package:flutter_webrtc/webrtc.dart';
import 'package:koram/services/socket.dart';

class VideoRecieve extends StatefulWidget {
  @override
  _VideoRecieveState createState() => _VideoRecieveState();
}

class _VideoRecieveState extends State<VideoRecieve> {
  @override
  deactivate() {
    super.deactivate();
    Signaling.instance.hangUp();
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: OrientationBuilder(builder: (context, orientation) {
        return Container(
          child: Stack(children: <Widget>[
            Positioned(
                left: 0.0,
                right: 0.0,
                top: 0.0,
                bottom: 0.0,
                child: Container(
                  margin: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 0.0),
                  width: MediaQuery.of(context).size.width,
                  height: MediaQuery.of(context).size.height,
                  child: RTCVideoView(Signaling.instance.getRemoteRenderer()),
                  decoration: BoxDecoration(color: Colors.black54),
                )),
            Positioned(
              left: 20.0,
              top: 20.0,
              child: Container(
                width: orientation == Orientation.portrait ? 90.0 : 120.0,
                height: orientation == Orientation.portrait ? 120.0 : 90.0,
                child: RTCVideoView(Signaling.instance.getLocalRenderer()),
                decoration: BoxDecoration(color: Colors.black54),
              ),
            ),
            Positioned(
              right: 10.0,
              top: 50.0,
              child: RawMaterialButton(
                onPressed: () {
                  Signaling.instance.switchCamera();
                },
                elevation: 2.0,
                fillColor: Colors.white,
                child: Icon(
                  Icons.rotate_left,
                  size: 20.0,
                ),
                padding: EdgeInsets.all(6.0),
                shape: CircleBorder(),
              ),
            ),
          ]),
        );
      }),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
      floatingActionButton: FloatingActionButton(
        backgroundColor: Colors.red,
        onPressed: () {
          Signaling.instance.hangUp();
        },
        tooltip: 'Hangup',
        child: Icon(Icons.call_end, color: Colors.white,),
      ),
    );
  }
}
`

Video start call
`
import 'package:flutter/material.dart';
import 'package:flutter_webrtc/rtc_video_view.dart';
import 'package:flutter_webrtc/webrtc.dart';
import 'package:koram/services/socket.dart';

class Video extends StatefulWidget {
  @override
  _VideoState createState() => _VideoState();
}

class _VideoState extends State<Video> {
  bool isCalling = true;

  @override
  void initState() {
    super.initState();
  }

  @override
  deactivate() {
    super.deactivate();
    Signaling.instance.hangUp();
  }

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: (!isCalling)
          ? Center(
              child: CircularProgressIndicator(
                backgroundColor: Colors.green,
              ),
            )
          : OrientationBuilder(builder: (context, orientation) {
              return Container(
                child: Stack(children: <Widget>[
                  Positioned(
                      left: 0.0,
                      right: 0.0,
                      top: 0.0,
                      bottom: 0.0,
                      child: Container(
                        margin: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 0.0),
                        width: MediaQuery.of(context).size.width,
                        height: MediaQuery.of(context).size.height,
                        child: RTCVideoView(
                            Signaling.instance.getRemoteRenderer()),
                        decoration: BoxDecoration(color: Colors.black54),
                      )),
                  Positioned(
                    left: 20.0,
                    top: 20.0,
                    child: Container(
                      width: orientation == Orientation.portrait ? 90.0 : 120.0,
                      height:
                          orientation == Orientation.portrait ? 120.0 : 90.0,
                      child:
                          RTCVideoView(Signaling.instance.getLocalRenderer()),
                      decoration: BoxDecoration(color: Colors.black54),
                    ),
                  ),
                  Positioned(
                    right: 10.0,
                    top: 50.0,
                    child: RawMaterialButton(
                      onPressed: () {
                        Signaling.instance.switchCamera();
                      },
                      elevation: 2.0,
                      fillColor: Colors.white,
                      child: Icon(
                        Icons.rotate_left,
                        size: 20.0,
                      ),
                      padding: EdgeInsets.all(6.0),
                      shape: CircleBorder(),
                    ),
                  ),
                ]),
              );
            }),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
      floatingActionButton: FloatingActionButton(
        backgroundColor: Colors.red,
        onPressed: () {
          Signaling.instance.hangUp();
        },
        tooltip: 'Hangup',
        child: Icon(
          Icons.call_end,
          color: Colors.white,
        ),
      ),
    );
  }
}

`

**Comment by Rajnish63** [comment]
Video recieve call
`

    import 'package:flutter/material.dart';
    import 'package:flutter_webrtc/rtc_video_view.dart';
    import 'package:flutter_webrtc/webrtc.dart';
    import 'package:koram/services/socket.dart';

    class VideoRecieve extends StatefulWidget {
      @override
      _VideoRecieveState createState() => _VideoRecieveState();
    }

    class _VideoRecieveState extends State<VideoRecieve> {
      @override
      deactivate() {
        super.deactivate();
        Signaling.instance.hangUp();
      }

      @override
      Widget build(BuildContext context) {
        return new Scaffold(
          body: OrientationBuilder(builder: (context, orientation) {
            return Container(
              child: Stack(children: <Widget>[
                Positioned(
                    left: 0.0,
                    right: 0.0,
                    top: 0.0,
                    bottom: 0.0,
                    child: Container(
                      margin: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 0.0),
                      width: MediaQuery.of(context).size.width,
                      height: MediaQuery.of(context).size.height,
                      child: RTCVideoView(Signaling.instance.getRemoteRenderer()),
                      decoration: BoxDecoration(color: Colors.black54),
                    )),
                Positioned(
                  left: 20.0,
                  top: 20.0,
                  child: Container(
                    width: orientation == Orientation.portrait ? 90.0 : 120.0,
                    height: orientation == Orientation.portrait ? 120.0 : 90.0,
                    child: RTCVideoView(Signaling.instance.getLocalRenderer()),
                    decoration: BoxDecoration(color: Colors.black54),
                  ),
                ),
                Positioned(
                  right: 10.0,
                  top: 50.0,
                  child: RawMaterialButton(
                    onPressed: () {
                      Signaling.instance.switchCamera();
                    },
                    elevation: 2.0,
                    fillColor: Colors.white,
                    child: Icon(
                      Icons.rotate_left,
                      size: 20.0,
                    ),
                    padding: EdgeInsets.all(6.0),
                    shape: CircleBorder(),
                  ),
                ),
              ]),
            );
          }),
          floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
          floatingActionButton: FloatingActionButton(
            backgroundColor: Colors.red,
            onPressed: () {
              Signaling.instance.hangUp();
            },
            tooltip: 'Hangup',
            child: Icon(Icons.call_end, color: Colors.white,),
          ),
        );
      }
    }

    
`

**Comment by Rajnish63** [comment]
Video start call UI

`


    import 'package:flutter/material.dart';
    import 'package:flutter_webrtc/rtc_video_view.dart';
    import 'package:flutter_webrtc/webrtc.dart';
    import 'package:koram/services/socket.dart';

    class Video extends StatefulWidget {
      @override
      _VideoState createState() => _VideoState();
    }

    class _VideoState extends State<Video> {
      bool isCalling = true;

      @override
      void initState() {
        super.initState();
      }

      @override
      deactivate() {
        super.deactivate();
        Signaling.instance.hangUp();
      }

      @override
      Widget build(BuildContext context) {
        return new Scaffold(
          body: (!isCalling)
              ? Center(
                  child: CircularProgressIndicator(
                    backgroundColor: Colors.green,
                  ),
                )
              : OrientationBuilder(builder: (context, orientation) {
                  return Container(
                    child: Stack(children: <Widget>[
                      Positioned(
                          left: 0.0,
                          right: 0.0,
                          top: 0.0,
                          bottom: 0.0,
                          child: Container(
                            margin: EdgeInsets.fromLTRB(0.0, 0.0, 0.0, 0.0),
                            width: MediaQuery.of(context).size.width,
                            height: MediaQuery.of(context).size.height,
                            child: RTCVideoView(
                                Signaling.instance.getRemoteRenderer()),
                            decoration: BoxDecoration(color: Colors.black54),
                          )),
                      Positioned(
                        left: 20.0,
                        top: 20.0,
                        child: Container(
                          width: orientation == Orientation.portrait ? 90.0 : 120.0,
                          height:
                              orientation == Orientation.portrait ? 120.0 : 90.0,
                          child:
                              RTCVideoView(Signaling.instance.getLocalRenderer()),
                          decoration: BoxDecoration(color: Colors.black54),
                        ),
                      ),
                      Positioned(
                        right: 10.0,
                        top: 50.0,
                        child: RawMaterialButton(
                          onPressed: () {
                            Signaling.instance.switchCamera();
                          },
                          elevation: 2.0,
                          fillColor: Colors.white,
                          child: Icon(
                            Icons.rotate_left,
                            size: 20.0,
                          ),
                          padding: EdgeInsets.all(6.0),
                          shape: CircleBorder(),
                        ),
                      ),
                    ]),
                  );
                }),
          floatingActionButtonLocation: FloatingActionButtonLocation.centerFloat,
          floatingActionButton: FloatingActionButton(
            backgroundColor: Colors.red,
            onPressed: () {
              Signaling.instance.hangUp();
            },
            tooltip: 'Hangup',
            child: Icon(
              Icons.call_end,
              color: Colors.white,
            ),
          ),
        );
      }
    }


`

**Comment by Rajnish63** [comment]
> Only by providing a minimal test project with your issue could give someone the possibility to help you.
> 
> But in general, does [flutter-webrtc-demo](/flutter-webrtc/flutter-webrtc-demo) work for you? Do you have the same issue with it?
Yes it works.

**Comment by ycherniavskyi** [comment]
Wow, @Rajnish63 creating [Gist](https://gist.github.com) and sharing here link to it will be much handy then posting such bit blocks of code in comments.

**Comment by Rajnish63** [comment]
Snippets over here:
https://gist.github.com/Rajnish63/35b31fd16df824a01e0f8d7871d7a93e

**Comment by wer-mathurin** [comment]
Not sure if it can help.  But, I faced the same problem but was related to the coturn sever configuration rejecting certain IP.
