### ISSUE TITLE
Demo project for interacting with other WebRTC implementation.

### ISSUE THREAD

**Issue by pickledbrill** [flutter-webrtc/flutter-webrtc#285]
**Is your feature request related to a problem? Please describe.**

I'm working on an Electron App for broadcasting the screen, and I want to know if this plugin going to work on Flutter Android App for receiving the stream.

**Describe the solution you'd like**

Any available demo projects about interacting with different WebRTC implementations.

**Describe alternatives you've considered**

No

**Additional context**

No

**Comment by cloudwebrtc** [comment]
> I'm working on an Electron App for broadcasting the screen, and I want to know if this plugin going to work on Flutter Android App for receiving the stream.

Yes

> Any available demo projects about interacting with different WebRTC implementations.

No, just flutter for Cross-platform example.
https://github.com/flutter-webrtc/flutter-webrtc-demo
