### ISSUE TITLE
Record audio-only

### ISSUE THREAD

**Issue by vtungn** [flutter-webrtc/flutter-webrtc#286]
I try record audio-only and got 
```
//TODO(rostopira): audio only recording
                throw new Exception("Audio-only recording not implemented yet");
```
So @rostopira in the mean time can you help me some idea to implement this feature.

Thank you guy.

**Comment by jcnoriega** [comment]
@vtungn have you heard from @rostopira? Or at least found a why to implemented? I could really need the help! im implementing an app that needs to record audio only on a call, when the user requests it.

**Comment by softronaut** [comment]
Do you mean audio-only is MediaRecorder or Audio Call/Streaming? I'm trying to build an app that requires audio-only calls.

**Comment by jsyqrt** [comment]
> @vtungn have you heard from @rostopira? Or at least found a why to implemented? I could really need the help! im implementing an app that needs to record audio only on a call, when the user requests it.

Hi @jcnoriega , did you find a solution for this?  I am in the same problem now
