### ISSUE TITLE
How to send dtmf over webrtc

### ISSUE THREAD

**Issue by xyzbilal** [flutter-webrtc/flutter-webrtc#292]
Hi, is there any way to send dtmf tones over this package. I see there is a class named RTCDTMFSender  but its empty.
please guide me to make this available on my project. thanks.

**Comment by cloudwebrtc** [comment]
@xyzbilal Yes, the dart interface needs to be packaged

**Comment by xyzbilal** [comment]
any plan to put it in the package?

**Comment by ghenry** [comment]
rfc2833 version :-)

**Comment by xyzbilal** [comment]
> rfc2833 version :-)

I didnt get the point. sorry. Can you please tell me what should I do?

**Comment by maanas** [comment]
@cloudwebrtc Can you guide me on how to patch for DTMF and integrate the rfc2833.

I also see in rtc_peerconnection the methods addTrack do not exist. 
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addTrack
Can you point me to the right resource I want to contribute the patch? 

I am trying to make a port of janus.js and got stuck in the missing calls.
https://github.com/maanasnetwork/flutter_janus

**Comment by cloudwebrtc** [comment]
@maanas 
We just need to export the following two API interfaces to rtc_dtmf_sender.dart
https://github.com/flutter-webrtc/webrtc-mirror/blob/master/sdk/objc/api/peerconnection/RTCDtmfSender.h
https://github.com/flutter-webrtc/webrtc-mirror/blob/master/sdk/android/api/org/webrtc/DtmfSender.java

These two interface files are included in the GoogleWebRTC SDK.

**Comment by xyzbilal** [comment]
dear @cloudwebrtc , is there any plan to add this functionality to package. I desperately  waiting for this update. thanks

**Comment by xyzbilal** [comment]
Finally I found my own solution.

first I added this code block to android MethodCallHandlerImpl.java

```
case "sendDtmf": {
        String peerConnectionId = call.argument("peerConnectionId");
        String tone = call.argument("tone");
        PeerConnection peerConnection = getPeerConnection(peerConnectionId);
        if (peerConnection != null) {
        
          RtpSender m_audioSender = null;
          for (RtpSender sender : peerConnection.getSenders()) {

            if (sender.track().kind().equals("audio")) {
             m_audioSender = sender;
            } 
          }
          if (m_audioSender != null) {
            DtmfSender dtmfSender = m_audioSender.dtmf();
            dtmfSender.insertDtmf(tone, 50, 50);
          }
          result.success("success");
        } else {
          Log.d(TAG, "dtmf() peerConnection is null");
          result
              .error("dtmf", "getRemoteDescription() peerConnection is null",
                  null);
        }
        break;
      }
```

then I added sendDtmf function to rtc_peerconnection.dart

```
Future<void> sendDtmf(String tone) async {
    await _channel.invokeMethod('sendDtmf', <String, dynamic>{
      'peerConnectionId': this._peerConnectionId,
      'tone': tone,
    });
  }
```

and yes it worked. I know it is not right way but it solved my problem. I will try it for IOS also and will update my answer

**Comment by cloudwebrtc** [comment]
If it works, maybe you can submit a PR,  ;)
