### ISSUE TITLE
Flutter web echo/reverb

### ISSUE THREAD

**Issue by wer-mathurin** [flutter-webrtc/flutter-webrtc#295]
**Describe the bug**
On Flutter web only, when initializing userMedia from a browser (Chrome) and for some reason their I can hear myself.

**To Reproduce**
```dart
var mediaConstraints= {
    'audio': true,
    'video': {
      'mandatory': {
        'minWidth': '640',
        'minHeight': '480',
        'minFrameRate': '30',
      },
      'facingMode': 'user',
      'optional': [],
    }
  };
var _localStream = await navigator.getUserMedia(mediaConstraints);
var _localRenderer = RTCVideoRenderer();
var _localRenderer.srcObject = stream;
```

**Expected behavior**
I'm not supposed to ear myself.

**Platform information**
Flutter Web

* **Flutter version**: 
[√] Flutter (Channel beta, 1.19.0-4.3.pre, on Microsoft Windows [version 10.0.18363.900], locale fr-CA)
    • Flutter version 1.19.0-4.3.pre at C:\we-r\development\flutter
    • Framework revision 8fe7655ed2 (3 weeks ago), 2020-07-01 14:31:18 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\we-r\development\android
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\we-r\development\android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\we-r\development\intelliJ\2019.2.2
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6603.23

[√] VS Code (version 1.47.2)
    • VS Code at C:\Users\mathu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.2

[√] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server                • web-server    • web-javascript • Flutter Tools
    • Chrome                    • chrome        • web-javascript • Google Chrome 84.0.4147.89

• No issues found!

* **Plugin version**:
 flutter_webrtc:
    git:
      url: git://github.com/cloudwebrtc/flutter-webrtc.git

* **OS**: 
Windows 10 Professional

* **OS version**:
18363.900

**Comment by wer-mathurin** [comment]
After looking at the **web** source code of RTCVideoRenderer

I found out that this piece of code seems doing the problem;
 ui.platformViewRegistry.registerViewFactory(stream.id, (int viewId) {
      final x = HTML.VideoElement();
      x.autoplay = true;
      x.muted = false;
      x.srcObject = stream.jsStream;
      x.id = stream.id;
      _htmlVideoElement = x;
      _videoViews.add(x);
      return x;
    });


By changing the 
x.muted = false; =>x.muted = true; 

Problem solved :-)

I can do a PR if needed.

**Comment by ycherniavskyi** [comment]
@wer-mathurin PR is always welcome 😉!

**Comment by wer-mathurin** [comment]
Pull request done.
If someone can check it quick and merge it, can be very helpful.
We need this fix to release the app into production :-)

**Comment by ujwalbasnet1** [comment]
getting this issue on iOS.
i can hear myself but other person cannot hear me.
In android, i do not hear myself and other person can hear me without any issue.
