### ISSUE TITLE
Video artifacts

### ISSUE THREAD

**Issue by Lisomatrix** [flutter-webrtc/flutter-webrtc#297]
**Describe the bug:**
On call with 2 specific devices some video artifacts happen.

**To Reproduce:**
Run the demo with a Samsung S10+ exynos version and Galaxy J5

**Expected behavior:**
A normal video call

**Flutter version:**
Channel dev, 1.21.0-1.0.pre
Plugin version: happens for both demo version and latest

**OS versions**
J5 Android 7.1.1 and S10 + Android 10

I have tested the call with other devices like IPhone XI, IPhone 7, IPhone XR, SM-T530 and KIW-L21 and no problems occur only with those 2 specific devices.

![received_306319814050298.jpeg](https://user-images.githubusercontent.com/36449927/88393848-4b57ab00-cdb6-11ea-89c0-a65aabcb7bae.jpeg)
![Screenshot_20200724-130538.jpg](https://user-images.githubusercontent.com/36449927/88393861-501c5f00-cdb6-11ea-974b-ef5df36b246b.jpg)

**Comment by ycherniavskyi** [comment]
I almost sure that this issue related not to `flutter-webrtc` but to Google webrtc library and exactly to currently used `org.webrtc:google-webrtc:1.0.30039` version. So it is better to look for the answer to your issue in webrtc library trackers/forums/lists.
