### ISSUE TITLE
Support E2E encryption

### ISSUE THREAD

**Issue by cloudwebrtc** [flutter-webrtc/flutter-webrtc#300]
Insertable Streams.

**Comment by Ayman-Kortobaa** [comment]
Is there any documentation that can help us implementing insertable streams in native Android and iOS?
I'd love to help with this issue as it is critical.

**Comment by cloudwebrtc** [comment]
My plan is to use dart:ffi to directly call back the data of the native layer to the dart side, and directly modify the memory to encrypt the data.

**Comment by cloudwebrtc** [comment]
For example:


test.c for libtest.dylib

```C
typedef void (*add)(int, int);

int addcb(add addfn) {
    for(;;) {
        addfn(10, 20);
    }
    return 1;
}
```


test.dart
```dart
import 'dart:ffi';

typedef AddCbNative = Int32 Function(Pointer<NativeFunction<Add>> cb);
typedef AddCb = int Function(Pointer<NativeFunction<Add>> cb);

typedef Add = Void Function(Int32 a, Int32 b);

void add(int a, int b) {
  print('$a $b');
  return;
}

void main() {
  var library = DynamicLibrary.open("/Users/dww/Test/dart-ffi/test.dylib");
  var addcb = library.lookupFunction<AddCbNative, AddCb>("addcb");
  print(addcb(Pointer.fromFunction(add)));
}
```

Makefile
```Makefile
all: lib link

link:
	gcc test.o -dynamiclib -o test.dylib

lib:
	gcc -c test.c -o test.o

clean:
	rm -rf *.o *.dylib

test:
	dart test.dart
```

Run:
```bash
dart test.dart
10 20
10 20
10 20
10 20
10 20
10 20
10 20
```

**Comment by cloudwebrtc** [comment]
One thing to note is that we must write callbacks in the C++ layer, dart:ffi only supports C++/C.

**Comment by Ayman-Kortobaa** [comment]
@cloudwebrtc 
Firstly, thanks for replying and sorry for the late reply.
Sadly, this is out of my scope.

But I was reading the [Webrtc draft for insertable streams](https://htmlpreview.github.io/?https://github.com/w3c/webrtc-insertable-streams/blob/master/index.html) and noticed that they use Readable and Writable `streams` but since these are not found in Java's or Obj-C's API but there are `InputStream`, `OutputStream`, `CFReadStream` and `CFWriteStream`.

So I am wondering, is it feasible to wrapping Android and Obj-C's Webrtc SDKs even if they don't provide these interfaces?

**Comment by cloudwebrtc** [comment]
I think we must implement the [FrameEncryptorInterface](https://chromium.googlesource.com/external/webrtc/+/refs/heads/master/api/crypto/frame_encryptor_interface.h) and [FrameDecryptorInterface](https://chromium.googlesource.com/external/webrtc/+/refs/heads/master/api/crypto/frame_decryptor_interface.h), and export the raw data via dart:ffi, In this way, we can use encryption functions to manipulate raw data at the dart level. The binary file of GooglgeWebRTC does not provide such an interface. We need to compile libwebrtc and add the corresponding e2eetodart.cpp file.

**Comment by wvffle** [comment]
Sorry for writing in stale issue but was there any work done on that topic? @cloudwebrtc

**Comment by ltoenjes** [comment]
Hey there! Any updates on this? @cloudwebrtc

**Comment by cloudwebrtc** [comment]
This function must rely on self-compiled binary, so I created another organization https://github.com/webrtc-sdk. In this project, we need to expose the encryption and decryption interface to the native SDK, so we need to patch the libwebrtc native SDK first.
The development of this feature will take a lot of time. If anyone is willing to help or sponsor, it will speed up the implementation of this feature.

**Comment by ltoenjes** [comment]
@cloudwebrtc we'd like to financially support your efforts to enable this feature ASAP. Is a feature-specific sponsoring possible?

**Comment by cloudwebrtc** [comment]
Glad to hear this, It takes a lot of time for these platforms to support E2EE. The libwebrtc must be patched for all platforms, and then use Dart FFI to implement the encrypt interface on synchronously or asynchronously mode. I think the overall time will exceed 40-50 hours.

**Comment by qadoker** [comment]
@cloudwebrtc are there any changes about e2e encryption?

**Comment by cloudwebrtc** [comment]
done https://github.com/flutter-webrtc/flutter-webrtc/pull/1201
