### ISSUE TITLE
addStream() deprecated , doesn't work with angular webrtc-adapter 

### ISSUE THREAD

**Issue by coder491** [flutter-webrtc/flutter-webrtc#301]
Tried to integrate Flutter-webrtc with angular-webrtc , video and audio rendering not happening on latest browsers.

**Comment by wer-mathurin** [comment]
Hi coder491,

Probably this is cause by the implementation of 
lib/web/get_user_media.dart

```
final jsStream = await nav.getUserMedia(
          audio: mediaConstraints['audio'] ?? false,
          video: mediaConstraints['video'] ?? false);
```
   


According to:
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia

This means it will probably only work on Chrome and you need to change the above code to:
`final jsStream = await nav.mediaDevices.getUserMedia(mediaConstraints);`

I did not test it.  But seems a good startting point for your investigation.
If this works let me know, I or you can do a PR.

Best regards,
Louis-Michel

**Comment by wer-mathurin** [comment]
What is the browser you are currently using?
As per the compatibility table bellow: the current implementation may be not working since we are relying on onAddStream event!
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addStream#Browser_compatibility

**Comment by coder491** [comment]
I use latest browsers of mozilla and chrome, neither of them are working with flutter webrtc. Addstream is deprecated , no longer supported on latest browsers.

**Comment by coder491** [comment]
How to make peer.Addstream() of flutter- webrtc compatible with ontrack() of angular-webrtc?

**Comment by wer-mathurin** [comment]
Can you share your code to see what is going on.
I used flutter-webrtc with flutter web without problems running on Chrome.

**Comment by coder491** [comment]
navigator.getUsermedia(mediaConstrainsts).then(stream) {
_peerConnection.addStream(stream)
}

On flutter-webrtc

_remotepeerConnection.onteack =(event) => {
this.video.srcObject=event.streams[0];
}

On angular-webrtc

**Comment by wer-mathurin** [comment]
Thanks for sharing.  Looks like you are using an older version of the library.  Can you update to the latest one: 0.3.3?
You will need to change your import and change navigator by MediaDevices.

And as I can see in the RTCPeerConnection.  It listen to on the onAddStream event provided by the JS dart implementation.

**Comment by coder491** [comment]
Let me try over latest changes and update, i understand it works with onAddStream in an intra-framework context . Does latest flutterwebrtc changes work with angular webrtc on an inter-framework context ?

**Comment by xiemeilong** [comment]
The `addTrack` method should be added,  some version of webrtc can not work with `addStream` now.

**Comment by wer-mathurin** [comment]
Related to #380
