### ISSUE TITLE
Can i alway use camera1 api to call getUserVideo ？

### ISSUE THREAD

**Issue by kklldog** [flutter-webrtc/flutter-webrtc#302]
hi ,
I develop a webrtc app , but on some stupid  andriod devices test is failed !
When i review the code in GetUserMediaImpl.java class  , i found these code :
`
      if (Camera2Enumerator.isSupported(context)) {
                Log.d(TAG, "Creating video capturer using Camera2 API.");
                cameraEnumerator = new Camera2Enumerator(context);
            } else {
                Log.d(TAG, "Creating video capturer using Camera1 API.");
                cameraEnumerator = new Camera1Enumerator(false);
            }

`
  I think this is the KEY . On stupid devices when call method Camera2Enumerator.isSupported(context) return true , but  call camera2 api  will fail .
So can i always  use camera1 api to call getUserVideo ??
Hope some one help me !!!
Thanks !!!!

**Comment by cloudwebrtc** [comment]
This seems to be a special case. You can fork this repository, then modify a specific version, and then directly rely on your github repository in pubspec.yml.
