### ISSUE TITLE
Flutter WebRTC not on wifi

### ISSUE THREAD

**Issue by matrixhacker0001** [flutter-webrtc/flutter-webrtc#303]
Hey there.. i m working on flutter webrtc and successfully created application which sharing video streams to each other. But my issue is here that it only works on mobile network. And when connecting both the clients to each other than its not working and always stuck in checking state. Please help me to solve this out.

**Comment by ycherniavskyi** [comment]
For sure it is wifi routing/firewall issue.

**Comment by ycherniavskyi** [comment]
Do I understand correctly, you did not confirm TURN server for your clients?

**Comment by matrixhacker0001** [comment]
The thing is that... I just used public turn servers and created media server on kurento... When using it on mobile data network then all works fine... But when using it on wifi network its not working...web to web works... But the only reason is on flutter..

**Comment by matrixhacker0001** [comment]
I checked the permissions... All you listed us present.
