### ISSUE TITLE
Error while adding ICE Candidate (Android)

### ISSUE THREAD

**Issue by saurav-singh** [flutter-webrtc/flutter-webrtc#305]
Working on a simple p2p App.
Works fine on the web version but not on Android.
When tried on Android to Web: Audio/ Video from Web can be seen on Android but not the other way around.

The debug console shows the following error for Android: 

D/FlutterWebRTCPlugin( 9291): peerConnectionAddICECandidate() start
E/MethodChannel#FlutterWebRTC.Method( 9291): Failed to handle method call
**E/MethodChannel#FlutterWebRTC.Method( 9291): java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference**
E/MethodChannel#FlutterWebRTC.Method( 9291): 	at com.cloudwebrtc.webrtc.utils.ConstraintsMap.getInt(ConstraintsMap.java:43)
E/MethodChannel#FlutterWebRTC.Method( 9291): 	at com.cloudwebrtc.webrtc.FlutterWebRTCPlugin.peerConnectionAddICECandidate(FlutterWebRTCPlugin.java:1264)
E/MethodChannel#FlutterWebRTC.Method( 9291): 	at com.cloudwebrtc.webrtc.FlutterWebRTCPlugin.onMethodCall(FlutterWebRTCPlugin.java:242)
E/MethodChannel#FlutterWebRTC.Method( 9291): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/MethodChannel#FlutterWebRTC.Method( 9291): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#FlutterWebRTC.Method( 9291): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:683)
E/MethodChannel#FlutterWebRTC.Method( 9291): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#FlutterWebRTC.Method( 9291): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#FlutterWebRTC.Method( 9291): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#FlutterWebRTC.Method( 9291): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#FlutterWebRTC.Method( 9291): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#FlutterWebRTC.Method( 9291): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#FlutterWebRTC.Method( 9291): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by cloudwebrtc** [comment]
It seems to be an sdp format problem, please post your candidate information and code snippets.

**Comment by zommerberg** [comment]
It is possible that ```sdpMlineIndex``` is null when creating the ```RTCIceCandidate```. I had this problem and it gave me this error.

**Comment by obshksw** [comment]
I'm getting this error like 1 time out of 5 only using getUserMedia, not working at all with a peer connection yet. The camera normally appears, but when this error occurs it does not.

**Comment by saurav-singh** [comment]
So @zommerberg was correct! The sdpMlineIndex was null because of some parsing error in the signaling process.

I fixed the NullPointerException after parsing the correctly but the main issue:
" Works fine on the web version but not on Android.
  When tried on Android to Web: Audio/ Video from Web can be seen on Android but not the other way around. "
still exists.

This one error still exists: 

```
E/CameraCaptureSession( 7570): Session 0: Exception while stopping repeating: 
E/CameraCaptureSession( 7570): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): cancelRequest:456: Camera 1: 
Error clearing streaming request: Function not implemented (-38)
E/CameraCaptureSession( 7570):  at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:826)      
E/CameraCaptureSession( 7570):  at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:97)
E/CameraCaptureSession( 7570):  at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1139)   
E/CameraCaptureSession( 7570):  at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:526)
E/CameraCaptureSession( 7570):  at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:737)
E/CameraCaptureSession( 7570):  at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:239)
E/CameraCaptureSession( 7570):  at android.os.Handler.handleCallback(Handler.java:883)
E/CameraCaptureSession( 7570):  at android.os.Handler.dispatchMessage(Handler.java:100)
E/CameraCaptureSession( 7570):  at android.os.Looper.loop(Looper.java:214)
E/CameraCaptureSession( 7570):  at android.os.HandlerThread.run(HandlerThread.java:67)
E/CameraCaptureSession( 7570): Caused by: android.os.ServiceSpecificException: cancelRequest:456: Camera 1: Error clearing streaming request: Function not implemented (-38) (code 10)
E/CameraCaptureSession( 7570):  at android.os.Parcel.createException(Parcel.java:2085)
E/CameraCaptureSession( 7570):  at android.os.Parcel.readException(Parcel.java:2039)
E/CameraCaptureSession( 7570):  at android.os.Parcel.readException(Parcel.java:1987)
E/CameraCaptureSession( 7570):  at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:658)
E/CameraCaptureSession( 7570):  at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:95)
E/CameraCaptureSession( 7570):  ... 8 more
I/org.webrtc.Logging( 7570): Camera2Session: Stop internal
I/org.webrtc.Logging( 7570): SurfaceTextureHelper: stopListening()
I/org.webrtc.Logging( 7570): Camera2Session: Stop done
D/FlutterWebRTCPlugin( 7570): CameraEventsHandler.onCameraDisconnected
I/org.webrtc.Logging( 7570): CameraCapturer: Stop capture
I/org.webrtc.Logging( 7570): CameraCapturer: Stop capture: Nulling session
I/org.webrtc.Logging( 7570): CameraCapturer: Stop capture done
I/org.webrtc.Logging( 7570): Camera2Session: Camera device closed.
D/FlutterWebRTCPlugin( 7570): CameraEventsHandler.onFirstFrameAvailable
I/org.webrtc.Logging( 7570): Camera2Session: Stop camera2 session on camera 1
I/org.webrtc.Logging( 7570): Camera2Session: Camera opened.
I/org.webrtc.Logging( 7570): Camera2Session: Camera capture session configured.
I/org.webrtc.Logging( 7570): Camera2Session: Using video stabilization.
I/org.webrtc.Logging( 7570): Camera2Session: Using continuous video auto-focus.
I/org.webrtc.Logging( 7570): Camera2Session: Camera device successfully started.
I/org.webrtc.Logging( 7570): CameraCapturer: Create session done. Switch state: IDLE
I/org.webrtc.Logging( 7570): SurfaceTextureHelper: Setting listener to org.webrtc.-$$Lambda$Camera2Session$CaptureSessionCallback$UDvzHNj8-cAJE1WNByx98pxD9vA@cb1b64d
D/FlutterWebRTCPlugin( 7570): peerConnectionSetRemoteDescription() start
I/org.webrtc.Logging( 7570): AndroidVideoDecoder: ctor name: c2.qti.vp8.decoder type: VP8 color format: 19 context: org.webrtc.EglBase14Impl$Context@6239850
I/org.webrtc.Logging( 7570): AndroidVideoDecoder: ctor name: c2.qti.vp9.decoder type: VP9 color format: 19 context: org.webrtc.EglBase14Impl$Context@6239850
I/org.webrtc.Logging( 7570): AndroidVideoDecoder: ctor name: c2.qti.avc.decoder type: H264 color format: 19 context: org.webrtc.EglBase14Impl$Context@6239850
I/org.webrtc.Logging( 7570): AndroidVideoDecoder: ctor name: OMX.google.h264.decoder type: H264 color format: 19 context: org.webrtc.EglBase14Impl$Context@6239850
```

I believe I have implemented all the dispose methods but not sure what might have gone wrong here.
Any ideas?

**Comment by zommerberg** [comment]
@saurav-singh  I was able to build a working webrtc flutter app  with the help of this project:
` https://github.com/nhancv/nc-flutter-webrtc-ex ` , maybe this can help you?

**Comment by Servo97** [comment]
@saurav-singh Hi, I'm getting the same error. Did you manage to solve it?

**Comment by saurav-singh** [comment]
@Servo97 I managed the Null pointer exception issue.
The sdpMlineIndex was null while creating RTCIceCandidate.

But I still haven't fixed the issue where I can't transmit the audio/video data from mobile but it receives it.

**Comment by ardeshir-33033** [comment]
@saurav-singh 
did you finally fixed the issue with the camera?
