### ISSUE TITLE
video mediaConstraints minWidth, minHeight, minAspectRatio not working on iOS

### ISSUE THREAD

**Issue by zanesc** [flutter-webrtc/flutter-webrtc#307]
**Describe the bug**
I tried setting the video media constraints key for 'min/maxWidth' and 'min/maxHeight' on iOS to be a square (640x640) but it does not work. I also tried setting 'minAspectRatio' to 1 and even tried 'maxAspectRatio' to 1 and 'width' and 'height' to 640 but nothing worked. It works properly on Android, I have 2 android and 2 iOS devices for testing and the iOS video displays both locally and on remote devices as a rectangle with the height longer than the width in portrait and vice versa in landscape. The android devices display both locally and on remote devices as a square as desired.

**To Reproduce**
Set 'video' of mediaConstraints to:
`{
    'mandatory': {
        'minWidth': '640',
        'maxWidth': '640',
        'minHeight': '640',
        'maxHeight': '640',
        'minFrameRate': '15',
        'maxFrameRate': '15',
        'minAspectRatio': '1',
        // 'width': '640',
        // 'height': '640',
        // 'maxAspectRatio': '1',
    },
    'facingMode': 'user',
    'optional': [],
}`

**Expected behaviour**
Local and remote video from iOS should be square.

**Platform information**
* **Flutter version**: 
`[✓] Flutter (Channel beta, 1.20.0-7.2.pre, on Mac OS X 10.15.5 19F101, locale en-CA)
    • Flutter version 1.20.0-7.2.pre at /Users/*****/Development/Flutter
    • Framework revision a2bde82fbd (3 weeks ago), 2020-07-18 15:16:35 -0700
    • Engine revision 60b269d898
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/*****/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (6 available)
    • Nexus 7 (mobile)  • *****                                 • android-arm    • Android 10 (API 29)
    • VOG L04 (mobile)  • *****                         • android-arm64  • Android 10 (API 29)
    • iPhone 7 (mobile) • ***** • ios            • iOS 13.6
    • Phone X (mobile)    • ***** • ios            • iOS 13.5.1
    • Web Server (web)  • web-server                               • web-javascript • Flutter Tools
    • Chrome (web)      • chrome                                   • web-javascript • Google Chrome 84.0.4147.105

• No issues found!`
* **Plugin version**:
flutter_webrtc: ^0.2.8
* **OS**: 
iPhone X (iOS 13.5.1)
iPhone 7 (iOS 13.6)

**Comment by zanesc** [comment]
I worked around this by setting objectFit = RTCVideoViewObjectFit.RTCVideoViewObjectFitCover on all of my RTCVideoRenderers.

**Comment by wer-mathurin** [comment]
@zanesc:  Do you think is more a documentation issue or you were confused by specifying size and aspect ratio that the renderer is not adjusted automatically
