### ISSUE TITLE
MissingPluginException(No implementation found for method listen on channel FlutterWebRTC/peerConnectoinEventCFA8C16D-C17E-45CD-B206-40324A680E31) on iOS

### ISSUE THREAD

**Issue by Ayman-Kortobaa** [flutter-webrtc/flutter-webrtc#309]
Using package from pub, master branch, or unified-plan I get `MissingPluginException(No implementation found for method listen on channel FlutterWebRTC/peerConnectoinEventCFA8C16D-C17E-45CD-B206-40324A680E31)` exception on iOS only but not on Android.

**To Reproduce**
```dart
       peerConnection = await createPeerConnection({
        "iceServers": [{}],
        "sdpSemantics": "unified-plan",
        "bundlePolicy": "max-bundle",
        "rtcpMuxPolicy": "require",
        //forceEncodedVideoInsertableStreams  : isCryptoEnabled
      }, {});
```
**Expected behavior**
It works perfectly on Android, so it should not throw an error on iOS and work normally as I can see that the `EventChannel` is implemented in the plugin for iOS as well.

**Platform information**

* **Flutter version**:
```bash
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale en-EG)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
[✓] VS Code (version 1.47.3)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category..
```
* **Plugin version**:
unified-plan branch
* **OS**: MacOS Catalina
* **OS version**: 10.15.6

**Comment by Ayman-Kortobaa** [comment]
Apparently this line is what's causing the issue:

```dart
        "iceServers": [{}],
```
I am using the unified-plan and I have no need for iceServers but their implementation in Android and iOS (for empty values) are different.

The solution was removing that line (which caused an issue on Android) and then updated the Java side of the plugin to check for `null` iceServers key as follows (in `MethodCallHandlerImpl.java` `parseRTCConfiguration` method):

```java
    private RTCConfiguration parseRTCConfiguration(ConstraintsMap map) {
        List<IceServer> iceServers = new ArrayList<>(0);
        if (map.hasKey("iceServers")) {
            ConstraintsArray iceServersArray = map.getArray("iceServers");
            iceServers = createIceServers(iceServersArray);
        }
        
        RTCConfiguration conf = new RTCConfiguration(iceServers);
        if (map == null) {
            return conf;
        }
```

**Comment by BABYSHARPYIN** [comment]
Thanks, I modified iceServers and now no errors are reported.
