### ISSUE TITLE
Flutter Screen Share in between Current Video Call

### ISSUE THREAD

**Issue by matrixhacker0001** [flutter-webrtc/flutter-webrtc#310]
Hey there..!!!
I just want to know how to change media stream tracks in peer connection for sharing screen at the same time or between the ongoing video call... I checked for the senders method like in Web Browsers but not found any. Tried to remove and add stream but video stuck. Is there any other method to do this? Please help.

**Comment by cloudwebrtc** [comment]
If you replace track or stream, you need to renegotiate sdp (offer/answer again),

**Comment by naveenbharadwaj19** [comment]
@cloudwebrtc  Could you tell me more how to do that ? i need to swap from video to screen share during the meeting and vice versa as @matrixhacker0001 mentioned either video get stuck or getting camera error
