### ISSUE TITLE
Closed by server [1002 => null]! - Can not connect with https socket server

### ISSUE THREAD

**Issue by ztpr0035** [flutter-webrtc/flutter-webrtc#313]
I am trying to connect with https socket server but it got disconnect immediately after connecting successfully with this response : Closed by server [1002 => null]! - Can not connect with https socket server

**Comment by wer-mathurin** [comment]
Hi @ztpr0035,

Websocket connectivity is not related to this project.  In the examples around the net, they suggest using websocket for your signaling mechanism.  But this is an implementation choice on your side.  As an example, you could use Firesotre as your middle tier to implement your signaling as described [here](https://webrtc.org/getting-started/firebase-rtc-codelab).

So, if you agree to my comment, can you please mark this issue as closed.

**Comment by ztpr0035** [comment]
Thanks for the explanation!
