### ISSUE TITLE
Orientation in localrenderer

### ISSUE THREAD

**Issue by A7Aima** [flutter-webrtc/flutter-webrtc#315]
![Screenshot_1598088162](https://user-images.githubusercontent.com/61746272/90953296-b1078780-e487-11ea-8fcb-a4c24551c336.png)
![Screenshot_1598088210](https://user-images.githubusercontent.com/61746272/90953298-b369e180-e487-11ea-81dd-0ea7646feb59.png)

**Comment by vladimircores** [comment]
Facing the same issue but only on local emulator

**Comment by serjoca** [comment]
@A7Aima  and @vladimircores I Found out that it's better to create your own RTCVideoView. There's a lot of things that you can't control in the actual RTCVideoView. 

To render your video you just have to change the RTCVideoView line of code for the one bellow:

```
Texture(
        textureId: _localRenderer.textureId,
),
```

**Comment by serjoca** [comment]
Be aware that the RTCVideoView listen to changes on the texture's rotation and size so your custom widget has to listen and react to these events as well. 

@cloudwebrtc I think that the main problem here is that we are not allowed to set the **width**, **height**, **rotation** and **aspectRatio** since these don't have any setters like the **srcObject** or the **objectFit**.

**Comment by wer-mathurin** [comment]
Hi serjoca,

PRs are always welcome :-)  
I know there is an [open PR ](https://github.com/flutter-webrtc/flutter-webrtc/pull/223)that will affect RTCVideoView.

@cloudwebrtc : Maybe we can start from there and make others improvements as soon t[he PR](https://github.com/flutter-webrtc/flutter-webrtc/pull/223) will be merged.

**Comment by wer-mathurin** [comment]
@serjoca and @A7Aima 

Does the PR resolved your issue or usefull for your use case?

**Comment by A7Aima** [comment]
> Did you guys figure this out? Also having the same issue :-)

This is because of some default behavior for emulator 
but running the app on mobile will behave normally
