### ISSUE TITLE
.ownerTag is not defined for the type of MediaStream

### ISSUE THREAD

**Issue by AniruddhaRawale** [flutter-webrtc/flutter-webrtc#317]
**Describe the bug**it says thatownet tag is not defined i tried everything from getting dependencies to clean project and to rebuild but still its not working any help will be helpful

**To Reproduce**

**Expected behavior**

**Platform information**

* **Flutter version**: 
* **Plugin version**:
* **OS**: 
* **OS version**:

**Comment by cloudwebrtc** [comment]
fixed https://github.com/flutter-webrtc/flutter-webrtc/commit/36405d16b25ede87d9e7d962cd489ba8942fee89
