### ISSUE TITLE
Is 'RTCPeerConnection.onRenegotiationNeeded' same as WebRTC Spec's 'onnegotationneeded' event?

### ISSUE THREAD

**Issue by cielo** [flutter-webrtc/flutter-webrtc#326]
https://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-onnegotiationneeded

I don't see 'onRenegotiationNeeded' in the spec documents, so I was curious if 'onRenegotiationNeeded' in this package actually means to handle 'onnegotationneeded' event.

**Comment by wer-mathurin** [comment]
Yes
