### ISSUE TITLE
'setLocalDescription' accepting optional session description.

### ISSUE THREAD

**Issue by cielo** [flutter-webrtc/flutter-webrtc#329]
I am trying to implement 'perfect negotiation' (no signaling glare, no need to separate logic for caller/callee etc) as defined in spec documents.
https://w3c.github.io/webrtc-pc/#perfect-negotiation-example

I think perfect negotiation requires following changes in this library.

1. `setLocalDescription` optionally accepts Sdp. If argument is not provided, it will either automatically choose to create offer or answer based on RTCPeerConnection's signaling state. 
- https://w3c.github.io/webrtc-pc/#dom-peerconnection-setlocaldescription

2. `setRemoteDescription` supports `rollback` as defined in the spec doc.
https://w3c.github.io/webrtc-pc/#dom-peerconnection-setremotedescription

Would this be something that can be implemented near future?

**Comment by pA1nD** [comment]
This seems to be a restriction on not from flutter-webrtc but from the dependency (GoogleWebRTC@android to 1.0.32006). It's currently the latest version and does not support it (yet) - as far as I can say.

**Comment by shyndman** [comment]
Hello there,

This is no longer the case. Looks like support for the sdp-less overload was added about a year ago: https://chromium.googlesource.com/external/webrtc/+/4e9e723dae91abf2307b2436c3e49c888e4374d2

As @cielo mentioned, this is particularly useful for the [perfect negotiation described in the WebRTC spec](https://w3c.github.io/webrtc-pc/#perfect-negotiation-example)

Think this is worth reopening?
