### ISSUE TITLE
 Bluetooth control incall

### ISSUE THREAD

**Issue by ghenry** [flutter-webrtc/flutter-webrtc#331]
Hi,

I see Bluetooth is built in and I can switch on a Bluetooth device and audio switches. How do you suggest accessing Bluetooth to pick a device mid call from the in call screen?

Thanks.

**Comment by cloudwebrtc** [comment]
I’m wondering if I want to separate the incall control independently, it needs a complete control function, such as enumerating the currently available audio devices, and then switching on demand

**Comment by ghenry** [comment]
Yeah, I was going to use the Bluetooth plugin in our app and create a
button on the in call screen to switch.

It does need something if you are stepping in and out of a car etc.

**Comment by 97loser** [comment]
Hey,
Anyone found any solution?
