### ISSUE TITLE
Is only Chrome supported?

### ISSUE THREAD

**Issue by michaelgalliakis** [flutter-webrtc/flutter-webrtc#347]
Hi,

I have an issue about flutter-webrtc in Web.

While playing great in Chrome and Opera, unfortunately, not working in Firefox.

Do you know this or am I doing something wrong?

Specifically, is created an exception “Uncaught (in promise) TypeError: constructorName is not a constructor”

![ss1](https://user-images.githubusercontent.com/13280354/93224444-c49dc980-f779-11ea-9ab7-776d6807097f.png)

createPeerConnection  `rtc_peerconnection_factory.dart:8`
![ss2](https://user-images.githubusercontent.com/13280354/93224438-c36c9c80-f779-11ea-90c4-0eca5bdafa7f.png)

_async `async_path.dart:123`
![ss3](https://user-images.githubusercontent.com/13280354/93224446-c5366000-f779-11ea-9e9b-ae7806b8c8a7.png)

runBody `async_patch.dart:84`
![ss4](https://user-images.githubusercontent.com/13280354/93224433-c23b6f80-f779-11ea-8044-75613efed740.png)

createPeerConnection `rtc_peerconnection_factory.dart:19`
![ss5](https://user-images.githubusercontent.com/13280354/93224436-c2d40600-f779-11ea-8e0c-23ac414f0302.png)

new `html_dart2js.dart:26775`
![ss6](https://user-images.githubusercontent.com/13280354/93224442-c4053300-f779-11ea-8f00-c82578421d15.png)

At last screenshot I see `@SupportedBrowser.Chrome`.
Is only Chrome supported?
I would be very happy if you could help me.
Thank you in advance.
Michael.

**Platform information**

* **Flutter version**: 
[✓] Flutter (Channel dev, 1.21.0-9.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.21.0-9.0.pre at /home/michael/snap/flutter/common/flutter
    • Framework revision 7c6f9dd239 (5 weeks ago), 2020-08-09 10:31:03 -0400
    • Engine revision 6d86e67f04
    • Dart version 2.10.0 (build 2.10.0-4.0.dev 0341576448)
[✓] Android Studio (version 4.0)
    • Android Studio at /var/lib/snapd/snap/android-studio/91/android-studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
[✓] Connected device (1 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
* **Plugin version**:
flutter_webrtc: ^0.3.3
* **OS**:
Desktop (Mozilla Firefox 80.0.1 (64-bit))
* **OS version**:
Linux

**Comment by cloudwebrtc** [comment]
@michaelgalliakis Yes, it is currently only tested on chrome, because Firefox and chrome are different and need to be adapted at the js level.

**Comment by michaelgalliakis** [comment]
Thank you very much for your answer.
