### ISSUE TITLE
Telemetry / Stats 

### ISSUE THREAD

**Issue by ghenry** [flutter-webrtc/flutter-webrtc#348]
Hi all,

Is there an API to retrieve this in-call?

Similar to dio interceptor / middleware. 

Thanks.

**Comment by cloudwebrtc** [comment]
@ghenry Can you explain in more detail?

**Comment by ghenry** [comment]
Hi,

This type of stuff:

https://testrtc.com/webrtc-internals-documentation/

**Comment by cloudwebrtc** [comment]
Here is the getStats method to get all statistics.
https://github.com/flutter-webrtc/flutter-webrtc/blob/master/lib/src/rtc_peerconnection.dart#L314

**Comment by izaiasemjr** [comment]
@cloudwebrtc this link give not found 404. Ther are no more this feature?

**Comment by cloudwebrtc** [comment]
@izaiasemjr The new location is here
https://github.com/flutter-webrtc/flutter-webrtc/blob/master/lib/src/interface/rtc_peerconnection.dart#L84
