### ISSUE TITLE
Hangup doesn't close the audio stream

### ISSUE THREAD

**Issue by LucMoreau33560** [flutter-webrtc/flutter-webrtc#351]
Hello,

**Describe the bug**
When I hangup, the streams are not closed. I can continue to dialog between my two devices

**To Reproduce**
The simplest way is to install flutter webrtc demo and select P2P Call Sample.
The signaling server is flutter-webrtc-server.
my hangup function : 
_hangUp() {
    if (_signaling != null) {
      _signaling.bye();
      _localRenderer.srcObject = null;
      _remoteRenderer.srcObject = null;
      _inCalling = false;
    }
  }
And in the signaling onstate change :
  case SignalingState.CallStateBye:
            this.setState(() {
              _localRenderer.srcObject = null;
              _remoteRenderer.srcObject = null;
              _inCalling = false;
  });
            break;

The signaling output when I hangup : 

2020-09-18T08:14:03+02:00 INF Send keepalive !!!
2020-09-18T08:14:03+02:00 INF Send data: {}
2020-09-18T08:14:06+02:00 INF Recivied data: {"type":"bye","data":{"session_id":"L56789-C56789","from":"C56789"}}
2020-09-18T08:14:06+02:00 INF Send data: {"data":{"session_id":"L56789-C56789","to":"L56789"},"type":"bye"}
2020-09-18T08:14:06+02:00 INF Send data: {"data":{"session_id":"L56789-C56789","to":"C56789"},"type":"bye"}
2020-09-18T08:14:08+02:00 INF Send keepalive !!!
2020-09-18T08:14:08+02:00 INF Send data: {}

**Expected behavior**
When I hangup, I expect the stream to be closed.

**Platform information**

* **Flutter version**: 
flutter doctor -v
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G73, locale fr-FR)
    • Flutter version 1.20.3 at /Users/luc/dev/flutter
    • Framework revision 216dee60c0 (il y a 2 semaines), 2020-09-01 12:24:47
      -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/luc/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

 
[✓] Connected device (3 available)            
    • PRA LX1 (mobile)                    • 9DC7N17728011472
      • android-arm64 • Android 8.0.0 (API 26)
    • iPhone (mobile)                     •
      31b986f50d23e14fb68cd129c83cf31aa29e052d • ios           • iOS 12.4.8
    • iPhone SE (2nd generation) (mobile) • 08A1922A-3607-4C34-9C8F-1330BA578EC6
      • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)

! Doctor found issues in 1 category

* **Plugin version**:
0.3.3

* **OS**: 
Android and iOS

* **OS version**:
iOS 12.4.8. ,  Android 8.0.0 (API 26)

**Comment by cloudwebrtc** [comment]
You need  run the `localStream.dispose();` and `pc.dispose();` to close peerconnection and local stream.

**Comment by wer-mathurin** [comment]
@LucMoreau33560 Can you confirm it resolve the issue?  Without a response we will close the bug.

**Comment by wer-mathurin** [comment]
Without response from @LucMoreau33560 we close the issue.
Feel free to reopen it if you consider it not resolved.

**Comment by benyamin218118** [comment]
Hi.
i have the same problem.


this is my log after hangup : 
```

I/org.webrtc.Logging( 2091): CameraStatistics: Camera fps: 30.
I/flutter ( 2091): call ended
I/flutter ( 2091): visitroom dispose called
I/flutter ( 2091): [incall]setting incall to false
I/flutter ( 2091): false
I/flutter ( 2091): signaling close called
I/org.webrtc.Logging( 2091): CameraCapturer: Stop capture
I/org.webrtc.Logging( 2091): CameraCapturer: Stop capture: Nulling session
I/org.webrtc.Logging( 2091): CameraCapturer: Stop capture done
I/org.webrtc.Logging( 2091): CameraCapturer: dispose
I/org.webrtc.Logging( 2091): CameraCapturer: Stop capture
I/org.webrtc.Logging( 2091): CameraCapturer: Stop capture: No session open
I/org.webrtc.Logging( 2091): CameraCapturer: Stop capture done
D/FlutterWebRTCPlugin( 2091): mediaStreamRelease() mediaStream is null
W/org.webrtc.Logging( 2091): CameraCapturer: onFrameCaptured from another session.
I/org.webrtc.Logging( 2091): Camera1Session: Stop camera1 session on camera 1
I/org.webrtc.Logging( 2091): Camera1Session: Stop internal
I/org.webrtc.Logging( 2091): SurfaceTextureHelper: stopListening()
I/flutter ( 2091): ◤◢◤◢◤◢◤◢◤◢◤ send_json_to_socket ---> | {"method":"leaveRoom","id":35,"jsonrpc":"2.0"} | ◤◢◤◢◤◢◤◢◤◢◤
I/org.webrtc.Logging( 2091): WebRtcAudioRecordExternal: stopRecording
I/org.webrtc.Logging( 2091): WebRtcAudioRecordExternal: stopThread
I/flutter ( 2091): ◤◢◤◢◤◢◤◢◤◢◤ dispose() ALL ◤◢◤◢◤◢◤◢◤◢◤
I/CameraManagerGlobal( 2091): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_IDLE for client com.hamrahdoctor.mhdr_physician API Level 1
I/CameraManagerGlobal( 2091): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_IDLE for client com.hamrahdoctor.mhdr_physician API Level 1
I/CameraManagerGlobal( 2091): CameraDevice 1 state changed to (facing CAMERA_FACING_FRONT state now CAMERA_STATE_IDLE for client com.hamrahdoctor.mhdr_physician), which is what it already was, skip callback
I/org.webrtc.Logging( 2091): WebRtcAudioEffectsExternal: release
I/org.webrtc.Logging( 2091): WebRtcAudioRecordExternal: releaseAudioResources
I/flutter ( 2091): signaling.onStateChange: SignalingState.ConnectionClosed
I/flutter ( 2091): ◤◢◤◢◤◢◤◢◤◢◤ Socket disconnected <-/--> ◤◢◤◢◤◢◤◢◤◢◤
I/org.webrtc.Logging( 2091): HardwareVideoEncoder: Releasing MediaCodec on output thread
I/ACodec  ( 2091): [OMX.qcom.video.encoder.vp8] Now Executing->Idle
I/CameraManagerGlobal( 2091): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client com.hamrahdoctor.mhdr_physician API Level 1
D/FlutterWebRTCPlugin( 2091): CameraEventsHandler.onFirstFrameAvailable
I/ACodec  ( 2091): [OMX.qcom.video.encoder.vp8] Now Idle->Loaded
I/org.webrtc.Logging( 2091): Camera1Session: Stop done
I/ACodec  ( 2091): [OMX.qcom.video.encoder.vp8] Now Loaded
I/ACodec  ( 2091):  [OMX.qcom.video.encoder.vp8] Now kWhatShutdownCompleted event : 8508
I/ACodec  ( 2091):  [OMX.qcom.video.encoder.vp8] Now uninitialized
I/ACodec  ( 2091):  [] Now kWhatShutdownCompleted event : 8508
I/MediaCodec( 2091): Codec shutdown complete
I/org.webrtc.Logging( 2091): HardwareVideoEncoder: Release on output thread done
I/org.webrtc.Logging( 2091): AndroidVideoDecoder: release
I/org.webrtc.Logging( 2091): AndroidVideoDecoder: Releasing MediaCodec on output thread
I/ACodec  ( 2091): [OMX.qcom.video.decoder.vp8] Now Executing->Idle
I/ACodec  ( 2091): [OMX.qcom.video.decoder.vp8] Now Idle->Loaded
I/ACodec  ( 2091): [OMX.qcom.video.decoder.vp8] Now Loaded
I/ACodec  ( 2091):  [OMX.qcom.video.decoder.vp8] Now kWhatShutdownCompleted event : 8508
D/SurfaceUtils( 2091): disconnecting from surface 0xaba8e808, reason disconnectFromSurface
I/SmartFittingClass( 2091): ShutDownSmartFitting!!
I/SmartFittingClass( 2091): SmartFittingManagerServiceProxy::Deinit
I/SmartFittingClass( 2091): Destroy SmartFittingListener
I/SmartFittingClass( 2091): Destroy ~SmartFittingManagerServiceProxy::EventHandler
I/SmartFittingClass( 2091): Destroy SmartFitting!!
I/SmartFittingClass( 2091): Destroy SmartFittingManagerServiceProxy!!
I/ACodec  ( 2091):  [OMX.qcom.video.decoder.vp8] Now uninitialized
I/ACodec  ( 2091):  [] Now kWhatShutdownCompleted event : 8508
I/MediaCodec( 2091): Codec shutdown complete
I/org.webrtc.Logging( 2091): AndroidVideoDecoder: Release on output thread done
I/org.webrtc.Logging( 2091): SurfaceTextureHelper: stopListening()
I/org.webrtc.Logging( 2091): SurfaceTextureHelper: dispose()
I/org.webrtc.Logging( 2091): VolumeLogger: stop@[name=worker_thread - 2389, id=30807]
I/org.webrtc.Logging( 2091): WebRtcAudioTrackExternal: stopPlayout
I/org.webrtc.Logging( 2091): WebRtcAudioTrackExternal: underrun count: 0
I/org.webrtc.Logging( 2091): WebRtcAudioTrackExternal: stopThread
I/org.webrtc.Logging( 2091): WebRtcAudioTrackExternal: Stopping the AudioTrackThread...
I/org.webrtc.Logging( 2091): WebRtcAudioTrackExternal: Calling AudioTrack.stop...
D/AudioTrack( 2091): stop(1704): called with 361440 frames delivered
I/org.webrtc.Logging( 2091): WebRtcAudioTrackExternal: AudioTrack.stop is done.
I/org.webrtc.Logging( 2091): WebRtcAudioTrackExternal: AudioTrackThread has now been stopped.
I/org.webrtc.Logging( 2091): WebRtcAudioTrackExternal: releaseAudioResources
I/org.webrtc.Logging( 2091): NetworkMonitor: Stop monitoring with native observer -1257268320
I/org.webrtc.Logging( 2091): NetworkMonitorAutoDetect: Unregister network callback
D/FlutterWebRTCPlugin( 2091): peerConnectionDispose() peerConnection is null
I/org.webrtc.Logging( 2091): EglRenderer: Releasing.
I/org.webrtc.Logging( 2091): GlShader: Deleting shader.
I/org.webrtc.Logging( 2091): EglRenderer: eglBase detach and release.
I/org.webrtc.Logging( 2091): EglRenderer: Releasing done.
I/org.webrtc.Logging( 2091): EglRenderer: Releasing.
I/org.webrtc.Logging( 2091): GlShader: Deleting shader.
I/org.webrtc.Logging( 2091): EglRenderer: Quitting render thread.
I/org.webrtc.Logging( 2091): EglRenderer: eglBase detach and release.
I/org.webrtc.Logging( 2091): EglRenderer: Releasing done.
I/org.webrtc.Logging( 2091): EglRenderer: Quitting render thread.
D/FlutterWebRTCPlugin( 2091): peerConnectionClose() peerConnection is null
I/flutter ( 2091): remotePeerConnection.onSignalingState: RTCSignalingState.RTCSignalingStateClosed
```

it seems like every thing should be released and stoped but : 

if i play a music
go into the app and start a webrtc call
music will stop (ok)
i test the call , every think is ok
then i hangup
but music is going to play again
but music will be played if i close the app (terminating)

whats wrong?

my flutter version : `Flutter 1.22.6 • channel stable`
my flutter-webrtc version is :  `0.2.8`
