### ISSUE TITLE
PlatformException (PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null))

### ISSUE THREAD

**Issue by asif4483** [flutter-webrtc/flutter-webrtc#353]
![error](https://user-images.githubusercontent.com/24164393/93662920-590d7200-fa81-11ea-8a95-41d62dc5f295.JPG)

**Comment by asif4483** [comment]
and also getting this error : "Unable to RTCPeerConnection::setRemoteDescription: Failed to set remote answer sdp: Called in wrong state: kStable"

**Comment by asif4483** [comment]
This issue is closed.

**Comment by quick-witted-coder** [comment]
> and also getting this error : "Unable to RTCPeerConnection::setRemoteDescription: Failed to set remote answer sdp: Called in wrong state: kStable"

I'm having the same issue, could you help me out?

**Comment by Ethiel97** [comment]
> This issue is closed.

Please, how did you get to resolve this. I'm still stuck on this.
