### ISSUE TITLE
RTCPeerConnection does not have RTCPeerConnectionState

### ISSUE THREAD

**Issue by animeshjain** [flutter-webrtc/flutter-webrtc#355]
**Is your feature request related to a problem? Please describe.**
I am using `flutter_webrtc: 0.3.3`. Currently it seems there is no way to get the RTCPeerConnectionState. It is expected in the RTCPeerConnection class, and should have an event handler such as `onConnectionState` or something like that.

**Describe the solution you'd like**
I checked the Android implementation, and it seems the `org.webrtc.PeerConnection` class does have a method called `connectionState`.  And it seems an event handler could be implemented in `PeerConnectionObserver` class.

**Describe alternatives you've considered**
Could not find any particular alternative. It seems the `iceConnectionState` is a bit of a proxy to the `connectionState`, but not really the same thing.

Would like to know if this is simply an oversight, or is there some other reason for it? I can add the implementation in Android I feel, shouldn't be too hard. Will have to check what is the status on iOS.

**Comment by cloudwebrtc** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/connectionState
