### ISSUE TITLE
Have to always reload to view the localRenderer.srcObject stream in RTCVideoView.

### ISSUE THREAD

**Issue by trishantpahwa** [flutter-webrtc/flutter-webrtc#362]
**Describe the bug**
I am trying to use the package, flutter WebRTC. I use it in the following manner:

Declare the localRenderer.
Initialize it.
Call the getUserMedia function to get the stream.
Assign the srcObject of localRenderer to the stream.
View the local renderer in RTCVideoView widget.
I use 2 and 3 in the initState, and 4 within the getUserMedia.

**To Reproduce**

**Expected behavior**
But, What I am facing is. At first the video does not appear. Until, reload it using r while debugging, it suddenly appears.

When in production reloading might not be possible. Is there a way to view the video without reloading everytime?

**Platform information**
Android

* **Flutter version**: 1.20  
* **Plugin version**: ^0.3.3
* **OS**:  Android
* **OS version**: Android 10

**Comment by trishantpahwa** [comment]
I guess I tried that, here's the code to clear the issue a bit.
```
class _ScreenState extends State<Screen> {
  final _localRenderer = new RTCVideoRenderer();

  void initRenderers() async {
    await _localRenderer.initialize();
  }

  void _getUserMedia() async {
    final Map<String, dynamic> constraints = {
      'audio': true,
      'video': {
        'facingMode': 'user'
      }
    };
    try {
      var stream = await MediaDevices.getUserMedia(constraints);
      _localRenderer.srcObject = stream;
    } catch (e) {
      print(e.toString());
    }
  }

  @override
  void deactivate() {
    super.deactivate();
    _localRenderer.dispose();
  }

  @override
  void initState() {
    initRenderers();
    Future.delayed(Duration(seconds: 5), () {
      _getUserMedia();
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    TextStyle textStyle = Theme.of(context).textTheme.body1;
    return SafeArea(
      child: Scaffold(
        appBar: AppBar(
          title: Text('Test app'), 
        ),
        body: Container(
          child: new Stack(
            children: [
              new RTCVideoView(_localRenderer, mirror: true),
              // new FloatingActionButton(
              //   child: Icon(Icons.phone),
              //   onPressed: _getUserMedia
              // )
            ]
          )
        ),
      ),
    );
  }
}
```

**Comment by cloudwebrtc** [comment]
Did you add setState to change the state?

```dart
try {
      var stream = await MediaDevices.getUserMedia(constraints);
      setState(() {
          _localRenderer.srcObject = stream;
      });
    } catch (e) {
      print(e.toString());
    }
```

**Comment by itsthetaste** [comment]
> You have to pass the `RTCVideoRenderer` to the `RTCVideoView` after its `srcObject` has been set, if not, then you need to notify your UI to rebuild after its `srcObject` has been set in any way you prefer (setState, ChangeNotifier, etc..), this is what happens when you reload using flutter tools.
> Also, sharing your minimal code to reproduce when opening an issue can help tremendously.

Thank you 👍
