### ISSUE TITLE
Build fails for Android, on a fresh install!

### ISSUE THREAD

**Issue by Ham3D** [flutter-webrtc/flutter-webrtc#370]
**Describe the bug**

please ignore flutter doctor about android studio missing dart and flutter installed, I have recently updated android studio to 4.1, its a bug.

> A problem occurred configuring project ':flutter_webrtc'.
> Could not resolve all artifacts for configuration ':flutter_webrtc:classpath'.
   > Could not find gradle.jar (com.android.tools.build:gradle:3.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.6.3/gradle-3.6.3.jar
   > Could not find builder.jar (com.android.tools.build:builder:3.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.6.3/builder-3.6.3.jar
   > Could not find crash.jar (com.android.tools.analytics-library:crash:26.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/crash/26.6.3/crash-26.6.3.jar
   > Could not find lint-gradle-api.jar (com.android.tools.lint:lint-gradle-api:26.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/lint/lint-gradle-api/26.6.3/lint-gradle-api-26.6.3.jar
   > Could not find gradle-api.jar (com.android.tools.build:gradle-api:3.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle-api/3.6.3/gradle-api-3.6.3.jar
   > Could not find databinding-compiler-common.jar (androidx.databinding:databinding-compiler-common:3.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-compiler-common/3.6.3/databinding-compiler-common-3.6.3.jar
   > Could not find manifest-merger.jar (com.android.tools.build:manifest-merger:26.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/manifest-merger/26.6.3/manifest-merger-26.6.3.jar
   > Could not find sdk-common.jar (com.android.tools:sdk-common:26.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/sdk-common/26.6.3/sdk-common-26.6.3.jar
   > Could not find builder-test-api.jar (com.android.tools.build:builder-test-api:3.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-test-api/3.6.3/builder-test-api-3.6.3.jar
   > Could not find ddmlib.jar (com.android.tools.ddms:ddmlib:26.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/ddms/ddmlib/26.6.3/ddmlib-26.6.3.jar
   > Could not find signflinger.jar (com.android:signflinger:3.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/signflinger/3.6.3/signflinger-3.6.3.jar
   > Could not find zipflinger.jar (com.android:zipflinger:3.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/zipflinger/3.6.3/zipflinger-3.6.3.jar
   > Could not find tracker.jar (com.android.tools.analytics-library:tracker:26.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/tracker/26.6.3/tracker-26.6.3.jar
   > Could not find sdklib.jar (com.android.tools:sdklib:26.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/26.6.3/sdklib-26.6.3.jar
   > Could not find layoutlib-api.jar (com.android.tools.layoutlib:layoutlib-api:26.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/layoutlib/layoutlib-api/26.6.3/layoutlib-api-26.6.3.jar
   > Could not find dvlib.jar (com.android.tools:dvlib:26.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/dvlib/26.6.3/dvlib-26.6.3.jar
   > Could not find repository.jar (com.android.tools:repository:26.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/repository/26.6.3/repository-26.6.3.jar
   > Could not find shared.jar (com.android.tools.analytics-library:shared:26.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/shared/26.6.3/shared-26.6.3.jar
   > Could not find common.jar (com.android.tools:common:26.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/common/26.6.3/common-26.6.3.jar
   > Could not find jetifier-processor.jar (com.android.tools.build.jetifier:jetifier-processor:1.0.0-beta08).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-processor/1.0.0-beta08/jetifier-processor-1.0.0-beta08.jar
   > Could not find bundletool.jar (com.android.tools.build:bundletool:0.10.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/bundletool/0.10.3/bundletool-0.10.3.jar
   > Could not find jetifier-core.jar (com.android.tools.build.jetifier:jetifier-core:1.0.0-beta08).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/jetifier/jetifier-core/1.0.0-beta08/jetifier-core-1.0.0-beta08.jar
   > Could not find protos.jar (com.android.tools.analytics-library:protos:26.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/protos/26.6.3/protos-26.6.3.jar
   > Could not find builder-model.jar (com.android.tools.build:builder-model:3.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/builder-model/3.6.3/builder-model-3.6.3.jar
   > Could not find apkzlib.jar (com.android.tools.build:apkzlib:3.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apkzlib/3.6.3/apkzlib-3.6.3.jar
   > Could not find apksig.jar (com.android.tools.build:apksig:3.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/apksig/3.6.3/apksig-3.6.3.jar
   > Could not find annotations.jar (com.android.tools:annotations:26.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/annotations/26.6.3/annotations-26.6.3.jar
   > Could not find databinding-common.jar (androidx.databinding:databinding-common:3.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/databinding/databinding-common/3.6.3/databinding-common-3.6.3.jar
   > Could not find baseLibrary.jar (com.android.databinding:baseLibrary:3.6.3).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/databinding/baseLibrary/3.6.3/baseLibrary-3.6.3.jar
> Could not get unknown property 'android' for project ':flutter_webrtc' of type org.gradle.api.Project.

**To Reproduce**
create a new flutter Project
add `flutter_webrtc: ^0.3.3` to pubspec.yaml
and try to build fo android.
i have to add, there is no problem on building for ios

**Platform information**

* **Flutter version**: 

> [✓] Flutter (Channel stable, 1.22.1, on Mac OS X 10.15.6 19G73, locale en-IR)
>     • Flutter version 1.22.1 at /Users/someuser/Tools/flutter
>     • Framework revision f30b7f4db9 (6 days ago), 2020-10-08 10:06:30 -0700
>     • Engine revision 75bef9f6c8
>     • Dart version 2.10.1
> 
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at /Users/someuser/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.2
>     • ANDROID_HOME = /Users/someuser/Library/Android/sdk
>     • Java binary at: /Applications/Android
>       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_242-release-1644-b3-6222593)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.5)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.5, Build version 11E608c
>     • CocoaPods version 1.9.3
> 
> [!] Android Studio (version 4.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     ✗ Flutter plugin not installed; this adds Flutter specific functionality.
>     ✗ Dart plugin not installed; this adds Dart specific functionality.
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_242-release-1644-b3-6222593)
> 
> [✓] VS Code (version 1.49.3)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.3.0
> 
> [!] Connected device
>     ! No devices available
> 
> ! Doctor found issues in 2 categories.

* **Plugin version**: 
`flutter_webrtc: ^0.3.3`

**Comment by cloudwebrtc** [comment]
This seems to be an error in the development environment of android studio and flutter sdk, rather than a problem with the plugin itself.

**Comment by Ham3D** [comment]
im still not sure how, maybe upgrading webrtc to latest version, maybe struggling with gradle, now sure, but its compile now.
 so  I will close this.
