### ISSUE TITLE
Setting audio output source for remote peers (Flutter web)

### ISSUE THREAD

**Issue by postacik** [flutter-webrtc/flutter-webrtc#375]
All browser based webrtc applications let the user choose the audio output source for remote peers using the setSinkId function.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId

Can you suggest how this can be done with this library or an external function?

**Comment by postacik** [comment]
I wrote a work around function to call the setSinkId function. 

```
// ignore: avoid_web_libraries_in_flutter
import 'dart:js_util' as jsutil;
import 'package:flutter_webrtc/flutter_webrtc.dart';
// ignore: implementation_imports
import 'package:flutter_webrtc/src/web/rtc_video_renderer_impl.dart';


class CallManager {
  Future<void> setSinkId({RTCVideoRenderer renderer, String deviceId}) async {
    try {
      RTCVideoRendererWeb webRenderer = renderer.delegate as RTCVideoRendererWeb;
      if (jsutil.hasProperty(webRenderer.videoElement, 'setSinkId')) {
        final result = await jsutil.promiseToFuture<void>(jsutil.callMethod(webRenderer.videoElement, 'setSinkId', [deviceId]));

        return result;
      }
    } catch (e) {
      throw 'Unable to setSinkId: ${e.toString()}';
    }
  }
}
```
I had to include an implementation file `rtc_video_renderer_impl.dart` in your package and this is not a preferred way of doing things since the implementation may change in the future.

Since this functionality is vital for browser based WebRTC communication, would it be possible to add this function to VideoRenderer class? 

The function can be empty for Android and iOS.

**Comment by wer-mathurin** [comment]
@postacik: thanks for sharing code.
To not change the API I think we can expose an utility class specific for the Web.  Like RTCWebUtil.dart

This way we are keeping the API clean and provide functionality for the Web use case.

**Comment by wer-mathurin** [comment]
@postacik There is a new class Helper that can serve as proxy for things like this.  I think this is a fair tradeoff to "hide" the implementation usage in the Helper class.  This bug is also related to #395 on the native implementation.

As a first step, I think this is ok to just copy/paste your code.  Eventually, we can implement a delegate strategy in Helper class to move implementation detail, closer to the implementation.

@postacik What do you think about this path?

**Comment by postacik** [comment]
Fair enough, thanks.

**Comment by postacik** [comment]
Thanks, I will try this asap.
