### ISSUE TITLE
Need Complete Mobile Screen Sharing Example for iOS

### ISSUE THREAD

**Issue by pravinkumarputta** [flutter-webrtc/flutter-webrtc#376]
I'm developing an app having a peer to peer video calling and screen sharing app. This is the library that has great features that I'm searching for few months.

Now, I implemented an example of video calling and screen sharing. Right now I can share only the app screen. Can anyone provide me an example that can help me to share a complete mobile screen?

**Comment by cloudwebrtc** [comment]
@pravinkumarputta Please refer to https://github.com/flutter-webrtc/flutter-webrtc-demo

**Comment by pravinkumarputta** [comment]
Sorry for not mentioning Platform.

Actually, I'm facing this issue for iOS. In iOS, screen sharing works only for app screens. Not showing any other system screens like notification trey, home screen, or other screens except this app.

**Comment by cloudwebrtc** [comment]
The plug-in function of ReplayKit is not fully implemented, so currently only widgets in the app can be recorded, and desktop recording needs to be developed.

**Comment by pravinkumarputta** [comment]
Google meet supports complete desktop recording.
Any idea about, how google meet achieved it??

**Comment by pravinkumarputta** [comment]
I have just gone through the iOS Live Broadcasting topic from the below link.
https://developer.apple.com/videos/play/wwdc2018/601/

And I have noticed that there are 2 types of broadcasting,
1. In-App Broadcast
2. iOS System Broadcast

<img width="776" alt="Screenshot 2020-10-17 at 3 25 04 PM" src="https://user-images.githubusercontent.com/45730502/96334513-04184800-108f-11eb-8765-86d65fa3484f.png">
<img width="776" alt="Screenshot 2020-10-17 at 3 34 06 PM" src="https://user-images.githubusercontent.com/45730502/96334518-08dcfc00-108f-11eb-914c-8ef442abd83f.png">
<img width="776" alt="Screenshot 2020-10-17 at 3 34 17 PM" src="https://user-images.githubusercontent.com/45730502/96334519-0a0e2900-108f-11eb-8ac8-b16d0f005ae3.png">


As you said ReplayKit not fully implemented (https://github.com/flutter-webrtc/flutter-webrtc/issues/376#issuecomment-710759364).

By using ReplayKit 2 it will be possible.

**Comment by cloudwebrtc** [comment]
Yes, as you said, a single flutter-webrtc plug-in cannot complete the second replaykit method, it needs ios application extension and Runner to implement together.

**Comment by usama333** [comment]
HELLO how can i use both screenshare and vedio call at same time help me out as early as possible.

**Comment by ekingunoncu** [comment]
Hello, 

I promised one of my clients for complete screen share, has anyone solution for this?

**Comment by AmirhosseinShk** [comment]
> HELLO how can i use both screenshare and vedio call at same time help me out as early as possible.

hi 
you can make it with 2 peerConnections , u should Open 2 Connection and Use one of them for video Stream and another one for Sharing Screen 
another solution is add 2 Track at same time on your Stream but you need get access for both of video and screen share back to back and you can't change Stream after establish connection and you just can replaceTrack

**Comment by thammaknot** [comment]
Has anyone figured out a solution that works for iOS? (complete desktop screensharing)

Since it's been over a year since the question was posted, I figure someone may have implemented this.

Thank you.

**Comment by mohd-afid** [comment]
@pravinkumarputta you got any sample screen sharing project .
currently i am stuck in screen share on ios using broadcast extension its working fine on android
@cloudwebrtc

**Comment by HensiStackApp** [comment]
@mohd-afid can you share screen sharing code for android?

**Comment by brijeshbodariya** [comment]
@ekingunoncu do you get any solution for screen sharing?
