### ISSUE TITLE
Screen sharing (getDisplayMedia) is not working in Android 10 and above

### ISSUE THREAD

**Issue by samuelg123** [flutter-webrtc/flutter-webrtc#378]
**Describe the bug**
Screen sharing (getDisplayMedia) is not working in Android 10 & 11. 
Current Solution: https://github.com/flutter-webrtc/flutter-webrtc/issues/377#issuecomment-710049087

**To Reproduce**
When calling getDisplayMedia, this exception will be thrown and the app is crashed. 
```
E/AndroidRuntime( 5480): java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
E/AndroidRuntime( 5480): 	at android.os.Parcel.createException(Parcel.java:2071)
E/AndroidRuntime( 5480): 	at android.os.Parcel.readException(Parcel.java:2039)
E/AndroidRuntime( 5480): 	at android.os.Parcel.readException(Parcel.java:1987)
```

**Platform information**
* **OS**:  Android
* **OS version**: 10 & 11

Thank you very much.

**Comment by pravinkumarputta** [comment]
This issue can be solved on your own.
Refer https://github.com/flutter-webrtc/flutter-webrtc/issues/377

**Comment by samuelg123** [comment]
Yes, actually I already use your solution. Maybe if this fix can be applied inside flutter-webrtc it could be better. But I don't know whether if it's possible or not.
