### ISSUE TITLE
Need callback for "Stop sharing" in web browser

### ISSUE THREAD

**Issue by tstr2** [flutter-webrtc/flutter-webrtc#382]
Hi all,
Is there any callback to listen "Stop sharing" in web browser? I've tried to set onEnded in every mediastream track but none called.

<img width="317" alt="Screenshot 2020-10-22 150526" src="https://user-images.githubusercontent.com/73278362/96843742-deb58080-1478-11eb-8bdf-fcf73c56a63f.png">

Thanks!

**Comment by wer-mathurin** [comment]
Hi @tstr2 ,

just merge a PR into master.  onEnded and onMuted was not call upon track closure.
You can now listen to onEnded to detect stop sharing.

@cloudwebrtc : Maybe you can release a new revision of the library for that.
