### ISSUE TITLE
How to handle setRemoteDescription error - SessionDescription is NULL.

### ISSUE THREAD

**Issue by kimvdmeulen** [flutter-webrtc/flutter-webrtc#383]
Hi,

I'm trying to set the remote session description with an sdp string (containing all characters, including regex such as '\r\')   and type "offer".
However 

` await connection.rtcConnection.setRemoteDescription(RTCSessionDescription(finalSdp, finalType));`

returns the following error:
Unable to RTCPeerConnection::setRemoteDescription: SessionDescription is NULL.

Any suggestions on how to handle this error?

**Comment by kimvdmeulen** [comment]
This was due to an error in my sdp!

**Comment by quick-witted-coder** [comment]
@kimvdmeulen Could you give some details on how you got the issue, and how you fixed it cause I'm getting it too.

**Comment by kimvdmeulen** [comment]
@quick-witted-coder I didn't decode my SDP the right way, it works now:

![image](https://user-images.githubusercontent.com/47859051/98665126-8b35a480-234b-11eb-8dda-95a083729257.png)
