### ISSUE TITLE
Can't get facingMode: environment to work

### ISSUE THREAD

**Issue by treeder** [flutter-webrtc/flutter-webrtc#388]
**Describe the bug**

I can't get `facingMode: environment` to work properly following the demo example. This is running on an Android phone with latest Chrome. 

**To Reproduce**

I'm using this:

```dart
final Map<String, dynamic> mediaConstraints = {
      'audio': false,
      'video': {
        'mandatory': {
          'minWidth':
              '640', // Provide your own width, height and frame rate here
          'minHeight': '480',
          'minFrameRate': '30',
        },
        'facingMode': 'environment',
        'optional': [],
      }
    };

    try {
      var stream = await navigator.mediaDevices.getUserMedia(mediaConstraints);
      _localStream = stream;
      _localRenderer.srcObject = _localStream;
    } catch (e) {
      print(e.toString());
      setState(() {
        _errorMsg = e.toString();
      });
      return;
    }
```

**Expected behavior**

Use the back camera, but instead it's using the front. 

**Platform information**

* **Flutter version**: .23.0-18.1.pre
* **Plugin version**: 0.4.0
* **OS**: Android
* **OS version**: 11 (latest)

**Comment by Sunbreak** [comment]
Check https://github.com/tekartik/app_camera.dart/tree/master/qrscan_flutter_web

**Comment by treeder** [comment]
FYI, I did end up fixing this by bypassing dart and calling Javascript directly. There are apparently some issues with dart's HTML package that doesn't work properly. You can see what I did here: https://github.com/treeder/jsqr_flutter/tree/main/lib
