### ISSUE TITLE
Get audio sources list and change localstream audio

### ISSUE THREAD

**Issue by LucMoreau33560** [flutter-webrtc/flutter-webrtc#395]
Hello,

Is it possible to list all audio sources : headphones, speaker, bluetooth, ... available on the device ?
An how can I change from one to another during a call ? 

   Thank you,
   Luc

**Comment by wer-mathurin** [comment]
You can use:
 navigator.mediaDevices.getSources() 

after you authorize the user to access media.

Look for device of kind == 'audiooutput'

After you can specify the deviceid is in the constraint.

Sorry I'm on my mobile, but I hope it five you enough direction

**Comment by LucMoreau33560** [comment]
Hello,
Thank you, I'm using ios and android implementation.
I have to test more. For the moment the getSources() gives me 2 cameras and one audio (even if I plug a headphone, the audio source label becomes "écouteurs" (headphones in French). I was thinking that there will be 2 audio sources if I plug headphones. I don't have any bluetooth devices, I will get one tomorrow to test with a bluetooth device.

Another point, you said I have to specify the device id in the constraint, does it mean that I can't change audio source during the call ?

   Thanks,
   Luc

**Comment by gbmiranda** [comment]
I have the same problem, I can't see the audio outputs or disable the ear speaker

**Comment by LucMoreau33560** [comment]
Hello,
I have tested my devices (iphone 7 and Huawei P8 Lite) with a Jabra bluetooth headset BT2045.
The very simple code I wrote to list media devices is :
          final mediaDevices = navigator.mediaDevices;
          var devices = await mediaDevices.getSources();
          for (int i=0; i<devices.length; i++){
            print(devices[i]);
          }

The result is the same on Android and iOS, and the result is the same if the bluetooth headset is connected or not : 
IOS :
flutter: {deviceId: com.apple.avfoundation.avcapturedevice.built-in_video:0, label: Back Camera, facing: back, kind: videoinput}
flutter: {deviceId: com.apple.avfoundation.avcapturedevice.built-in_video:1, label: Front Camera, facing: front, kind: videoinput}
flutter: {deviceId: com.apple.avfoundation.avcapturedevice.built-in_audio:0, label: iPhone Micro, facing: , kind: audioinput}

ANDROID (All permissions (AUDIO, BLUETOOTH, ...) are present in AndroidManifest.xml) :
I/flutter (21295): {kind: videoinput, facing: back, label: Camera 0, Facing back, Orientation 90, deviceId: 0}
I/flutter (21295): {kind: videoinput, facing: front, label: Camera 1, Facing front, Orientation 270, deviceId: 1}
I/flutter (21295): {kind: audioinput, facing: , label: Audio, deviceId: audio-1}

Do I forgot something to have all audio devices listed ?

**Comment by gbmiranda** [comment]
And to access the two native speakers of the devices? How do I do?

I have a problem that I can't disable the ear speaker and use only the main one.

**Comment by LucMoreau33560** [comment]
Hello gbmiranda,
On my phones, when I simply call someone with the vanilla phone functionnality, I can select my audio sources bewteen phone ear speaker, the main speaker and bluetooth device.
If I plug a wire headset, the phone ear speaker is replaced by the wire headset. I can not choose between them. I have to unplug the wire headset if I want to use the phone ear speaker again.

Maybe I misunderstand your question, you just want to enable or disable the speaker.
In that case, I am using the following 3 lines of code :
_remoteRenderer.srcObject.getAudioTracks()[0].enabled = true;
_remoteRenderer.srcObject.getAudioTracks()[0].setVolume(5);
_remoteRenderer.srcObject.getAudioTracks()[0].enableSpeakerphone(true);

**Comment by wer-mathurin** [comment]
@LucMoreau33560 

You can look at the latest commit on the master.
I implemented a Helper class to start implementing basing functionality, change camera and so on. 
Maybe we can add change audio source in the future.  Feel free to provide a PR to add that :-)

For the web implementation, is a little bit easier, since we can provide a different constraints.  Look at the code on switchCamera().

We can probably do the same thing for changeAudioOutput.

**Comment by wer-mathurin** [comment]
#375

**Comment by wer-mathurin** [comment]
The helper class is:
 [flutter-webrtc](https://github.com/flutter-webrtc/flutter-webrtc)/[lib](https://github.com/flutter-webrtc/flutter-webrtc/tree/master/lib)/[src](https://github.com/flutter-webrtc/flutter-webrtc/tree/master/lib/src)/helper.dart

Make sure you have accept the permission request for accessing camera and microphone before enumerating devices.

**Comment by thammaknot** [comment]
Thank you. Sorry I just got a chance to revisit this again.

I was hoping to see how you enumerate camera devices so that I could adapt the implementation for audio outputs. However, I couldn't find it in helper.dart; I probably misinterpreted your comment.

Would you be able to help point me in the right direction?
Starting from being able to enumerate all audio devices... do we need to start with native implementation?

**Comment by ycherniavskyi** [comment]
Have you try/look at something like [audio_session](https://pub.dev/packages/audio_session) plugin.

I am not sure that this functionality must be implemented within `flutter-webrtc`. If you have arguments/thoughts why must - let's discuss.

**Comment by thammaknot** [comment]
Thank you! I will check it out.

I don't think the webrtc constraint is a must.

**Comment by thammaknot** [comment]
I was able to the the audio input device IDs. However, webrtc's getUserMedia() does not seem to respect the device ID specified in the constraints.

Does FlutterWebRTC support selecting audio input by device IDs?
I tried hardcoding the sourceId, but the audio seems to always come from the default mic.

**Comment by fortrannew** [comment]
the same thing - the microphone can't be changed. and I think it can't even be completely destroyed
