### ISSUE TITLE
Facing mode Camera

### ISSUE THREAD

**Issue by Faishal13** [flutter-webrtc/flutter-webrtc#398]
how to make button to change facing mode using front and back camera?

**Comment by wer-mathurin** [comment]
HI @Faishal13 ,

I'm not sure what you are asking.  Can you clarify?  Are you looking to understand how to react to a state change and update a button accordingly?

**Comment by MSalaah96** [comment]
bool isFrontCamera = true;

  void switchCamera() async {
    if (_localStream != null) {
      bool switchCameraState = await _localStream.getVideoTracks()[0].switchCamera();
      while (switchCameraState == this.isFrontCamera)
        switchCameraState = await _localStream.getVideoTracks()[0].switchCamera();
      this.isFrontCamera = switchCameraState;
    }
  }

**Comment by bazted** [comment]
@Faishal13  Can you please specify which platform you are trying to handle? 
Current Master does not allow to switch camera for Web.

**Comment by MSalaah96** [comment]
> @Faishal13 Can you please specify which platform you are trying to handle?
> Current Master does not allow to switch camera for Web.

this for Mobile platforms (Android & IOS )

**Comment by wer-mathurin** [comment]
@MSalaah96 

Its possible to do it.  Just need extra work to achieve it.
You need to get the cameras (devices with kind==video),
setup the constraints to specify the deviceId and getUserMedia with this constraint
I agree, this is not trivial.

I provided an Helper class on master to simplify this.  You can either:

-  copy/paste the code from the Helper if you can't use the master branch
- wait until the next version of the library will be publish (hopefully soon!)
