### ISSUE TITLE
Could update the ion-app-flutter demo to use the latest lib?

### ISSUE THREAD

**Issue by vjeson** [flutter-webrtc/flutter-webrtc#411]
The ion-app-flutter demo still use v0.2.8 version, I try to update use the latest lib, but can't get it work.

thanks

**Comment by cloudwebrtc** [comment]
Hey, I'm working for flutter-webrtc support unified-plan, this will be completed within a week, and then ion-sdk-flutter needs to be fully updated, after which it will be able to work again.

**Comment by vjeson** [comment]
thanks for you updating the ion-sdk-flutter and waiting for the ion-app-flutter  update
