### ISSUE TITLE
captureFrame memory leak

### ISSUE THREAD

**Issue by sky-48** [flutter-webrtc/flutter-webrtc#415]
When repeatedly calling `videoTrack.captureFrame()` to save a frame to file, it will cause memory leak, at least on Android (I have not tested other platforms yet). For example, on two different Android phones I've tested, calling `captureFrame()` once every 20 seconds will cause them to crash in about 5 hours and 11 hours, respectively, because they have different RAM size. Changing the timer interval can make it crasher soon or later. For example, calling it every 2 seconds will make it crash in about 30 minutes or so.

From the Android Studio "Profiler", it can be clearly observed that the memory usage is increasing after each capture.

**Comment by sky-48** [comment]
Issue still exists

**Comment by mishkov** [comment]
Hello!!!!!!

**Comment by mishkov** [comment]
I think I found the solution. Developers forget to add one simple but very important line:

```
i420Buffer.release();
```

in the `onFrame()`.

Maybe I will create a pull request to fix the bug.

**Comment by mishkov** [comment]
@sky-48 Maybe you open this issue again until I (or someone else) create PR?

**Comment by mishkov** [comment]
Fixed in #919
