### ISSUE TITLE
PeerConnection Initial State is missing

### ISSUE THREAD

**Issue by itsthetaste** [flutter-webrtc/flutter-webrtc#416]
Hi, though I was doing something wrong, I might still be... 

Only tested this on Android so far.  

What I'm seeing is that after creating a peer connection, the iceConnectionState, iceGatheringState and signalingState are all null.

Also, their onSignalingState, onIceGatheringState and onIceConnectionState handlers don't initially fire.

I do see the state change and the handlers fire after setting the remote description.

**To Reproduce**

In the loopback_sample.dart, I have added some debugging code.

 ```
 void _onSignalingState(RTCSignalingState state) {
    print("###### Signaling State Change:" + state.toString());
  }

  void _onIceGatheringState(RTCIceGatheringState state) {
    print("###### Ice Gathering State Change:" + state.toString());
  }

  void _onIceConnectionState(RTCIceConnectionState state) {
    print("###### Ice Connection State Change:" + state.toString());
  }

```

and then after the connection creation, I add some code to read the states.

```
 try {
      _peerConnection = await createPeerConnection(configuration, loopbackConstraints);

      print("###### Ice Connection State:" + _peerConnection.iceConnectionState.toString());
      print("###### Ice Gathering State:" + _peerConnection.iceGatheringState.toString());
      print("###### Signaling State:" + _peerConnection.signalingState.toString());

      _peerConnection.onSignalingState = _onSignalingState;
      _peerConnection.onIceGatheringState = _onIceGatheringState;
      _peerConnection.onIceConnectionState = _onIceConnectionState;
      _peerConnection.onConnectionState = _onPeerConnectionState;
      _peerConnection.onAddStream = _onAddStream;
      _peerConnection.onRemoveStream = _onRemoveStream;
      _peerConnection.onIceCandidate = _onCandidate;
      _peerConnection.onRenegotiationNeeded = _onRenegotiationNeeded;
```

and then either side of the setting of the offer, I add the same logging code

```
      print("###### Ice Connection State:" + _peerConnection.iceConnectionState.toString());
      print("###### Ice Gathering State:" + _peerConnection.iceGatheringState.toString());
      print("###### Signaling State:" + _peerConnection.signalingState.toString());

      var description = await _peerConnection.createOffer(offerSdpConstraints);
      var sdp = description.sdp;
      print('sdp = $sdp');
      await _peerConnection.setLocalDescription(description);
      //change for loopback.
      description.type = 'answer';
      await _peerConnection.setRemoteDescription(description);

      print("###### Ice Connection State:" + _peerConnection.iceConnectionState.toString());
      print("###### Ice Gathering State:" + _peerConnection.iceGatheringState.toString());
      print("###### Signaling State:" + _peerConnection.signalingState.toString());
```

I also tried adding some logging into the PeerConnectionObserver.java

```
@Override
  public void onIceConnectionChange(PeerConnection.IceConnectionState iceConnectionState) {
    System.out.println(">>>>>>>>>>>> onIceConnectionChange:" + iceConnectionState.name());
    Log.d(TAG, ">>>>>>>>>>>> onIceConnectionChange:" + iceConnectionState.name());
    ConstraintsMap params = new ConstraintsMap();
    params.putString("event", "iceConnectionState");
    params.putString("state", iceConnectionStateString(iceConnectionState));
    sendEvent(params);
  }
```

**Expected behavior**

After the creation of the connection, I would expect the state to be;
iceConnectionState == RTCIceConnectionState.RTCIceConnectionStateNew
iceGatheringState == RTCIceGatheringState.RTCIceGatheringStateNew
signalingState == RTCSignalingState.RTCSignalingStateStable

I would have expected the event handlers to have fired to show this, but they don't fire until after the remoteDescription is set, at which point the connection state also updates.

**Platform information**

* **Flutter version**: 

PS C:\Git\flutter-webrtc\example> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.20231.1005], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.51.1)
[√] Connected device (4 available)

• No issues found!

* **Plugin version**:

0.5.3 master commit:fdbcdaa00939d37c0b11f0891f91e6af50773b99 

* **OS**: Running on windows 10, inside the Pixel_3a_API_30_x86 emulator, which I have attached a logitech c920 as webcam0
* **OS version**: Windows 10 OS Build 20231.1005.  Android Emulator version 30.1.5-6855416.  Android version 11.0 - API 30

**Comment by cloudwebrtc** [comment]
please try this commit https://github.com/flutter-webrtc/flutter-webrtc/commit/9bdc491daeb68f2835d44833098320760a01df71.

**Comment by itsthetaste** [comment]
I'll have a go, but the issue I was seeing was in Android and IOS.

I think the actual issue I was having is that in rtc_peerconnection_impl.dart the private properties are not set to anything until the eventListener sets them.

 ```
 /*
   * PeerConnection event listener.
   */
  void eventListener(dynamic event) {
    final Map<dynamic, dynamic> map = event;

    switch (map['event']) {
      case 'signalingState':
        _signalingState = signalingStateForString(map['state']);
        onSignalingState?.call(_signalingState);
        break;
      case 'peerConnectionState':
        _connectionState = peerConnectionStateForString(map['state']);
        onConnectionState?.call(_connectionState);
        break;
      case 'iceGatheringState':
        _iceGatheringState = iceGatheringStateforString(map['state']);
        onIceGatheringState?.call(_iceGatheringState);
        break;
      case 'iceConnectionState':
        _iceConnectionState = iceConnectionStateForString(map['state']);
        onIceConnectionState?.call(_iceConnectionState);
        break;
```

So, when I was trying to read the property straight after creating the connection it was null, I know this is probably an uncommon thing to do so I put a work around in my code as I needed to convert the value of the properties back into a string so that I could send it to the other peer.  So in my conversion function, I have a switch, which if it's null returns "new".

```
String stringForIceConnectionState(RTCIceConnectionState state) {
  switch (state) {
    case RTCIceConnectionState.RTCIceConnectionStateNew:
      return 'new';
    case RTCIceConnectionState.RTCIceConnectionStateChecking:
      return 'checking';
    case RTCIceConnectionState.RTCIceConnectionStateConnected:
      return 'connected';
    case RTCIceConnectionState.RTCIceConnectionStateCompleted:
      return 'completed';
    case RTCIceConnectionState.RTCIceConnectionStateFailed:
      return 'failed';
    case RTCIceConnectionState.RTCIceConnectionStateDisconnected:
      return 'disconnected';
    case RTCIceConnectionState.RTCIceConnectionStateClosed:
      return 'closed';
    case RTCIceConnectionState.RTCIceConnectionStateCount:
      return 'count';
  }
  return 'new';
}
```

So, I will close this.
