### ISSUE TITLE
Camera stream cropping instead of scaling

### ISSUE THREAD

**Issue by x401om** [flutter-webrtc/flutter-webrtc#418]
Hi everyone! 

We are creating voip-calling application. Trying to get stream from camera on iOS we are getting perfect result, but doing this on Android sometimes we can see some strange behaviour. Instead of getting scaled picture, we are getting cropped rect from the center. 
For example, if device camera has resolution of 3264 x 2448 pixels and we are trying to request HD picture of 1280 x 720, we'll get this  1280 x 720, but it will be just center of picture.

This is our config:

```
mediaConstraints = {
          'audio': true,
          'video': {
            'mandatory': {
              'minWidth': '720', // Provide your own width, height and frame rate here
              'minHeight': '1280',
              'minFrameRate': '30',
            },
            'facingMode': 'user',
            'optional': [],
          }
        },
```

Am I doing this wrong? What is the better way to achieve scaled picture as expected?

**Comment by marcoberetta96** [comment]
Have you tried this?

```
RTCVideoView(remoteRenderer,` objectFit: RTCVideoViewObjectFit.RTCVideoViewObjectFitCover)
```
