### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by dkubrakov** [flutter-webrtc/flutter-webrtc#423]
Thanks for the great work done!

1) Are there any plans to continue implementing WebRTC on Windows?

2) What the libwebrtc.lib library was based on, is there an update?
How do I implement the peerconnection.addTrack () method so that it returns RtpSender?

Thanks!

**Comment by SamStenner1** [comment]
https://github.com/flutter-webrtc/flutter-webrtc/blob/master/README.md
