### ISSUE TITLE
After add flutter_webrtc library into project start from version 3.0 and build onto macos, Code Sign error occured

### ISSUE THREAD

**Issue by iakrevetkho** [flutter-webrtc/flutter-webrtc#427]
**Describe the bug**

Start from version 3.0 of library project can't be build for MacOS platform.

**To Reproduce**

1. Add 
`# webrtc library
  flutter_webrtc: ^0.5.6` to pubscpec.yaml
2. Build project for MacOS

**Expected behavior**

$ flutter run
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Launching lib/main.dart on macOS in debug mode...
mkdir -p /Users/ishchukin/Desktop/Project/Mamba/client/desktop/build/macos/Build/Products/Debug/desktop_app.app/Contents/Frameworks
rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/ishchukin/Desktop/Project/Mamba/client/desktop/macos/Pods/../Flutter/ephemeral/.symlinks/flutter/darwin-x64/FlutterMacOS.framework" "/Users/ishchukin/Desktop/Project/Mamba/client/desktop/build/macos/Build/Products/Debug/desktop_app.app/Contents/Frameworks"
building file list ... done                                             
FlutterMacOS.framework/                                                 
FlutterMacOS.framework/Versions/                                        
FlutterMacOS.framework/Versions/A/                                      
FlutterMacOS.framework/Versions/A/FlutterMacOS                          
FlutterMacOS.framework/Versions/A/Resources/                            
FlutterMacOS.framework/Versions/A/Resources/Info.plist                  
FlutterMacOS.framework/Versions/A/Resources/icudtl.dat                  
FlutterMacOS.framework/Versions/A/_CodeSignature/                       
FlutterMacOS.framework/Versions/A/_CodeSignature/CodeResources          
                                                                        
sent 39650809 bytes  received 138 bytes  79301894.00 bytes/sec          
total size is 39645383  speedup is 1.00                                 
Destination binary is symlinked...                                      
Code Signing /Users/ishchukin/Desktop/Project/Mamba/client/desktop/build/macos/Build/Products/Debug/desktop_app.app/Contents/Frameworks/FlutterMacOS.framework with Identity -
/usr/bin/codesign --force --sign -  --preserve-metadata=identifier,entitlements '/Users/ishchukin/Desktop/Project/Mamba/client/desktop/build/macos/Build/Products/Debug/desktop_app.app/Contents/Frameworks/FlutterMacOS.framework'
/Users/ishchukin/Desktop/Project/Mamba/client/desktop/build/macos/Build/Products/Debug/desktop_app.app/Contents/Frameworks/FlutterMacOS.framework: replacing existing signature
rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/ishchukin/Desktop/Project/Mamba/client/desktop/macos/Pods/../Flutter/ephemeral/.symlinks/plugins/flutter_webrtc/macos/WebRTC.framework" "/Users/ishchukin/Desktop/Project/Mamba/client/desktop/build/macos/Build/Products/Debug/desktop_app.app/Contents/Frameworks"
building file list ... done                                             
                                                                        
sent 368 bytes  received 20 bytes  776.00 bytes/sec                     
total size is 44033619  speedup is 113488.71                            
Code Signing /Users/ishchukin/Desktop/Project/Mamba/client/desktop/build/macos/Build/Products/Debug/desktop_app.app/Contents/Frameworks/WebRTC.framework with Identity -
/usr/bin/codesign --force --sign -  --preserve-metadata=identifier,entitlements '/Users/ishchukin/Desktop/Project/Mamba/client/desktop/build/macos/Build/Products/Debug/desktop_app.app/Contents/Frameworks/WebRTC.framework'
/Users/ishchukin/Desktop/Project/Mamba/client/desktop/build/macos/Build/Products/Debug/desktop_app.app/Contents/Frameworks/WebRTC.framework: bundle format is ambiguous (could be app or framework)
Command PhaseScriptExecution failed with a nonzero exit code            
/Users/ishchukin/Desktop/Project/Mamba/client/desktop/build/macos/Build/Products/Debug/desktop_app.app: code object is not signed at all
In subcomponent: /Users/ishchukin/Desktop/Project/Mamba/client/desktop/build/macos/Build/Products/Debug/desktop_app.app/Contents/Frameworks/WebRTC.framework
Command CodeSign failed with a nonzero exit code                        
note: Using new build system                                            
note: Building targets in parallel                                      
note: Planning build                                                    
note: Constructing build description                                    
** BUILD FAILED **                                                      
                                                                        
Building macOS application...                                           
Exception: Build process failed

**Platform information**

MacOS

* **Flutter version**: 
$ flutter doctor -v
[✓] Flutter (Channel dev, 1.25.0-4.0.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-RU)
    • Flutter version 1.25.0-4.0.pre at /Users/ishchukin/flutter
    • Framework revision a7f5fd5360 (6 days ago), 2020-11-30 13:14:13 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.7 19H15 darwin-x64
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 86.0.4240.198

• No issues found!

* **Plugin version**:
3.0+

* **OS**: 
MacOS Desktop
XCode 11
* **OS version**:
Does not matter

**Comment by cloudwebrtc** [comment]
https://github.com/flutter-webrtc/flutter-webrtc/issues/421

**Comment by iakrevetkho** [comment]
Duplicated
