### ISSUE TITLE
getDisplayMedia function bug in mediadevices_impl.dart

### ISSUE THREAD

**Issue by postacik** [flutter-webrtc/flutter-webrtc#430]
Hi,
An implementation bug in the `getDisplayMedia` function drew me crazy until I found the problem in the code.

https://github.com/flutter-webrtc/flutter-webrtc/blob/1d32678d02375e68f35953b050e2c42de2a8828e/lib/src/web/mediadevices_impl.dart#L47

The problem is in the following line:

`final arg = JsObject.jsify(mediaConstraints);`

It should be:

`final arg = jsutil.jsify(mediaConstraints);`

In Chrome, one can share audio together with the entire screen or a Chrome tab if you set `"audio": true` in mediaConstraints.

![image](https://user-images.githubusercontent.com/3977227/101821631-46af4b80-3b39-11eb-98e5-e8fae8e7a999.png)

However this did not work with the implemented function because of using the wrong `jsify` function.

I also made some changes in the function to make it less error prone. I would be glad if you can test and modify it in your source code:

```
  Future<MediaStream> getDisplayMedia(Map<String, dynamic> mediaConstraints) async {
    try {
      mediaConstraints ??= <String, dynamic>{};
      if (mediaConstraints['video'] is Map) {
        mediaConstraints['video'] = true;
      }
      if (mediaConstraints['audio'] is Map) {
        mediaConstraints['audio'] = true;
      }
      mediaConstraints.putIfAbsent('video', () => true);
      final mediaDevices = html.window.navigator.mediaDevices;
      if (jsutil.hasProperty(mediaDevices, 'getDisplayMedia')) {
        final args = jsutil.jsify(mediaConstraints);
        final jsStream = await jsutil.promiseToFuture<html.MediaStream>(jsutil.callMethod(mediaDevices, 'getDisplayMedia', [args]));
        return MediaStreamWeb(jsStream, 'local');
      } else {
        final jsStream = await html.window.navigator.getUserMedia(video: {'mediaSource': 'screen'}, audio: mediaConstraints['audio'] ?? false);
        return MediaStreamWeb(jsStream, 'local');
      }
    } catch (e) {
      throw 'Unable to getDisplayMedia: ${e.toString()}';
    }
  }

```

**Comment by cloudwebrtc** [comment]
Thanks, fixed.
