### ISSUE TITLE
Support for Subtitles ?

### ISSUE THREAD

**Issue by gedw99** [flutter-webrtc/flutter-webrtc#432]
I could not find any code where Sub-titles are supported.

Can someone advice me if it is, and if not best approach for it.

This is related to this btw: https://github.com/pion/ion-avp/issues/163

**Comment by cloudwebrtc** [comment]
We can send voice data to ion-avp, and open a data-channel at the same time, and display the received translated subtitles directly on the upper layer of Video with Text Widget.
