### ISSUE TITLE
Implementation is not working on iOS Safari

### ISSUE THREAD

**Issue by StefanoGR** [flutter-webrtc/flutter-webrtc#434]
Hello,
my company is working on a internal platform based on webrtc. We have successfully implemented the webrtc server side (stun/turn) and the webrtc client.

Our client based on flutter works fine on Android and web (desktop and android).  We are using latest 0.5.7  release of flutter webrtc plugin.
**The real issue is the web version on iOS (iPhone/iPad).**

We are struggling to find the bug here, I think it's something related to the security, but I am not sure. Local cam works, the socket is open ( I can start and close the call on both clients), but the remote rendering is not showing the client's webcam.

The only error I am getting is an exception when I invite the peer:
```
[Error] 
	$0 (main.dart.js:29962)
	aBH (main.dart.js:4356)
	aBZ (main.dart.js:4358)
	$1 (main.dart.js:28825)
	aDh (main.dart.js:2851)
	(funzione anonima) (main.dart.js:2859)
```

Even in debug the code is not readable and I am struggling to find a solution:
```
  P.ank.prototype = {
        $0: function() {
            var s = H.b(this.a)
            s.stack = J.bV(this.b)
            throw s
        },
        $S: 0
    }
```

The method that throws exception is just an invite:
```
this._sessionId = this._selfId + '-' + peer_id;

    if (this.onStateChange != null) {
      this.onStateChange(SignalingState.CallStateNew);
    }
    if(camera == null) camera = CAMERA_FRONT;
    _createPeerConnection(peer_id, media, use_screen,camera).then((pc) {
      _peerConnections[peer_id] = pc;
      if (media == 'data') {
        _createDataChannel(peer_id, pc);
      }
      _createOffer(peer_id, pc, media);
    });
```
_This works on android and web (mac, windows and android)_

**Have you ever tried the web version of webrtc on iOS? Are there known issues? This is really important in order to understand how to proceed.**

I am using  
[√] Flutter (Channel beta, 1.25.0-8.1.pre, on Microsoft Windows [Versione 10.0.18363.1198], locale it-IT)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] IntelliJ IDEA Community Edition (version 2019.3)
[√] VS Code (version 1.43.2)
[√] Connected device (1 available)

Test run on Safari 14 and iOS 14.3.

Thanks,
Stefano

**Comment by StefanoGR** [comment]
Hello, is someone trying the web implementation on iOS safari? Am I the only one? :)

**Comment by wer-mathurin** [comment]
Hi @StefanoGR ,

To help other reproduce the problem, just add more information on the version of iOS and safari you are having the issue.

Also, you.can look at : https://stackoverflow.com/questions/53483975/navigator-mediadevices-getusermedia-not-working-on-ios-12-safari

I didn't try it, but maybe you can, and add comments for your findings.

**Comment by StefanoGR** [comment]
Hello @wer-mathurin  we have tried on many iOS - Safari versions. The last test made on Safari 14 and iOS 14.3.
I am checking the stackoverflow solution, the server configuration is https. It's really hard to find out what is the exception fired.
I'll try to add more logs and update the issue with more details.

Thanks

**Comment by StefanoGR** [comment]
Hello @wer-mathurin after many tries I've found the issue.. Safari on iOS needs a secure connection with the turn server. I was using 'url': 'turn:xxx.xxx.xxx.xxx', I've switched to 'urls': 'turn:xxx.xxx.xxx.xxx',  and now it works.

Chrome and other browsers don't require this! I close the issue.

**Comment by wer-mathurin** [comment]
Hello @StefanoGR ,

great :-)  Many thanks for the update.
