### ISSUE TITLE
How to close / dispose everything when user closes the app?

### ISSUE THREAD

**Issue by AndreGroeschel** [flutter-webrtc/flutter-webrtc#436]
Hi there,

We are wondering how to shutdown all WebRTC resources + stopping streams when the user closes the app on Android. 
Ware using WidgetsBindingObserver to get a callback when the app has been detached. So basically the moment when a user decides to close the app.
The problem is that the resources never get released and the camera is still working in the background although the app is gone.
Drilling down on this issue we found that calls to native Android won't work anymore. I.e. in RTCPeerConnectionNative this 
`await _channel.invokeMethod(
      'peerConnectionDispose',
      <String, dynamic>{'peerConnectionId': _peerConnectionId},
    );`
never completes.

Do you have any other ideas / suggestions how we can close everything in a clean fashion and make sure the peer connections and media streams are closed?

**Comment by PapyElGringo** [comment]
@AndreGroeschel I have the same concern today did you find any way to close connection when app is detached?

**Comment by PapyElGringo** [comment]
@AndreGroeschel thanks for the snippet but my concern is about the peer to be aware fo the connection is now closed it's seem that if the android application is closed from the system then the connected peer is not notified

**Comment by AndreGroeschel** [comment]
@PapyElGringo as far as I remember we solved this with `WidgetsBindingObserver `on the stateful widget. This allows you to check if the app got inactive and you can close the stream

```
 @override
  Future<void> didChangeAppLifecycleState(AppLifecycleState state) async {

    if (state == AppLifecycleState.inactive) {
      //
    } else if (state == AppLifecycleState.resumed) {
      //
    }
  }
```

**Comment by PapyElGringo** [comment]
Thanks again for you answers @AndreGroeschel 

It's exactly what I do but its seem that webRtcPlugin is destroyed before being able to properly close the connection and the connected peer is never noticed of the closing connection that's annoying but if you  succeed I'm wondering what I'm missing

**Comment by AndreGroeschel** [comment]
@PapyElGringo This sound like a serious bug in the plugin itself and I would suggest that you report a separate issue for this. Can you reproduce the issue with the example app?

**Comment by AndreGroeschel** [comment]
ah just saw that you reported it already 👍
