### ISSUE TITLE
[Android] Switch from STREAM_VOICE_CALL to STREAM_MUSIC

### ISSUE THREAD

**Issue by aevzp** [flutter-webrtc/flutter-webrtc#438]
Hi, everyone!

Guys, have you faced the task on Android of switching audio from **AudioManager.STREAM_VOICE_CALL** to **AudioManager. STREAM_MUSIC**, to make the volume control available for media audio not call audio?

Thank you!

**Comment by kklldog** [comment]
this is a good idea . why close this issue .

**Comment by aevzp** [comment]
I found this:
https://codereview.webrtc.org/2411263003

Please pay attention about revert changes.

**Comment by kklldog** [comment]
> I found this:
> https://codereview.webrtc.org/2411263003
> 
> Please pay attention about revert changes.
> And not the ability to switch between sound channels is the only reason that forced us to abandon WebRTC

My English is not good . Is that means we unable to switch the webrtc to use STREAM_MUSIC audio force ?

**Comment by aevzp** [comment]
Based on this link and our experiments, we were unable to switch the sound to another channel.
