### ISSUE TITLE
Unable to getUserMedia

### ISSUE THREAD

**Issue by lucasfq** [flutter-webrtc/flutter-webrtc#440]
When I try to enable the camera the following errors occur:

**Unable to getUserMedia: Instance of 'minified:a8y'**
or
**Unable to getUserMedia: Error: m is not an Object. (evaluating '"getUserMedia" in m')**

This only occurs when I am using a web version on safari (iOS).

Some help?

**Comment by wer-mathurin** [comment]
Hi @lucasfq ,

Like the bug #434 

Safari on iOS needs a secure connection with the turn server.  switch to 'urls': 'turn:xxx.xxx.xxx.xxx'.

I'll close the bug.  But feel free to reopen it if you still encounter the.bug.
