### ISSUE TITLE
run ion-sdk-flutter pubsub_view example for web with ion-sfu server throw excepiton, Failed to set local offer sdp: The order of m-lines in subsequent offer doesn't match order from previous offer/answer

### ISSUE THREAD

**Issue by vjeson** [flutter-webrtc/flutter-webrtc#450]
"Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local offer sdp: The order of m-lines in subsequent offer doesn't match order from previous offer/answer."

Future<void> onnegotiationneeded() async {
    try {
      var pc = transports[RolePub].pc;
      var offer = await pc.createOffer();
      await pc.setLocalDescription(offer);  // throw exception here
      var answer = await signal.offer(offer);
      await pc.setRemoteDescription(answer);
    } catch (err) {
      log.error(err);
    }
  }

**Comment by vjeson** [comment]
It's ion-sdk-flutter issue.

**Comment by ShilpaVania** [comment]
@vjeson 
I am having the same issue when i tried to set session.pc.setRemoteDescription() second time within stream for ios only.
have you found solution for it?
Thanks in advance.
