### ISSUE TITLE
RTCVideoView displaying local video only when orientation is changed 

### ISSUE THREAD

**Issue by jayaram9877** [flutter-webrtc/flutter-webrtc#453]
local video from front cam is displayed only when orientation is changed in ios and android but working fine in Web  did anyone face this issue?

Flutter 1.25.0-8.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision b0a2299859 (11 days ago) • 2021-01-05 12:34:13 -0800
Engine • revision 92ae191c17
Tools • Dart 2.12.0 (build 2.12.0-133.2.beta)
Package version : 0.5.7

**Comment by jamalag** [comment]
Hi Jayaram
the solution is quite simple, I got it from this issue resolution: https://github.com/flutter-webrtc/flutter-webrtc/issues/362
seems like you update state when assigning stream to localRenderer.srcObject so that UI can be rerendered ...

setState(() {
        _localRenderer.srcObject = _localStream;
});
