### ISSUE TITLE
Add Unified-Plan support for windows

### ISSUE THREAD

**Issue by cloudwebrtc** [flutter-webrtc/flutter-webrtc#457]

**Comment by Ayman-Kortobaa** [comment]
Is there any progress or a time estimate on this issue?

**Comment by cloudwebrtc** [comment]
We must first implement [libwebrtc](https://github.com/flutter-webrtc/libwebrtc) to support unified-plan and simulcast, this may take 2~3 weeks, but I have no chance to return to this line.

**Comment by dkubrakov** [comment]
Hello!

In the process of implementing the Unified-Plan functions, questions arose.

My implementation examples:
https://github.com/dkubrakov/libwebrtc
https://github.com/dkubrakov/flutter-webrtc/tree/support_windows

First of all, I was interested in the "addTrack" method of the "RTCPeerConnection" interface.
The parameters of this method, according to the native "webrtc :: PeerConnectionInterface" method, must be MediaStreamTrack and the MediaStream id list.

            RTCErrorOr<rtc::scoped_refptr<RtpSenderInterface>> AddTrack(
                  rtc::scoped_refptr<MediaStreamTrackInterface> track,
                  const std::vector<std::string>& stream_ids);

**Question 1** - do I need to pre-create a track through the RTCPeerConnectionFactory or just pass information about a new track?
 (https://github.com/dkubrakov/flutter-webrtc/blob/3cc61236f1072ad36c9bc78872148dbab0f2825a/windows/src/flutter_peerconnection.cc#L251)

Next, the result of AddTrack () is the RtpSenderInterface that needs to be returned to the client.
One of the RtpSender parameters is the complex structure RtpParameters (GetParameters()), which consists of the lists RtpCodecParameters, RtpHeaderExtensionParameters, RtpEncodingParameters.

**Question 2** - why is it that when I call AddTrack() when creating an audio track, these lists _are empty_? (What is recorded in the message.)
(https://github.com/dkubrakov/libwebrtc/blob/955b4c1e082f8bff7d82706c6cc82b91cf038527/src/rtc_rtp_sender_impl.cc#L97)

**Question 3** - how to correctly return the structure and lists/map from virtual functions to the client application?
(https://github.com/dkubrakov/libwebrtc/blob/955b4c1e082f8bff7d82706c6cc82b91cf038527/src/rtc_rtp_sender_impl.h#L35)

If to return the structure by value, then the lists are not returned correctly (error "can't dereference value-initialized vector iterator")
(https://github.com/dkubrakov/flutter-webrtc/blob/3cc61236f1072ad36c9bc78872148dbab0f2825a/windows/src/flutter_peerconnection.cc#L197)

**Comment by cloudwebrtc** [comment]
Hey, @dkubrakov  I know that packaging libwebrtc and developing flutter windows plug-ins are very challenging. If you have any questions or need my help, please leave a message.

> Question 1 - do I need to pre-create a track through the RTCPeerConnectionFactory or just pass information about a new track?

The PeerConnection.AddTrack method in dart needs to use an existing audio/video track as a parameter. You don’t need to create it in flutter_peerconnection.cc#L251. Here you only need to find it from base_->media_tracks_ by trackID. If not found, return error.

The dart side usage looks like this
```dart
var localStream = await navigator.mediaDevices.getUserMedia({'audio': true, 'video': true});

 localStream.getTracks().forEach((track) {
        var sender = pc.addTrack(track, localStream);
 });
 
```

The cpp side looks like this
```C++
void FlutterPeerConnection::AddTrack(RTCPeerConnection *pc, const std::string &track_id, const EncodableList &stream_ids, std::unique_ptr<MethodResult<EncodableValue>> result) {

    scoped_refptr<RTCMediaTrack> track =  base_->MediaTrackForID(track_id);
    if(!track) {
          result->Error("AddTrackFailed", "track [" + track_id + "] not found.");
    }

   std::vector<std::string> streamIds = toStringVector(stream_ids);
   scoped_refptr<RTCRtpSender> sender = pc->AddTrack(track, streamIds[0].c_str());
    ...
}
```


> Next, the result of AddTrack () is the RtpSenderInterface that needs to be returned to the client.
One of the RtpSender parameters is the complex structure RtpParameters (GetParameters()), which consists of the lists RtpCodecParameters, RtpHeaderExtensionParameters, RtpEncodingParameters.

Yes, The parameters here are indeed very complicated and need to be packaged with Encodeable correctly

> Question 2 - why is it that when I call AddTrack() when creating an audio track, these lists are empty? (What is recorded in the message.)

We must create an interface wrapper similar to webrtc::RtpParameters in libwebrtc. Let's say it is called RTCRtpParameters, and wrap it with scoped_refptr and return it to the user. Any std::string id; parameter in any webrtc object must be copied as char id_[kMaxStringLength ];, This is very important. The purpose of this is to make the exported libwebrtc.dll applicable to any caller environment, because the user's libstdc++ cannot be consistent with libwebrtc.dll when compiled.

please refer to this example.
https://github.com/dkubrakov/libwebrtc/blob/955b4c1e082f8bff7d82706c6cc82b91cf038527/src/rtc_audio_track_impl.cc#L9


> Question 3 - how to correctly return the structure and lists/map from virtual functions to the client application?

When we export using the new RTCRtpParameters interface, it will look like this

```C++

#define Vector bsp::inlined_vector

class RTCRtpParameters : public RefCountInterface {
  virtual const char*  transaction_id() = 0;
  
  vitrual const char* mid()   = 0;
  
  Vector<RTCRtpCodecParameters> codecs;

  Vector<RTCRtpExtension> header_extensions;

  Vector<RTCRtpEncodingParameters> encodings;

  vitrual  scoped_refptr<RtcpParameters> rtcp() = 0;
}

```

**Comment by dkubrakov** [comment]
Sorry, but had to switch to another task (((

**Comment by dahabit** [comment]
Helllo @cloudwebrtc  Thank you for your effort, it will be great if you got the chance to finish this issue :), and is there is any estimated time for it? , Thank you again

**Comment by cloudwebrtc** [comment]
solved by https://github.com/flutter-webrtc/flutter-webrtc/pull/688
