### ISSUE TITLE
Failed to create EGL context while rendering in flutter webrtc

### ISSUE THREAD

**Issue by ShilpaVania** [flutter-webrtc/flutter-webrtc#460]
I have implemented flutter webrtc and there are one case where i am failing to getUserMedia and the case is I had live video from User A and User B is join video to watch now User B left and repeat this process around 10 times after 11 and 12 it's failed and apk getting crashed. does anybody faced this issue in flutter webrtc? Thanks in advance. for information i am getting below issue in logcat:

org.webrtc.Logging: SurfaceTextureHelper: decoder-texture-thread create failure
SurfaceTextureHelper: java.lang.RuntimeException: Failed to create EGL context: 0x3003
E/org.webrtc.Logging: SurfaceTextureHelper: java.lang.RuntimeException: Failed to create EGL context: 0x3003
at org.webrtc.EglBase14Impl.createEglContext(EglBase14Impl.java:282)
        at org.webrtc.EglBase14Impl.<init>(EglBase14Impl.java:78)
        at org.webrtc.EglBase.createEgl14(EglBase.java:215)
        at org.webrtc.EglBase.create(EglBase.java:158)
        at org.webrtc.SurfaceTextureHelper.<init>(SurfaceTextureHelper.java:187)

**Comment by g0rdan** [comment]
I have the same issue.

**Comment by MohamedRisaldarTA** [comment]
Do we have a workaround for this issue..?

**Comment by pavan19084** [comment]
any updates on this
