### ISSUE TITLE
peerConnection.createOffer fails in Safari (Flutter Web)

### ISSUE THREAD

**Issue by philchekhov** [flutter-webrtc/flutter-webrtc#473]
**Describe the bug**

After obtaining a local media stream and adding it to a peer connection, I'm trying to create an offer:

```dart
final description = await _peerConnection.createOffer();
```

This line fails with the following error message:

```
Expected a value of type 'FutureOr<RtcSessionDescription>?', but got one of type 'NativeJavaScriptObject'
```

The peer connection is created the following way:

```dart
_peerConnection = await createPeerConnection(
  {
    'iceServers': iceServers,
    'sdpSemantics': 'unified-plan',
  },
  {
    'optional': [
      {
        'DtlsSrtpKeyAgreement': true,
      }
    ],
  },
);
```

I've encountered this bug in Safari only, the code works in Chrome and on the native platforms.

**To Reproduce**

This is a Safari-specific bug. The app should be running in Safari in order for the bug to appear.

1. Obtain a local media stream.
2. Create a peer connection with parameters shown above.
3. Add the stream obtained earlier to the peer connection.
4. Create an offer using that peer connection by calling the `createOffer` method.

**Expected behavior**

Awaiting on `createOffer` returns an `RTCSessionDescription` instance.

**Platform information**

* **Flutter version**:

```
[✓] Flutter (Channel unknown, 1.24.0-10.2.pre, on macOS 11.2.1 20D74 darwin-x64, locale en)
    • Flutter version 1.24.0-10.2.pre at /Users/aicantar/fvm/versions/1.24.0-10.2.pre
    • Framework revision 022b333a08 (3 months ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/aicantar/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 88.0.4324.150

• No issues found!
```

* **Plugin version**: 0.5.8
* **OS**: Web, Safari 14.0.3 (16610.4.3.1.4) on macOS 11.2.1
* **OS version**: Safari 14.0.3 (16610.4.3.1.4) on macOS 11.2.1

**Comment by wer-mathurin** [comment]
Are you using URL**S** for your turn server?

**Comment by philchekhov** [comment]
@wer-mathurin yes, I'm putting the URL of my TURN server into the `urls` field.

**Comment by esase** [comment]
I have the same issue, cold you guys give some explanation on it?

**Comment by wer-mathurin** [comment]
Seems Like the bug #434

**Safari on iOS needs a secure connection** with the turn server. switch to 'urls': 'turn:xxx.xxx.xxx.xxx'.

**Comment by philchekhov** [comment]
@wer-mathurin thanks for your help. The problem indeed was in the fact that we used insecure connection for testing.

**Comment by andreineacsu** [comment]
This is happening from my again on Firefox:
`Expected a value of type 'FutureOr<RtcSessionDescription>?', but got one of type 'NativeJavaScriptObject'`

I am using `urls` for the turn server.
