### ISSUE TITLE
How can I get audio activity?

### ISSUE THREAD

**Issue by LFSousa** [flutter-webrtc/flutter-webrtc#479]
I'm trying to get audio activity to shows if the user is speaking or not. Someone know any way to do that?

**Comment by barretzhi** [comment]
Have you found a way? I'm looking for it, too!

**Comment by LFSousa** [comment]
> Have you found a way? I'm looking for it, too!

not yet

**Comment by kzawadi** [comment]
This is not archived yet on webrtc implementation especially flutter implementation ...this archived by emission from your media server which can detect mic gain and then access this information through rest or WebSockets not only speaking but also muting and many more.....
