### ISSUE TITLE
When I try to get User media second time after ending first session, App closed without any error in Android.

### ISSUE THREAD

**Issue by 488taimoor** [flutter-webrtc/flutter-webrtc#480]
Its working properly on iOS and web. but on android When I try to get usermedia second time after completing my first call. my app closed suddenly at this point when It call 

return await navigator.mediaDevices
          .getUserMedia(mediaConstraints)
          .then((value) {
        print("this is stream ${value.id}");
        return value;
      }).catchError((onError) {
        print("this is error $onError");
      });

**my mediaConstraints are** 
 Map<String, dynamic> mediaConstraints = {
        'audio': true,
        'video': {
          'mandatory': {
            // 'minWidth':
            //     '640', // Provide your own width, height and frame rate here
            // 'minHeight': '480',
            'minFrameRate': '30',
          },
          'facingMode': 'user',
          'optional': [],
        }
      };

**I'm also closing  session after first call.** 

Future<void> _closeSession() async {
    _localStream?.getTracks()?.forEach((element) async {
      await element.stop();
    });
    await _localStream?.dispose();
    _localStream = null;

    await _peerConnection.close();
  }

Please let me know where is the problem. Thanks in advance

**Comment by 488taimoor** [comment]
any solution?

**Comment by muhammedrashidm** [comment]
same issue, have you found any solution?

**Comment by 4015taimoor** [comment]
@muhammedrashidm  fix issue #478. please update webrtc package .
