### ISSUE TITLE
onTrack event never call for the answer

### ISSUE THREAD

**Issue by Xaviou1003** [flutter-webrtc/flutter-webrtc#481]
**Describe the bug**
Hello flutter-webrtc team,

I try to make a peer visio call with flutter-webrtc and firestore and I have an issue. 
On caller side: local video and remote video are displayed -> OK
On answer side: local video is displayed, but remote is never displayed -> KO

I think I have found the source of this issue:  onTack event (on answer side) is never called. 

I have already read this post https://stackoverflow.com/questions/61354018/webrtc-connection-is-successful-but-answering-peer-never-receives-track-event
But this fix does not work in my case.

**To Reproduce**
`
  void _answerCall() async {
_peerConnection =
        await createPeerConnection(configuration, loopbackConstraints);

    _peerConnection.onSignalingState = _onSignalingState;
    _peerConnection.onIceGatheringState = _onIceGatheringState2;
    _peerConnection.onIceConnectionState = _onIceConnectionState;
    _peerConnection.onConnectionState = _onPeerConnectionState;
    _peerConnection.onAddStream = _onAddStream;
    _peerConnection.onRemoveStream = _onRemoveStream;
    _peerConnection.onIceCandidate = _onCandidateJoinRoom;
    _peerConnection.onRenegotiationNeeded = _onRenegotiationNeeded;
    _peerConnection.onRemoveTrack = _onRemoveTrack;
    // _peerConnection.onTrack = _onTrack;

    _localStream = await navigator.mediaDevices.getUserMedia(mediaConstraints);
    _localRenderer.srcObject = _localStream;

    await _peerConnection.addStream(_localStream);
    switch (sdpSemantics) {
      case 'plan-b':
        await _peerConnection.addStream(_localStream);
        break;
      case 'unified-plan':
        _peerConnection.onTrack = _onTrack;
        _localStream.getTracks().forEach((track) {
          _peerConnection.addTrack(track, _localStream);
        });
        break;
    }

    await _peerConnection.setRemoteDescription(
        RTCSessionDescription(call.offer.sdp, call.offer.type));

    answer = await _peerConnection.createAnswer();

    //Update firestore model with answer
    call.answer = VisioOffer(answer.type, answer.sdp);
    _visioCallRepository.update(call);

    await _peerConnection.setLocalDescription(answer);

    (await _visioCallRepository.getById(call.id))
        .reference
        .collection('callerCandidates')
        .snapshots()
        .listen((querySnapshot) async {
      querySnapshot.docChanges.forEach((change) async {
        if (change.type == DocumentChangeType.added) {
          var data = change.doc.data();
          _peerConnection.addCandidate(RTCIceCandidate(
              data['candidate'], data['sdpMid'], data['sdpMLineIndex']));
        }
      });
    });

}

`

**Expected behavior**
onTrack should be called?

**Platform information**

* **Flutter version**: 
`
[✓] Flutter (Channel beta, 1.26.0-17.5.pre, on macOS 11.1 20C69 darwin-x64, locale fr-CH)
    • Flutter version 1.26.0-17.5.pre at /Users/xavierbordy/Travail/flutter/flutter
    • Framework revision 1fe38dcb5f (2 weeks ago), 2021-02-10 16:25:47 -0800
    • Engine revision d4453f6018
    • Dart version 2.12.0 (build 2.12.0-259.9.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/xavierbordy/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2017.2.7)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 52.2.5
    • Dart plugin version 203.6912

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Android SDK built for x86 (mobile) • emulator-5558 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 88.0.4324.192

• No issues found!
`
* **Plugin version**: 0.5.8
* **OS**: Android and web

**Comment by cloudwebrtc** [comment]
Have you checked whether sdpSemantics is plan-b or unified-plan?
If it is plan-b, your code is missing 
```dart
_peerConnection.onAddStream = (MediaStream stream) {

}
```

**Comment by Xaviou1003** [comment]
Thanks for your answer.
Yes I check,  sdpSemantics and it is unified-plan. 

And I have an handler for the  onAddStream  event:
`  void _onAddStream(MediaStream stream) {
    print('New stream: ' + stream.id);
    setState(() {
      _remoteRenderer.srcObject = stream;
    });
  }`

**Comment by Xaviou1003** [comment]
I just saw my copy/paste is bad (sorry for the mistake, but I try a lot of thing before to create this issue).

I remove this terrible await _peerConnection.addStream(_localStream) before the switch.

Now my code is:
`
...
_localStream = await navigator.mediaDevices.getUserMedia(mediaConstraints);
_localRenderer.srcObject = _localStream;

switch (sdpSemantics) {
  case 'plan-b':
    await _peerConnection.addStream(_localStream);
    break;
  case 'unified-plan':
    _peerConnection.onTrack = _onTrack;
    _localStream.getTracks().forEach((track) {
      _peerConnection.addTrack(track, _localStream);
    });
    break;
}
...
`

**Comment by Xaviou1003** [comment]
@cloudwebrtc 
Can you confirm my expectation : onTrack should be call automatically when setRemoteDescription is called?
 
Do you want that I share all the code?
