### ISSUE TITLE
请问这个sdk是基于声网nativesdk封装的还是websdk封装的？

### ISSUE THREAD

**Issue by xinlee333** [flutter-webrtc/flutter-webrtc#483]
因为我看到官网上写着，websdk在某些平台上会有问题，比如ios设备商因为默认的webview都是Safari，声网websdk在ios的safari上会有很多问题，所以官方不建议使用。
那这个flutter的sdk是封装的nativesdk还是websdk呢？
谢谢。

**Comment by cloudwebrtc** [comment]
使用flutter app 时，sdk 时使用google webrtc native，使用flutter web 依赖各自的平台的浏览器或webview.
例如你在iOS上开发app，调用`flutter build ios`时,使用了来自google 官方webrtc 编译的WebRTC.framework，
而使用`flutter build web` 得到的html文件，并在ios的safari 上打开，则调用的时浏览器webrtc.
