### ISSUE TITLE
请问支持 flutter2 吗？

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [flutter-webrtc/flutter-webrtc#484]
谷歌刚刚发布了 Flutter 2——专为 Web、移动和桌面开发而构建。

Flutter 2 是 Flutter 的重大升级版本，可帮助开发者为任何平台创建美观、快速和可移植的应用程序。谷歌表示，开发者借助 Flutter 2 可使用同一份代码库面向 5 个操作系统（iOS, Android, Windows, macOS 和 Linux）发布原生应用，以及发布面向 Chrome, Firefox, Safari 和 Edge 等浏览器的应用。此外，Flutter 还可以嵌入到汽车、电视和智能家电中。

**Comment by cloudwebrtc** [comment]
支持，刚刚我将windows/macos 上的flutter 升级到 2.0.0可以正常编译运行.
