### ISSUE TITLE
RTCIceConnectionStateFailed

### ISSUE THREAD

**Issue by johntyty912** [flutter-webrtc/flutter-webrtc#487]
Hi, I implemented an app with this plugin, it works very well in the same wifi network. But with cellular network, it seems cannot connect. I have already implement a TURN server and checked it works with [trickle-ice](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/). 
![aaa](https://user-images.githubusercontent.com/19371767/110094155-7ab3a900-7dd6-11eb-9fba-3b8e67ae9e91.PNG)
And add it like this
![Capture](https://user-images.githubusercontent.com/19371767/110095987-6d97b980-7dd8-11eb-8155-daa296f317b7.PNG)

Also, here's the error logs
![f69adb59-b82a-4f81-a88c-12b558dedc75](https://user-images.githubusercontent.com/19371767/110094590-f44b9700-7dd6-11eb-8910-ffa859a23506.jpg)
![f7c29730-12b6-4156-b5db-b56cd0c84e95](https://user-images.githubusercontent.com/19371767/110094598-f57cc400-7dd6-11eb-8e37-25b4acdee89e.jpg)

Edit: I just tested, it also works with different wifi network, but it didn't work with cellular network

**Comment by johntyty912** [comment]
Hi, I also tested my turn server with [firebaseRTC](https://webrtc.org/getting-started/firebase-rtc-codelab) and changed the configuration as below:
![Capture](https://user-images.githubusercontent.com/19371767/110270734-73bcae80-8001-11eb-87c3-c0ddea2220e2.PNG)
it works.

What should I check? Any ideas?

**Comment by supermuesli** [comment]
i'm having the exact same issue. any update on this?
