### ISSUE TITLE
Screen Capture on Windows

### ISSUE THREAD

**Issue by troyzhao** [flutter-webrtc/flutter-webrtc#488]
When screen capture feature could supporte windows

**Comment by cloudwebrtc** [comment]
It will be implemented after the [unfied-plan for windows](https://github.com/flutter-webrtc/flutter-webrtc/issues/457), we need to merge this PR https://github.com/flutter-webrtc/libwebrtc/pull/4 first.

**Comment by danilonogueirateixeira** [comment]
Waiting for this feature, is there any forecast to publish?

**Comment by cloudwebrtc** [comment]
https://github.com/flutter-webrtc/flutter-webrtc/issues/799

**Comment by cloudwebrtc** [comment]
support now
