### ISSUE TITLE
Support for desktop linux version

### ISSUE THREAD

**Issue by dnsoumik** [flutter-webrtc/flutter-webrtc#492]
Waiting for the Linux desktop version.

**Comment by cloudwebrtc** [comment]
Depend on this PR to land first.

https://github.com/flutter/engine/pull/20714

**Comment by dnsoumik** [comment]
I can help if anything required, thank you.

**Comment by muriloventuroso** [comment]
The PR is now in flutter/engine#24916

**Comment by fksik** [comment]
> The PR is now in [flutter/engine#24916](https://github.com/flutter/engine/pull/24916)

This PR is merged now When can we expect this feature

**Comment by cloudwebrtc** [comment]
https://github.com/flutter-webrtc/flutter-webrtc/pull/740

I have tried to port this plug-in on Linux, but because the flutter Linux platform cannot reuse the CPP code of the windows platform, I have to completely rewrite the plug-in adaptation layer, which will be a difficult project. The amount of code is huge, so any help would be appreciated

**Comment by cloudwebrtc** [comment]
Linux platform must use GTK's GObject interface to wrap, not C++

**Comment by iDings** [comment]
@cloudwebrtc    i try to impl flutter-webrtc on linux desktop based on common/cpp code,  mostly seems is working, 
 [iDings/flutter-webrtc/try_linux](https://github.com/iDings/flutter-webrtc/commits/try_linux), but have a issue:
if desktop callout, the remote video can't be showed, but after i resize the flutter window, remote vidoe shows up
seems remote RTCVideoView didn't be actived first time, but after resize RTCVideoView is enabled?
any ideas about what's the problem to help me to dig-in thi issue?

if remote calling desktop answered, the remote video works normal,

https://user-images.githubusercontent.com/2938288/167543159-9e30907d-b280-48e4-a410-0ea0381178fe.mp4

**Comment by cloudwebrtc** [comment]
Hey @iDings, Is the loopback sample working?  It looks like the RTCVideoRenderer is not initialized.

**Comment by iDings** [comment]
> Hey @iDings, Is the loopback sample working? It looks like the RTCVideoRenderer is not initialized.

 loopback sample works fine
https://user-images.githubusercontent.com/2938288/167607399-7ab09216-2a73-4afc-9d1d-54fe705a5070.mp4

**Comment by iDings** [comment]
https://github.com/flutter-webrtc/flutter-webrtc-demo/issues/118#issuecomment-801804745  this patch fix my problem, 
but main reason is ```ValueListenableBuilder``` does not rebuild child when ```RTCVideoValue``` changes,  so for this view need make sure ```videoRenderer.textureId != null && videoRenderer.srcObject != null``` when create RTCVideoView.

https://github.com/flutter-webrtc/flutter-webrtc/blob/a754e0df7e052a0501af0274adb14816ef9ee204/lib/src/native/rtc_video_view_impl.dart#L43-L62

in [flutter-webrtc-demo/call_sample.dart](https://github.com/flutter-webrtc/flutter-webrtc-demo/blob/master/lib/src/call_sample/call_sample.dart#L277),  RTCVideoView is created when ```_inCalling``` is true, but for callout,  async ```setRemoteDescription``` didn't ensure ```videoRenderer.srcObject``` is setted.
https://github.com/flutter-webrtc/flutter-webrtc-demo/blob/master/lib/src/call_sample/signaling.dart#L202

await  ```setRemoteDescription```  done fix this.
```
@@ -199,7 +200,7 @@ class Signaling {
           var description = data['description'];
           var sessionId = data['session_id'];
           var session = _sessions[sessionId];
-          session?.pc?.setRemoteDescription(
+          await session?.pc?.setRemoteDescription(
               RTCSessionDescription(description['sdp'], description['type']));
           onCallStateChange?.call(session!, CallState.CallStateConnected);
         }
```

**Comment by cloudwebrtc** [comment]
@iDings Are you still interested in continuing your PR? I'm trying to write a generic layer to adapt to linux/windows/ and e-linux differences.
