### ISSUE TITLE
An open-source chat application

### ISSUE THREAD

**Issue by aliyazdi75** [flutter-webrtc/flutter-webrtc#494]
Hi @cloudwebrtc 
Thank you for this awesome plugin.

I made an open-source chat application with Bloc and understandable states.
I'm asking you to mention it in the readme.
It would be great for new developers to use that project and understand how to implement it in the right way,

Thanks a lot.
https://github.com/aliyazdi75/flutter_chat

**Comment by cloudwebrtc** [comment]
Hey, Thank you for your great work. I created this repo  [awesome-flutter-webrtc](https://github.com/flutter-webrtc/awesome-flutter-webrtc), include all projects that use flutter-webrtc.  Later I will do some PR and put your project on it.

**Comment by aliyazdi75** [comment]
Thank you so much for this great work :100:
