### ISSUE TITLE
Screen share: landscape orientation if you launch the stream in portrait orientation

### ISSUE THREAD

**Issue by Blancduman** [flutter-webrtc/flutter-webrtc#495]
**Describe the bug**
If you start the screensharing in portrait orientation, then if you turn the android to landscape orientation, the stream resolution does not change, but the picture is compressed. In opposite, if your start the screensharing in landscape and switch between orientations, there is no issue.
**To Reproduce**
Start to screenshare on android in portrait orientation and then switch to landscape orientation 
**Expected behavior**
Changing resolution of mediastream.
**Platform information**
Only android.
* **Flutter version**:
```
[✓] Flutter (Channel master, 1.26.0-13.0.pre.118, on Mac OS X 10.15.7 19H114
    darwin-x64, locale ru-RU)
    • Flutter version 1.26.0-13.0.pre.118 at
      /Users/admin/Documents/Repos/flutter
    • Framework revision 08068fd94c (7 weeks ago), 2021-01-21 22:51:03 -0800
    • Engine revision 90641fa923
    • Dart version 2.12.0 (build 2.12.0-248.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (3 available)
    • iphone7(Love) (mobile) • d98fd62c721324caef25490a6e345a9ed9bb1607 • ios
      • iOS 14.1
    • macOS (desktop)          • macos                                    •
      darwin-x64     • Mac OS X 10.15.7 19H114 darwin-x64
    • Chrome (web)             • chrome                                   •
      web-javascript • Google Chrome 89.0.4389.82

• No issues found!
```
* **Plugin version**: 0.4.1
* **OS**: Android
* **OS version**: Any

**Comment by Blancduman** [comment]
![issue](https://cdn.discordapp.com/attachments/810893079796121630/820920072800305152/jesos.png)

**Comment by Blancduman** [comment]
![issue](https://cdn.discordapp.com/attachments/810893079796121630/820921680313581578/unknown.png)

**Comment by Ayman-Kortobaa** [comment]
I am having the same issue, trying to use the greater dimension would result in a square black screen with the actual screen frames in the middle, also we can force it to start as landscape, but it isn't the most optimal solution.

I can't find an optimal solution to listen for orientation changes for instance and call the `ScreenCapturerAndroid`'s `changeCaptureFormat` method, also we don't have access to the method that handles the frames (frame by frame) to check for dimensions and change orientation or width and height accordingly.

If @cloudwebrtc can point me in the right direction I can create a pull request ASAP as this issue is blocking my app, your help is greatly appreciated.
