### ISSUE TITLE
captureFrame is producing desaturated images

### ISSUE THREAD

**Issue by carman247** [flutter-webrtc/flutter-webrtc#496]
Hi, 

I'm not sure if this is an issue or I'm just doing something wrong.

I'm using the `captureFrame` method on a `MediaStreamTrack` and my images are appearing incredibly desaturated, and almost black and white.

Here's an example of what I'm doing

```
MediaStreamTrack _localVideoTrack;
Directory _directory;
String _path;
File _imageFile;

 // Find video tracks
final videoTracks = localStream.getVideoTracks();
// Set MediaStreamTrack
_localVideoTrack = videoTracks[0];
// Get application directory
_directory = await getApplicationDocumentsDirectory();
// Set path
_path = _directory.path;
// Create file
_imageFile = await File('$_path/streamSnapshot/snapshot.jpeg').create(recursive: true);
// Capture frame
await _localVideoTrack.captureFrame(_imageFile.path);
```

P.S. this is occurring on both Android devices I've tested on.

**Comment by ChihayaK** [comment]
I am not sure if the following is related to this issue, but I had a problem using the [yuv helper function](https://github.com/flutter-webrtc/flutter-webrtc/blob/96da9497f7b11709038ae54fe03a1a1b3fa47249/android/src/main/java/com/cloudwebrtc/webrtc/record/FrameCapturer.java#L59). Which gives me an incorrect output of the frame with a line(or some lines?) of pixels supposed to be on the bottom but ended up on the top. I was able to fix this issue by compiling and use an [libyuv](https://chromium.googlesource.com/libyuv/libyuv/) myself and it even enables a more direct way to convert from I420 to ABGR. After that all my problems regarding to the color and conversion instantly gone. Maybe you can give it a try?

**Comment by Parfyonator** [comment]
The problem still persist. I'm not very good at native development but it seems that there is a `I420ToNV12 ` conversion that introduces those artefacts @ChihayaK mentioned above.

@ChihayaK can you share some code or guide on how to solve this problem at native layer and get it working in flutter project? Thanks in advance.

**Comment by ChihayaK** [comment]
> The problem still persist. I'm not very good at native development but it seems that `I420ToNV12` conversion or compression to jpeg introduces those artefacts @ChihayaK mentioned above.
> 
> @ChihayaK can you share some code or guide on how to solve this problem at native layer and get it working in flutter project? Thanks in advance.

Basicaly you need to build the libyuv your self, and find any places that uses the previous one, replaces the old function with the one come from the libyuv libaray. You will need to setup jni functions in order to bridge the java part and the native part. 
You can check out [here](https://chromium.googlesource.com/libyuv/libyuv/+/refs/heads/main/include/libyuv/convert.h) for list of functions you can use.

**Comment by Parfyonator** [comment]
@ChihayaK thank you for your reply. Yes, it WebRTC bug. I didn't notice that the import of `YuvHelper` is not from the same repo.

I'm not sure about JNI functions, since I'm not very familiar with Android native development. I found [this repo](https://github.com/crow-misia/libyuv-android) which seems to implement those interfaces. At least I see the the function I need [here](https://github.com/crow-misia/libyuv-android/blob/ffaea9bc63f8db0d7bc9e77a1ea0fca7a1d70b55/core/src/main/java/io/github/crow_misia/libyuv/Yuv.kt#L938). As far as I understand it can already be added as a java dependency in gradle file. So I guess I can fork the current repo and use the mentioned dependence to replace appearances of the `I420ToNV12` with the one from the libyuv.

What do you think?

**Comment by ChihayaK** [comment]
I will provide my code for using the JNI functions.
Folder structure(start from [here](https://github.com/flutter-webrtc/flutter-webrtc/tree/main/android/src/main))
```
-cpp[new]
--native-lib.cpp  // see below
--include
---libyuv.h  // copy from the libyuv repo
---libyuv[folder]  // you need to copy this from the libyuv repo, which contains all the header file for the libyuv
----basic_types.h
----compare_row.h
----....

-jniLibs[new]
--arm64-v8a
---libyuv.so  // you need to compile this yourself for each cpu arch
--armeabi-v7a
---libyuv.so 

-java/com/cloudwebrtc/webrtc/utils
--YuvUtil.java[new]  // see below
```

Example for `native-lib.cpp`, you will need to modify the function signature to the function you want to use
native-lib.cpp
```
#include <jni.h>
#include <string>
#include "libyuv.h"

extern "C"
JNIEXPORT void JNICALL
Java_com_cloudwebrtc_webrtc_utils_YuvUtil_I420ToABGR(JNIEnv *env, jclass clazz, jbyteArray src_y_j,
                                                     jint src_stride_y, jbyteArray src_u_j,
                                                     jint src_stride_u, jbyteArray src_v_j,
                                                     jint src_stride_v, jbyteArray dst_abgr_j,
                                                     jint dst_stride_abgr, jint width,
                                                     jint height) {
    uint8_t* src_y=(uint8_t*) env->GetByteArrayElements(src_y_j, 0);
    uint8_t* src_u=(uint8_t*) env->GetByteArrayElements(src_u_j, 0);
    uint8_t* src_v=(uint8_t*) env->GetByteArrayElements(src_v_j, 0);

    uint8_t* dst_abgr=(uint8_t*) env->GetByteArrayElements(dst_abgr_j, 0);

    libyuv::I420ToABGR(src_y,src_stride_y,src_u,src_stride_u,src_v,src_stride_v,dst_abgr,dst_stride_abgr,width,height);

    //remember release
    env->ReleaseByteArrayElements(src_y_j, (jbyte*)src_y, 0);
    env->ReleaseByteArrayElements(src_u_j, (jbyte*)src_u, 0);
    env->ReleaseByteArrayElements(src_v_j, (jbyte*)src_v, 0);
    env->ReleaseByteArrayElements(dst_abgr_j, (jbyte*)dst_abgr, 0);

}
```

YuvUtil.java
```
package com.cloudwebrtc.webrtc.utils;

public class YuvUtil {
    static {
        System.loadLibrary("native-lib");
        System.loadLibrary("yuv");
    }


    public native static void I420ToABGR(byte[] src_y, int src_stride_y, byte[] src_u, int src_stride_u, byte[] src_v, int src_stride_v, byte[] dst_abgr, int dst_stride_abgr, int width, int height);

}
```
