### ISSUE TITLE
Crash: org.webrtc.Camera2Enumerator.convertSizes

### ISSUE THREAD

**Issue by carman247** [flutter-webrtc/flutter-webrtc#501]
Not sure what the cause it but this seems to be happening a lot for users on Samsung devices

100% samsung
43% Galaxy S20 Ultra 5G
42% Galaxy S20+ 5G
10% Galaxy Note10+ 5G
5% Other (1)

Camera2Enumerator.java line 5
org.webrtc.Camera2Enumerator.convertSizes

`Fatal Exception: java.lang.NullPointerException
Attempt to get length of null array
org.webrtc.Camera2Enumerator.convertSizes (Camera2Enumerator.java:5)
org.webrtc.Camera2Enumerator.getSupportedSizes (Camera2Enumerator.java:26)
org.webrtc.Camera2Session.findCaptureFormat (Camera2Session.java:27)
org.webrtc.Camera2Session.start (Camera2Session.java:57)
org.webrtc.Camera2Session.<init> (Camera2Session.java:60)
org.webrtc.Camera2Session.create (Camera2Session.java:14)
org.webrtc.Camera2Capturer.createCameraSession (Camera2Capturer.java:14)
org.webrtc.CameraCapturer$5.run (CameraCapturer.java:48)
android.os.Handler.handleCallback (Handler.java:938)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:246)
android.os.HandlerThread.run (HandlerThread.java:67)`

**Comment by LiFaWang** [comment]
同样有这个问题

**Comment by FidaMOhsin** [comment]
Any soluation for this?

**Comment by hiepu** [comment]
```
Fatal Exception: java.lang.NullPointerException
Attempt to get length of null array
org.webrtc.Camera2Enumerator.convertSizes (Camera2Enumerator.java:234)
org.webrtc.Camera2Enumerator.getSupportedSizes (Camera2Enumerator.java:147)
org.webrtc.Camera2Session.findCaptureFormat (Camera2Session.java:325)
org.webrtc.Camera2Session.start (Camera2Session.java:313)
org.webrtc.Camera2Session.<init> (Camera2Session.java:296)
org.webrtc.Camera2Session.create (Camera2Session.java:274)
org.webrtc.Camera2Capturer.createCameraSession (Camera2Capturer.java:35)
org.webrtc.CameraCapturer$5.run (CameraCapturer.java:272)
```
