### ISSUE TITLE
IceConnectionStateCheckingFailed

### ISSUE THREAD

**Issue by tygm** [flutter-webrtc/flutter-webrtc#506]
**Describe the bug**
flutter_webrtc_demo项目在跨网视频的时候，经常失败，成功率低，经过观察插件日志得知，失败是因为IceConnectionStateChecking这步失败导致的，我现在处理方式是：先把收集到的候选地址暂存，监听RTCIceGatheringState事件等到RTCIceGatheringStateComplete的时候，再一起发送给对方，经过测试这样可以避免跨网失败的问题，但又有新的问题，RTCIceGatheringStateComplete事件触发的时间比较长，10多秒左右，如何减少这个时间呢?
**To Reproduce**
两台Android设备运行flutter_webrtc_demo，一个wifi一个4G，进行通话
**Expected behavior**
希望跨网通信成功率高，且等待时间少
**Platform information**
Android
* **Flutter version**: 2.0.1
* **Plugin version**:0.5.8
* **OS**: Android 
* **OS version**:10.0

**Comment by tygm** [comment]
现在我用一个定时器暂时解决，如果1秒内没有新的候选地址产生，那么判断收集完成，开始发送候选地址给对方。请问有其他更好的解决方式吗？

**Comment by cloudwebrtc** [comment]
没有用trickle吗？只要时许无问题，trickle 可以做到最短的连通时间

**Comment by tygm** [comment]
请问trickle如何用啊，可以给点例子吗
