### ISSUE TITLE
网络切换后不能正常视频

### ISSUE THREAD

**Issue by tygm** [flutter-webrtc/flutter-webrtc#509]
flutter app能够正常使用自己部署的turn服务器了，但如果一开始视频通话走的是内网，没有走turn转发，通话过程中切换到4g网络，这个时候就无法正常视频了，请问这种情况有什么解决方案吗？

**Comment by cloudwebrtc** [comment]
切换4G后，需要使用重协商流程

**Comment by lxl518000** [comment]
> 切换4G后，需要使用重协商流程
> 
> ```dart
>     var constraints = {
>       'mandatory': {
>         'OfferToReceiveAudio': true,
>         'OfferToReceiveVideo': true,
>         'IceRestart': true
>       },
>       'optional': [],
>     };
> 
>     var desc = await pc.createOffer(constraints);
>     await pc.setLocalDescription(desc);
> ```
> 
> 然后再次交换candidate 就能重连了

我切换重连以后对方可以看到我和听到我的声音，我却得不到对方的声音和视频，请问还需要操作什么？
