### ISSUE TITLE
Errors were reported when the release version was initialized,version0.5.7

### ISSUE THREAD

**Issue by cj123195** [flutter-webrtc/flutter-webrtc#514]
E/flutter (21771): [ERROR:flutter/shell/platform/android/platform_view_android_jni_impl.cc(43)] java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals() (tried Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals and Java_org_webrtc_PeerConnectionFactory_nativeInitializeAndroidGlobals__)
E/flutter (21771): 	at org.webrtc.PeerConnectionFactory.nativeInitializeAndroidGlobals(Native Method)
E/flutter (21771): 	at org.webrtc.PeerConnectionFactory.initialize(Unknown Source:12)
E/flutter (21771): 	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.ensureInitialized(Unknown Source:20)
E/flutter (21771): 	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.onMethodCall(Unknown Source:4)
E/flutter (21771): 	at h.b.c.a.j$a.a(Unknown Source:17)
E/flutter (21771): 	at io.flutter.embedding.engine.e.b.a(Unknown Source:57)
E/flutter (21771): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/flutter (21771): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (21771): 	at android.os.MessageQueue.next(MessageQueue.java:363)
E/flutter (21771): 	at android.os.Looper.loop(Looper.java:176)
E/flutter (21771): 	at android.app.ActivityThread.main(ActivityThread.java:8387)
E/flutter (21771): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (21771): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/flutter (21771): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
E/flutter (21771): 
F/flutter (21771): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(942)] Check failed: CheckException(env).

**Comment by cloudwebrtc** [comment]
Please use v0.6.0.

**Comment by cj123195** [comment]
Thanks, it's working. Then i'll close the issue.
