### ISSUE TITLE
How to force to set the voice use media audio ?

### ISSUE THREAD

**Issue by kklldog** [flutter-webrtc/flutter-webrtc#515]
now , flutter-webrtc use call audio default on andriod  even set enableSpeakerphone = true .
How can i force use media audio ?

flutter-webrtc 如何使用媒体音量来播放声音？

**Comment by cloudwebrtc** [comment]
This is related to the internal native implementation of google libwebrtc

**Comment by kklldog** [comment]
That's sad  :（
