### ISSUE TITLE
webrtc-internals

### ISSUE THREAD

**Issue by sm2017** [flutter-webrtc/flutter-webrtc#518]
**Is your feature request related to a problem? Please describe.**
Chrome has a **chrome://webrtc-internals** page that help to inspect WebRTC, 

**Describe the solution you'd like**
Having a dev tool for inspecting WebRTC events can help for troubleshooting

**Additional context**
See https://github.com/flutter/devtools/issues/2558

**Comment by cloudwebrtc** [comment]
flutter-webrtc provides the pc.getStats interface, which can obtain statistics consistent with chrome://webrtc-internals, but you need to develop a flutter page similar to chrome://webrtc-internals to display this information.

**Comment by ghenry** [comment]
Are these exposed into dart-sip-ua at all?

**Comment by cloudwebrtc** [comment]
@ghenry I don’t think it is exposed, but it can be done very easily, just pass the getStats api upwards here in RTCSeesion
