### ISSUE TITLE
java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION

### ISSUE THREAD

**Issue by zhangyangyang3** [flutter-webrtc/flutter-webrtc#520]
**Describe the bug**
when I allow record screen. my app crashed
**To Reproduce**
when I allow record screen. my app crashed
**Expected behavior**
D/InputTransport(29144): Input channel destroyed: 'ClientS', fd=86
D/ViewRootImpl@de1e870[MainActivity](29144): stopped(false) old=false
I/org.webrtc.Logging(29144): EglBase14Impl: Using OpenGL ES version 2
D/AndroidRuntime(29144): Shutting down VM
E/AndroidRuntime(29144): FATAL EXCEPTION: main
E/AndroidRuntime(29144): Process: net.tsingyun.flutter_app, PID: 29144
E/AndroidRuntime(29144): java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
E/AndroidRuntime(29144): 	at android.os.Parcel.createException(Parcel.java:2088)
E/AndroidRuntime(29144): 	at android.os.Parcel.readException(Parcel.java:2056)
E/AndroidRuntime(29144): 	at android.os.Parcel.readException(Parcel.java:2004)
E/AndroidRuntime(29144): 	at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:231)
E/AndroidRuntime(29144): 	at android.media.projection.MediaProjection.<init>(MediaProjection.java:68)
E/AndroidRuntime(29144): 	at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:147)
E/AndroidRuntime(29144): 	at org.webrtc.ScreenCapturerAndroid.startCapture(ScreenCapturerAndroid.java:114)
E/AndroidRuntime(29144): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl$3.onReceiveResult(GetUserMediaImpl.java:498)
E/AndroidRuntime(29144): 	at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
E/AndroidRuntime(29144): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(29144): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(29144): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(29144): 	at android.app.ActivityThread.main(ActivityThread.java:7860)
E/AndroidRuntime(29144): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29144): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(29144): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
E/AndroidRuntime(29144): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(29144): 	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:501)
E/AndroidRuntime(29144): 	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:135)
E/AndroidRuntime(29144): 	at android.os.Binder.execTransactInternal(Binder.java:1021)
E/AndroidRuntime(29144): 	at android.os.Binder.execTransact(Binder.java:994)
E/AndroidRuntime(29144): 
I/Process (29144): Sending signal. PID: 29144 SIG: 9
Lost connection to device.

And my config file 

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="net.tsingyun.flutter_app">
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.CHANGE_NETWORK_STATE" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />

    <application
        android:label="flutter_app"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true"
        android:requestLegacyExternalStorage="true"
        android:networkSecurityConfig="@xml/network_security_config"

       >
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
        <service
            android:name=".ScreenRecorder"
            android:enabled="true"
            android:foregroundServiceType="mediaProjection"/>
        <service android:name=".CaptureScreenService"
            android:enabled="true"
            android:foregroundServiceType="mediaProjection"/>
    </application>
</manifest>

**Platform information**
windows 10 
* **Flutter version**: 
D:\flutter_windows_2.0.1-stable\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.868], locale zh-CN)
    • Flutter version 2.0.1 at D:\flutter_windows_2.0.1-stable\flutter
    • Framework revision c5a4b4029c (4 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:/Users/zyy/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:/Users/zyy/AppData/Local/Android/Sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA 2020.3.1
    • Flutter plugin version 54.1.3
    • Dart plugin version 203.7759

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\zyy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • SM A9200 (mobile) • 2cd060a8771d7ece • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!
 

* **Plugin version**:

  flutter_webrtc: ^0.6.1

* **OS**: 

android

* **OS version**:
windows 10 64

**Comment by cloudwebrtc** [comment]
Please refer to this commit
https://github.com/flutter-webrtc/flutter-webrtc/commit/0c21fa5880e904fa53ecc9e09b374724dd861c27

**Comment by zhangyangyang3** [comment]
> Please refer to this commit
> [0c21fa5](https://github.com/flutter-webrtc/flutter-webrtc/commit/0c21fa5880e904fa53ecc9e09b374724dd861c27)

I try it ,it seems not works for me.

**Comment by zhangyangyang3** [comment]
I used both 'flutter_foreground_plugin' and  'flutter_background' ,it still crashed after I click allow button.
`
E/AndroidRuntime(23593): java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
E/AndroidRuntime(23593): 	at android.os.Parcel.createException(Parcel.java:2088)
E/AndroidRuntime(23593): 	at android.os.Parcel.readException(Parcel.java:2056)
E/AndroidRuntime(23593): 	at android.os.Parcel.readException(Parcel.java:2004)
E/AndroidRuntime(23593): 	at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:231)
E/AndroidRuntime(23593): 	at android.media.projection.MediaProjection.<init>(MediaProjection.java:68)
E/AndroidRuntime(23593): 	at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:147)
E/AndroidRuntime(23593): 	at org.webrtc.ScreenCapturerAndroid.startCapture(ScreenCapturerAndroid.java:114)
E/AndroidRuntime(23593): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl$3.onReceiveResult(GetUserMediaImpl.java:498)
E/AndroidRuntime(23593): 	at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
E/AndroidRuntime(23593): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(23593): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(23593): 	at android.os.Looper.loop(Looper.java:237)
E/AndroidRuntime(23593): 	at android.app.ActivityThread.main(ActivityThread.java:7860)
E/AndroidRuntime(23593): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23593): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(23593): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
E/AndroidRuntime(23593): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(23593): 	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:501)
E/AndroidRuntime(23593): 	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:135)
E/AndroidRuntime(23593): 	at android.os.Binder.execTransactInternal(Binder.java:1021)
E/AndroidRuntime(23593): 	at android.os.Binder.execTransact(Binder.java:994)
E/AndroidRuntime(23593): 
I/Process (23593): Sending signal. PID: 23593 SIG: 9
`

if click deny button. it does not crashed. log tell me 'User did not allow xxx permission'

**Comment by zhangyangyang3** [comment]
I think the webrct do not need must record the screen.Can I avoid it ?

**Comment by zhangyangyang3** [comment]
I know that ,the api I invoke was wrong. use 
navigator.mediaDevices.getUserMedia(mediaConstraints);
not 
navigator.mediaDevices.getDisplayMedia(mediaConstraints);

**Comment by KurdAppDev** [comment]
add below service to the AndroidManifest.xml file.
```
<service android:name="de.julianassmann.flutter_background.IsolateHolderService"
            android:foregroundServiceType="mediaProjection"
            tools:targetApi="q"
            android:enabled="true"
            android:exported="false"/>
```

**Comment by femidof** [comment]
Please what's the fix to this issue, because I tried everything on this trend and nothing worked. Or am I doing things wrongly?

**Comment by prashantspandey** [comment]
Is there a fix to this?

**Comment by linus-ha** [comment]
For all I can tell by now, decreasing the `targetSdkVersion` down to `28` prevents crashing.

`./android/app/src/main/build.gradle`
```...
android {
    ...
    defaultConfig {
        applicationId "XXX // Specify your own unique Application ID
        minSdkVersion 21
        // TODO incresing the target version to flutter.targetSdkVersion leads to crash on screen mirroring
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }
...
```

**Comment by Rexobias** [comment]
I'm still getting this crash with the last version of the plugin. I'm forced to target the SDK 28 to avoid the crash. 

Are there any news related to this?

**Comment by Rexobias** [comment]
I found the solution here: https://github.com/flutter-webrtc/flutter-webrtc/issues/979

It works!

**Comment by Vinayak0-0** [comment]
Is there any working solution besides downgrading target SDK version?

**Comment by jogapps** [comment]
> Is there any working solution besides downgrading target SDK version?

yes @Rexobias  reply fixed it
