### ISSUE TITLE
Not able to connect NodeJS simple-peer and flutter-webrtc

### ISSUE THREAD

**Issue by aakashpothepalli** [flutter-webrtc/flutter-webrtc#521]
Is there a way to connect a nodejs server with a flutter device where both act as peers?
i have tried to establish a connection between them but I always end up getting onConnectionChangeFAILED on flutter and ERR_ICE_CONNECTION_FAILURE on NodeJS

**Comment by cloudwebrtc** [comment]
This is usually related to the WebRTC standard negotiation process. If your two devices are not under the same LAN, you need to deploy a turn server.

**Comment by aakashpothepalli** [comment]
Okay, got it
Thanks
