### ISSUE TITLE
通话录屏首次可以第二次app崩溃

### ISSUE THREAD

**Issue by tygm** [flutter-webrtc/flutter-webrtc#522]
**Describe the bug**
我在做视频通话过程中对整个过程进行录制保存的功能，通过如下代码实现：

  

> _record() async {
>     MediaStream stream = await navigator.mediaDevices.getDisplayMedia({
>       'audio': false,
>       'video': {
>         'mandatory': {
>           'minWidth': '640',
>           'minHeight': '480',
>         },
>         'facingMode': 'user',
>         'optional': [],
>       }
>     });
>     Directory directory = await getExternalStorageDirectory();
>     String path = directory.path +
>         "/videocall/" +
>         DateTime.now().millisecondsSinceEpoch.toString() +
>         ".mp4";
>     mediaRecorder.start(path,
>         videoTrack: stream.getVideoTracks()[0], audioChannel: null);
>   }

发现第一次视频通话可以正常被录制下来，第二次视频通话会崩溃，日志如下：（没有录制音频是因为无法录制，如果同时录制视频+音频的话，那么录制的文件始终是0大小的，希望作者也能关注并修复这个）

> 
> E/AndroidRuntime(17612): java.lang.IllegalStateException: Reply already submitted
> E/AndroidRuntime(17612): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:155)
> E/AndroidRuntime(17612): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:243)
> E/AndroidRuntime(17612): 	at com.cloudwebrtc.webrtc.utils.AnyThreadResult.lambda$error$1$AnyThreadResult(AnyThreadResult.java:23)
> E/AndroidRuntime(17612): 	at com.cloudwebrtc.webrtc.utils.-$$Lambda$AnyThreadResult$ccKxFpM2amkNZNKH8YO8t8OktKE.run(Unknown Source:8)
> E/AndroidRuntime(17612): 	at android.os.Handler.handleCallback(Handler.java:900)
> E/AndroidRuntime(17612): 	at android.os.Handler.dispatchMessage(Handler.java:103)
> E/AndroidRuntime(17612): 	at android.os.Looper.loop(Looper.java:219)
> E/AndroidRuntime(17612): 	at android.app.ActivityThread.main(ActivityThread.java:8387)
> E/AndroidRuntime(17612): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(17612): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
> E/AndroidRuntime(17612): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

**To Reproduce**
两方通过navigator.mediaDevices.getUserMedia进行视频通话，同时通过navigator.mediaDevices.getDisplayMedia来获取屏幕内容，并通过mediaRecorder录制屏幕内容
**Expected behavior**
正常录制视频，最好音频也能弄好
**Platform information**

* **Flutter version**: 2.0.3
* **Plugin version**:0.6.3
* **OS**: android
* **OS version**:10

**Comment by tygm** [comment]
摸索出一个解决第二次录屏崩溃的bug的解决方法，\flutter_webrtc-0.6.3\android\src\main\java\com\cloudwebrtc\webrtc\utils下的AnyThreadResult.java，修改如下，但感觉不是合适的解决方式
```

package com.cloudwebrtc.webrtc.utils;

import android.os.Looper;
import android.os.Handler;

import io.flutter.plugin.common.MethodChannel;

public final class AnyThreadResult implements MethodChannel.Result {
    final private MethodChannel.Result result;
    final private Handler handler = new Handler(Looper.getMainLooper());
    boolean submited=false;
    public AnyThreadResult(MethodChannel.Result result) {
        submited=false;
        this.result = result;
    }

    @Override
    public void success(Object o) {
        post(()->result.success(o));
    }

    @Override
    public void error(String s, String s1, Object o) {
        post(()->result.error(s, s1, o));
    }

    @Override
    public void notImplemented() {
        post(result::notImplemented);
    }

    private void post(Runnable r) {
        if(submited)return;
        submited=true;
        if(Looper.getMainLooper() == Looper.myLooper()){
            r.run();
        }else{
            handler.post(r);
        }
    }
}

```

**Comment by cloudwebrtc** [comment]
您可以尝试修复它，如果能提供PR，将会更好。 :) 因为我手上没有这么全的测试设备.

**Comment by tygm** [comment]
> 您可以尝试修复它，如果能提供PR，将会更好。

我有尝试去修复这个崩溃，如下的修改，虽然不崩溃了，但是第二次录制的时候，会报错permission revoked,我并没有拒绝录屏权限，不明白为什么会报这个错
```

package com.cloudwebrtc.webrtc.utils;

import android.os.Looper;
import android.os.Handler;

import io.flutter.plugin.common.MethodChannel;

public final class AnyThreadResult implements MethodChannel.Result {
    final private MethodChannel.Result result;
    final private Handler handler = new Handler(Looper.getMainLooper());
    boolean submited=false;
    public AnyThreadResult(MethodChannel.Result result) {
        submited=false;
        this.result = result;
    }

    @Override
    public void success(Object o) {
        post(()->result.success(o));
    }

    @Override
    public void error(String s, String s1, Object o) {
        post(()->result.error(s, s1, o));
    }

    @Override
    public void notImplemented() {
        post(result::notImplemented);
    }

    private void post(Runnable r) {
        if(submited)return;
        submited=true;
        if(Looper.getMainLooper() == Looper.myLooper()){
            r.run();
        }else{
            handler.post(r);
        }
    }
}

```

**Comment by cloudwebrtc** [comment]
我认为您应该检查为何会reply 两次，按正常来说一个method invoke，只会返回一次reply.

**Comment by tygm** [comment]
> 我认为您应该检查为何会reply 两次，按正常来说一个method invoke，只会返回一次reply.
> AnyThreadResult 对象只是为了同步线程队列 。

这个问题我修复了，一会给您提交PR（初次提交PR如有不对多多包涵），另一个问题是，录制的视频没有声音，我已经设置了audio:true，请问这个问题是因为在视频通话的原因吗？（视频通话的时候已经获取了audio的原因？）
