### ISSUE TITLE
still can not use camera after endcall. samsung(SM A9200) 语音通话期间无法录制视频

### ISSUE THREAD

**Issue by zhangyangyang3** [flutter-webrtc/flutter-webrtc#527]
after endcall webRTC , in SM A9200 still can not use camera in other place.it says that  '语音通话期间无法录制视频'.
but in other phones , it works well.(android Mi10 (小米手机) works well  ) 
flutter doctor info :

`
D:\flutter_windows_2.0.1-stable\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19042.868], locale zh-CN)
    • Flutter version 2.0.1 at D:\flutter_windows_2.0.1-stable\flutter
    • Framework revision c5a4b4029c (6 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0
    • Pub download mirror https://mirrors.tuna.tsinghua.edu.cn/dart-pub
    • Flutter download mirror https://mirrors.tuna.tsinghua.edu.cn/flutter

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:/Users/zyy/AppData/Local/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:/Users/zyy/AppData/Local/Android/Sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA 2020.3.1
    • Flutter plugin version 54.1.3
    • Dart plugin version 203.7759

[√] VS Code (version 1.55.0)
    • VS Code at C:\Users\zyy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • SM A9200 (mobile) • 2cd060a8771d7ece • android-arm64  • Android 10 (API 29)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 89.0.4389.114
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 89.0.774.45

• No issues found!
Process finished with exit code 0
`
webrtc version:
  flutter_webrtc: ^0.6.3

my close rtc code:

`
/// var define

 RTCVideoRenderer _localRender = RTCVideoRenderer();
  RTCVideoRenderer _remoteRender = RTCVideoRenderer();
  RTCPeerConnection _peerConnection;
  MediaStream _localStream;
  MediaStream _remoteStream;

/// some other codes....
/// close method
Future<void> _clearMediaInfo() async {
    if (_peerConnection != null) {
      await _peerConnection.close();
    }
    // local stream
    if (_localStream != null) {
      _localStream.getTracks().forEach((element) async {
        print("removeLocalTracks:$element");
        await _localStream.removeTrack(element);
        await element.stop();
      });
      print("remove local tracks success");
      await _localStream.dispose();
      _localStream = null;
    }

    if (_localRender != null) {
      _localRender.srcObject = null;
      _localRender = null;
    }
    // remote stream

    if (_remoteRender != null) {
      _remoteRender.srcObject = null;
      _remoteRender = null;
    }
  }
`

**Comment by zhangyangyang3** [comment]
I  found the reason. just stop the track is ok
`
if (_localStream != null) {
_localStream.getTracks().forEach((element) async {
print("removeLocalTracks:$element");
//await _localStream.removeTrack(element);// remove this line 
await element.stop();
});
`

**Comment by paulhobbel** [comment]
A simple `_localStream.dispose()` would've done the same
