### ISSUE TITLE
How I can get Internal audio/ system audio with screen share? 

### ISSUE THREAD

**Issue by 4015taimoor** [flutter-webrtc/flutter-webrtc#529]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Platform information**

* **Flutter version**: 
* **Plugin version**:
* **OS**: 
* **OS version**:

**Comment by 488taimoor** [comment]
@cloudwebrtc any solution please?

**Comment by entrehuihui** [comment]
> @cloudwebrtc any solution please?



> **Describe the bug**
> 
> **To Reproduce**
> 
> **Expected behavior**
> 
> **Platform information**
> 
> * **Flutter version**:
> * **Plugin version**:
> * **OS**:
> * **OS version**:

Have you found a solution? I have a screen sharing software, and I want to share the voice of my phone when I share the screen
