### ISSUE TITLE
How to switch the video stream of the camera directly to the video stream of the replaykit without re negotiation

### ISSUE THREAD

**Issue by huoda1237** [flutter-webrtc/flutter-webrtc#533]
In the development of IOS, how to switch the video stream of the camera directly to the video stream of the replaykit without re negotiation

**Comment by cabdirashiid-developer** [comment]
What's the replaykit?

**Comment by cloudwebrtc** [comment]
I don’t think it is currently possible to switch between Camera and ReplayKit directly, because they are two different VideoSourceTracks, so you can only switch using `RTPsender.replaceTrack`, and use re-negotiation.

**Comment by huoda1237** [comment]
> I don’t think it is currently possible to switch between Camera and ReplayKit directly, because they are two different VideoSourceTracks, so you can only switch using `RTPsender.replaceTrack`, and use re-negotiation.
got it

**Comment by huoda1237** [comment]
> I don’t think it is currently possible to switch between Camera and ReplayKit directly, because they are two different VideoSourceTracks, so you can only switch using `RTPsender.replaceTrack`, and use re-negotiation.

I create  an  new RTCPeerconnection in Boradcast Upload Extension, it can send video very well,but can not send audio,how can i solve this problem ?thank you
