### ISSUE TITLE
App size

### ISSUE THREAD

**Issue by sm2017** [flutter-webrtc/flutter-webrtc#535]
After adding `flutter-webrtc` to my application its size increases from 27MB to 39MB, The library added 12MB!!
Is there any lite version of `flutter-webrtc`, Why its so large

I am using the following command to build apk
```
flutter build apk --obfuscate --split-debug-info=./build/info
```

**Comment by cloudwebrtc** [comment]
This is because the native .so size of libwebrtc is so large.
You can rename your_app.apk to .zip, unzip it and see if it contains .so of multiple architectures, I think it will include x86, armv7, arm64. three so by default
```
lib/x86/libjingle_peerconnection_so.so
lib/armeabi-v7a/libjingle_peerconnection_so.so
lib/arm64-v8a/libjingle_peerconnection_so.so
```

**Comment by laxkarparas1** [comment]
After adding flutter-webrtc to my application its size increases from 27MB to 97MB , Why its so large

**Comment by misterneo** [comment]
Has anyone found a way to reduce the app size?

**Comment by sm2017** [comment]
@ycherniavskyi Yes I know
I just asking to be sure there is no lite version of the library
It's awesome and good enough

**Comment by RtgrV** [comment]
Can't we re-open this issue? 
Although there is no lite-version, it would be great if we had any choice of features in the form of packages. It's a big framework with many functionalities where many developers only need a subset improving on app size.

**Comment by md-rifatkhan** [comment]
sama here

**Comment by md-rifatkhan** [comment]
I've fixed by `flutter build apk --split-per-abi` 80 MB to 13MB

**Comment by pharidali** [comment]
`ndk {
    abiFilters "armeabi-v7a", "arm64-v8a"
}`

Add this in build.gradle inside of app folder. 

When you add this apk wont run on emulator but it will run on real devices and when you add this lines of code, your app will be increase by around 10MB only.
