### ISSUE TITLE
RTCVideoRenderer & RTCPeerConnection reconnect mechanism!!!

### ISSUE THREAD

**Issue by chungquantin** [flutter-webrtc/flutter-webrtc#554]
Hi everyone, as I am developing a feature of **calling a random user**, I need to implement the cancel current video call and reconnect. However, I have tried to use this for the initialization
`initRenderer() {
    _localRenderer.initialize();
    _remoteRenderer.initialize();
  }`
And this for canceling the current video call
`void bye() {
    if (_localStream != null) {
      _localStream!.dispose();
      _localStream = null;
    }
    peerConnection.close();
  }`
For the first time calling, clients are both connected to another normally
![image](https://user-images.githubusercontent.com/56880684/117311064-1385a400-aeae-11eb-9caf-05d3399df1e7.png)

However, when I tried to reconnect with another user, the video screen is like this
![image](https://user-images.githubusercontent.com/56880684/117311250-3ca63480-aeae-11eb-9ccd-e9dec7975508.png)

**Comment by JimmieLoca** [comment]
@chungquantin How to solve this problem ?
