### ISSUE TITLE
[Q] How to build windows/third_party/libwebrtc/lib/libwebrtc.dll

### ISSUE THREAD

**Issue by kasru** [flutter-webrtc/flutter-webrtc#570]
Hi,

Q1. How to build this file?
https://github.com/flutter-webrtc/flutter-webrtc/blob/master/windows/third_party/libwebrtc/lib/libwebrtc.dll

Q2. Where can I see which version of WebRTC for this dll?

I'm looking for a build for Linux.

**Comment by cloudwebrtc** [comment]
@kasru 
Q1, Please refer to this repo
https://github.com/flutter-webrtc/libwebrtc
Q2, The current dll dependency is M72
