### ISSUE TITLE
How to close debugging info?

### ISSUE THREAD

**Issue by vjeson** [flutter-webrtc/flutter-webrtc#575]
When debugging,the webrtc lib print too many logs,How to close it?

I/org.webrtc.Logging(26300): EglRenderer: Duration: 4004 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.

**Comment by ruodeng** [comment]
same issue

**Comment by alejandrogiubel** [comment]
same here. Even after dispose the local stream

**Comment by pizazzsy** [comment]
same issue

**Comment by VictorUvarov** [comment]
@vjeson You fixed the issue?
