### ISSUE TITLE
How to select the audio output?

### ISSUE THREAD

**Issue by Appleprabh** [flutter-webrtc/flutter-webrtc#591]
While debugging the console selected speaker and not the earpiece. The connection was established successfully between two device the only thing I need is how to select the audio output device as earpiece.

So How can I change the output device. This is What I saw in console

```Device status: available=[], selected=NONE, user selected=NONE
D/RTCAudioManager(10254): setAudioDeviceInternal(device=SPEAKER_PHONE)
I/AudioManager(10254): In isSpeakerphoneOn(), calling application: com.example.flutter_voip_calling
D/RTCAudioManager(10254): New device status: available=[EARPIECE, SPEAKER_PHONE], selected=SPEAKER_PHONE
D/FlutterWebRTCPlugin(10254): onAudioManagerDevicesChanged: [EARPIECE, SPEAKER_PHONE], selected: SPEAKER_PHONE
```

**Comment by Appleprabh** [comment]
@cloudwebrtc Could you spare some time and help me please?

**Comment by hct-berkay** [comment]
@Appleprabh  Hello, good work. Can you explain how you solved the problem?
