### ISSUE TITLE
[Windows] Creating a videostream without audio track cause crash

### ISSUE THREAD

**Issue by Blancduman** [flutter-webrtc/flutter-webrtc#594]
**Describe the bug**
[Windows] Creating a videostream without audio track cause crash
**To Reproduce**
Creating a videostream without audio track cause crash
**Expected behavior**
No crash
**Platform information**
Windows

https://github.com/flutter-webrtc/flutter-webrtc/blob/master/lib/src/native/media_stream_impl.dart#L22

Add null check for arguments.

And looks like you forget to add `getLocalDescription` method for Windows

**Comment by Blancduman** [comment]
> Add null check for arguments.

[PR](https://github.com/flutter-webrtc/flutter-webrtc/pull/595)

**Comment by cloudwebrtc** [comment]
> And looks like you forget to add getLocalDescription method for Windows

Another contributor is upgrading libwebrtc for windows, and soon the Windows version will have full support (unified-plan)
https://github.com/wskfjtheqian/libwebrtc/commit/44b588f41bbce3017daab4d258f7e96f29484f18

**Comment by Blancduman** [comment]
Cool. Waiting for updates. : )

**Comment by Blancduman** [comment]
Btw, how to choose output device in which to output audio to?
![image](https://user-images.githubusercontent.com/36401723/121879129-2e510100-cd15-11eb-904e-a8f295d14972.png)
Like in picture above I have 2 audio output source.

**Comment by Blancduman** [comment]
And another question. About addTransivers. Does it actually work? Last time when I played with it.. It didn't work. So I had to use pc.addTrack instead.

**Comment by cloudwebrtc** [comment]
`addTransivers` is included in the unified plan api, so it is temporarily unavailable on windows.

**Comment by cloudwebrtc** [comment]
I am sure it works because I used this method in ion-flutter-sdk
https://github.com/pion/ion-sdk-flutter/blob/master/lib/src/stream.dart#L236

Can you show relevant code snippets?

**Comment by Blancduman** [comment]
Okay! THANK YOU : )
What about selecting output source? Can you share with some example or how to use it? Looks like you using some AudioManager inside
