### ISSUE TITLE
Stop logging after call

### ISSUE THREAD

**Issue by marcoberetta96** [flutter-webrtc/flutter-webrtc#598]
When I end a call, these lines of logs never end...

`I/org.webrtc.Logging(10708): EglRenderer: Duration: 4004 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: .0. Average render time: NA. Average swapBuffer time: NA.`

How can I stop them?
I think I'm already disposing all.
```

  @override
  void dispose() {
    _dataChannel.close();
    _localRenderer.dispose();
    _remoteRenderer.dispose();
    _localVideoRef.dispose();
    _remoteVideoRef?.dispose();
    _rtcPeerConnection.onIceCandidate = null;
    _rtcPeerConnection.onTrack = null;
    _rtcPeerConnection.close();
    _rtcPeerConnection.dispose();
    super.dispose();
  }
```

I'm using  flutter_webrtc 0.6.4  and I'm on android.

Thanks!

**Comment by mrhaydari** [comment]
u must set null to `srcObject`  in  `RTCVideoRenderer` before dispose

**Comment by marcoberetta96** [comment]
Solved, thank you @mrhaydari
