### ISSUE TITLE
How to change the audio output from speaker_phone to earpiece speaker?

### ISSUE THREAD

**Issue by Appleprabh** [flutter-webrtc/flutter-webrtc#602]
So, While running the code the by default it automatically selects the audio output as `SPEAKER_PHONE` for android device. But I need the output in `Earpiece`. How can I do that?

@cloudwebrtc  Please help me with this! Please!

debug Console message

```
D/RTCAudioManager(11101): Device status: available=[], selected=NONE, user selected=NONE
D/RTCAudioManager(11101): setAudioDeviceInternal(device=SPEAKER_PHONE)
D/RTCAudioManager(11101): New device status: available=[SPEAKER_PHONE, EARPIECE], selected=SPEAKER_PHONE
D/FlutterWebRTCPlugin(11101): onAudioManagerDevicesChanged: [SPEAKER_PHONE, EARPIECE], selected: SPEAKER_PHONE
```

**Comment by marcoberetta96** [comment]
How did you get this solved?

**Comment by makstheimba** [comment]
@Appleprabh @marcoberetta96 I solved it like this - https://github.com/makstheimba/flutter-webrtc/commit/7841fc3e6238c63ce99b2ade2a76f3dd98d9e71e

I changed default audio device and added a method handler which notifies dart code about changes to audio devices. This was enough for us to properly manage audio routing

**Comment by marcoberetta96** [comment]
Thank you @makstheimba 

@cloudwebrtc is there any chance this will be added to this package?

**Comment by bella0x0** [comment]
can you share the code i am not able to change audio device
