### ISSUE TITLE
Can we use same EGL Context used while decoding the stream to render it.

### ISSUE THREAD

**Issue by MohamedRisaldarTA** [flutter-webrtc/flutter-webrtc#618]
I am implementing an app to play 30 cameras at a time using flutter_webrtc wrapper to get webRTC implemented.
and is perfectly fine on iOS.
and on PWA we have implemented the same using google webRTC and also works well without any issues in browser on the same android phone.
But in Android, 
Once app starts receiving streams webRTC starts creating EGL contexts to decode it.
and to play it we need to call RTCVideoRender.initialize();
here while invoking this method, it also creates new EGL context. 
and once available EGL contexts are gets exhausted, app is crashing (Its working for 15 cameras now, found that maximum 32 EGL contexts can be created in my device (Poco M3, Android 10, 6GB RAM, Snapdragon 662)).

If we can use the same EGL context created while decoding to render the video too, I can implement 30 cameras.

**Comment by cloudwebrtc** [comment]
fixed in 0.9.5
