### ISSUE TITLE
The ability to mute the microphone on iOS does not work

### ISSUE THREAD

**Issue by Coloud1** [flutter-webrtc/flutter-webrtc#624]
**Describe the bug**
The transmitted sound cannot be muted. The demo version of WebRTC flutter was used, the connection took place ios with Android. When the method is called in the Signaling muteMic class on android, the sound is not transmitted, on iOS it is always transmitted
**To Reproduce**
    _localStream!.getAudioTracks()[0].enabled = false;
or 
    _localStream!.getAudioTracks()[0].setMicrophoneMute(false);
just use a method or setter

**Expected behavior**
It works well on android, does not react to ayos in any way. Methods receive their payload with bool or trackId, but audio is transmitted
**Platform information**
Android - everything works well
iOS - does not work
* **Flutter version**:  [✓] Flutter (Channel stable, 2.0.5, on macOS 11.1 20C69 darwin-x64, locale ru-UA)
    • Flutter version 2.0.5 at /Users/coloud/development/flutter
    • Framework revision adc687823a (3 months ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

* **Plugin version**:  flutter_webrtc: ^0.6.5
* **OS**:  iOS 14.5.1
* **OS version**: macOS 11.1

**Comment by carman247** [comment]
Hi,

I am facing a similar problem. 

I think muting the local stream is working, however attempting to mute the remote stream on iOS doesn't work unless I call `await mediaStream.getMediaTracks` (which is now deprecated) before attempting to disable/mute the audio track.

I can confirm this method works on 0.6.3 and up e.g.

```
  Future<void> _getMediaTracksForStream(MediaStream mediaStream) async {
    // ignore: deprecated_member_use
    await mediaStream.getMediaTracks();
  }

  void _toggleRemoteAudioTrack(bool toggle) async {
    if (_remoteStream == null) {
      log('>>> returning - remote stream null');
      return;
    }
    log('>>> toggling remote audio: $toggle');
    await _getMediaTracksForStream(_remoteStream);
    _remoteStream.getAudioTracks().forEach((audioTrack) {
      log('>>> remote audio track: $audioTrack');
      audioTrack.enabled = toggle;
    });
  }
  ```

Hope that helps you and anyone else while devs fix this problem

**Comment by UCetinkaya94** [comment]
> Hi,
> 
> I am facing a similar problem.
> 
> I think muting the local stream is working, however attempting to mute the remote stream on iOS doesn't work unless I call `await mediaStream.getMediaTracks` (which is now deprecated) before attempting to disable/mute the audio track.
> 
> I can confirm this method works on 0.6.3 and up e.g.
> 
> ```
>   Future<void> _getMediaTracksForStream(MediaStream mediaStream) async {
>     // ignore: deprecated_member_use
>     await mediaStream.getMediaTracks();
>   }
> 
>   void _toggleRemoteAudioTrack(bool toggle) async {
>     if (_remoteStream == null) {
>       log('>>> returning - remote stream null');
>       return;
>     }
>     log('>>> toggling remote audio: $toggle');
>     await _getMediaTracksForStream(_remoteStream);
>     _remoteStream.getAudioTracks().forEach((audioTrack) {
>       log('>>> remote audio track: $audioTrack');
>       audioTrack.enabled = toggle;
>     });
>   }
> ```
> 
> Hope that helps you and anyone else while devs fix this problem

Thank you so much, it worked! I can't believe something this basic and essential needs a hacky workaround like this...
