### ISSUE TITLE
Audio not working during the screenshare

### ISSUE THREAD

**Issue by naveenbharadwaj19** [flutter-webrtc/flutter-webrtc#674]
```
var displayMediaStream = await navigator.mediaDevices
        .getDisplayMedia({'video': true, 'audio': true});
```
I want to screenshare from one android to other android .Regular video call is working fine.Can someone help me how to add audio during screenshare ?

**Comment by anhlevfx** [comment]
Hi @naveenbharadwaj19 , did you find a way to embed audio with video screen sharing?

**Comment by naveenbharadwaj19** [comment]
@anhlevfx Yes. 
Get audio track from usermedia and add it to the local stream.After that create a peer connection
```
var displayMediaStream = await navigator.mediaDevices.getDisplayMedia({});
    localStream = displayMediaStream;
    var audioStream = await navigator.mediaDevices
        .getUserMedia({"video": false, "audio": true});
    var audioTrack = audioStream.getAudioTracks()[0];
    await localStream!.addTrack(audioTrack);
```

**Comment by anhlevfx** [comment]
@naveenbharadwaj19 Thank you for your solution.
I resolved problem by modified some files of the library, added code to get audio track combine with video track (screen capture). Your solution doesn't need custom library, so it's better. I'll try it.

**Comment by anhlevfx** [comment]
Hi @naveenbharadwaj19 did you facing problem on apple device about screen capture not working after the first time successfully stop?

**Comment by jayaram9877** [comment]
I am facing the same issue. The audio track count is 0 on getDisplayMedia(). How did you manage to solve this? Thanks in advance.

**Comment by anhlevfx** [comment]
Can you share your implement code to get audio stream? Are you sure permission microphone is granted?

**Comment by jayaram9877** [comment]
```
var displayMediaStream = await navigator.mediaDevices
        .getDisplayMedia({'video': true, 'audio': true});
```

I am able to share the microphone audio but I want to share internal audio. are you able to share internal device audio?

**Comment by tce-darshan** [comment]
Hi @jayaram9877 
Any luck with sharing internal device audio? Did you find a way? 
Thanks in advance:)

**Comment by HensiStackApp** [comment]
hello @naveenbharadwaj19 i have use same code as you show for screen sharing but my side app crash
