### ISSUE TITLE
Resources are not disposed

### ISSUE THREAD

**Issue by alejandrogiubel** [flutter-webrtc/flutter-webrtc#680]
Hi I have this project [https://github.com/alejandrogiubel/streaming_video_openvidu_testing](url) and when I call `_hangUp ()` method (in `CallSampleWidget`) and navigate back the dispose method call `_signaling?.close();` and this close method (inside `Signaling` class )should close all resources like streams, and notify to others clients in `onParticipantsRemove ` callback. This works when there is only one participant in the sessions but when there are two or more participants this method is not triggered (`onParticipantsRemove `).

Also it works (with any participant number) when I kill the app.

Logs show this when I call `_hangUp ()` method.

`I/CameraManagerGlobal(30868): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client com.samsung.adaptivebrightnessgo API Level 2
I/CameraManagerGlobal(30868): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_OPEN for client com.samsung.adaptivebrightnessgo API Level 2
I/CameraManagerGlobal(30868): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_ACTIVE for client com.samsung.adaptivebrightnessgo API Level 2
I/CameraManagerGlobal(30868): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_IDLE for client com.samsung.adaptivebrightnessgo API Level 2
I/CameraManagerGlobal(30868): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client com.samsung.adaptivebrightnessgo API Level 2
I/CameraManagerGlobal(30868): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_OPEN for client com.samsung.adaptivebrightnessgo API Level 2
I/CameraManagerGlobal(30868): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_ACTIVE for client com.samsung.adaptivebrightnessgo API Level 2
I/CameraManagerGlobal(30868): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_IDLE for client com.samsung.adaptivebrightnessgo API Level 2
I/CameraManagerGlobal(30868): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client com.samsung.adaptivebrightnessgo API Level 2`

**Comment by alejandrogiubel** [comment]
Never mind.  I solved it.  Two parentheses were missing

**Comment by nandiniramaswamy14** [comment]
How did you solve it , even I'm getting same error. How to overcome from this issue?

**Comment by nandiniramaswamy14** [comment]
> Hi @nandiniramaswamy14. In my implementation I forget tow parentheses and this made a function never execute (maybe passed the function like a parameter and not call it) or something else that I never found a correct response about that. But debugging I found that thos tow parentheses was lost. I correct it and works. Sorry if is not enougth, may be post some code help to find a workaround.

I don't have function call issue and any other. Thanks for your valuable replay.
