### ISSUE TITLE
Failed to Set Remote Description Answer SDP : Format Exception thrown at the time of setting

### ISSUE THREAD

**Issue by piyushChopra20** [flutter-webrtc/flutter-webrtc#689]
### SetRemoteDescription Format Exception ERROR
Format Exception is being thrown when i try to set the SDP in remote Description.
I m using Stomp server to receive and send the sdp offer and answer with ice candidates with the state changing.
When i Try to put the Answer SDP in the remote description an exception is thrown of FORMAT EXCEPTION.
FormatException: Unhandled_Exception at char [1] v=0
Can anyone help me with this?

![Screenshot 2021-09-17 at 7 05 16 PM](https://user-images.githubusercontent.com/87702344/133884729-0bddfb27-3d23-4b59-8150-d86ee226f44e.png)

**SDP Format**
      v=0
      o=- 4097894098692939566 2 IN IP4 127.0.0.1
      s=-
      t=0 0
      a=group:BUNDLE audio video
      a=msid-semantic: WMS RcLX24Vdst6RnSMPpATGC1cTcYUBiPXtqe8e
      m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
      c=IN IP4 0.0.0.0
      a=rtcp:9 IN IP4 0.0.0.0
      a=ice-ufrag:jyFG
      a=ice-pwd:CqnEAhDaxfGBWHYo59XOcUsJ
      a=ice-options:trickle
      a=fingerprint:sha-256 D9:62:D9:10:8D:53:D8:71:8E:99:9E:63:BE:CE:00:34:E1:A0:BB:1C:35:6A:0E:86:D0:16:76:7C:DC:EF:D7:FC
      a=setup:active
      a=mid:audio
      a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
      a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
      a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
      a=sendrecv
      a=rtcp-mux
      a=rtpmap:111 opus/48000/2
      a=rtcp-fb:111 transport-cc
      a=fmtp:111 minptime=10;useinbandfec=1
      a=rtpmap:103 ISAC/16000
      a=rtpmap:104 ISAC/32000
      a=rtpmap:9 G722/8000
      a=rtpmap:0 PCMU/8000
      a=rtpmap:8 PCMA/8000
      a=rtpmap:106 CN/32000
      a=rtpmap:105 CN/16000
      a=rtpmap:13 CN/8000
      a=rtpmap:110 telephone-event/48000
      a=rtpmap:112 telephone-event/32000
      a=rtpmap:113 telephone-event/16000
      a=rtpmap:126 telephone-event/8000
      a=ssrc:284173004 cname:VlmCOrp2QCTYUjD5
      a=ssrc:284173004 msid:RcLX24Vdst6RnSMPpATGC1cTcYUBiPXtqe8e 4f57a874-c14e-4276-9715-218ad050a479
      a=ssrc:284173004 mslabel:RcLX24Vdst6RnSMPpATGC1cTcYUBiPXtqe8e
      a=ssrc:284173004 label:4f57a874-c14e-4276-9715-218ad050a479
      m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 123 125
      c=IN IP4 0.0.0.0
      a=rtcp:9 IN IP4 0.0.0.0
      a=ice-ufrag:jyFG
      a=ice-pwd:CqnEAhDaxfGBWHYo59XOcUsJ
      a=ice-options:trickle
      a=fingerprint:sha-256 D9:62:D9:10:8D:53:D8:71:8E:99:9E:63:BE:CE:00:34:E1:A0:BB:1C:35:6A:0E:86:D0:16:76:7C:DC:EF:D7:FC
      a=setup:active
      a=mid:video
      a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
      a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
      a=extmap:13 urn:3gpp:video-orientation
      a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
      a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
      a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
      a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
      a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
      a=sendrecv
      a=rtcp-mux
      a=rtcp-rsize
      a=rtpmap:96 VP8/90000
      a=rtcp-fb:96 goog-remb
      a=rtcp-fb:96 transport-cc
      a=rtcp-fb:96 ccm fir
      a=rtcp-fb:96 nack
      a=rtcp-fb:96 nack pli
      a=rtpmap:97 rtx/90000
      a=fmtp:97 apt=96
      a=rtpmap:98 VP9/90000
      a=rtcp-fb:98 goog-remb
      a=rtcp-fb:98 transport-cc
      a=rtcp-fb:98 ccm fir
      a=rtcp-fb:98 nack
      a=rtcp-fb:98 nack pli
      a=fmtp:98 profile-id=0
      a=rtpmap:99 rtx/90000
      a=fmtp:99 apt=98
      a=rtpmap:100 H264/90000
      a=rtcp-fb:100 goog-remb
      a=rtcp-fb:100 transport-cc
      a=rtcp-fb:100 ccm fir
      a=rtcp-fb:100 nack
      a=rtcp-fb:100 nack pli
      a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
      a=rtpmap:101 rtx/90000
      a=fmtp:101 apt=100
      a=rtpmap:127 red/90000
      a=rtpmap:123 rtx/90000
      a=fmtp:123 apt=127
      a=rtpmap:125 ulpfec/90000
      a=ssrc-group:FID 1640214744 1797724607
      a=ssrc:1640214744 cname:VlmCOrp2QCTYUjD5
      a=ssrc:1640214744 msid:RcLX24Vdst6RnSMPpATGC1cTcYUBiPXtqe8e 311ff807-a0a5-467b-979f-81348698fd3c
      a=ssrc:1640214744 mslabel:RcLX24Vdst6RnSMPpATGC1cTcYUBiPXtqe8e
      a=ssrc:1640214744 label:311ff807-a0a5-467b-979f-81348698fd3c
      a=ssrc:1797724607 cname:VlmCOrp2QCTYUjD5
      a=ssrc:1797724607 msid:RcLX24Vdst6RnSMPpATGC1cTcYUBiPXtqe8e 311ff807-a0a5-467b-979f-81348698fd3c
      a=ssrc:1797724607 mslabel:RcLX24Vdst6RnSMPpATGC1cTcYUBiPXtqe8e
      a=ssrc:1797724607 label:311ff807-a0a5-467b-979f-81348698fd3c

________________________________
* **Flutter version**: 2.5.0
* **Plugin version**: 0.6.7
* **OS**: Android , Web
* **OS version**: 10, Chrome

**Comment by cloudwebrtc** [comment]
The exception is raised by JsonDecoder.convert, not SetRemoteDescription.

**Comment by piyushChopra20** [comment]
yes, i can see it now because i m already receiving the sdp and candidate value in string i guess dont have to parse it again. or   there can be any other approach cuz in flutter webrtc i m kinda new.

**Comment by piyushChopra20** [comment]
After fixing the jsondecoder issue i m getting this error on this (how can i fix this)
### **Code**
await _peerConnection.setRemoteDescription(description);
### **Error**
Unable to RTCPeerConnection::setRemoteDescription: peerConnectionSetRemoteDescription(): WEBRTC_SET_REMOTE_DESCRIPTION_ERROR: peerConnection is null

![Screenshot 2021-09-20 at 11 09 53 AM](https://user-images.githubusercontent.com/87702344/133960861-91cedf56-dcfa-4ac2-97e0-35536ff948ed.png)

**Comment by nsanchezpc** [comment]
Hi, how did you fix this @piyushChopra20 ?

Thanks!

> After fixing the jsondecoder issue i m getting this error on this (how can i fix this)
> 
> ### **Code**
> await _peerConnection.setRemoteDescription(description);
> 
> ### **Error**
> Unable to RTCPeerConnection::setRemoteDescription: peerConnectionSetRemoteDescription(): WEBRTC_SET_REMOTE_DESCRIPTION_ERROR: peerConnection is null
> 
> ![Screenshot 2021-09-20 at 11 09 53 AM](https://user-images.githubusercontent.com/87702344/133960861-91cedf56-dcfa-4ac2-97e0-35536ff948ed.png)
