### ISSUE TITLE
Split flutter-webrtc pacakge to interface/native/web

### ISSUE THREAD

**Issue by cloudwebrtc** [flutter-webrtc/flutter-webrtc#692]
If we split `flutter_webrtc` into three packages, we will be able to support `flutter native`, `flutter web`, and `dart web` at the same time.

`flutter_webrtc_platform_interface` (pure dart package)
`flutter_webrtc` (flutter package)
`flutter_webrtc_web` (pure dart package)

Just like `video_player`
https://github.com/flutter/plugins/tree/master/packages/video_player

**Comment by wer-mathurin** [comment]
@cloudwebrtc :  Look also at this new package, this only define the WEBRTC interface!
Seems to be maintain by: https://flutter-webrtc.org/
https://pub.dev/packages/webrtc_interface

This can be the base if this is enough complete!

Also splitting Android, iOS, Windows, Mac.
This will make this package easier to maintain.

**Comment by cloudwebrtc** [comment]
@wer-mathurin Yeah, I am trying to separate packages of different platforms.

and the interface repo is here.
https://github.com/flutter-webrtc/webrtc-interface
