### ISSUE TITLE
Need listener for didFirstFrameRendered event

### ISSUE THREAD

**Issue by MohamedRisaldarTA** [flutter-webrtc/flutter-webrtc#721]
**Is your feature request related to a problem? Please describe.**
after setting srcObject to RTCVideoRenderer, it takes a small amount of time to get video rendered, So need a way to know when the video started playing after setting srcObject.

**Describe the solution you'd like**

I think implementing didFirstFrameRendered will provide an event on video starts playing.

Copying lines 64 to 82 from /.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.6.10/lib/src/native/rtc_video_renderer_impl.dart

```
void eventListener(dynamic event) {
    final Map<dynamic, dynamic> map = event;
    switch (map['event']) {
      case 'didTextureChangeRotation':
        value =
            value.copyWith(rotation: map['rotation'], renderVideo: renderVideo);
        onResize?.call();
        break;
      case 'didTextureChangeVideoSize':
        value = value.copyWith(
            width: 0.0 + map['width'],
            height: 0.0 + map['height'],
            renderVideo: renderVideo);
        onResize?.call();
        break;
      case 'didFirstFrameRendered':
        break;
    }
  }
```

**Comment by cloudwebrtc** [comment]
Actually didFirstFrameRendered can be triggered, but I would rather implement it as [MediaStreamTrack.onmute](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/onmute)/[onunmute](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/onunmute).

**Comment by MohamedRisaldarTA** [comment]
The listener is there and is working fine.
Closing this feature request as completed.
