### ISSUE TITLE
ScreenSharing usually fail on iPhone and iPad (com.apple.ReplayKit.RPRecordingErrorDomain Code=-5833)

### ISSUE THREAD

**Issue by anhlevfx** [flutter-webrtc/flutter-webrtc#749]
**Describe the bug**

[ERROR] -[RPScreenRecorder startCaptureWithHandler:completionHandler:]_block_invoke_2:478 failed to start due to error: Error Domain=com.apple.ReplayKit.RPRecordingErrorDomain Code=-5833 "Failed to start due to audio/video capture failure" UserInfo={NSLocalizedDescription=Failed to start due to audio/video capture failure}

**To Reproduce**

The first time attempt share screen will have a permission popup, press 'Allow record', after few seconds or minutes press end call.

From second attempt from iphone/ipad to iphone/ipad/android without restart application. Always happen in iPad.

**Expected behavior**

Screen sharing run smoothly like first attempt.

**Platform information**

* **Flutter version**: 2.5.3
* **Plugin version**: 0.6.8
* **OS**: iOS
* **OS version**: 14.1, 15

**Comment by anhlevfx** [comment]
Close issue. Because I mixed video track and audio track when create screen sharing stream, so on iOS you must stop video track (screen capture default no audio) before stop audio track (track added after getUserMedia audio only) when hangup call.

**Comment by leixiang1986** [comment]
I have the same issue, I can not fix it. How can I do to fix it? Can you tell me the detail about it?

**Comment by AllocAndInit** [comment]
> Close issue. Because I mixed video track and audio track when create screen sharing stream, so on iOS you must stop video track (screen capture default no audio) before stop audio track (track added after getUserMedia audio only) when hangup call.

what do you  mean by  mixing  video track and audio track when create screen sharing stream? can you explain it by detail? And what is the relationship with the  iOS you must stop video track (screen capture default no audio) before stop audio track (track added after getUserMedia audio only) when hangup call ?

**Comment by AllocAndInit** [comment]
> I have the same issue, I can not fix it. How can I do to fix it? Can you tell me the detail about it?

how do you meet the  issue? can I reproduce it ?

**Comment by anhlevfx** [comment]
@AllocAndInit @leixiang1986 After close this issue, I found that my solution not completely resolve problem. Sometimes, Ipad devices still randomly crash when share screen with log `Failed to start due to audio/video capture failure`. I think the root cause is ReplayKit.
To share screen include audio from mic of the device. I create a stream without audio track, only a video track of screen capture, by use function getDisplayMedia(). After that, use function getUserMedia(audio: true, video: false) to create another stream only have an audio track. Extract tracks and mix both of them to one stream by addTrack() function.

**Comment by anhlevfx** [comment]
> 
attempt
In my case, I start share screen has audio track, the first attempt will be success all times. But, the second will fail. Must restart application again.

**Comment by anhlevfx** [comment]
> > I have the same issue, I can not fix it. How can I do to fix it? Can you tell me the detail about it?
> 
> how do you meet the issue? can I reproduce it ?

In my case, I start share screen has audio track, the first attempt will be success all times. But, the second will fail. Must restart application again.

**Comment by AllocAndInit** [comment]
> @AllocAndInit @leixiang1986 After close this issue, I found that my solution not completely resolve problem. Although the issue not happen like before but sometimes, Ipad devices still randomly crash when share screen with log `Failed to start due to audio/video capture failure`. I think the root cause is ReplayKit.
> 
> To share screen include audio from mic of the device. I create a stream without audio track, only a video track of screen capture, by use function getDisplayMedia(). After that, use function getUserMedia(audio: true, video: false) to create another stream only have an audio track. Extract tracks and mix both of them to one stream by addTrack() function.
> 
> When stop stream, I stop video track before audio track.

@anhlevfx I have  made the same operation as you said, extract tracks and mix both of them to one stream, but i could not reproduce the issue finally, so i think it may  a system or device problem, even though i did not stop the both audio and video tracks, here is my code 

![image](https://user-images.githubusercontent.com/19301846/186802115-a6281f4d-5040-409f-8277-970da98f0a1d.png)

![image](https://user-images.githubusercontent.com/19301846/186802074-469b58ff-57a9-4998-acd1-dd4e61cdcfe3.png)

**Comment by AllocAndInit** [comment]
> I have the same issue, I can not fix it. How can I do to fix it? Can you tell me the detail about it?

@leixiang1986 how do you meet the issue? can I reproduce it ? and what is your device and system version?

**Comment by AllocAndInit** [comment]
> @AllocAndInit @leixiang1986 After close this issue, I found that my solution not completely resolve problem. Although the issue not happen like before but sometimes, Ipad devices still randomly crash when share screen with log `Failed to start due to audio/video capture failure`. I think the root cause is ReplayKit.
> 
> To share screen include audio from mic of the device. I create a stream without audio track, only a video track of screen capture, by use function getDisplayMedia(). After that, use function getUserMedia(audio: true, video: false) to create another stream only have an audio track. Extract tracks and mix both of them to one stream by addTrack() function.
> 
> When stop stream, I stop video track before audio track.

@anhlevfx since i found  stop video track and  audio track , just like the code below 

![image](https://user-images.githubusercontent.com/19301846/186811107-eee9cc8f-9d14-453d-86b6-298734fb1fe6.png)

so i guess may be there is nothing to do with the order between stop video track and audio track

**Comment by 0xDarker** [comment]
> Close issue. Because I mixed video track and audio track when create screen sharing stream, so on iOS you must stop video track (screen capture default no audio) before stop audio track (track added after getUserMedia audio only) when hangup call.

I'm facing the same issue now, any idea to fix it？
