### ISSUE TITLE
Build to push to TestFlight

### ISSUE THREAD

**Issue by nambui2000k** [flutter-webrtc/flutter-webrtc#751]
**Describe the bug**
When I Build Archive, I has error the same attachment image.
You can help me build to push to TestFlight.
**To Reproduce**

<img width="1246" alt="Screen Shot 2021-11-01 at 09 14 20" src="https://user-images.githubusercontent.com/49670327/139612537-dd3d6d3b-a668-4685-ab10-3b7b780db421.png">
**Expected behavior**

**Platform information**

* **Flutter version**: 
* **Plugin version**:
* **OS**: 
* **OS version**:

**Comment by ycherniavskyi** [comment]
Before creating the issue I recommend you to browse/find in already created ones - #713 (and there are more about this error).

**Comment by nambui2000k** [comment]
> Before creating the issue I recommend you to browse/find in already created ones - #713 (and there are more about this error) 😉.

Thanks you so much!
