### ISSUE TITLE
Crash in v0.7.1

### ISSUE THREAD

**Issue by sm2017** [flutter-webrtc/flutter-webrtc#757]
I have the following crash in video calls after upgrading from `0.6.10+hotfix.1` to `0.7.1`

```
W/System.err( 9262): java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: Not implemented.
W/System.err( 9262): 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
W/System.err( 9262): 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
W/System.err( 9262): 	at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper.initEncode(SimulcastVideoEncoderFactoryWrapper.kt:109)
W/System.err( 9262): Caused by: java.lang.UnsupportedOperationException: Not implemented.
W/System.err( 9262): 	at org.webrtc.WrappedNativeVideoEncoder.initEncode(WrappedNativeVideoEncoder.java:22)
W/System.err( 9262): 	at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper$initEncode$future$1.call(SimulcastVideoEncoderFactoryWrapper.kt:107)
W/System.err( 9262): 	at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper$initEncode$future$1.call(SimulcastVideoEncoderFactoryWrapper.kt:83)
W/System.err( 9262): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err( 9262): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err( 9262): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err( 9262): 	at java.lang.Thread.run(Thread.java:923)
E/rtc     ( 9262): #
E/rtc     ( 9262): # Fatal error in: gen/sdk/android/generated_metrics_jni/../../../../../../sdk/android/src/jni/jni_generator_helper.h, line 94
E/rtc     ( 9262): # last system error: 0
E/rtc     ( 9262): # Check failed: !env->ExceptionCheck()
E/rtc     ( 9262): # 
```

**Comment by liemfs** [comment]
> I have the following crash in video calls after upgrading from `0.6.10+hotfix.1` to `0.7.1`
> 
> ```
> W/System.err( 9262): java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: Not implemented.
> W/System.err( 9262): 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
> W/System.err( 9262): 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
> W/System.err( 9262): 	at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper.initEncode(SimulcastVideoEncoderFactoryWrapper.kt:109)
> W/System.err( 9262): Caused by: java.lang.UnsupportedOperationException: Not implemented.
> W/System.err( 9262): 	at org.webrtc.WrappedNativeVideoEncoder.initEncode(WrappedNativeVideoEncoder.java:22)
> W/System.err( 9262): 	at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper$initEncode$future$1.call(SimulcastVideoEncoderFactoryWrapper.kt:107)
> W/System.err( 9262): 	at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper$initEncode$future$1.call(SimulcastVideoEncoderFactoryWrapper.kt:83)
> W/System.err( 9262): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> W/System.err( 9262): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> W/System.err( 9262): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> W/System.err( 9262): 	at java.lang.Thread.run(Thread.java:923)
> E/rtc     ( 9262): #
> E/rtc     ( 9262): # Fatal error in: gen/sdk/android/generated_metrics_jni/../../../../../../sdk/android/src/jni/jni_generator_helper.h, line 94
> E/rtc     ( 9262): # last system error: 0
> E/rtc     ( 9262): # Check failed: !env->ExceptionCheck()
> E/rtc     ( 9262): # 
> ```

I'm having the same problem. Crash on an exact error like you

**Comment by cloudwebrtc** [comment]
Hey @sm2017 and @liemfs,  Can you try to add these codes to your test program? If it can be fixed, I will release the hotfix version.
https://github.com/flutter-webrtc/flutter-webrtc/pull/746/files#diff-a6a4704a4c3debd7fe827e1fc563a49ef74e9bec9916fb57daaecb12e5b52438R177-R179

**Comment by sm2017** [comment]
@cloudwebrtc  I edit `SimulcastVideoEncoderFactoryWrapper.kt` and add the following part

```java
if (encoder is WrappedNativeVideoEncoder) {
   return null
}
```

I see that in the `android/build.gradle` in v0.7.1 `implementation 'com.github.webrtc-sdk:android:92.4515.03'` has newer version, So I don't change it, After making some video calls, I found that we have no crash but a problem!

I make a call from a client with `0.6.10+hotfix.1` to a client with `0.7.1` and vise versa, The remote stream of `0.7.1`  in the `0.6.10+hotfix.1` client was a black screen, there is no video data

**Comment by Muhammad-Jamali** [comment]
> I have the following crash in video calls after upgrading from `0.6.10+hotfix.1` to `0.7.1`
> 
> ```
> W/System.err( 9262): java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: Not implemented.
> W/System.err( 9262): 	at java.util.concurrent.FutureTask.report(FutureTask.java:123)
> W/System.err( 9262): 	at java.util.concurrent.FutureTask.get(FutureTask.java:193)
> W/System.err( 9262): 	at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper.initEncode(SimulcastVideoEncoderFactoryWrapper.kt:109)
> W/System.err( 9262): Caused by: java.lang.UnsupportedOperationException: Not implemented.
> W/System.err( 9262): 	at org.webrtc.WrappedNativeVideoEncoder.initEncode(WrappedNativeVideoEncoder.java:22)
> W/System.err( 9262): 	at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper$initEncode$future$1.call(SimulcastVideoEncoderFactoryWrapper.kt:107)
> W/System.err( 9262): 	at com.cloudwebrtc.webrtc.SimulcastVideoEncoderFactoryWrapper$StreamEncoderWrapper$initEncode$future$1.call(SimulcastVideoEncoderFactoryWrapper.kt:83)
> W/System.err( 9262): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> W/System.err( 9262): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> W/System.err( 9262): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> W/System.err( 9262): 	at java.lang.Thread.run(Thread.java:923)
> E/rtc     ( 9262): #
> E/rtc     ( 9262): # Fatal error in: gen/sdk/android/generated_metrics_jni/../../../../../../sdk/android/src/jni/jni_generator_helper.h, line 94
> E/rtc     ( 9262): # last system error: 0
> E/rtc     ( 9262): # Check failed: !env->ExceptionCheck()
> E/rtc     ( 9262): # 
> ```

Having the exact same issue.

**Comment by mrcsh** [comment]
I have seen this as well.

**Comment by maralerdene** [comment]
Hello, in 7.2.1 this error also occured. I just download source code from github. Please, how to fix it.
