### ISSUE TITLE
Flutter iOS App Error

### ISSUE THREAD

**Issue by Diy2210** [flutter-webrtc/flutter-webrtc#773]
I got fatal error: 'WebRTC/WebRTC.h' file not found on flutter_webrtc 0.67.
0.7.1 version print error when try pod install.
How fix it?!

**Comment by cloudwebrtc** [comment]
hey @Diy2210, have you tried running `pod repo update` before compiling the flutter app?

**Comment by Diy2210** [comment]
Yup, its not work too...

**Comment by oseeshogun** [comment]
I also got the same error with flutter_webrtc 0.7.1

    While building module 'flutter_webrtc' imported from
    /Users/masolo/Documents/masolo/ios/Runner/GeneratedPluginRegistrant.m:70:
    In file included from <module-includes>:1:
    In file included from
    /Users/masolo/Documents/masolo/build/ios/Debug-iphonesimulator/flutter_webrtc/flutter_webrtc
    .framework/Headers/flutter_webrtc-umbrella.h:14:
    /Users/masolo/Documents/masolo/build/ios/Debug-iphonesimulator/flutter_webrtc/flutter_webrtc
    .framework/Headers/FlutterRPScreenRecorder.h:1:9: fatal error: 'WebRTC/WebRTC.h' file not
    found
    #import <WebRTC/WebRTC.h>
            ^~~~~~~~~~~~~~~~~
    1 error generated.
    /Users/masolo/Documents/masolo/ios/Runner/GeneratedPluginRegistrant.m:70:9: fatal error:
    could not build module 'flutter_webrtc'
    #import <flutter_webrtc/FlutterWebRTCPlugin.h>
     ~~~~~~~^
    2 errors generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel

**Comment by Diy2210** [comment]
> error

Error with flutter_webrtc 0.7.1 too

**Comment by mIwr** [comment]
I faced with the same problem on dart-sip-ua plugin, which based on webrtc (During building release archive).
I [excluded armv7 architectures for flutter-webrtc and WEBRTC-SDK pods (Build Settings - Architectures - set only arm64)](https://github.com/flutter-webrtc/flutter-webrtc/issues/713#issuecomment-939868285). After that I can build release archive

**Comment by ycherniavskyi** [comment]
It seems that the issue is resolved. Related Q&A discussion - #1026.
