### ISSUE TITLE
How to set "contentHint" attribute of video track?

### ISSUE THREAD

**Issue by Larry-Arun** [flutter-webrtc/flutter-webrtc#776]
If this MediaStreamTrack's kind attribute is "video", contentHint value can be set to "motion", "detail" or "text".
Normally I want to set it to "motion". When sharing the screen, I want to set it to "detail", which can save some network traffic, but in flutter-webrtc, I did not find a way to set the "contentHint" property. I hope someone can help me, where to set this attribute?
Thanks very much.
Here is the explanation of contentHint [https://w3c.github.io/mst-content-hint/](url)

**Comment by Larry-Arun** [comment]
I have solved the problem

**Comment by bigbigqiang** [comment]
> I have solved the problem
I have also encountered this problem. How did you solve it? Thanks very much.

**Comment by bigbigqiang** [comment]
> I have solved the problem


I have also encountered this problem. How did you solve it? Thanks very much.
