### ISSUE TITLE
Flutter 两端交换完 sdp 信息后，并未触发 ice 事件

### ISSUE THREAD

**Issue by iooc** [flutter-webrtc/flutter-webrtc#779]
发起方：
```
var offer = await pc.createOffer({
      'offerToReceiveAudio': true,
      'offerToReceiveVideo': true,
    });

    pc.setLocalDescription(offer);
    // 将请求信息发送给应答方
    hubConnection!.send('offerToPeer', args: [clientId, offer.sdp]);
```
```
var pc = peer.peerConnetion;
pc!.setRemoteDescription(RTCSessionDescription(answer, 'answer'));
```

**Comment by iooc** [comment]
写错了，应答方是
```
var offer = RTCSessionDescription(sdp, type);
await pc.setRemoteDescription(offer);
      
      // 创建应答
var answer = await pc.createAnswer();
await pc.setLocalDescription(answer);

this.sendAnswer(answer.sdp);

**Comment by cloudwebrtc** [comment]
你有调用 pc.addIceCandidate(candidate); 吗？

**Comment by iooc** [comment]
pc.onIceCandidate = (candidate) {
      print('发起候选交换请求');
      // 发送 ice 交换信息给客户端
      hubConnection!.send('iceToClient', args: [
        clientId,
        candidate.candidate,
        candidate.sdpMid,
        candidate.sdpMlineIndex
      ]);
    };
此事件未被触发，未能生成ICE

**Comment by cloudwebrtc** [comment]
发起方的完整过程:

var pc = peer.peerConnetion;
var offer = pc.createOffer();

//此方法触发oncandidate
pc.setLocalDescrption(offer);

//发送offer
// sig.send(offer);

pc!.setRemoteDescription(RTCSessionDescription(answer, 'answer'));`

**Comment by cloudwebrtc** [comment]
ice 收集是由setLocalDescrption 触发，主/被叫都是

**Comment by iooc** [comment]
发起方：
```
var offer = await pc.createOffer({
      'offerToReceiveAudio': true,
      'offerToReceiveVideo': true,
    });

    pc.setLocalDescription(offer);
    // 将请求信息发送给应答方
    hubConnection!.send('offerToPeer', args: [clientId, offer.sdp]);
```
参数似乎也正确，与NodeJS 通信也这么做的。

**Comment by iooc** [comment]
郁闷了，完全没有触发 ICE 的迹象

**Comment by iooc** [comment]
js 生成的offer 
v=0\r\no=- 8048626493533785641 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:M7V8\r\na=ice-pwd:ZMD7ET/YZ+K31vJmUXdYZe81\r\na=ice-options:trickle\r\na=fingerprint:sha-256 9B:CC:03:53:6A:4A:A1:BC:4A:1B:30:A7:9E:FE:24:7C:57:15:7B:32:F5:CD:4E:7F:7E:17:F1:0F:61:E7:09:73\r\na=setup:actpass\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=recvonly\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:102 ILBC/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 124 125\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:M7V8\r\na=ice-pwd:ZMD7ET/YZ+K31vJmUXdYZe81\r\na=ice-options:trickle\r\na=fingerprint:sha-256 9B:CC:03:53:6A:4A:A1:BC:4A:1B:30:A7:9E:FE:24:7C:57:15:7B:32:F5:CD:4E:7F:7E:17:F1:0F:61:E7:09:73\r\na=setup:actpass\r\na=mid:1\r\na=extmap:14 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:13 urn:3gpp:video-orientation\r\na=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07\r\na=extmap:9 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=recvonly\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=fmtp:98 profile-id=0\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:100 VP9/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=fmtp:100 profile-id=2\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:127 red/90000\r\na=rtpmap:124 rtx/90000\r\na=fmtp:124 apt=127\r\na=rtpmap:125 ulpfec/90000\r\n

flutter 生成的 offer
v=0\r\no=- 5570454269170679049 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS\r\n

似乎是 offer 信息不完整，如何才能生成较完整的 offer

**Comment by iooc** [comment]
谢谢，似乎找到原因了，flutter 上发起端似乎必须要有数据或者收发器才行。

**Comment by SELiOTe** [comment]
您好，我在 Flutter 集成 Kurento 中也遇到了类似问题，想咨询一下您，有偿 v -> fbf238559196da78

**Comment by iooc** [comment]
呵呵，作为水哥的我表示上一条就是答案😊

**Comment by PauwelsPieter** [comment]
Hi @iooc, I'm facing the same issue that the flutter offer is incomplete. Could you provide some more details on how you solved this? Making use of Google translate I couldn't figure out what exacly you did to resolve this issue...

Thanks in advance! :smile:

**Comment by iooc** [comment]
Try adding stream or track or transceiver before createOffer

**Comment by binvb** [comment]
> js 生成的offer v=0\r\no=- 8048626493533785641 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:M7V8\r\na=ice-pwd:ZMD7ET/YZ+K31vJmUXdYZe81\r\na=ice-options:trickle\r\na=fingerprint:sha-256 9B:CC:03:53:6A:4A:A1:BC:4A:1B:30:A7:9E:FE:24:7C:57:15:7B:32:F5:CD:4E:7F:7E:17:F1:0F:61:E7:09:73\r\na=setup:actpass\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 [http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:3](http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time%5Cr%5Cna=extmap:3) [http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:4](http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01%5Cr%5Cna=extmap:4) urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=recvonly\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:102 ILBC/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 124 125\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:M7V8\r\na=ice-pwd:ZMD7ET/YZ+K31vJmUXdYZe81\r\na=ice-options:trickle\r\na=fingerprint:sha-256 9B:CC:03:53:6A:4A:A1:BC:4A:1B:30:A7:9E:FE:24:7C:57:15:7B:32:F5:CD:4E:7F:7E:17:F1:0F:61:E7:09:73\r\na=setup:actpass\r\na=mid:1\r\na=extmap:14 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:2 [http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:13](http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time%5Cr%5Cna=extmap:13) urn:3gpp:video-orientation\r\na=extmap:3 [http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:12](http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01%5Cr%5Cna=extmap:12) [http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:11](http://www.webrtc.org/experiments/rtp-hdrext/playout-delay%5Cr%5Cna=extmap:11) [http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7](http://www.webrtc.org/experiments/rtp-hdrext/video-content-type%5Cr%5Cna=extmap:7) [http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8](http://www.webrtc.org/experiments/rtp-hdrext/video-timing%5Cr%5Cna=extmap:8) [http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07\r\na=extmap:9](http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07%5Cr%5Cna=extmap:9) [http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:4](http://www.webrtc.org/experiments/rtp-hdrext/color-space%5Cr%5Cna=extmap:4) urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=recvonly\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=fmtp:98 profile-id=0\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:100 VP9/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=fmtp:100 profile-id=2\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:127 red/90000\r\na=rtpmap:124 rtx/90000\r\na=fmtp:124 apt=127\r\na=rtpmap:125 ulpfec/90000\r\n
> 
> flutter 生成的 offer v=0\r\no=- 5570454269170679049 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS\r\n
> 
> 似乎是 offer 信息不完整，如何才能生成较完整的 offer

这是一个问题吧？为什么createoffer没有生成完整的sdp信息？
