### ISSUE TITLE
About libyuv

### ISSUE THREAD

**Issue by yangfanyu** [flutter-webrtc/flutter-webrtc#782]
https://github.com/flutter-webrtc/flutter-webrtc/issues/168

https://github.com/flutter-webrtc/flutter-webrtc/pull/188

conflict with

https://github.com/flutter-webrtc/flutter-webrtc-demo/issues/76

https://github.com/flutter-webrtc/flutter-webrtc-demo/issues/76#issuecomment-976444789

I am not familiar with ios, may be  change `#include "libyuv/xxx.h"` to `#include "Libyuv/xxx.h" (case sensitive)  in  libyuv library can resolved them?

**Comment by mrcsh** [comment]
I am seeing link errors with libyuv with an M1 mac which I know isn't 100% there yet, at least when compiling for the emulator.
I can build to an actual device and archive from the UI works but command line archive stopped working for some reason.
