### ISSUE TITLE
Add  `ended` event to MediaStreamTrack.

### ISSUE THREAD

**Issue by cloudwebrtc** [flutter-webrtc/flutter-webrtc#79]
When we connect to an SFU, peerconnection will increase or decrease the stream/track at any time. We need to know that those tracks are removed during renegotiation.

**Comment by rostopira** [comment]
Do this events trigger any callbacks in native SDK?
Is it the same as OnStreamAdded/OnStreamRemoved event?

**Comment by cloudwebrtc** [comment]
Used to listen to tracks, for example, there are two tracks (audio/video) in a stream, the user turns off the video or replaces a new video track, and the old track should trigger an ended event.

**Comment by cloudwebrtc** [comment]
It seems that iOS can find the corresponding event, but Android does not
https://chromium.googlesource.com/external/webrtc/+/refs/heads/master/sdk/objc/api/peerconnection/RTCPeerConnection.h#L142
```
/** Called when the receiver and its track are removed. */
- (void)peerConnection:(RTCPeerConnection *)peerConnection
     didRemoveReceiver:(RTCRtpReceiver *)rtpReceiver;
```

**Comment by rostopira** [comment]
Well, it's indeed missing
I've filled bug report here: https://bugs.chromium.org/p/webrtc/issues/detail?id=10586

**Comment by rostopira** [comment]
Their response:

> Seems like a reasonable thing to add, however not currently planned. Feel free to send a patch adding this if you need it.

https://bugs.chromium.org/p/webrtc/issues/detail?id=10586#c3

**Comment by cloudwebrtc** [comment]
We can submit the patch and it looks like just a bit of code.

**Comment by Ayman-Kortobaa** [comment]
@cloudwebrtc Any updates for this issue? I can see that the Dart `MediaStreamTrack` has `onEnded` callback but the native side doesn't have it and it's not available in the SDK AFAIk.

**Comment by cloudwebrtc** [comment]
@Ayman-Kortobaa It is easy to implement these methods in flutter web, but I am not sure if there is a track ended event triggered in the native SDK.
