### ISSUE TITLE
Screen Capture for Flutter Desktop

### ISSUE THREAD

**Issue by cloudwebrtc** [flutter-webrtc/flutter-webrtc#799]
I added a desktop-specific capture interface, which uses the desktop unified interface for Windows/macOS/Linux.

https://github.com/flutter-webrtc/webrtc-interface/blob/feat/desktop-cpaturer/lib/src/desktop_capturer.dart

``` dart
enum SourceType {
  kEntireScreen,
  kWindow,
}

class ThumbnailSize {
  ThumbnailSize(this.width, this.height);
  int width;
  int height;
}

abstract class DesktopCapturerSource {
  /// The identifier of a window or screen that can be used as a
  /// chromeMediaSourceId constraint when calling
  String get id;

  /// A screen source will be named either Entire Screen or Screen <index>,
  /// while the name of a window source will match the window title.
  String get name;

  ///A thumbnail image of the source. ARGB
  ByteBuffer get thumbnail;

  /// specified in the options passed to desktopCapturer.getSources.
  /// The actual size depends on the scale of the screen or window.
  ThumbnailSize get thumbnailSize;

  /// The type of the source.
  SourceType get type;
}

abstract class DesktopCapturer {
  Future<List<DesktopCapturerSource>> getSources(
      {List<SourceType> types, ThumbnailSize thumbnailSize});
}
```

### The enumeration is as follows

```dart
var sources = await navigator.desktopCapturer.getSources(
        types: [kScreen, kWindow], 
        thumbnailSize:  ThumbnailSize(width: 320, heigth: 180)
        );

DesktopCapturerSource selectedSource;
sources.forEach((item) => {
     // print item.id, item.title
     // display thumbnail
     selectedSource = item;
});

```

### get default display media.

```dart
var mediaStream = await navigator.mediaDevices.getDisplayMedia({video: true});
```

### get display media by source id.

```dart
var mediaStream = await navigator.mediaDevices.getDisplayMedia({
      video: {
               deviceId: {
                     exact: selectedSource.id
              }
              mandatory: {
                    minWidth: 1280,
                    minHeight: 720,
                    frameRate: 30.0
              }
      }
})
```

![image](https://user-images.githubusercontent.com/17733746/144859999-4b953abf-9a2a-4f30-a64b-135fa14438df.png)

**Comment by hiroshihorie** [comment]
Sounds like a plan !

**Comment by cloudwebrtc** [comment]
I think it is necessary to implement these interfaces in libwebrtc and macOS WebRTC.framework first, and then implement the dart-level API in flutter-webrtc.

**Comment by maxhora** [comment]
Hello @cloudwebrtc ,
We would like to contribute and help to bring a screen capture feature for desktops (mainly, are interested in MacOS support).
I've started to look into adding of interfaces you have mentioned above into libwebrtc. While compiling it locally on macos have found that there is a hardcoded dependency on some windows only sources since at least `libwebrtc/src/rtc_peerconnection_factory_impl.cc` has 

```
#if defined(USE_INTEL_MEDIA_SDK)
#include "src/win/mediacapabilities.h"
#include "src/win/msdkvideodecoderfactory.h"
#include "src/win/msdkvideoencoderfactory.h"
#endif
```
Temporary disabling of `USE_INTEL_MEDIA_SDK` have helped to build libwebrtc successfully.
![2022-01-15_23-25-59](https://user-images.githubusercontent.com/1928902/149638289-1f034c73-9040-43c1-a1c1-18bf2cb05184.png)

**Comment by maxhora** [comment]
@cloudwebrtc 

> I think it is necessary to implement these interfaces in libwebrtc and macOS WebRTC.framework first, and then implement the dart-level API in flutter-webrtc.

Could you please help me to locate a `macOS WebRTC.framework` you are referencing above? thanks!

**Comment by chentianxin** [comment]
> @cloudwebrtc
> 
> > I think it is necessary to implement these interfaces in libwebrtc and macOS WebRTC.framework first, and then implement the dart-level API in flutter-webrtc.
> 
> Could you please help me to locate a `macOS WebRTC.framework` you are referencing above? thanks!

Are there any updates?

**Comment by nikohpng** [comment]
您好，我想要实现您上面所示的接口，但是现在我卡在了一个地方。从 dll 返回数据（像vector、数组）到 exe 中，返回的数据总是有问题。您这边有什么好的建议吗？

**Comment by cloudwebrtc** [comment]
由于libwebrtc 会使用clang 编译dll，所以我们不能在接口处使用任何std/stl 类，这会让编译出来的dll 在不同编译器或std 库版本上出错，例如，flutter windows 会使用msvc 编译使用vc++ 特定的std 库，因此如果需要得到数据必须使用自己封装的portable 类。

**Comment by nikohpng** [comment]
好的，谢谢您的回复。目前我已经实现了大部分接口，虽然是使用了一个奇怪的方式解决的（数据放到文件里面）。
下面是我实现的代码内容，我在想这是否是比较好的实现方式。由于我这边一些原因，必须需要动态修改弹窗的样式。
就有了以下实现方式。
```dart
final mediaConstraints = <String, dynamic>{'audio': true, 'video': true};

    if (Platform.isWindows) {
      var sources = await navigator.mediaDevices.enumerateWindow();
      final result = await showMenu(
          context: context,
          position: RelativeRect.fromLTRB(100.0, 200.0, 100.0, 100.0),
//    position: RelativeRect.fromLTRB(1000.0, 1000.0, 0.0, 10.0),
          items: _buildPopupMenu(sources));
      navigator.mediaDevices.selectSource(result!);
    }
    // try {
      var stream =
          await navigator.mediaDevices.getDisplayMedia(mediaConstraints);
```

**Comment by cloudwebrtc** [comment]
@nikohpng 我正在尝试为flutter desktop添加 DesktopCapture 作为桌面专用的枚举接口，我参考了electron 和 chrome 内部实现，具体请参考此处, 也欢迎参与进来了讨论.
https://github.com/flutter-webrtc/webrtc-interface/pull/5/files

**Comment by nikohpng** [comment]
@cloudwebrtc 好的，谢谢您的回复。

**Comment by dkubrakov** [comment]
Updated the release of screen capture, taking into account the upgrade to m97.

**Comment by WxqKb** [comment]
windows截屏现在好像还没有支持？有什么办法可以解决不？

**Comment by cloudwebrtc** [comment]
support now

**Comment by WxqKb** [comment]
> support now

windows getUserMedia and captureFrame is not work，Are both the same? Is this supported?
see issues `https://github.com/flutter-webrtc/flutter-webrtc/issues/838`

**Comment by cloudwebrtc** [comment]
Not support now, this is another feature, single-frame snapshot

**Comment by cloudwebrtc** [comment]
I think you need 3 steps,
1. Get a frame of I420 from VideoTrack and convert it to RGB
2. Use libjpeg to convert RGB to jpeg memory or file
3. Get the memory or file storage path through the dart method channel.

**Comment by JiaoLiu** [comment]
PC 版本的录屏用的是GDI方式？ 发送端鼠标会闪烁很厉害，影响使用。

**Comment by zjzhang-cn** [comment]
![image](https://user-images.githubusercontent.com/1081308/197014451-beaf331a-a962-45c4-b1ae-034aafc5a601.png)
根据代码判断，确实时GDI的方式。

**Comment by cloudwebrtc** [comment]
可以编译一个测试版试试，如果改成dx 效果更好，也没有副作用，我们可以更新libwebrtc 库

**Comment by zjzhang-cn** [comment]
DXGI确实效果好， 在我的机器上，DXGI采集时间1~2ms  用GDI的回调间隔33ms了。 关于副作用， 跟据我对代码的阅读， 其 先用GDI打开，然后根据配置再尝试使用DXGI。

**Comment by JiaoLiu** [comment]
> 

可不可以兼容两种模式？ 好像WIN7下只有GDI可以用。
还有对鼠标的录制是否可选，不最后贴上鼠标。

**Comment by zjzhang-cn** [comment]
> > 
> 
> 可不可以兼容两种模式？ 好像WIN7下只有GDI可以用。
> 还有对鼠标的录制是否可选，不最后贴上鼠标。

是兼容的，先打开gdi 然后尝试dx

**Comment by JiaoLiu** [comment]
> 

使用0.9.12版本就是两种模式自动切换的吗？还是需要上层参数切换。

**Comment by cloudwebrtc** [comment]
0.9.12 还未修复此issue，预计下一个版本修复

**Comment by drantunes** [comment]
Is there a demo to share screen or window to multiple clients on local network? Example: By accessing the address 0.0.0.0/screen in the browser (client) it is possible to watch the streaming of the server's screen (desktop app).
