### ISSUE TITLE
replaceTrack is not implemented on windows

### ISSUE THREAD

**Issue by ashellunts** [flutter-webrtc/flutter-webrtc#800]
FlutterPeerConnection::RtpSenderReplaceTrack is empty/not implemented.

Due to that it is not possible to implement mute/unmute functionality with stopping track and replacing it with new track.
That is needed in order to stop camera/mic light indicator during mute.

**To Reproduce**: call `rtpSenderReplaceTrack`

* **Flutter version**: 0.8.0
* **OS**: windows

**Comment by cloudwebrtc** [comment]
I checked the underlying implementation of libwebrtc, and replaceTrack seems to be able to directly use SetTrack instead.

```cpp
void FlutterPeerConnection::RtpSenderReplaceTrack(
....
  auto sender = GetRtpSenderById(pc, rtpSenderId);
  if (nullptr == sender.get()) {
    result_ptr->Error("RtpSenderReplaceTrack", "sender is null");
    return;
  }

  sender->set_track(track);

  result_ptr->Success();
}
```
