### ISSUE TITLE
How use external camera and audio

### ISSUE THREAD

**Issue by hieplee2997** [flutter-webrtc/flutter-webrtc#812]
**Describe the bug**
I cannot set up flutter webRTC to use external camera on Desktop, i can get list camera devices with "navigator.mediaDevices.enumerateDevices" and pass deviceId to mediaconstraint like : 
```
final deviceId = (await navigator.mediaDevices.enumerateDevices)[1];
final Map<String, dynamic> mediaConstraints = {
      'audio': true,
      'video': {
        'mandatory': {
          'minWidth':
              '640', // Provide your own width, height and frame rate here
          'minHeight': '480',
          'minFrameRate': '30',
        },
        'facingMode': 'user',
        'optional': [],
        'deviceId': deviceId
      }
    };
```
but it not working, it still use default camera device

How can i set up other device, or what wrong i do?
**To Reproduce**

**Expected behavior**

**Platform information**

* **Flutter version**: 
* **Plugin version**:
* **OS**: 
* **OS version**:

**Comment by wupengbigMarker** [comment]
@hieplee2997 hi, how did you solve this issues

**Comment by hieplee2997** [comment]
It use Helper class, but it still not working
