### ISSUE TITLE
Using unified-plan, multiple Android phones join the same room, and the video stream cannot be displayed, which is a big problem

### ISSUE THREAD

**Issue by huoda1237** [flutter-webrtc/flutter-webrtc#819]
Using unified-plan, multiple Android phones join the same room, and the video stream cannot be displayed. In this method of Android plug-in, you need to judge whether it is unified-plan or plan-b

![截屏2021-12-27 下午4 54 58](https://user-images.githubusercontent.com/16382451/147462937-823dc51e-ec36-48cc-84eb-f43b517bb237.png)

**Comment by wupengbigMarker** [comment]
@huoda1237 hi, I got the same issue on iOS, can we talk about this on wechat or qq

**Comment by huoda1237** [comment]
> @huoda1237 hi, I got the same issue on iOS, can we talk about this on wechat or qq

加我微信：huolong1237
这个问题我已经解决了
