### ISSUE TITLE
App randomly crashing when starting screen share and always crashing when going back to camera

### ISSUE THREAD

**Issue by robvr** [flutter-webrtc/flutter-webrtc#820]
I've implemented the video call with an option to replace the camera stream with the screen record stream while in the call. Sometimes it happens that the application crashes as soon as I try to share the screen. When trying to go back to the camera stream it always crashes. This started happening when I started testing with an Android 11 device (was not happening with Android 7).

**Error message: F/libc    (15836): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 18006 (Thread-5), pid 15836**

* **Flutter version**:  2.8.1
* **Plugin version**: 0.8.0
* **OS**: Android
* **OS version**: 11

**Comment by ycherniavskyi** [comment]
@robvr did you solve the issue?
It will be really great if you could leave some comments about your issue and the way how you overcome it.

**Comment by robvr** [comment]
@ycherniavskyi Still debugging this one. I'm not sure if my code has issues or it is a library issue. Closed it in order to not disturb anyone because I'm having double thoughts on my code. Will write again after finding the real issue.

**Comment by robvr** [comment]
I've narrowed down my issue. It appears that my crash happens when I reach this piece of code:
```
(await _sessions[_sessionId]?.pc?.getSenders())
          ?.where((element) => element.track?.kind == 'video')
          .first
          .replaceTrack(
            _localStream!.getTracks().where((element) => element.kind == 'video').first)
```
And I'm getting this error:
**F/libc    ( 9768): Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 10914 (Thread-5), pid 9768**

The weird thing is that it sometimes happens, sometimes not (most of the time yes). Any ideas?
