### ISSUE TITLE
can we use ffi directly?

### ISSUE THREAD

**Issue by huang12zheng** [flutter-webrtc/flutter-webrtc#828]
* on purpose
1. faster, ffi and dart are in the same process cluster
2. convenient, You may only need to maintain dart

* solution
1. get lib from [github action](https://github.com/shiguredo-webrtc-build/webrtc-build/actions)
  [ref issue](https://github.com/webrtc-sdk/webrtc-build/issues/1)

2.1. share lib into platform

2.2. get header files to ffigen

3. test and adapt

**Comment by cloudwebrtc** [comment]
I think there are windows and Linux that can directly use ffi, ios/android framework relies on java, Obj-C interface (HW, audio manager), and other initialization call processes.

**Comment by huang12zheng** [comment]
close it for reason that may not be possible right now
