### ISSUE TITLE
RTCPeerConnection restartIce method is missing

### ISSUE THREAD

**Issue by hieplee2997** [flutter-webrtc/flutter-webrtc#830]
**Describe the bug**
I dont see the restartIce method of rtcpeerconnection. So can i use what instead? Or how can i create offer with iceRestart optional. The docs dont descript detail for this
In my case, after the renegotiate is completed, the connect was not successful, so i try create new offer but it not fire ice gathering event. What was wrong?

UPDATE: the label for restart ice is "IceRestart". Problem solved

**Comment by Arjunraj-k** [comment]
Can you please explain where you specified it? i still cant find the method on RTCPeerConnection object.

**Comment by AmirhosseinShk** [comment]
I have same issue too, can u please how can access to this method for IceRestart.
