### ISSUE TITLE
Android 12 - Need android.permission.BLUETOOTH_CONNECT permission for AttributionSource

### ISSUE THREAD

**Issue by sm2017** [flutter-webrtc/flutter-webrtc#846]
**Describe the bug**
On android 12, I have the following error when I call `createPeerConnection` for the first time each time I open fresh instance of app

```
I/flutter ( 1418): PlatformException(error, Need android.permission.BLUETOOTH_CONNECT permission for AttributionSource { uid = 10419, packageName = com.example, attributionTag = null, token = android.os.BinderProxy@e384ffe, next = null }: getName, null, java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for AttributionSource { uid = 10419, packageName = com.example, attributionTag = null, token = android.os.BinderProxy@e384ffe, next = null }: getName
I/flutter ( 1418): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
I/flutter ( 1418): 	at android.os.Parcel.createException(Parcel.java:2421)
I/flutter ( 1418): 	at android.os.Parcel.readException(Parcel.java:2404)
I/flutter ( 1418): 	at android.os.Parcel.readException(Parcel.java:2346)
I/flutter ( 1418): 	at android.bluetooth.IBluetoothManager$Stub$Proxy.getName(IBluetoothManager.java:1194)
I/flutter ( 1418): 	at android.bluetooth.BluetoothAdapter.getName(BluetoothAdapter.java:2344)
I/flutter ( 1418): 	at com.cloudwebrtc.webrtc.utils.RTCBluetoothManager.logBluetoothAdapterInfo(RTCBluetoothManager.java:432)
I/flutter ( 1418): 	at com.cloudwebrtc.webrtc.utils.RTCBluetoothManager.start(RTCBl
I/flutter ( 1418): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
I/flutter ( 1418): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
I/flutter ( 1418): <asynchronous suspension>
I/flutter ( 1418): #2      RTCFactoryNative.createPeerConnection (package:flutter_webrtc/src/native/factory_impl.dart:37:22)
I/flutter ( 1418): <asynchronous suspension>
I/flutter ( 1418): #3      CallCubit.connection.getConnection (package:example/blocs/call/call.dart:333:28)
I/flutter ( 1418): <asynchronous suspension>
I/flutter ( 1418): #4      CallCubit.createOffer (package:example/blocs/call/call.dart:535:26)
I/flutter ( 1418): <asynchronous suspension>
I/flutter ( 1418): #5      call (package:example/utils/helper.dart:519:5)
I/flutter ( 1418): <asynchronous suspension>
```

**To Reproduce**

Just call `createPeerConnection` on android 12

**Expected behavior**

As I don't want to pair Bluetooth devices, there is no need to check Bluetooth devices and I don't want to grant `BLUETOOTH_CONNECT` permission

**Platform information**

* **Flutter version**:  2.8.1
* **Plugin version**: 0.8.0
* **OS**: Android 
* **OS version**: 12

**Comment by sm2017** [comment]
@cloudwebrtc is it possible to remove requiring of BLUETOOTH_CONNECT permission

**Comment by cloudwebrtc** [comment]
I don't think so, because the AudioManager auto-switch thread needs to listen to BlueTooth, wired headphones, etc so it can go to the correct audio I/O device.

**Comment by 97loser** [comment]
@cloudwebrtc 
  Is there any update for the same?

**Comment by davidliu** [comment]
@cloudwebrtc I'll write up a PR to request the bluetooth permissions on Android 12, but I think it also might be better to do away with the `RTCAudioManager` related files and let the system handle the audio routing itself (which won't require any permissions). The only downside there is that we won't be able to request audio focus as a voice call, but it feels like it might be better served as a separate library rather than internally controlling it here.

**Comment by aashutosh-rana** [comment]
> Hi @sm2017
> 
> Try this:
> 
> ```
> 
>     <uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
>     <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30" />
> 
> 
>     <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
> ```
> 
> according to https://developer.android.com/guide/topics/connectivity/bluetooth/permissions

Thanks @

> Hi @sm2017
> 
> Try this:
> 
> ```
> 
>     <uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
>     <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30" />
> 
> 
>     <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
> ```
> 
> according to https://developer.android.com/guide/topics/connectivity/bluetooth/permissions

@BFamzz  Thanks , this is worked for me

**Comment by krillefear** [comment]
Hey there. Is this workaround still valid? Currently I'm unable to build the android app without the "android.permission.BLUETOOTH" on Android 12. I'm using Flutter WebRTC 0.9.5
