### ISSUE TITLE
Web app remote view not showing on macOS Safari, iOS Safari, iOS Chrome

### ISSUE THREAD

**Issue by 2i2i** [flutter-webrtc/flutter-webrtc#847]
**Describe the bug**

The web app works great on Android, macOS, Win browsers.

The web app basically provides p2p video calling. Signalling is implemented via firestore.

One device creates the `offer` (device A), the other device provides the `answer` (device B).

E.g.  If A = macOS Chrome (good), B = iOS Chrome (bad)
A sees local video and remote video
B sees only local video

E.g.  If A = iOS Chrome (bad), B = macOS Chrome (good)
A sees only local video
B sees only local video

So in a "bad" OS/browser, the remote is not shown.

Is it possible to be a problem in the signalling, given that it works on several OS/browsers?
Or is it rather a rendering issue in the "bad" OS/browsers?

How to determine whether the remote stream is sending video data or not?

We urgently need help for our app release. Is anyone able and willing to consult us on this? Feel free to dm (@2i2i_app).

thx

**To Reproduce**

**Expected behavior**

As on "good" OS/browsers, remote video should be showing.

**Platform information**

latest iOS, Chrome, Safari

* **Flutter version**: 
imi:2022-02-03 20:30:50:~ $ flutter doctor -v 
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-arm, locale
    en-GB)
    • Flutter version 2.8.1 at /Users/imi/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (7 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/imi/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.34.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 97.0.4692.99

• No issues found!

* **Plugin version**:
flutter_webrtc: ^0.8.1

* **OS**: 
iOS
* **OS version**:

**Comment by 2i2i** [comment]
copying the exact demo example, it does work

**Comment by 404danielnotfound** [comment]
I'm facing the exact same issue as you did. Would you mind sharing how you implement the demo example into your app? What might be the reason for remote video to not render on ios web? Thank you!
