### ISSUE TITLE
How to detect if the other peer has disabled/enabled their video or audio tracks?

### ISSUE THREAD

**Issue by misterneo** [flutter-webrtc/flutter-webrtc#854]
Hello, I'm working on a P2P video chat app, and my problem is that I don't seem to figure out how I could detect if the other-end user has disabled their camera or muted their mic in order to change the UI, so, for now, the user gets a black screen every time the other-end user disables their camera. Can anyone please tell me how I could solve this problem, is there a function I should use?? Thank you very much.

**Comment by cloudwebrtc** [comment]
I think you need to pass the media state at the signaling level.
```
{
   'usermedia.audio.muted': true | false,
   'usermedia.video.muted': true | false,
}
```

**Comment by misterneo** [comment]
Hello @cloudwebrtc, Thank you for your reply. But I don't think this is what I need because the issue is; Let's say 2 users are already connected via P2P and they both have their audio and video Media enabled at the signaling level. (See attachment below) 

![Capture 1](https://user-images.githubusercontent.com/25622326/153852295-a8739ac7-48c0-48e7-aaf5-01997ca309af.PNG)

And later on, one of them decides to turn off their camera mid-session. 

```
localStream!.getVideoTracks().forEach((track) {
    track.enabled = false;
});
```
So, What ends up happening is that User B gets a black screen! (See attachment below) 

![Capture 2](https://user-images.githubusercontent.com/25622326/153852571-6904d935-43f5-49a4-bcc8-2b98a71a7ca7.PNG)

Now what I need is to somehow detect if the remote stream of User B is receiving tracks with a turned-off video/audio! So I can hide the black screen and show a different UI Widget!

**Comment by cloudwebrtc** [comment]
I think both (data-channel or signaling) are ok, just send the status message to the other side when the user presses the mute/unmute button

**Comment by misterneo** [comment]
Thank you so much @jakobleck @cloudwebrtc for the insight. I managed to make it work with the data channel. very neat work around [👍](https://emojipedia.org/thumbs-up/)[👍](https://emojipedia.org/thumbs-up/)[👍](https://emojipedia.org/thumbs-up/)
