### ISSUE TITLE
Execution failed for task ':flutter_webrtc:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by roiskhoiron** [flutter-webrtc/flutter-webrtc#858]
this is my gradle task of 'assembleDebug' :

`e: Incompatible classes were found in dependencies. Remove them from the classpath or use '-Xskip-metadata-version-check' to suppress errors
e: /Users/roiskhoiron/.gradle/caches/transforms-3/06a50373d656b3b6af619c1f8ffd8be9/transformed/jetified-kotlin-stdlib-common-1.5.31.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /Users/roiskhoiron/.gradle/caches/transforms-3/216db9511a2b6d4ea493cf48f5296a33/transformed/jetified-window-1.0.0-beta04-api.jar!/META-INF/window_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /Users/roiskhoiron/.gradle/caches/transforms-3/3ccb1cd9f9383a14ed5577dd269d6c08/transformed/jetified-kotlinx-coroutines-core-jvm-1.5.2.jar!/META-INF/kotlinx-coroutines-core.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /Users/roiskhoiron/.gradle/caches/transforms-3/3cd9587ba94357591c04ff2cddd81eed/transformed/jetified-kotlin-stdlib-jdk8-1.5.30.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /Users/roiskhoiron/.gradle/caches/transforms-3/bbb99f7f1c662811afa5870bd3254281/transformed/jetified-window-java-1.0.0-beta04-api.jar!/META-INF/window-java_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /Users/roiskhoiron/.gradle/caches/transforms-3/c5606038b75d4caa068fad5006a7a429/transformed/jetified-kotlin-stdlib-jdk7-1.5.30.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /Users/roiskhoiron/.gradle/caches/transforms-3/c820b851b3cdce03007a31e2a33b37e5/transformed/jetified-kotlinx-coroutines-android-1.5.2.jar!/META-INF/kotlinx-coroutines-android.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /Users/roiskhoiron/.gradle/caches/transforms-3/f8c4aff3bd1eccc0771b7f35938344d4/transformed/jetified-kotlin-stdlib-1.5.31.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /usr/local/Caskroom/flutter/2.5.1/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.2/android/src/main/java/com/cloudwebrtc/webrtc/SimulcastVideoEncoderFactoryWrapper.kt: (68, 68): Unresolved reference: mutableListOf
e: /usr/local/Caskroom/flutter/2.5.1/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.2/android/src/main/java/com/cloudwebrtc/webrtc/SimulcastVideoEncoderFactoryWrapper.kt: (69, 40): Type mismatch: inferred type is Array<(out) VideoCodecInfo!>! but Collection<VideoCodecInfo> was expected
e: /usr/local/Caskroom/flutter/2.5.1/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.2/android/src/main/java/com/cloudwebrtc/webrtc/SimulcastVideoEncoderFactoryWrapper.kt: (70, 40): Type mismatch: inferred type is Array<(out) VideoCodecInfo!>! but Collection<VideoCodecInfo> was expected
e: /usr/local/Caskroom/flutter/2.5.1/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.2/android/src/main/java/com/cloudwebrtc/webrtc/SimulcastVideoEncoderFactoryWrapper.kt: (71, 40): Unresolved reference: toTypedArray
e: /usr/local/Caskroom/flutter/2.5.1/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.2/android/src/main/java/com/cloudwebrtc/webrtc/SimulcastVideoEncoderFactoryWrapper.kt: (92, 13): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /Users/roiskhoiron/.gradle/caches/transforms-3/f8c4aff3bd1eccc0771b7f35938344d4/transformed/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class
e: /usr/local/Caskroom/flutter/2.5.1/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.2/android/src/main/java/com/cloudwebrtc/webrtc/SimulcastVideoEncoderFactoryWrapper.kt: (139, 35): Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
The class is loaded from /Users/roiskhoiron/.gradle/caches/transforms-3/f8c4aff3bd1eccc0771b7f35938344d4/transformed/jetified-kotlin-stdlib-1.5.31.jar!/kotlin/Unit.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_webrtc:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s

┌─ Flutter Fix ────────────────────────────────────────────────────────────────────────────────┐
│ [!] Your project requires a newer version of the Kotlin Gradle plugin.                       │
│ Find the latest version on https://kotlinlang.org/docs/gradle.html#plugin-and-versions, then │
│ update /Users/roiskhoiron/AndroidStudioProjects/flutter-webrtc-demo/android/build.gradle:    │
│ ext.kotlin_version = '<latest-version>'                                                      │
└──────────────────────────────────────────────────────────────────────────────────────────────┘
Exception: Gradle task assembleDebug failed with exit code 1
`

can you help me to fix problem?

**Comment by roiskhoiron** [comment]
i've fixing this issue with add dependency kotlin in my base Java android project, but iam still error with new case.

`apply plugin: 'kotlin-android'`

**Comment by roiskhoiron** [comment]
iam doing update jdk to v11 and restart the IDE, this is was fixed

**Comment by roiskhoiron** [comment]
please, add this setup for installation documentation, thanks

**Comment by ryuujo1573** [comment]
JDK1.8 just works fine.
I guess changing jdk invalid all the cache which fixed the problem.
Maybe you might have tried `flutter clean`

**Comment by sagarappscrip** [comment]
I solved this error by doing these steps
> flutter clean
> flutter pub cache clean
> flutter pub get
> Restart your VS code or Android Studio whatever you are using

And done. Worked for me.
