### ISSUE TITLE
App crashing when playing a stream on Windows

### ISSUE THREAD

**Issue by MJ33** [flutter-webrtc/flutter-webrtc#874]
**Describe the bug**
My Windows app crashes when starting to play a WebRTC stream.

Debugging reveals the source of where the exception is thrown from:
**flutter_video_renderer.cc**: line 52
> Exception thrown at 0x00007FFC337063CA (libwebrtc.dll) in app_desktop.exe: 0xC0000005: Access violation reading location 0x0000000000000000

`frame_->ConvertToARGB(RTCVideoFrame::Type::kABGR, rgb_buffer_.get(), 0, (int)pixel_buffer_->width, (int)pixel_buffer_->height);`

I made **frame_** mutable in **flutter_video_renderer.h:**
`mutable scoped_refptr<RTCVideoFrame> frame_;`

and initializing the frame with **Create()** before calling **ConvertToARGB()**
`frame_ = frame_->Create((int)pixel_buffer_->width, (int)pixel_buffer_->height, rgb_buffer_.get(), 0);`

This got past **CopyPixelBuffer()** but the stream doesn't show correctly:
![image](https://user-images.githubusercontent.com/7661496/156508174-6ca739c5-1c77-44fd-9e01-95281a1eaa41.png)

**Flutter version**: 
[√] Flutter (Channel stable, 2.10.1, on Microsoft Windows [Version 10.0.19043.1526], locale en-ZA)
    • Flutter version 2.10.1 at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db747aa133 (3 weeks ago), 2022-02-09 13:57:35 -0600
    • Engine revision ab46186b24
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2022 17.0.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Enterprise
    • Visual Studio Enterprise 2022 version 17.0.31903.59
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code
    • VS Code at C:\Users\thinu\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] VS Code, 64-bit edition (version 1.64.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.36.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19043.1526]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 98.0.4758.102
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 98.0.1108.62
    ! Device emulator-5554 is offline.

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
exit code 0

* **Plugin version**: 0.8.3
* **OS**: Windows
* **OS version**: Windows 10 Pro, **Version:** 21H1, **OS build:** 19043.1526

**Comment by nikitatg** [comment]
I had the same issue. Interesting that my crash appears only when rendering remote video stream of **outgoing call** (incoming call renders correctly). 
The second thing is that until around February it was working well on plugin version 0.8.2.

Now plugin version: 0.8.3
OS version: Windows 10 Pro, 21H1 build 19043.1415

**Comment by nikitatg** [comment]
Huh... I don't know why, but today my problem described above spontaneously disappeared. 
Sorry now I just understand that I don't understand anything.
flutter_webrtc plugin version hasn't changed (0.8.3)
OS version now is: Windows 10 Pro, 21H1 build 19043.1586
Flutter 2.10.4

**Comment by RobotKSR** [comment]
Hello!
Same issue on Windows 10 Pro 21H2 19044.1706, Flutter 2.10.5, flutter_webrtc 0.8.9.

Have you found a solution?

**Comment by vickyleu** [comment]
**`sender (Windows 10)`**
![271658227334_ pic_hd](https://user-images.githubusercontent.com/19390292/179732285-86bafb2d-8b75-4d37-88ac-025ecb0ba193.jpg)

**`receiver (Mac mini 12.4)`**
![251658227331_ pic_hd](https://user-images.githubusercontent.com/19390292/179733170-4751580d-493b-40f0-a4b5-a646a9b44ff3.jpg)

**`receiver (iMac running Windows 10)`**
![261658227332_ pic_hd](https://user-images.githubusercontent.com/19390292/179733278-c2959b7b-baa0-4443-bc40-ad47292a4360.jpg)
 
i was adding `frame_ = frame_->Create((int)pixel_buffer_->width, (int)pixel_buffer_->height, rgb_buffer_.get(), 0);` above `frame_->ConvertToARGB(RTCVideoFrame::Type::kABGR, rgb_buffer_.get(), 0, (int)pixel_buffer_->width, (int)pixel_buffer_->height);`, and change `scoped_refptr<RTCVideoFrame> frame_;` property to mutable, shared screen work well, but windows's renderer cannot decode screen stream.

@cloudwebrtc

**Comment by vickyleu** [comment]
hi guys, flutter_webrtc:^0.9.0 is fixed crash on windows sharing, the issue should be close

**Comment by nikitatg** [comment]
I confirm. Call between thouse two devices that caused error before - working well on 0.9.0 flutter-webrtc version 
(Windows)

**Comment by chifandeyu** [comment]
And now running flutter-webrtc-demo on windows then crash at this: 
```
>	libwebrtc.dll!webrtc::I420Buffer::Rotate(const webrtc::I420BufferInterface & src, webrtc::VideoRotation rotation) 行 107	C++
 	[内联框架] libwebrtc.dll!webrtc::I420Buffer::Rotate(const webrtc::VideoFrameBuffer & src, webrtc::VideoRotation rotation) 行 58	C++
 	libwebrtc.dll!libwebrtc::VideoFrameBufferImpl::ConvertToARGB(libwebrtc::RTCVideoFrame::Type type, unsigned char * dst_buffer, int dst_stride, int dest_width, int dest_height) 行 65	C++
 	flutter_webrtc_plugin.dll!flutter_webrtc_plugin::FlutterVideoRenderer::CopyPixelBuffer(unsigned __int64 width, unsigned __int64 height) 行 56	C++
 	flutter_webrtc_plugin.dll!flutter_webrtc_plugin::FlutterVideoRenderer::{ctor}::__l2::<lambda>(unsigned __int64 width, unsigned __int64 height) 行 13	C++
 	[外部代码]	
 	flutter_webrtc_plugin.dll!flutter::PixelBufferTexture::CopyPixelBuffer(unsigned __int64 width, unsigned __int64 height) 行 39	C++
 	flutter_webrtc_plugin.dll!flutter::TextureRegistrarImpl::RegisterTexture::__l5::<lambda>(unsigned __int64 width, unsigned __int64 height, void * user_data) 行 168	C++
 	flutter_webrtc_plugin.dll!const FlutterDesktopPixelBuffer * <lambda>(unsigned __int64, unsigned __int64, void *)::<lambda_invoker_cdecl>(unsigned __int64 width, unsigned __int64 height, void * user_data) 行 170	C++
 	[外部代码]	```
