### ISSUE TITLE
Method setMicrophoneMute isn't defined  for the type 'MediaStreamTrack'

### ISSUE THREAD

**Issue by mostafaAbdelazim** [flutter-webrtc/flutter-webrtc#878]
After updating the pub version the setMicrophoneMute is gone, is there a way to set the mic to mute in the new version?

**Comment by ominibyte** [comment]
Use `Helper.setMicrophoneMute(true/false, stream.getAudioTracks()[0]);`

**Comment by mostafaAbdelazim** [comment]
Thanks @ominibyte
