### ISSUE TITLE
Update status bar clock design

### ISSUE THREAD

**Issue by zettry1** [flutter-webrtc/flutter-webrtc#886]
Hello, I want to change clock(left side of the status bar). background color.
I can only change full status bar background color. Example is like team on call or line on call design
But I want to only change left clock section of the status bar. Is this possible in flutter ?

https://stackoverflow.com/questions/71522723/how-to-change-status-bar-clock-design

**Comment by jakobleck** [comment]
This question seems to be unrelated to the flutter_webrtc package. This is a UI problem, right?

**Comment by ycherniavskyi** [comment]
For sure, this issue is entirely unrelated to this project.
