### ISSUE TITLE
RTCVideoValue(width: 0.0, height: 0.0, rotation: 0)) - IOS can't get video from Android

### ISSUE THREAD

**Issue by mb1shka** [flutter-webrtc/flutter-webrtc#889]
**Describe the bug**
I make a video call from IOS to Android, and IOS receives a "nullable" RTCVideoValue (1st picture), but the same time Android sends not nullable renderer's data (2nd picture).

When i make a call from Android to IOS, everything works fine.

Remote renderer disappears only on IOS only after calling from IOS to Android.

**To Reproduce**

**Expected behavior**

**Platform information**

* **Flutter version**: 
* **Plugin version**:
* **OS**: 
* **OS version**:
<img width="628" alt="Снимок экрана 2022-03-21 в 14 47 21" src="https://user-images.githubusercontent.com/80235393/159255066-9e639b6d-c216-46ce-a656-972ab03722a1.png">
<img width="999" alt="Снимок экрана 2022-03-21 в 14 50 51" src="https://user-images.githubusercontent.com/80235393/159255578-66def02b-ccf8-4b43-ae17-81fc052aabc9.png">

Some logs: I/org.webrtc.Logging( 6165): EglRenderer: Initializing EglRenderer
I/org.webrtc.Logging( 6165): EglRenderer: EglBase.create shared context
I/org.webrtc.Logging( 6165): EglBase14Impl: Using OpenGL ES version 2
I/org.webrtc.Logging( 6165): EglRenderer: Initializing EglRenderer
I/org.webrtc.Logging( 6165): EglRenderer: EglBase.create shared context
I/org.webrtc.Logging( 6165): EglBase14Impl: Using OpenGL ES version 2
I/flutter ( 6165): begin connect
I/org.webrtc.Logging( 6165): NetworkMonitor: Start monitoring with native observer -5476376645316451360
D/ConnectivityManager( 6165): StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3925)] [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3967)] [android.net.ConnectivityManager.requestNetwork(ConnectivityManager.java:4105)] [android.net.ConnectivityManager.requestNetwork(ConnectivityManager.java:4083)] [org.webrtc.NetworkMonitorAutoDetect$ConnectivityManagerDelegate.requestMobileNetwork(NetworkMonitorAutoDetect.java:404)] [org.webrtc.NetworkMonitorAutoDetect.<init>(NetworkMonitorAutoDetect.java:597)] [org.webrtc.NetworkMonitor$1.create(NetworkMonitor.java:50)] [org.webrtc.NetworkMonitor.createNetworkChangeDetector(NetworkMonitor.java:181)] [org.webrtc.NetworkMonitor.startMonitoring(NetworkMonitor.java:108)] [org.webrtc.NetworkMonitor.startMonitoring(NetworkMonitor.java:129)]
D/ConnectivityManager( 6165): StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3925)] [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3967)] [android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4349)] [android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4319)] [org.webrtc.NetworkMonitorAutoDetect$ConnectivityManagerDelegate.registerNetworkCallback(NetworkMonitorAutoDetect.java:391)] [org.webrtc.NetworkMonitorAutoDetect.<init>(NetworkMonitorAutoDetect.java:604)] [org.webrtc.NetworkMonitor$1.create(NetworkMonitor.java:50)] [org.webrtc.NetworkMonitor.createNetworkChangeDetector(NetworkMonitor.java:181)] [org.webrtc.NetworkMonitor.startMonitoring(NetworkMonitor.java:108)] [org.webrtc.NetworkMonitor.startMonitoring(NetworkMonitor.java:129)]
I/org.webrtc.Logging( 6165): NetworkMonitorAutoDetect: Network becomes available: 101
I/org.webrtc.Logging( 6165): NetworkMonitorAutoDetect: capabilities changed: [ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED&NOT_VCN_MANAGED LinkUpBandwidth>=260544Kbps LinkDnBandwidth>=110417Kbps TransportInfo: <SSID: <unknown ssid>, BSSID: 02:00:00:00:00:00, MAC: 02:00:00:00:00:00, Security type: 2, Supplicant state: COMPLETED, Wi-Fi standard: 5, RSSI: -53, Link speed: 175Mbps, Tx Link speed: 175Mbps, Max Supported Tx Link speed: 866Mbps, Rx Link speed: 526Mbps, Max Supported Rx Link speed: 866Mbps, Frequency: 5280MHz, Net ID: -1, Metered hint: false, score: 60, CarrierMerged: false, SubscriptionId: -1, IsPrimary: -1> SignalStrength: -53]
D/RTCAudioManager( 6165): ctor
D/RTCBluetoothManager( 6165): create@[name=main, id=2]
D/RTCBluetoothManager( 6165): ctor
D/RTCAudioManager( 6165): useSpeakerphone: auto
D/RTCProximitySensor( 6165): RTCProximitySensor@[name=main, id=2]
D/RTCAudioManager( 6165): defaultAudioDevice: SPEAKER_PHONE
D/RTCAudioManager( 6165): Android SDK: 31, Release: 12, Brand: samsung, Device: r8q, Id: SP1A.210812.016, Hardware: qcom, Manufacturer: samsung, Model: SM-G780G, Product: r8qser
D/RTCAudioManager( 6165): start
D/RTCAudioManager( 6165): AudioManager starts...
W/AudioManager( 6165): Use of stream types is deprecated for operations other than volume control
W/AudioManager( 6165): See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
D/RTCAudioManager( 6165): Audio focus request granted for VOICE_CALL streams
I/org.webrtc.Logging( 6165): NetworkMonitorAutoDetect: link properties changed
D/RTCBluetoothManager( 6165): start
W/RTCBluetoothManager( 6165): Process (pid=6165) lacks BLUETOOTH permission
D/RTCAudioManager( 6165): --- updateAudioDeviceState: wired headset=false, BT state=UNINITIALIZED
D/RTCAudioManager( 6165): Device status: available=[], selected=NONE, user selected=NONE
D/RTCAudioManager( 6165): setAudioDeviceInternal(device=SPEAKER_PHONE)
D/AudioTrack( 6165): stop(789): called with 57984 frames delivered
I/org.webrtc.Logging( 6165): EglRenderer: Duration: 4005 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: ,0. Average render time: NA. Average swapBuffer time: NA.
D/RTCAudioManager( 6165): New device status: available=[SPEAKER_PHONE, EARPIECE], selected=SPEAKER_PHONE
D/FlutterWebRTCPlugin( 6165): onAudioManagerDevicesChanged: [SPEAKER_PHONE, EARPIECE], selected: SPEAKER_PHONE
D/RTCAudioManager( 6165): --- updateAudioDeviceState done
D/RTCAudioManager( 6165): AudioManager started
I/FlutterWebRTCPlugin( 6165): getUserMedia(audio): mandatory: [], optional: [googNoiseSuppression: true, googEchoCancellation: true, echoCancellation: true, googEchoCancellation2: true, googDAEchoCancellation: true]
I/FlutterWebRTCPlugin( 6165): getUserMedia(video): ConstraintsMap{mMap={facingMode=user, optional=[], mandatory={maxHeight=914.2857142857143, maxFrameRate=30, maxWidth=411.42857142857144}}}
D/FlutterWebRTCPlugin( 6165): Creating video capturer using Camera2 API.
D/FlutterWebRTCPlugin( 6165): Create front camera 1 succeeded
I/org.webrtc.Logging( 6165): EglBase14Impl: Using OpenGL ES version 2
I/org.webrtc.Logging( 6165): CameraCapturer: startCapture: 1280x720@30
I/org.webrtc.Logging( 6165): Camera2Session: Create new camera2 session on camera 1
D/FlutterWebRTCPlugin( 6165): changeCaptureFormat: 1280x720@30
I/org.webrtc.Logging( 6165): Camera2Session: start
D/FlutterWebRTCPlugin( 6165): MediaStream id: 50bebad5-160c-4449-95a0-f1bb4bd3ed23
I/org.webrtc.Logging( 6165): Camera2Session: Available preview sizes: [3264x2448, 3264x1836, 3264x1468, 2448x2448, 2400x1080, 1920x864, 1920x824, 1920x1080, 1440x1080, 1088x1088, 1280x720, 960x720, 720x480, 640x480, 640x360, 352x288, 320x240, 256x144, 176x144]
I/org.webrtc.Logging( 6165): Camera2Session: Available fps ranges: [[15.0:15.0], [7.0:24.0], [24.0:24.0], [7.0:30.0], [30.0:30.0]]
I/org.webrtc.Logging( 6165): Camera2Session: Using capture format: 1280x720@[7.0:30.0]
I/org.webrtc.Logging( 6165): Camera2Session: Opening camera 1
D/FlutterWebRTCPlugin( 6165): CameraEventsHandler.onCameraOpening: cameraName=1
W/FlutterWebRTCPlugin( 6165): FlutterRTCVideoRenderer.setVideoTrack, set video track to 7752ef6b-62cc-414b-8ce7-0a29f06df151
I/flutter ( 6165): 0 in _connect
I/org.webrtc.Logging( 6165): EglRenderer: Releasing.
I/org.webrtc.Logging( 6165): EglRenderer: eglBase detach and release.
I/org.webrtc.Logging( 6165): EglRenderer: Releasing done.
I/org.webrtc.Logging( 6165): EglRenderer: Quitting render thread.
I/org.webrtc.Logging( 6165): EglRenderer: Initializing EglRenderer
I/org.webrtc.Logging( 6165): EglRenderer: EglBase.create shared context
I/org.webrtc.Logging( 6165): EglBase14Impl: Using OpenGL ES version 2
I/CameraManagerGlobal( 6165): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_OPEN for client com.****************.********* API Level 2
I/org.webrtc.Logging( 6165): Camera2Session: Camera opened.
I/ToneGenerator( 6165): startTone: try to start toneType 50 with volume=1.000000
I/org.webrtc.Logging( 6165): Camera2Session: Camera capture session configured.
I/org.webrtc.Logging( 6165): Camera2Session: Using video stabilization.
I/org.webrtc.Logging( 6165): Camera2Session: Auto-focus is not available.
I/org.webrtc.Logging( 6165): Camera2Session: Camera device successfully started.
I/org.webrtc.Logging( 6165): CameraCapturer: Create session done. Switch state: IDLE
I/CameraManagerGlobal( 6165): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_ACTIVE for client com.****************.********* API Level 2
I/org.webrtc.Logging( 6165): SurfaceTextureHelper: Setting listener to org.webrtc.Camera2Session$CaptureSessionCallback$$ExternalSyntheticLambda0@cb36dd1
D/AudioTrack( 6165): stop(789): called with 192 frames delivered
I/Choreographer( 6165): Skipped 31 frames!  The application may be doing too much work on its main thread.
I/org.webrtc.Logging( 6165): AndroidVideoDecoder: ctor name: OMX.qcom.video.decoder.vp8 type: VP8 color format: 19 context: org.webrtc.EglBase14Impl$Context@57e8a7
D/FlutterWebRTCPlugin( 6165): onAddTrack
D/FlutterWebRTCPlugin( 6165): onAddTrack
I/flutter ( 6165): RTCVideoRenderer#b8444(RTCVideoValue(width: 0.0, height: 0.0, rotation: 0))
W/FlutterWebRTCPlugin( 6165): FlutterRTCVideoRenderer.setVideoTrack, set video track to BFBEDE97-66E2-4495-962D-B597486E3BEC
I/org.webrtc.Logging( 6165): EglRenderer: Releasing.
I/org.webrtc.Logging( 6165): EglRenderer: eglBase detach and release.
I/org.webrtc.Logging( 6165): EglRenderer: Quitting render thread.
I/org.webrtc.Logging( 6165): EglRenderer: Releasing done.
I/org.webrtc.Logging( 6165): EglRenderer: Initializing EglRenderer
I/org.webrtc.Logging( 6165): EglRenderer: EglBase.create shared context
I/org.webrtc.Logging( 6165): EglBase14Impl: Using OpenGL ES version 2
I/org.webrtc.Logging( 6165): WebRtcAudioTrackExternal: initPlayout(sampleRate=48000, channels=1, bufferSizeFactor=1.0)
I/org.webrtc.Logging( 6165): WebRtcAudioTrackExternal: byteBuffer.capacity: 960
I/org.webrtc.Logging( 6165): WebRtcAudioTrackExternal: minBufferSizeInBytes: 7696
I/org.webrtc.Logging( 6165): WebRtcAudioTrackExternal: createAudioTrackOnLollipopOrHigher
I/org.webrtc.Logging( 6165): WebRtcAudioTrackExternal: nativeOutputSampleRate: 48000
I/org.webrtc.Logging( 6165): WebRtcAudioTrackExternal: AudioTrack: session ID: 5729, channels: 1, sample rate: 48000, max gain: 1.0
I/org.webrtc.Logging( 6165): WebRtcAudioTrackExternal: AudioTrack: buffer size in frames: 3848
I/org.webrtc.Logging( 6165): WebRtcAudioTrackExternal: AudioTrack: buffer capacity in frames: 3848
I/org.webrtc.Logging( 6165): VolumeLogger: start@[name=worker_thread - 6393, id=94]
I/org.webrtc.Logging( 6165): VolumeLogger: audio mode is: MODE_IN_COMMUNICATION
I/org.webrtc.Logging( 6165): WebRtcAudioTrackExternal: startPlayout
I/org.webrtc.Logging( 6165): WebRtcAudioTrackExternal: AudioTrackThread@[name=AudioTrackJavaThread, id=577]
I/org.webrtc.Logging( 6165): WebRtcAudioTrackExternal: doAudioTrackStateCallback: 0
I/org.webrtc.Logging( 6165): VolumeLogger: VOICE_CALL stream volume: 5 (max=8)
I/org.webrtc.Logging( 6165): AndroidVideoDecoder: ctor name: OMX.qcom.video.decoder.avc type: H264 color format: 19 context: org.webrtc.EglBase14Impl$Context@57e8a7
I/org.webrtc.Logging( 6165): AndroidVideoDecoder: ctor name: c2.android.avc.decoder type: H264 color format: 19 context: org.webrtc.EglBase14Impl$Context@57e8a7
I/org.webrtc.Logging( 6165): AndroidVideoDecoder: ctor name: OMX.qcom.video.decoder.avc type: H264 color format: 19 context: org.webrtc.EglBase14Impl$Context@57e8a7
I/org.webrtc.Logging( 6165): AndroidVideoDecoder: ctor name: c2.android.avc.decoder type: H264 color format: 19 context: org.webrtc.EglBase14Impl$Context@57e8a7
I/org.webrtc.Logging( 6165): WebRtcAudioRecordExternal: enableBuiltInAEC(true)
I/org.webrtc.Logging( 6165): WebRtcAudioEffectsExternal: setAEC(true)
I/org.webrtc.Logging( 6165): WebRtcAudioRecordExternal: enableBuiltInNS(true)
I/org.webrtc.Logging( 6165): WebRtcAudioEffectsExternal: setNS(true)
I/org.webrtc.Logging( 6165): NetworkMonitor: Stop monitoring with native observer -5476376645316451360
I/org.webrtc.Logging( 6165): NetworkMonitorAutoDetect: Unregister network callback
D/ConnectivityManager( 6165): StackLog: [android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:4598)] [org.webrtc.NetworkMonitorAutoDetect$ConnectivityManagerDelegate.releaseCallback(NetworkMonitorAutoDetect.java:422)] [org.webrtc.NetworkMonitorAutoDetect.destroy(NetworkMonitorAutoDetect.java:662)] [org.webrtc.NetworkMonitor.stopMonitoring(NetworkMonitor.java:148)] [org.webrtc.NetworkMonitor.stopMonitoring(NetworkMonitor.java:157)]
I/org.webrtc.Logging( 6165): NetworkMonitorAutoDetect: Unregister network callback
D/ConnectivityManager( 6165): StackLog: [android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:4598)] [org.webrtc.NetworkMonitorAutoDetect$ConnectivityManagerDelegate.releaseCallback(NetworkMonitorAutoDetect.java:422)] [org.webrtc.NetworkMonitorAutoDetect.destroy(NetworkMonitorAutoDetect.java:665)] [org.webrtc.NetworkMonitor.stopMonitoring(NetworkMonitor.java:148)] [org.webrtc.NetworkMonitor.stopMonitoring(NetworkMonitor.java:157)]
I/org.webrtc.Logging( 6165): NetworkMonitor: Start monitoring with native observer -5476376645316451360
D/ConnectivityManager( 6165): StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3925)] [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3967)] [android.net.ConnectivityManager.requestNetwork(ConnectivityManager.java:4105)] [android.net.ConnectivityManager.requestNetwork(ConnectivityManager.java:4083)] [org.webrtc.NetworkMonitorAutoDetect$ConnectivityManagerDelegate.requestMobileNetwork(NetworkMonitorAutoDetect.java:404)] [org.webrtc.NetworkMonitorAutoDetect.<init>(NetworkMonitorAutoDetect.java:597)] [org.webrtc.NetworkMonitor$1.create(NetworkMonitor.java:50)] [org.webrtc.NetworkMonitor.createNetworkChangeDetector(NetworkMonitor.java:181)] [org.webrtc.NetworkMonitor.startMonitoring(NetworkMonitor.java:108)] [org.webrtc.NetworkMonitor.startMonitoring(NetworkMonitor.java:129)]
D/ConnectivityManager( 6165): StackLog: [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3925)] [android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3967)] [android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4349)] [android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:4319)] [org.webrtc.NetworkMonitorAutoDetect$ConnectivityManagerDelegate.registerNetworkCallback(NetworkMonitorAutoDetect.java:391)] [org.webrtc.NetworkMonitorAutoDetect.<init>(NetworkMonitorAutoDetect.java:604)] [org.webrtc.NetworkMonitor$1.create(NetworkMonitor.java:50)] [org.webrtc.NetworkMonitor.createNetworkChangeDetector(NetworkMonitor.java:181)] [org.webrtc.NetworkMonitor.startMonitoring(NetworkMonitor.java:108)] [org.webrtc.NetworkMonitor.startMonitoring(NetworkMonitor.java:129)]
D/FlutterWebRTCPlugin( 6165): onIceGatheringChangeGATHERING
I/org.webrtc.Logging( 6165): NetworkMonitorAutoDetect: Network becomes available: 101
D/FlutterWebRTCPlugin( 6165): onIceCandidate
I/org.webrtc.Logging( 6165): NetworkMonitorAutoDetect: capabilities changed: [ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED&NOT_VCN_MANAGED LinkUpBandwidth>=260544Kbps LinkDnBandwidth>=110417Kbps TransportInfo: <SSID: <unknown ssid>, BSSID: 02:00:00:00:00:00, MAC: 02:00:00:00:00:00, Security type: 2, Supplicant state: COMPLETED, Wi-Fi standard: 5, RSSI: -53, Link speed: 175Mbps, Tx Link speed: 175Mbps, Max Supported Tx Link speed: 866Mbps, Rx Link speed: 526Mbps, Max Supported Rx Link speed: 866Mbps, Frequency: 5280MHz, Net ID: -1, Metered hint: false, score: 60, CarrierMerged: false, SubscriptionId: -1, IsPrimary: -1> SignalStrength: -53]
D/FlutterWebRTCPlugin( 6165): onIceCandidate
D/FlutterWebRTCPlugin( 6165): onIceCandidate
I/org.webrtc.Logging( 6165): NetworkMonitorAutoDetect: link properties changed
D/FlutterWebRTCPlugin( 6165): onIceCandidate
I/BufferQueueProducer( 6165): [SurfaceTexture-4-6165-14](id:181500000010,api:4,p:1225,c:6165) queueBuffer: queued for the first time.
D/FlutterWebRTCPlugin( 6165): CameraEventsHandler.onFirstFrameAvailable
I/BufferQueueProducer( 6165): [SurfaceTexture-0-6165-12](id:18150000000e,api:1,p:6165,c:6165) queueBuffer: queued for the first time.
I/org.webrtc.Logging( 6165): HardwareVideoEncoder: initEncode: 1280 x 720. @ 300kbps. Fps: 60 Use surface mode: true
I/ACodec  ( 6165):  [] Now uninitialized
I/ACodec  ( 6165): [] onAllocateComponent
I/OMXClient( 6165): IOmx service obtained
I/ACodec  ( 6165): [OMX.qcom.video.encoder.avc] Now Loaded
W/org.webrtc.Logging( 6165): HardwareVideoEncoder: Unknown profile level id: 42e034
I/org.webrtc.Logging( 6165): HardwareVideoEncoder: Format: {color-format=2130708361, i-frame-interval=20, mime=video/avc, width=1280, bitrate-mode=2, bitrate=300000, frame-rate=60.0, height=720}
D/VQApply ( 6165): minquality: applies only to VBR encoding
D/MediaCodec( 6165): shapeMediaFormat: deltas(0): AMessage(what = 0x00000000) = {
D/MediaCodec( 6165):   }
I/ACodec  ( 6165): app-pid(6165)
W/OMXUtils( 6165): do not know color format 0x7fa30c06 = 2141391878
W/OMXUtils( 6165): do not know color format 0x7fa30c04 = 2141391876
W/OMXUtils( 6165): do not know color format 0x7fa30c00 = 2141391872
W/OMXUtils( 6165): do not know color format 0x7fa30c09 = 2141391881
W/OMXUtils( 6165): do not know color format 0x7fa30c0a = 2141391882
W/OMXUtils( 6165): do not know color format 0x7fa30c08 = 2141391880
W/OMXUtils( 6165): do not know color format 0x7fa30c07 = 2141391879
W/OMXUtils( 6165): do not know color format 0x7f000789 = 2130708361
I/ACodec  ( 6165): app-name : com.**********.********************
I/ACodec  ( 6165): setupAVCEncoderParameters with [profile: Baseline] [level: Level32]
I/ACodec  ( 6165): Enable Perceptual Video Coding
I/ACodec  ( 6165): Success set IPB VideoMinQP(2/2/2) VideoMaxQP(50/50/50)
I/ACodec  ( 6165): reconfigEncoder4OtherApps
I/ACodec  ( 6165): [OMX.qcom.video.encoder.avc] cannot encode HDR static metadata. Ignoring.
I/ACodec  ( 6165): setupVideoEncoder succeeded
I/ACodec  ( 6165): [OMX.qcom.video.encoder.avc] configure, AMessage : AMessage(what = 'conf', target = 19) = {
I/ACodec  ( 6165):   int32_t color-format = 2130708361
I/ACodec  ( 6165):   int32_t i-frame-interval = 20
I/ACodec  ( 6165):   string mime = "video/avc"
I/ACodec  ( 6165):   int32_t width = 1280
I/ACodec  ( 6165):   int32_t bitrate-mode = 2
I/ACodec  ( 6165):   int32_t bitrate = 300000
I/ACodec  ( 6165):   float frame-rate = 60.000000
I/ACodec  ( 6165):   int32_t height = 720
I/ACodec  ( 6165):   int32_t flags = 1
I/ACodec  ( 6165):   int32_t encoder = 1
I/ACodec  ( 6165): }
W/OMXUtils( 6165): do not know color format 0x7f000789 = 2130708361
D/FlutterWebRTCPlugin( 6165): onIceCandidate
I/org.webrtc.Logging( 6165): EglBase14Impl: Using OpenGL ES version 2
I/ACodec  ( 6165): [OMX.qcom.video.encoder.avc] Now Loaded->Idle
I/ACodec  ( 6165): [OMX.qcom.video.encoder.avc] Now Idle->Executing
I/MediaCodec( 6165): setCodecState state : 0
I/ACodec  ( 6165): [OMX.qcom.video.encoder.avc] Now Executing
D/FlutterWebRTCPlugin( 6165): onIceCandidate
D/FlutterWebRTCPlugin( 6165): onIceCandidate
I/org.webrtc.Logging( 6165): HardwareVideoEncoder: Releasing MediaCodec on output thread
I/ACodec  ( 6165): [OMX.qcom.video.encoder.avc] Now Executing->Idle
I/ACodec  ( 6165): [OMX.qcom.video.encoder.avc] Now Idle->Loaded
I/ACodec  ( 6165): [OMX.qcom.video.encoder.avc] Now Loaded
I/ACodec  ( 6165):  [OMX.qcom.video.encoder.avc] Now kWhatShutdownCompleted event : 8056
I/org.webrtc.Logging( 6165): HardwareVideoEncoder: Release on output thread done
E/org.webrtc.Logging( 6165): HardwareVideoEncoder: MediaCodec is only tested with resolutions that are 16x16 aligned.
I/ACodec  ( 6165):  [OMX.qcom.video.encoder.avc] Now uninitialized
I/ACodec  ( 6165):  [] Now kWhatShutdownCompleted event : 8056
I/MediaCodec( 6165): Codec shutdown complete
E/org.webrtc.Logging( 6165): HardwareVideoEncoder: MediaCodec is only tested with resolutions that are 16x16 aligned.
E/org.webrtc.Logging( 6165): HardwareVideoEncoder: MediaCodec is only tested with resolutions that are 16x16 aligned.
E/org.webrtc.Logging( 6165): HardwareVideoEncoder: MediaCodec is only tested with resolutions that are 16x16 aligned.
I/org.webrtc.Logging( 6165): EglRenderer: Duration: 4005 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: ,0. Average render time: NA. Average swapBuffer time: NA.
D/FlutterWebRTCPlugin( 6165): onConnectionChangeCONNECTING
D/FlutterWebRTCPlugin( 6165): onIceGatheringChangeCOMPLETE
D/FlutterWebRTCPlugin( 6165): onSelectedCandidatePairChanged
D/FlutterWebRTCPlugin( 6165): onConnectionChangeCONNECTED
I/flutter ( 6165): MediaStreamTrack:enableSpeakerphone true
I/org.webrtc.Logging( 6165): WebRtcAudioRecordExternal: enableBuiltInAEC(true)
I/org.webrtc.Logging( 6165): WebRtcAudioEffectsExternal: setAEC(true)
I/org.webrtc.Logging( 6165): WebRtcAudioRecordExternal: enableBuiltInNS(true)
I/org.webrtc.Logging( 6165): WebRtcAudioEffectsExternal: setNS(true)
I/org.webrtc.Logging( 6165): WebRtcAudioRecordExternal: initRecording(sampleRate=48000, channels=1)
I/org.webrtc.Logging( 6165): WebRtcAudioRecordExternal: byteBuffer.capacity: 960
I/org.webrtc.Logging( 6165): WebRtcAudioRecordExternal: AudioRecord.getMinBufferSize: 3840
I/org.webrtc.Logging( 6165): WebRtcAudioRecordExternal: bufferSizeInBytes: 7680
I/org.webrtc.Logging( 6165): WebRtcAudioRecordExternal: createAudioRecordOnMOrHigher
I/flutter ( 6165): RTCVideoRenderer#b8444(RTCVideoValue(width: 0.0, height: 0.0, rotation: 0))
I/org.webrtc.Logging( 6165): WebRtcAudioEffectsExternal: enable(audioSession=5737)
I/org.webrtc.Logging( 6165): WebRtcAudioEffectsExternal: AcousticEchoCanceler: was enabled, enable: true, is now: enabled
I/org.webrtc.Logging( 6165): WebRtcAudioEffectsExternal: NoiseSuppressor: was disabled, enable: true, is now: enabled
I/org.webrtc.Logging( 6165): WebRtcAudioRecordExternal: AudioRecord: session ID: 5737, channels: 1, sample rate: 48000
I/org.webrtc.Logging( 6165): WebRtcAudioRecordExternal: AudioRecord: buffer size in frames: 3840
I/org.webrtc.Logging( 6165): WebRtcAudioRecordExternal: Number of active recording sessions: 0
I/org.webrtc.Logging( 6165): WebRtcAudioRecordExternal: startRecording
I/org.webrtc.Logging( 6165): WebRtcAudioRecordExternal: scheduleLogRecordingConfigurationsTask
I/org.webrtc.Logging( 6165): WebRtcAudioRecordExternal: AudioRecordThread@[name=AudioRecordJavaThread, id=591]
I/org.webrtc.Logging( 6165): WebRtcAudioRecordExternal: doAudioRecordStateCallback: START
I/org.webrtc.Logging( 6165): WebRtcAudioRecordExternal: Number of active recording sessions: 1
I/org.webrtc.Logging( 6165): WebRtcAudioRecordExternal: AudioRecordingConfigurations: 
I/org.webrtc.Logging( 6165): WebRtcAudioRecordExternal:   client audio source=VOICE_COMMUNICATION, client session id=5737 (5737)
I/org.webrtc.Logging( 6165):   Device AudioFormat: channel count=1, channel index mask=0, channel mask=IN_MONO, encoding=PCM_16BIT, sample rate=48000
I/org.webrtc.Logging( 6165):   Client AudioFormat: channel count=1, channel index mask=0, channel mask=IN_MONO, encoding=PCM_16BIT, sample rate=48000
I/org.webrtc.Logging( 6165):   AudioDevice: type=TYPE_BUILTIN_MIC, id=19
I/org.webrtc.Logging( 6165): WebRtcAudioRecordExternal: verifyAudioConfig: PASS
I/ToneGenerator( 6165): startTone: try to start toneType 50 with volume=1.000000
D/AudioTrack( 6165): stop(789): called with 192 frames delivered
I/org.webrtc.Logging( 6165): EglRenderer: Duration: 4007 ms. Frames received: 0. Dropped: 0. Rendered: 0. Render fps: ,0. Average render time: NA. Average swapBuffer time: NA.
I/org.webrtc.Logging( 6165): EglBase14Impl: Using OpenGL ES version 2
I/org.webrtc.Logging( 6165): AndroidVideoDecoder: initDecodeInternal name: OMX.qcom.video.decoder.avc type: H264 width: 640 height: 360
I/org.webrtc.Logging( 6165): SurfaceTextureHelper: Setting listener to org.webrtc.AndroidVideoDecoder@59b0a4b

**Comment by mb1shka** [comment]
UPD:
Android - Android: remote renderer works fine.
IOS - IOS: remote renderer works fine.
IOS -> Android samsung: no remote video
Android samsung -> IOS: fine
IOS -> Android Pixel: no remote video
Android Pixel -> IOS: fine
Android AYYA -> IOS: fine
IOS -> Android AYYA: fine

**Comment by sokpheng** [comment]
I have no solution yet.

**Comment by mb1shka** [comment]
> I have no solution yet.

I thought, it can be because of this logs, but I am not sure now.
May be some media can't be encoded / decoded?

I/ACodec ( 6165): reconfigEncoder4OtherApps
I/ACodec ( 6165): [OMX.qcom.video.encoder.avc] cannot encode HDR static metadata. Ignoring.

**Comment by mb1shka** [comment]
> I have no solution yet.

I fixed it!!!
I had to fork library (I can't show here the solution because of having in in my company's gitlab).

But everything was because of encoder.

Steps to solve this:
1. Make a fork of the flutter_webrtc library.
2. In android/src/main/java/com/cloudwebrtc/webrtc/MethodCallHandlerImpl.java in MethodCallHandlerImpl class change:
```java
mFactory = PeerConnectionFactory.builder()
            .setOptions(new Options())
            .setVideoEncoderFactory(new SimulcastVideoEncoderFactoryWrapper(eglContext, true, false))
            .setVideoDecoderFactory(new DefaultVideoDecoderFactory(eglContext))
            .setAudioDeviceModule(audioDeviceModule)
            .createPeerConnectionFactory();
```



to


```java
mFactory = PeerConnectionFactory.builder()
            .setOptions(new Options())
            .setVideoEncoderFactory(new SimulcastVideoEncoderFactoryWrapper(eglContext, true, true))
            .setVideoDecoderFactory(new DefaultVideoDecoderFactory(eglContext))
            .setAudioDeviceModule(audioDeviceModule)
            .createPeerConnectionFactory();
```
//159 line - change false to true

It was all because H264HighProfile was disabled and video could'n be properly encoded.

I tried to make calls between Samsung, Pixel, IPhone and AYYA. Everything now works fine for me.

**Comment by ycherniavskyi** [comment]
@mb1shka did you create PR? If not I can do it.

**Comment by mb1shka** [comment]
> @mb1shka did you create PR? If not I can do it.

I'm going to make it in a few moments.

**Comment by mb1shka** [comment]
@ycherniavskyi ready

**Comment by sokpheng** [comment]
I get this error after forked and modify the code.
![Screen Shot 2022-03-23 at 4 54 49 PM](https://user-images.githubusercontent.com/27798903/159672353-8b9a7eeb-2aa8-44f3-bf7a-6c6def13ecd7.png)

**Comment by ycherniavskyi** [comment]
@mb1shka thank you for PR #890. I will analyze whether we need to move this property in some settings and then merge it.

**Comment by gabeconvo** [comment]
I have been having this same issue, and I can confirm that PR #890 fixes it.

**Comment by davidliu** [comment]
Hey @mb1shka, could you post the Android offer/iPhone answer sdps? It seems like something's going wrong with the negotiation there, making the Android use a profile-level-id for the encoding that it doesn't know how to handle:

````
W/org.webrtc.Logging( 6165): HardwareVideoEncoder: Unknown profile level id: 42e034, 
````

This corresponds to Constrained Baseline Level 5.2, but it can't handle it so it falls back to what it can do, which is CB 3.2.

**Comment by torretorich** [comment]
hello @mb1shka my peer to peer connection is done in android but I always get black screen and width height is 0.
can you help me to solve this issue ?

**Comment by eric-tc** [comment]
Hi @torretorich ,

I have the same problem. Did you find a way to solve?

Thanks
