### ISSUE TITLE
'WebRTC/WebRTC.h' file not found

### ISSUE THREAD

**Issue by abhilash-profecialinks** [flutter-webrtc/flutter-webrtc#892]
While building the application got below error:

<img width="1680" alt="135850252-63108631-0f9f-4b15-b60e-b7d1d3f6fc9d" src="https://user-images.githubusercontent.com/95013325/160054964-5a8c6db1-4e97-4723-9d0f-c3739fe4434c.png">

**Comment by jakobleck** [comment]
Cf. https://github.com/flutter-webrtc/flutter-webrtc/issues/713
Please provide more info: iOS version, plugin version etc. ;)

**Comment by abhilash-profecialinks** [comment]
iOS version: 10,
plugin version is: 0.8.3

**Comment by IronHeartDan** [comment]
This is only happening to me when I am trying to build for a simulator but when I switch to real device the error fades away.
Very strange I would like to know why this is happening.

**Comment by ycherniavskyi** [comment]
The answer to the issue is in Q&A - #1026.
