### ISSUE TITLE
 type 'int' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by hrxiang** [flutter-webrtc/flutter-webrtc#910]
E/flutter (17579): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'int' is not a subtype of type 'String'
E/flutter (17579): #0      RTCDataChannelNative.eventListener (package:flutter_webrtc/src/native/rtc_data_channel_impl.dart:54:42)
E/flutter (17579): #1      _rootRunUnary (dart:async/zone.dart:1434:47)
E/flutter (17579): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter (17579): #3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter (17579): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter (17579): #5      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (17579): #6      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter (17579): #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter (17579): #8      _rootRun (dart:async/zone.dart:1418:47)
E/flutter (17579): #9      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (17579): #10     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (17579): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (17579): #12     _rootRun (dart:async/zone.dart:1426:13)
E/flutter (17579): #13     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (17579): #14     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (17579): #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (17579): #16     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (17579): #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

flutter_webrtc: ^0.8.5
flutter:  Channel stable  2.10.3

**Comment by simonbengtsson** [comment]
Are you using windows? If so this might be related to this issue https://github.com/flutter-webrtc/flutter-webrtc/issues/907

**Comment by hrxiang** [comment]
> Are you using windows? If so this might be related to this issue #907

android emulator

**Comment by isqad** [comment]
Have the same issue
```
I/flutter (26535): Error occurred: type 'int' is not a subtype of type 'String'
I/flutter (26535): Stacktrace: #0      RTCDataChannelNative.eventListener (package:flutter_webrtc/src/native/rtc_data_channel_impl.dart:54:42)
I/flutter (26535): #1      _rootRunUnary (dart:async/zone.dart:1434:47)
I/flutter (26535): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
I/flutter (26535): #3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
I/flutter (26535): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
I/flutter (26535): #5      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
I/flutter (26535): #6      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
I/flutter (26535): #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
I/flutter (26535): #8      _rootRun (dart:async/zone.dart:1418:47)
I/flutter (26535): #9      _CustomZone.run (dart:async/zone.dart:1328:19)
I/flutter (26535): #10     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
I/flutter (26535): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
I/flutter (26535): #12     _rootRun (dart:async/zone.dart:1426:13)
I/flutter (26535): #13     _CustomZone.run (dart:async/zone.dart:1328:19)
I/flutter (26535): #14     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
I/flutter (26535): #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
I/flutter (26535): #16     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
I/flutter (26535): #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```
Android 9.0 Xiaomi Redmi 4X
