### ISSUE TITLE
MacOS libyuv_internal.a needs to be built for arm64 support

### ISSUE THREAD

**Issue by jbrisko** [flutter-webrtc/flutter-webrtc#948]
With the release of Flutter 3, and support for Universal binaries we need a version of [libyuv_internal.a](https://github.com/flutter-webrtc/flutter-webrtc/blob/master/macos/third_party/lib/libyuv_internal.a) that is compiled for universal binary support. Currently, it cannot link to the library due to missing symbols.

**To Reproduce**
Build an app with arm64 support on Mac.

**Expected behavior**
It should build

**Platform information**
Flutter 3, Mac OS 12.3.1

**Comment by letungcntt** [comment]
``` console
ld: warning: ignoring file /Users/tungle/.pub-cache/git/flutter-webrtc/macos/third_party/lib/libyuv_internal.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_I420Rotate", referenced from:
      -[FlutterRTCVideoRenderer correctRotation:withRotation:] in FlutterRTCVideoRenderer.o
  "_I420ToARGB", referenced from:
      -[FlutterRTCVideoRenderer copyI420ToCVPixelBuffer:withFrame:] in FlutterRTCVideoRenderer.o
  "_I420ToBGRA", referenced from:
      -[FlutterRTCVideoRenderer copyI420ToCVPixelBuffer:withFrame:] in FlutterRTCVideoRenderer.o
  "_I420ToNV12", referenced from:
      -[FlutterRTCVideoRenderer copyI420ToCVPixelBuffer:withFrame:] in FlutterRTCVideoRenderer.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
** BUILD FAILED **

**Comment by leesc81** [comment]
I have the same problem.
At build time, the following log appears:

Launching lib/main.dart on macOS in debug mode...
Building macOS application...
objc[95601]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x1e1499eb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1040f04f8). One of the two will be used. Which one is undefined.
objc[95601]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1e1499f00) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1040f0548). One of the two will be used. Which one is undefined.
objc[95601]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1e1499f50) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1040f0598). One of the two will be used. Which one is undefined.
objc[95601]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x1e1499fa0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1040f05e8). One of the two will be used. Which one is undefined.
objc[95601]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x1e1499ff0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1040f0638). One of the two will be used. Which one is undefined.
objc[95601]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x1e149a040) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1040f0688). One of the two will be used. Which one is undefined.
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006000-000A496C1ED8801E }
{ platform:macOS, arch:x86_64, id:00006000-000A496C1ED8801E }
ld: warning: ignoring file /Users/soochanglee/MyApp/DevEnv/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.6/macos/third_party/lib/libyuv_internal.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_I420Rotate", referenced from:
      -[FlutterRTCVideoRenderer correctRotation:withRotation:] in FlutterRTCVideoRenderer.o
  "_I420ToARGB", referenced from:
      -[FlutterRTCVideoRenderer copyI420ToCVPixelBuffer:withFrame:] in FlutterRTCVideoRenderer.o
  "_I420ToBGRA", referenced from:
      -[FlutterRTCVideoRenderer copyI420ToCVPixelBuffer:withFrame:] in FlutterRTCVideoRenderer.o
  "_I420ToNV12", referenced from:
      -[FlutterRTCVideoRenderer copyI420ToCVPixelBuffer:withFrame:] in FlutterRTCVideoRenderer.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
** BUILD FAILED **

Exception: Build process failed

**Comment by rokk4** [comment]
Same here, blocking my release right now  :(
```
Running "flutter pub get" in xxxx...
Launching lib/main.dart on macOS in debug mode...
Running pod install...
Building macOS application...
objc[40674]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x1e2a29eb0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10424c4f8). One of the two will be used. Which one is undefined.
objc[40674]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1e2a29f00) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10424c548). One of the two will be used. Which one is undefined.
objc[40674]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1e2a29f50) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10424c598). One of the two will be used. Which one is undefined.
objc[40674]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x1e2a29fa0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10424c5e8). One of the two will be used. Which one is undefined.
objc[40674]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x1e2a29ff0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10424c638). One of the two will be used. Which one is undefined.
objc[40674]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x1e2a2a040) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10424c688). One of the two will be used. Which one is undefined.
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:XXX }
{ platform:macOS, arch:x86_64, id:XXX }
/Users/r0/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.6/macos/Classes/FlutterWebRTCPlugin.m:1637:16: warning: enumeration value 'RTCRtpTransceiverDirectionStopped' not handled in switch [-Wswitch]
       switch (direction) {
               ^
       switch (direction) {
               ^
1 warning generated.
ld: warning: ignoring file /Users/XX/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.6/macos/third_party/lib/libyuv_internal.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_I420Rotate", referenced from:
      -[FlutterRTCVideoRenderer correctRotation:withRotation:] in FlutterRTCVideoRenderer.o
  "_I420ToARGB", referenced from:
      -[FlutterRTCVideoRenderer copyI420ToCVPixelBuffer:withFrame:] in FlutterRTCVideoRenderer.o
  "_I420ToBGRA", referenced from:
      -[FlutterRTCVideoRenderer copyI420ToCVPixelBuffer:withFrame:] in FlutterRTCVideoRenderer.o
  "_I420ToNV12", referenced from:
      -[FlutterRTCVideoRenderer copyI420ToCVPixelBuffer:withFrame:] in FlutterRTCVideoRenderer.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
** BUILD FAILED **

Exception: Build process failed

```

**Comment by cloudwebrtc** [comment]
Should we add [copyI420ToCVPixelBuffer](https://github.com/flutter-webrtc/flutter-webrtc/blob/master/common/darwin/Classes/FlutterRTCVideoRenderer.m#L113) to [RTCVideoFrame](https://github.com/webrtc-sdk/webrtc/blob/m97_release/sdk/objc/base/RTCVideoFrame.h#L83)(rename the method to `convertToCVPixelBuffer`)? This way we will not import the `libyuv` library explicitly,

`libyuv` actually already exists in the darwin framework,   But currently one is imported externally, only for I420To *RGB

@hiroshihorie  @ycherniavskyi @davidliu  what do y'all think？

**Comment by jdde** [comment]
We ran into the same problem.

Our workaround until this is fixed: we just re-installed the x86 flutter 3 version on our silicon machines, then it will build for x86 and running our application with rosetta works, as we used it before.

We will move to flutter3 for silicon, when this is fixed :) looking forward to it.

Thank you for your awesome work @cloudwebrtc

**Comment by davidliu** [comment]
@cloudwebrtc could we just expose the libyuv methods from the webrtc lib?

**Comment by cloudwebrtc** [comment]
@davidliu  we could name it `RTCYUVHelper` and just expose the `libyuv` methods we need to use. 
maybe we still need to use these methods when developing other RTC native SDKs.
so, I think it's a good idea.

**Comment by cloudwebrtc** [comment]
Related PRs.
https://github.com/webrtc-sdk/webrtc/pull/28
https://github.com/flutter-webrtc/flutter-webrtc/pull/954
