### ISSUE TITLE
after uprade to fullter 0.8.6 when use flutter dataChannel for send get D/FlutterWebRTCPlugin( 9800): dataChannelSend() dataChannel is null error

### ISSUE THREAD

**Issue by AmirhosseinShk** [flutter-webrtc/flutter-webrtc#950]
use flutter dataChannel work fine when use 0.8.5 version when upgrade to 0.8.6 when try use dataChannel send() method get error that dataChannelSend() dataChannel is null , this error appear on call side that call createDataChannel method on peerConnetion and other side that recivied channel from .onDataChannel method is work fine and get send and recivied but the other side just can recivied message and can't send them at all

* **Flutter version**: 
D:\Work\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.1706], locale en-US)
    • Flutter version 2.10.5 at D:\Work\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (4 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at C:\Users\AmirShk\AppData\Local\Android\sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.11.8)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.11.32002.261
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] VS Code, 64-bit edition (version 1.67.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • SM A515F (mobile) • R58N924NVAN • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.19044.1706]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 101.0.4951.67
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 101.0.1210.32

[√] HTTP Host Availability
    • All required HTTP hosts are available

Process finished with exit code 0

* **Plugin version**: 0.8.6
* **OS**: Desktop
* android 12
* **OS version**: window 10

**Comment by simonbengtsson** [comment]
Might be related to #963. If so there is a workaround linked there.

**Comment by AmirhosseinShk** [comment]
tnx for ur mention , my problem solved
