### ISSUE TITLE
Getting an error attempting to build a simple Flutter app on iPhone SE emulator with webRTC

### ISSUE THREAD

**Issue by tfrysinger** [flutter-webrtc/flutter-webrtc#966]
### Discussed in https://github.com/flutter-webrtc/flutter-webrtc/discussions/965

<div type='discussions-op-text'>

<sup>Originally posted by **tfrysinger** May 26, 2022</sup>
I have not actually used any of the APIs yet in my sample app, but have only included the flutter_webrtc: ^0.8.7 line in my pubsepc.yaml. Now simply attempting to build a default app with this dependency results in a failure: 

Lexical or Preprocessor Issue (Xcode): 'WebRTC/WebRTC.h' file not found
/Users/tadfrysinger/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.7/ios/Classes/FlutterWebRTCPlugin.h:7:8

Could not build the application for the simulator.
Error launching application on iPhone SE (3rd generation).

I'm not sure why this is happening or what I should do about it?</div>

**Comment by jakobleck** [comment]
Could be down to architecture settings in you xcode project, cf https://github.com/flutter-webrtc/flutter-webrtc/issues?q=is%3Aissue+is%3Aopen+webrtc%2Fwebrtc.h, especially #713

**Comment by tfrysinger** [comment]
Well, I did check the plist file and yep, I did comment out the armv7 references but still getting this error:

    warning: [CP] WebRTC.xcframework: Unable to find matching slice in 'ios-arm64_armv7 ios-arm64_x86_64-simulator' for the current build architectures (arm64 x86_64 i386) and platform (-iphonesimulator).
    /Users/tadfrysinger/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.7/ios/Classes/FlutterRTCMediaStream.m:3:9: fatal error: 'WebRTC/WebRTC.h' file not found
    #import <WebRTC/WebRTC.h>

I notice down in the thread from #713 it talks specifically about this not working in simulators (which is what I am trying to do). And it suggests adding this to the podfile:

# ./ios/Podfile
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|

      # https://github.com/flutter-webrtc/flutter-webrtc/issues/713
      if target.name == "flutter_webrtc" || target.name == "WebRTC-SDK"
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      end
    end
  end
end

I did this, and voila, it worked!

Thanks for the pointer

**Comment by ycherniavskyi** [comment]
Related [Q&A discussion](#1026).
