### ISSUE TITLE
app is crashing when when screen sharing 

### ISSUE THREAD

**Issue by mohd-afid** [flutter-webrtc/flutter-webrtc#979]
**Describe the bug**
 app is crashing when when screen sharing  

**To Reproduce**
 no mediaType information
W/MediaCodec(30226): mapFormat: no mediaType information
W/MediaCodec(30226): mapFormat: no mediaType information
I/ViewRootImpl@7937bd6[MainActivity](30226): stopped(false) old=false
I/org.webrtc.Logging(30226): CameraCapturer: startCapture: 1280x720@30
W/org.webrtc.Logging(30226): CameraCapturer: Session already open
I/DecorView(30226): notifyKeepScreenOnChanged: keepScreenOn=false
I/MSHandlerLifeCycle(30226): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@e6c64ac[MainActivity]
I/MSHandlerLifeCycle(30226): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@e6c64ac[MainActivity]
I/MSHandlerLifeCycle(30226): removeMultiSplitHandler: no exist. decor=DecorView@e6c64ac[MainActivity]
I/org.webrtc.Logging(30226): EglBase14Impl: Using OpenGL ES version 2
D/OrientationAwareSC(30226): OrientationAwareScreenCapturer: initialized and orientation isPortrait? false
D/AndroidRuntime(30226): Shutting down VM
E/AndroidRuntime(30226): FATAL EXCEPTION: main
E/AndroidRuntime(30226): Process: com.example, PID: 30226
E/AndroidRuntime(30226): java.lang.SecurityException: Media projections require a foreground service of type ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION
E/AndroidRuntime(30226): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
E/AndroidRuntime(30226): 	at android.os.Parcel.createException(Parcel.java:2421)
E/AndroidRuntime(30226): 	at android.os.Parcel.readException(Parcel.java:2404)
E/AndroidRuntime(30226): 	at android.os.Parcel.readException(Parcel.java:2346)
E/AndroidRuntime(30226): 	at android.media.projection.IMediaProjection$Stub$Proxy.start(IMediaProjection.java:235)
E/AndroidRuntime(30226): 	at android.media.projection.MediaProjection.<init>(MediaProjection.java:77)
E/AndroidRuntime(30226): 	at android.media.projection.MediaProjectionManager.getMediaProjection(MediaProjectionManager.java:165)
E/AndroidRuntime(30226): 	at org.webrtc.ScreenCapturerAndroid.startCapture(ScreenCapturerAndroid.java:114)
E/AndroidRuntime(30226): 	at com.cloudwebrtc.webrtc.OrientationAwareScreenCapturer.startCapture(OrientationAwareScreenCapturer.java:62)
E/AndroidRuntime(30226): 	at com.cloudwebrtc.webrtc.GetUserMediaImpl$3.onReceiveResult(GetUserMediaImpl.java:478)
E/AndroidRuntime(30226): 	at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
E/AndroidRuntime(30226): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(30226): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(30226): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(30226): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(30226): 	at android.app.ActivityThread.main(ActivityThread.java:8663)
E/AndroidRuntime(30226): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30226): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
E/AndroidRuntime(30226): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
E/AndroidRuntime(30226): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(30226): 	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:575)
E/AndroidRuntime(30226): 	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:137)
E/AndroidRuntime(30226): 	at android.os.Binder.execTransactInternal(Binder.java:1215)
E/AndroidRuntime(30226): 	at android.os.Binder.execTransact(Binder.java:1179)
E/AndroidRuntime(30226): 
W/MediaCodec(30226): mapFormat: no mediaType information
I/Process (30226): Sending signal. PID: 30226 SIG: 9
Lost connection to device.
**Expected behavior**

**Platform information**

* **Flutter version**: 
*  Flutter (Channel stable, 3.0.0, on Microsoft Windows [Version 10.0.22000.675], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.5)

* **Plugin version**:
* **OS**: 
* Android
* **OS version**:

**Comment by davidliu** [comment]
You'll need to start up a foreground service on Android with the mediaProjection type.

See https://github.com/flutter-webrtc/flutter-webrtc/blob/fc2749b4e9e21bbae63fa9d0ddb83443e0c2744d/example/lib/main.dart#L26
