### ISSUE TITLE
 pthread_create failed: clone failed: Out of memory

### ISSUE THREAD

**Issue by wangzewa** [flutter-webrtc/flutter-webrtc#988]
android crash when created about 25 FlutterRTCVideoRenders
this is problem:
  W/libc    (30308): pthread_create failed: clone failed: Out of memory
W/ital.video_roo(30308): Throwing OutOfMemoryError "pthread_create (1040KB stack) failed: Out of memory" (VmSize 63208120 kB)
E/AndroidRuntime(30308): FATAL EXCEPTION: main
E/AndroidRuntime(30308): Process: com.digital.video_room, PID: 30308
E/AndroidRuntime(30308): java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Out of memory
E/AndroidRuntime(30308): 	at java.lang.Thread.nativeCreate(Native Method)
E/AndroidRuntime(30308): 	at java.lang.Thread.start(Thread.java:893)
E/AndroidRuntime(30308): 	at org.webrtc.EglRenderer.init(EglRenderer.java:219)
E/AndroidRuntime(30308): 	at org.webrtc.EglRenderer.init(EglRenderer.java:259)
E/AndroidRuntime(30308): 	at com.cloudwebrtc.webrtc.SurfaceTextureRenderer.init(SurfaceTextureRenderer.java:61)
E/AndroidRuntime(30308): 	at com.cloudwebrtc.webrtc.SurfaceTextureRenderer.init(SurfaceTextureRenderer.java:41)
E/AndroidRuntime(30308): 	at com.cloudwebrtc.webrtc.FlutterRTCVideoRenderer.<init>(FlutterRTCVideoRenderer.java:103)
E/AndroidRuntime(30308): 	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:426)
E/AndroidRuntime(30308): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime(30308): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/AndroidRuntime(30308): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/AndroidRuntime(30308): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/AndroidRuntime(30308): 	at android.os.Handler.handleCallback(Handler.java:900)
E/AndroidRuntime(30308): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(30308): 	at android.os.Looper.loop(Looper.java:219)
E/AndroidRuntime(30308): 	at android.app.ActivityThread.main(ActivityThread.java:8668)
E/AndroidRuntime(30308): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(30308): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(30308): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
I/Process (30308): Sending signal. PID: 30308 SIG: 9

**Comment by wangzewa** [comment]
> Could you please mention Android devices with their specs and OS versions on which this issue reproduces?
> 
> Also, please point out your desired solution. Is it the possibility to create 100, 1000, 10000, etc. `FlutterRTCVideoRenders`, or is it the possibility to catch and handle this `Exception`?

Android devices: redmi k40 versions :android 12. I hope at least 100 FlutterRTCVideoRenders

**Comment by ycherniavskyi** [comment]
Have you tried any android app tuning? For example [largeHeap](https://stackoverflow.com/questions/27396892/what-are-advantages-of-setting-largeheap-to-true) parameter?

**Comment by wangzewa** [comment]
> Have you tried any android app tuning? For example [largeHeap](https://stackoverflow.com/questions/27396892/what-are-advantages-of-setting-largeheap-to-true) parameter?

I tried the latest version of flutter_webrtc ,I found that the issue disapper.

**Comment by ycherniavskyi** [comment]
Hmm, that's good (but I am not sure that exactly new version of flutter_webrtc resolve your issue). In such case I close the issue.
