### ISSUE TITLE
Support for Unified Plan.

### ISSUE THREAD

**Issue by cloudwebrtc** [flutter-webrtc/flutter-webrtc#99]
We need to add a series of interfaces, such as RtpTransceiver, RtpSender, RtpReceiver.

**Comment by rostopira** [comment]
I have doubt, that regular developer would need to use them
Anyway, you can get them on android by just few lines in `PeerConnectionObserver` class
```java
    @Override
    public void onTrack(RtpTransceiver transceiver) {
        final RtpSender rtpSender = transceiver.getSender();
        final RtpReceiver rtpReceiver = transceiver.getReceiver();
    }
```

**Comment by cloudwebrtc** [comment]
[WIP] https://github.com/cloudwebrtc/flutter-webrtc/tree/unified-plan

**Comment by rostopira** [comment]
Well, Flutter Web doesn't fit into unified plan at all due to missing `dart:io` package
I'm working on it in separate `web` folder, so resulting `webrtc.dart` will look like this:
```dart
export 'get_user_media.dart'
  if (dart.library.js) 'web/get_user_media.dart';
export 'media_stream_track.dart'
  if (dart.library.js) 'web/media_stream_track.dart';
export 'media_stream.dart'
  if (dart.library.js) 'web/media_stream.dart';
export 'rtc_data_channel.dart'
  if (dart.library.js) 'web/rtc_data_channel.dart';
export 'rtc_video_view.dart'
  if (dart.library.js) 'web/rtc_video_view.dart';
export 'rtc_ice_candidate.dart'
  if (dart.library.js) 'web/rtc_ice_candidate.dart';
export 'rtc_session_description.dart'
  if (dart.library.js) 'web/rtc_session_description.dart';
export 'rtc_peerconnection.dart'
  if (dart.library.js) 'web/rtc_peerconnection.dart';
export 'rtc_peerconnection_factory.dart'
  if (dart.library.js) 'web/rtc_peerconnection_factory.dart';
export 'rtc_stats_report.dart';
export 'media_recorder.dart'
  if (dart.library.js) 'web/media_recorder.dart';
```

I hope this won't hurt (=

**Comment by cloudwebrtc** [comment]
No problem, let's make it work first. :)

**Comment by rostopira** [comment]
When you will merge this?
I wanna make Flutter Web PR API compatible to avoid compile time errors and merge conflicts

**Comment by cloudwebrtc** [comment]
You can temporarily commit the changes to the branch and wait for me to complete the unified-plan work, then resolve the conflicts and merge them into the master.

**Comment by ycherniavskyi** [comment]
Just found rather useful related to this issue doc - [“Unified Plan” Transition Guide (JavaScript)](https://docs.google.com/document/d/1-ZfikoUtoJa9k-GZG1daN0BU3IjIanQ_JSscHxQesvU/edit) (it could be helpful for new contributors, such as me 😊, to understand what this issue is about).

**Comment by cloudwebrtc** [comment]
Now support `Unified-Plan` for iOS/Android/macOS. 
https://github.com/flutter-webrtc/flutter-webrtc/pull/359
just need path the web plugin.

**Comment by cloudwebrtc** [comment]
So close the issue and open a new one related to the web.
