### ISSUE TITLE
Disable logs

### ISSUE THREAD

**Issue by ollydixon** [flutter-webrtc/flutter-webrtc#997]
Trying to implement this, but it's difficult to see my own steps when there's a lot of log spam.

Would be nice to disable the logs.

<img width="655" alt="Screenshot 2022-07-13 at 07 34 04" src="https://user-images.githubusercontent.com/6940726/178658307-a54ca7c5-7a13-43d1-bd6b-2c90cdac1cce.png">

**Comment by ycherniavskyi** [comment]
Could you please explain what exactly you are "Trying to implement" 🤔?

As for logs level, from your screenshot, it is unclear what explicitly logs you would like to disable.

**Comment by ollydixon** [comment]
@ycherniavskyi they are logs from our plug-in; just looking for an option to disable them without doing a fork :-)

**Comment by ycherniavskyi** [comment]
@ollydixon but as I see [by default logging is disabled/commented](https://github.com/flutter-webrtc/flutter-webrtc/blob/6c047adbb8c2fa35e6740f0962f6f5485e429029/common/darwin/Classes/FlutterWebRTCPlugin.m#L66), and I looking for an option to enable them 😉.

**Comment by ollydixon** [comment]
@ycherniavskyi there’s a lot of logs that swallow out useful info; I also see that they log during production (big no no for performance)

**Comment by ollydixon** [comment]
@ycherniavskyi perhaps it's from the Flutter Mediasoup client https://pub.dev/packages/mediasoup_client_flutter

**Comment by tigrenok00** [comment]
@ycherniavskyi Hi, did you find a way to enable logs? I'm looking for a way to have a verbose logging level too, especially why connection fails...

**Comment by ycherniavskyi** [comment]
Unfortunately, I still do it manually by uncommenting [this line](https://github.com/flutter-webrtc/flutter-webrtc/blob/d637c122ef9ef7dacc36a8428fbdc7a177c0149c/common/darwin/Classes/FlutterWebRTCPlugin.m#L75) in dev env.

**Comment by VerioN1** [comment]
@ycherniavskyi , hey! 
After uncommenting this line, anything else to do ? like recompile it or something ? cause I uncommented this line and no logs are printed to debug console in vscode.
Any help will be much appreciated !
