### ISSUE TITLE
Need a way to tell to use SW decoding instead of setting HW as primary which falls back to SW

### ISSUE THREAD

**Issue by MohamedRisaldarTA** [flutter-webrtc/flutter-webrtc#998]
**Is your feature request related to a problem? Please describe.**
Android App is crashing when receiving more number of video streams and displaying it.(when receiving and displaying larger than 15 streams)

**Describe the solution you'd like**
Using SW decoder to decode streams helps us to increase the number of video streams.
So providing a way to choose default video decoder will help.

**Comment by davidliu** [comment]
Are you displaying more than 15 streams all on stream at the same time? Or are they displayed like in a list or paging, where only a certain number of streams are displaying at any specific time?

**Comment by MohamedRisaldarTA** [comment]
> Are you displaying more than 15 streams all on stream at the same time? Or are they displayed like in a list or paging, where only a certain number of streams are displaying at any specific time?

I am displaying multiple small resolution streams on screen in a grid and the phone's display has enough size to show 25 streams at a time.

Running with the current implementation makes the app to crash when 15th stream gets added.
When tried with software decoding it can go more than that.

So I would be happy if my app can tell flutter_webrtc to use software decoder to decode the stream.

**Comment by ycherniavskyi** [comment]
@cloudwebrtc I exactly look for the place/mechanism to pass `logLevel` into the native part instead of every time uncommenting `RTCSetMinDebugLogLevel` call 😊.

**Comment by cloudwebrtc** [comment]
@ycherniavskyi Yes, it makes sense, we can do a plugin settings API,
```dart
await WebRTC.initialize(
    options: {
       'bypassVoiceProcessing': true,
       'forceUseSWDecoder': true,
       'logLevel': 'info',
    }
);

await WebRTC.updateSettings(
    options: {
       'bypassVoiceProcessing': true,
       'forceUseSWDecoder': true,
       'logLevel': 'info',
    }
);
```

**Comment by MohamedRisaldarTA** [comment]
@cloudwebrtc I found that #825 have plugin settings API but is still open, will it get merged in near future.

**Comment by MohamedRisaldarTA** [comment]
Now supports forceSWCodec on Android. Closing this issue as resolved.
